import Researchproofs
open Research.P4
#print axioms Research.P4.naive_step_drift
#print axioms Research.P4.naive_share_increasing
#print axioms Research.P4.corrected_share_closed_form
#print axioms Research.P4.corrected_share_tendsto
#print axioms Research.P4.naiveShare_strictMono
#print axioms Research.P4.naiveShare_tendsto_one
#print axioms Research.P4.not_summable_shifted_harmonic
#print axioms Research.P4.naiveShare_rate_bound
#print axioms Research.P4.naiveTotal_ge
#print axioms Research.P5.Table.chouldechova
#print axioms Research.P5.impossibility
#print axioms Research.P5.true_base_rate_bounds
#print axioms Research.P5.lower_bound_attained
#print axioms Research.P5.upper_bound_attained
#print axioms Research.P5.trueRate_observedRate
#print axioms Research.P1.TwoSource.petersen_identity
#print axioms Research.P1.TwoSource.petersen_bounds
#print axioms Research.P1.petersen_lower_attained
#print axioms Research.P1.petersen_upper_attained
#print axioms Research.P1.true_rate_bounds
#print axioms Research.P1.dark_figure_bounds
#print axioms Research.P3.Model.exposure_adjustment
#print axioms Research.P3.Model.misspecified_exposure_bias
#print axioms Research.P3.Model.pooled_mean_mixture
#print axioms Research.P7.gini_zero_decomposition
#print axioms Research.P7.poisson_zero_prob
#print axioms Research.P2.rate_bounds
#print axioms Research.P2.disparity_bounds
#print axioms Research.P2.disparity_sign_identified
#print axioms Research.P6.aggregate_not_identifying
#print axioms Research.P6.invariance_not_necessary
#print axioms Research.P8.constant_dimension_not_identified
#print axioms Research.P8.corner_design_identified
#print axioms Research.P5.compare_decided
#print axioms Research.P5.compare_undecided
#print axioms Research.P1.conclusion_holds_below_breakdown
#print axioms Research.P1.conclusion_fails_above_breakdown
#print axioms Research.P3.Design.ht_unbiased
#print axioms Research.P3.Design.ht_contrast_unbiased
#print axioms Research.P4.rho_cap
#print axioms Research.P4.cap_zero
#print axioms Research.P4.cap_one
#print axioms Research.P4.Urn.urn_step_martingale
#print axioms Research.P4.Urn.polya_uniform
#print axioms Research.P4.Urn.polya_no_concentration
#print axioms Research.P3.Design.ht_variance
#print axioms Research.P3.Design.ht_variance_estimator_unbiased
#print axioms Research.P7.Mixture.mixture_zero_ge_exp_neg_mean
#print axioms Research.P7.Mixture.variance_eq
#print axioms Research.P7.Mixture.mixture_var_ge_mean
#print axioms Research.P7.Mixture.mixture_var_eq_mean_iff
#print axioms Research.P1.petersen_ge_floor
#print axioms Research.P1.chapman_ge_floor
#print axioms Research.P1.three_list_saturated_fits
#print axioms Research.P1.missing_cell_unconstrained
#print axioms Research.P2.offset_shift
#print axioms Research.P2.disparity_ratio_shift
#print axioms Research.P2.benchmark_product
#print axioms Research.P2.benchmark_not_additive
#print axioms Research.P9.total_invariant_of_colStochastic
#print axioms Research.P9.total_le_of_colSubstochastic
#print axioms Research.P9.reclassification_moves_ratio
#print axioms Research.P9.detection_rate_rises
#print axioms Research.P10.generation_mean
#print axioms Research.P10.cluster_size_of_lt_one
#print axioms Research.P10.stationary_rate
#print axioms Research.P10.cluster_size_diverges_of_ge_one
#print axioms Research.P10.endogeneity_share
#print axioms Research.P3.SYG.row_sum_zero
#print axioms Research.P3.SYG.syg_eq_ht
#print axioms Research.P3.SYG.syg_zero_of_const
#print axioms Research.P11.Pop.pz_compl
#print axioms Research.P11.Pop.outcome_bounds
#print axioms Research.P11.Pop.lower_attained
#print axioms Research.P11.Pop.upper_attained
#print axioms Research.P11.Pop.ate_width_one
#print axioms Research.P11.Pop.ate_contains_zero
#print axioms Research.P12.within_orth
#print axioms Research.P12.cov_decomp
#print axioms Research.P12.var_decomp
#print axioms Research.P12.var_nonneg
#print axioms Research.P12.ecological_ge
#print axioms Research.P7.log_le_S
#print axioms Research.P7.S_le_log
#print axioms Research.P7.expectedDistinct_bounds
#print axioms Research.P11.clean_bounds
#print axioms Research.P11.clean_lower_attained
#print axioms Research.P11.clean_upper_attained
#print axioms Research.P11.clean_width
#print axioms Research.P11.clean_informative
#print axioms Research.P11.Pop.mtr_lower
#print axioms Research.P11.Pop.mtr_upper
#print axioms Research.P11.Pop.mtr_upper_attained
#print axioms Research.P5.rescale_pos
#print axioms Research.P5.rescale_le_one
#print axioms Research.P5.rescale_lt_one
#print axioms Research.P5.rescale_eq_one_iff
#print axioms Research.P5.reduced_coefficient
#print axioms Research.P5.ratio_is_rescaling
#print axioms Research.P2.or_eq_rr_mul
#print axioms Research.P2.rr_between
#print axioms Research.P2.or_overstates
#print axioms Research.P5.rank_reversal_exists
#print axioms Research.P5.rank_stable_of_gap
#print axioms Research.P5.identified_scores_le
#print axioms Research.P1.offence_count_bounds
#print axioms Research.P1.offence_count_eq
#print axioms Research.P1.category_not_identified
#print axioms Research.P5.survivor_hazard_mono
#print axioms Research.P5.hr2_gt_one_of_depletion
#print axioms Research.P5.hr2_witness
#print axioms Research.P8.certainty_monotone
#print axioms Research.P8.severity_monotone
#print axioms Research.P8.aggregate_monotone
#print axioms Research.P2.rate_per_offender_group
#print axioms Research.P2.null_slope_positive
#print axioms Research.P2.dyad_ratio
#print axioms Research.P2.pair_exposure_rate_constant
#print axioms Research.P8.necessity_bounds
#print axioms Research.P8.necessity_of_monotone
#print axioms Research.P8.necessity_of_disjoint
#print axioms Research.P2.collider_or_eq_background
#print axioms Research.P2.collider_or_lt_one
#print axioms Research.P2.population_or_one
#print axioms Research.P13.truncation_bias
#print axioms Research.P13.pos_part_ge
#print axioms Research.P13.pos_part_pos
#print axioms Research.P13.dl_biased_under_homogeneity
#print axioms Research.P13.tauDL_nonneg
#print axioms Research.P13.tauDL_eq_zero_iff
#print axioms Research.P13.re_weight_le
#print axioms Research.P13.re_var_ge
#print axioms Research.P13.re_var_eq_iff
#print axioms Research.P5.ll1_strictMono
#print axioms Research.P5.ll1_neg
#print axioms Research.P5.loglik_lt_shift
#print axioms Research.P5.loglik_lt_shift_quasi
#print axioms Research.P5.no_mle
#print axioms Research.P5.no_mle_quasi
#print axioms Research.P5.loglik_neg
#print axioms Research.P5.loglik_tendsto_zero
#print axioms Research.P3.cut_compl
#print axioms Research.P3.testVec_orth
#print axioms Research.P3.testVec_dnorm
#print axioms Research.P3.testVec_dirichlet
#print axioms Research.P3.rayleigh_testVec
#print axioms Research.P3.rayleigh_le_two_conductance
#print axioms Research.P3.lambda2_le_rayleigh_testVec
#print axioms Research.P3.cheeger_easy
#print axioms Research.P11.prob_mono
#print axioms Research.P11.region_coverage_le
#print axioms Research.P11.coverage_strictMono_c
#print axioms Research.P11.im_cutoff_antitone
#print axioms Research.P11.im_cutoff_between
#print axioms Research.P11.two_sided_overcovers
#print axioms Research.P12.pq_ge
#print axioms Research.P12.dd_bounds
#print axioms Research.P12.dd_complement
#print axioms Research.P12.Cells.overlaps_feasible
#print axioms Research.P12.Cells.ends_attained
#print axioms Research.P12.dd_aggregate_bounds
#print axioms Research.P11.Pop.mean_split
#print axioms Research.P11.Pop.cmean_consistent
#print axioms Research.P11.Pop.mts_mean_b_le
#print axioms Research.P11.Pop.mts_mean_a_ge
#print axioms Research.P11.Pop.mts_ate_le_naive
#print axioms Research.P11.Pop.mtr_mts_bounds
#print axioms Research.P10.pgf_mono
#print axioms Research.P10.iter_mono
#print axioms Research.P10.iter_le_fixed
#print axioms Research.P10.iter_tendsto
#print axioms Research.P10.extinction_fixed
#print axioms Research.P10.extinction_le_fixed
#print axioms Research.P10.one_sub_pgf_le
#print axioms Research.P10.subcritical_extinction_one
#print axioms Research.P10.one_sub_pgf_ge
#print axioms Research.P10.supercritical_extinction_lt_one
#print axioms Research.P14.itt_decomposition
#print axioms Research.P14.first_stage_decomposition
#print axioms Research.P14.late_identification
#print axioms Research.P14.wald_with_defiers
#print axioms Research.P14.defiers_can_flip
#print axioms Research.P15.twofold_B
#print axioms Research.P15.twofold_A
#print axioms Research.P15.threefold
#print axioms Research.P15.reference_dependence
#print axioms Research.P15.explained_eq_iff
#print axioms Research.P15.attribution_shift
#print axioms Research.P16.indicator_integral
#print axioms Research.P16.occupancy_integral
#print axioms Research.P16.little
#print axioms Research.P16.little_backlog
#print axioms Research.P16.little_target
#print axioms Research.P17.steady_state_rate
#print axioms Research.P17.cycle_rate
#print axioms Research.P17.rate_le_lam
#print axioms Research.P17.prevented_share_eq
#print axioms Research.P17.prevented_share_lt_one
#print axioms Research.P17.rate_antitone_in_S
#print axioms Research.P17.rate_antitone_in_q
#print axioms Research.P17.marginal_prevention_eq
#print axioms Research.P17.marginal_prevention_pos
#print axioms Research.P17.high_rate_more_prevented
#print axioms Research.P18.observed_rate_is_conditional
#print axioms Research.P18.nested_rate_identified
#print axioms Research.P18.fails_split
#print axioms Research.P18.unobserved_bounds
#print axioms Research.P18.unobserved_width
#print axioms Research.P18.unobserved_ends_attained
