import Researchproofs
open Research.P4
#print axioms Research.P4.naive_step_drift
#print axioms Research.P4.naive_share_increasing
#print axioms Research.P4.corrected_share_closed_form
#print axioms Research.P4.corrected_share_tendsto
#print axioms Research.P4.naiveShare_strictMono
#print axioms Research.P4.naiveShare_tendsto_one
#print axioms Research.P4.not_summable_shifted_harmonic
#print axioms Research.P4.naiveShare_rate_bound
#print axioms Research.P4.naiveTotal_ge
#print axioms Research.P5.Table.chouldechova
#print axioms Research.P5.impossibility
#print axioms Research.P5.true_base_rate_bounds
#print axioms Research.P5.lower_bound_attained
#print axioms Research.P5.upper_bound_attained
#print axioms Research.P5.trueRate_observedRate
#print axioms Research.P1.TwoSource.petersen_identity
#print axioms Research.P1.TwoSource.petersen_bounds
#print axioms Research.P1.petersen_lower_attained
#print axioms Research.P1.petersen_upper_attained
#print axioms Research.P1.true_rate_bounds
#print axioms Research.P1.dark_figure_bounds
#print axioms Research.P3.Model.exposure_adjustment
#print axioms Research.P3.Model.misspecified_exposure_bias
#print axioms Research.P3.Model.pooled_mean_mixture
#print axioms Research.P7.gini_zero_decomposition
#print axioms Research.P7.poisson_zero_prob
#print axioms Research.P2.rate_bounds
#print axioms Research.P2.disparity_bounds
#print axioms Research.P2.disparity_sign_identified
#print axioms Research.P6.aggregate_not_identifying
#print axioms Research.P6.invariance_not_necessary
#print axioms Research.P8.constant_dimension_not_identified
#print axioms Research.P8.corner_design_identified
#print axioms Research.P5.compare_decided
#print axioms Research.P5.compare_undecided
#print axioms Research.P1.conclusion_holds_below_breakdown
#print axioms Research.P1.conclusion_fails_above_breakdown
#print axioms Research.P3.Design.ht_unbiased
#print axioms Research.P3.Design.ht_contrast_unbiased
#print axioms Research.P4.rho_cap
#print axioms Research.P4.cap_zero
#print axioms Research.P4.cap_one
#print axioms Research.P4.Urn.urn_step_martingale
#print axioms Research.P4.Urn.polya_uniform
#print axioms Research.P4.Urn.polya_no_concentration
#print axioms Research.P3.Design.ht_variance
#print axioms Research.P3.Design.ht_variance_estimator_unbiased
#print axioms Research.P7.Mixture.mixture_zero_ge_exp_neg_mean
#print axioms Research.P7.Mixture.variance_eq
#print axioms Research.P7.Mixture.mixture_var_ge_mean
#print axioms Research.P7.Mixture.mixture_var_eq_mean_iff
#print axioms Research.P1.petersen_ge_floor
#print axioms Research.P1.chapman_ge_floor
#print axioms Research.P1.three_list_saturated_fits
#print axioms Research.P1.missing_cell_unconstrained
