import Researchproofs
open Research.P4
#print axioms Research.P4.naive_step_drift
#print axioms Research.P4.naive_share_increasing
#print axioms Research.P4.corrected_share_closed_form
#print axioms Research.P4.corrected_share_tendsto
#print axioms Research.P4.naiveShare_strictMono
#print axioms Research.P4.naiveShare_tendsto_one
#print axioms Research.P4.not_summable_shifted_harmonic
#print axioms Research.P4.naiveShare_rate_bound
#print axioms Research.P4.naiveTotal_ge
#print axioms Research.P5.Table.chouldechova
#print axioms Research.P5.impossibility
#print axioms Research.P5.true_base_rate_bounds
#print axioms Research.P5.lower_bound_attained
#print axioms Research.P5.upper_bound_attained
#print axioms Research.P5.trueRate_observedRate
#print axioms Research.P1.TwoSource.petersen_identity
#print axioms Research.P1.TwoSource.petersen_bounds
#print axioms Research.P1.petersen_lower_attained
#print axioms Research.P1.petersen_upper_attained
#print axioms Research.P1.true_rate_bounds
#print axioms Research.P1.dark_figure_bounds
#print axioms Research.P3.Model.exposure_adjustment
#print axioms Research.P3.Model.misspecified_exposure_bias
#print axioms Research.P3.Model.pooled_mean_mixture
#print axioms Research.P7.gini_zero_decomposition
#print axioms Research.P7.poisson_zero_prob
#print axioms Research.P2.rate_bounds
#print axioms Research.P2.disparity_bounds
#print axioms Research.P2.disparity_sign_identified
#print axioms Research.P6.aggregate_not_identifying
#print axioms Research.P6.invariance_not_necessary
#print axioms Research.P8.constant_dimension_not_identified
#print axioms Research.P8.corner_design_identified
#print axioms Research.P5.compare_decided
#print axioms Research.P5.compare_undecided
#print axioms Research.P1.conclusion_holds_below_breakdown
#print axioms Research.P1.conclusion_fails_above_breakdown
#print axioms Research.P3.Design.ht_unbiased
#print axioms Research.P3.Design.ht_contrast_unbiased
#print axioms Research.P4.rho_cap
#print axioms Research.P4.cap_zero
#print axioms Research.P4.cap_one
#print axioms Research.P4.Urn.urn_step_martingale
#print axioms Research.P4.Urn.polya_uniform
#print axioms Research.P4.Urn.polya_no_concentration
#print axioms Research.P3.Design.ht_variance
#print axioms Research.P3.Design.ht_variance_estimator_unbiased
#print axioms Research.P7.Mixture.mixture_zero_ge_exp_neg_mean
#print axioms Research.P7.Mixture.variance_eq
#print axioms Research.P7.Mixture.mixture_var_ge_mean
#print axioms Research.P7.Mixture.mixture_var_eq_mean_iff
#print axioms Research.P1.petersen_ge_floor
#print axioms Research.P1.chapman_ge_floor
#print axioms Research.P1.three_list_saturated_fits
#print axioms Research.P1.missing_cell_unconstrained
#print axioms Research.P2.offset_shift
#print axioms Research.P2.disparity_ratio_shift
#print axioms Research.P2.benchmark_product
#print axioms Research.P2.benchmark_not_additive
#print axioms Research.P9.total_invariant_of_colStochastic
#print axioms Research.P9.total_le_of_colSubstochastic
#print axioms Research.P9.reclassification_moves_ratio
#print axioms Research.P9.detection_rate_rises
#print axioms Research.P10.generation_mean
#print axioms Research.P10.cluster_size_of_lt_one
#print axioms Research.P10.stationary_rate
#print axioms Research.P10.cluster_size_diverges_of_ge_one
#print axioms Research.P10.endogeneity_share
#print axioms Research.P3.SYG.row_sum_zero
#print axioms Research.P3.SYG.syg_eq_ht
#print axioms Research.P3.SYG.syg_zero_of_const
#print axioms Research.P11.Pop.pz_compl
#print axioms Research.P11.Pop.outcome_bounds
#print axioms Research.P11.Pop.lower_attained
#print axioms Research.P11.Pop.upper_attained
#print axioms Research.P11.Pop.ate_width_one
#print axioms Research.P11.Pop.ate_contains_zero
#print axioms Research.P12.within_orth
#print axioms Research.P12.cov_decomp
#print axioms Research.P12.var_decomp
#print axioms Research.P12.var_nonneg
#print axioms Research.P12.ecological_ge
#print axioms Research.P7.log_le_S
#print axioms Research.P7.S_le_log
#print axioms Research.P7.expectedDistinct_bounds
#print axioms Research.P11.clean_bounds
#print axioms Research.P11.clean_lower_attained
#print axioms Research.P11.clean_upper_attained
#print axioms Research.P11.clean_width
#print axioms Research.P11.clean_informative
