test_that("MCSE equals mcmc::initseq, logit proportions equal metafor, Legendre equals orthopolynom", {
  skip_if_not_installed("mcmc")
  skip_if_not_installed("metafor")
  skip_if_not_installed("orthopolynom")
  e <- .morie_random_normal(800, seed = 5)
  ch <- as.numeric(stats::filter(e, 0.7, method = "recursive"))
  ref <- mcmc::initseq(ch)
  ours <- McStandardError(ch)
  expect_equal(c(ours$gamma0, ours$var_pos, ours$var_dec), c(ref$gamma0, ref$var.pos, ref$var.dec), tolerance = 1e-12)
  es <- metafor::escalc("PLO", xi = c(3, 17, 45, 8), ni = c(20, 60, 50, 9))
  lp <- LogitProportion(c(3, 17, 45, 8), c(20, 60, 50, 9))
  expect_equal(lp$yi, as.numeric(es$yi), tolerance = 1e-14)
  expect_equal(lp$vi, as.numeric(es$vi), tolerance = 1e-14)
  x <- c(-0.83, -0.2, 0.05, 0.61, 0.99)
  pl <- orthopolynom::legendre.polynomials(6)
  ref_p <- sapply(pl, function(q) as.function(q)(x))
  expect_equal(LegendrePolynomials(x, 6), ref_p, tolerance = 1e-12, ignore_attr = TRUE)
})
