test_that("Delaunay equals deldir and hull metrics equal sf", {
  skip_if_not_installed("deldir")
  skip_if_not_installed("sf")
  u <- .morie_random_uniform(120, seed = 19, stream = 0)
  P <- cbind(u[1:60], u[61:120])
  ref <- deldir::deldir(P[, 1], P[, 2])
  tl <- deldir::triang.list(ref)
  mine <- Delaunay(P)
  rt <- t(vapply(tl, function(d) sort(d$ptNum), numeric(3)))
  rt <- rt[order(rt[, 1], rt[, 2], rt[, 3]), ]
  expect_equal(mine, unname(rt), ignore_attr = TRUE)
  mp <- sf::st_multipoint(P)
  hull <- sf::st_convex_hull(mp)
  m <- HullMetrics(P)
  expect_equal(m$hull_area, sf::st_area(hull), tolerance = 1e-13)
  expect_equal(m$hull_perimeter, sf::st_length(sf::st_cast(hull, "LINESTRING")), tolerance = 1e-13)
  rr <- sf::st_minimum_rotated_rectangle(mp)
  expect_equal(m$width * m$length, sf::st_area(rr), tolerance = 1e-10)
})
