test_that("TerrainIndices, D8FlowDirection, FlowAccumulation and Watershed equal terra", {
  skip_if_not_installed("terra")
  u <- .morie_random_uniform(120, seed = 23, stream = 0)
  m <- outer(1:8, 1:11, function(i, j) 30 + 2 * i + sin(j)) + matrix(3 * u[1:88], 8, 11)
  r <- terra::rast(m, extent = terra::ext(0, 55, 0, 40), crs = "EPSG:3857")
  g <- function(x) terra::as.matrix(x, wide = TRUE)
  t <- TerrainIndices(m, res = 5)
  expect_equal(t$slope, g(terra::terrain(r, "slope", unit = "radians")), tolerance = 1e-13, ignore_attr = TRUE)
  expect_equal(t$aspect, g(terra::terrain(r, "aspect", unit = "radians")), tolerance = 1e-13, ignore_attr = TRUE)
  expect_equal(t$tri, g(terra::terrain(r, "TRI")), tolerance = 1e-13, ignore_attr = TRUE)
  fd <- terra::terrain(r, "flowdir")
  expect_equal(D8FlowDirection(m, res = 5), g(fd), ignore_attr = TRUE)
  expect_equal(FlowAccumulation(D8FlowDirection(m, res = 5)), g(terra::flowAccumulation(fd)), ignore_attr = TRUE)
})
