test_that("GWR extras equal GWmodel", {
  skip_if_not_installed("GWmodel")
  skip_if_not_installed("sp")
  u <- .morie_random_uniform(150, seed = 13, stream = 0)
  P <- cbind(10 * u[1:30], 10 * u[31:60])
  d <- data.frame(x1 = u[61:90], x2 = u[91:120])
  d$y <- 1 + (1 + 0.2 * P[, 1]) * d$x1 - 2 * d$x2 + 0.2 * u[121:150]
  spd <- sp::SpatialPointsDataFrame(P, d)
  X <- cbind(1, d$x1, d$x2)
  cd <- GWmodel::gwr.collin.diagno(y ~ x1 + x2, spd, bw = 4, kernel = "bisquare")
  cl <- GwrCollinearity(X, P, 4)
  expect_equal(do.call(rbind, cl$vif), unname(cd$VIF), tolerance = 1e-10)
  expect_equal(cl$local_cn, cd$local_CN, tolerance = 1e-10)
  expect_equal(do.call(rbind, cl$vdp), unname(cd$VDP), tolerance = 1e-10)
  expect_equal(vapply(cl$corr, `[`, 0, 3), cd$corr.mat[, 3], tolerance = 1e-10)
  NP <- rbind(c(2, 3), c(7, 1), c(5, 5))
  nd <- sp::SpatialPointsDataFrame(NP, data.frame(x1 = c(0.2, 0.5, 0.8), x2 = c(0.3, 0.9, 0.1)))
  gp <- GWmodel::gwr.predict(y ~ x1 + x2, spd, nd, bw = 4, kernel = "bisquare")
  pr <- GwrPredict(d$y, X, P, cbind(1, nd$x1, nd$x2), NP, 4)
  expect_equal(pr$prediction, gp$SDF$prediction, tolerance = 1e-10)
  expect_equal(pr$variance, gp$SDF$prediction_var, tolerance = 1e-10)
  gb <- GWmodel::gwr.basic(y ~ x1 + x2, spd, bw = 4, kernel = "bisquare", F123.test = TRUE)
  ft <- GwrFTests(d$y, X, P, 4, method = "gwmodel")
  expect_equal(c(ft$F1, ft$F2, ft$F4), unname(c(gb$Ftests$F1.test[1, 1], gb$Ftests$F2.test[1, 1], gb$Ftests$F4.test[1, 1])),
               tolerance = 1e-10)
  expect_equal(ft$F2_p, unname(gb$Ftests$F2.test[1, 4]), tolerance = 1e-10)
  expect_equal(ft$F3, unname(gb$Ftests$F3.test[, 1]), tolerance = 1e-10)
  expect_equal(ft$F3_p, unname(gb$Ftests$F3.test[, 4]), tolerance = 1e-10)
  gs <- GWmodel::gwss(spd, vars = c("x1", "x2", "y"), bw = 4, kernel = "bisquare")
  s <- GwSummary(cbind(d$x1, d$x2, d$y), P, 4)
  sdf <- as.data.frame(gs$SDF)
  expect_equal(do.call(rbind, s$mean), unname(as.matrix(sdf[, c("x1_LM", "x2_LM", "y_LM")])), tolerance = 1e-12)
  expect_equal(do.call(rbind, s$skewness), unname(as.matrix(sdf[, c("x1_LSKe", "x2_LSKe", "y_LSKe")])),
               tolerance = 1e-10)
  expect_equal(vapply(s$cov, `[`, 0, 2), sdf$Cov_x1.y, tolerance = 1e-10)
  expect_equal(vapply(s$corr, `[`, 0, 2), sdf$Corr_x1.y, tolerance = 1e-10)
  expect_equal(vapply(s$spearman, `[`, 0, 2), sdf$Spearman_rho_x1.y, tolerance = 1e-10)
})
