test_that("point-pattern extras equal spatstat and vegan", {
  skip_if_not_installed("spatstat.explore")
  skip_if_not_installed("vegan")
  u <- .morie_random_uniform(180, seed = 29, stream = 0)
  P <- cbind(u[1:60], u[61:120])
  mk <- factor(ifelse(u[121:180] < 0.4, "a", "b"))
  X <- spatstat.geom::ppp(P[, 1], P[, 2], c(0, 1), c(0, 1), marks = mk)
  for (k in 1:3) expect_equal(KnnDistances(P, k)$distance, spatstat.geom::nndist(X, k = k), tolerance = 1e-14)
  qt <- spatstat.explore::quadrat.test(spatstat.geom::unmark(X), nx = 3, ny = 2)
  q <- QuadratTest(P, c(0, 1, 0, 1), 3, 2)
  expect_equal(q$statistic, unname(qt$statistic), tolerance = 1e-12)
  expect_equal(q$p_value, qt$p.value, tolerance = 1e-12)
  expect_equal(as.vector(t(q$counts)), as.vector(t(unclass(spatstat.geom::quadratcount(X, 3, 2)))))
  rr <- c(0.05, 0.1, 0.15, 0.2)
  kc <- spatstat.explore::Kcross(X, "a", "b", r = c(0, rr), correction = "isotropic")
  expect_equal(CrossK(P, as.character(mk), "a", "b", c(0, 1, 0, 1), rr)$K, kc$iso[-1], tolerance = 1e-12)
  cnt <- c(3, 0, 5, 1, 1, 9, 0, 2, 4, 0)
  vm <- vegan::dispindmorisita(matrix(cnt, ncol = 1))
  mi <- MorisitaIndex(cnt)
  expect_equal(c(mi$imor, mi$mclu, mi$muni, mi$imst, mi$p_value), unlist(vm[1, ]), tolerance = 1e-12,
               ignore_attr = TRUE)
  set.seed(1)
  sg <- spatstat.explore::segregation.test(X, sigma = 0.1, nsim = 2, verbose = FALSE)
  expect_equal(SegregationTest(P, as.character(mk), 0.1, nsim = 2)$statistic, unname(sg$statistic), tolerance = 1e-10)
})
