test_that("KulldorffScan, BesagNewell and TangoTest equal smerc and SpatialEpi", {
  skip_if_not_installed("smerc")
  skip_if_not_installed("SpatialEpi")
  u <- .morie_random_uniform(120, seed = 53, stream = 0)
  P <- cbind(8 * u[1:25], 8 * u[26:50])
  pop <- round(300 + 700 * u[51:75])
  y <- floor(pop * 0.012 * (0.5 + u[76:100]) * ifelse(P[, 1] < 3, 2.5, 1))
  st <- suppressWarnings(smerc::scan.test(P, y, pop, nsim = 0))
  k <- KulldorffScan(P, y, pop, nsim = 0)
  expect_equal(k$all_zones[[1]], as.vector(st$clusters[[1]]$locids))
  expect_equal(k$all_tobs[1], st$clusters[[1]]$loglikrat, tolerance = 1e-10)
  expect_length(ScanZones(P, pop), length(smerc::scan.zones(P, pop)))
  bn <- SpatialEpi::besag_newell(P, pop, y, NULL, 15, 0.05)
  expect_equal(BesagNewell(P, y, pop, 15)$p_values, bn$p.values, tolerance = 1e-12)
  W <- exp(-as.matrix(stats::dist(P)))
  expect_equal(TangoTest(y, pop, W)$tstat, smerc::tango.test(y, pop, W)$tstat, tolerance = 1e-12)
})
