test_that("party measures equal manifestoR", {
  skip_if_not_installed("manifestoR")
  U <- .morie_random_uniform(400, seed = 42, stream = 0)
  codes <- c(manifestoR::rile_r(), manifestoR::rile_l(), 108, 110)
  D <- as.data.frame(matrix(round(8 * U[1:(6 * length(codes))], 3), 6, dimnames = list(NULL, paste0("per", codes))))
  D$total <- 100 + floor(300 * U[301:306])
  r <- ManifestoScales(D, total = D$total)
  expect_lt(max(abs(r$rile - as.numeric(manifestoR::rile(D)))), 1e-10)
  expect_lt(max(abs(r$logit - as.numeric(manifestoR::logit_rile(D)))), 1e-10)
  E <- matrix(round(20 * U[320:339], 3), 4)
  w <- round(40 * U[340:343], 3)
  f <- get("meyer_miller_single_election", asNamespace("manifestoR"))
  Ed <- as.data.frame(E)
  expect_lt(max(abs(PartyNicheness(E, w) - f(Ed, vars = names(Ed), weights = w))), 1e-12)
  mv <- get("median_voter_single", asNamespace("manifestoR"))
  pos <- round(100 * U[350:356] - 50, 2)
  vs <- round(40 * U[360:366], 2)
  expect_lt(abs(KimFordingMedian(pos, vs) - mv(pos, vs)), 1e-10)
  expect_lt(abs(KimFordingMedian(pos, vs, adjusted = TRUE) - mv(pos, vs, adjusted = TRUE)), 1e-10)
})
