# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Auto-generated by gen_anchors_w4d.py -- DO NOT hand-edit.
# Anchors for the wave-4d hm* module parity tests (54 modules).

A4d <- list(
  hmsdp = list(
    attention_row0 = c(0.5, 0.5),
    Y_row0 = c(0.5, 5.0),
    estimate = 0.5
  ),
  hmsatt = list(
    attn_row_sums = c(1.0, 1.0),
    estimate = 0.6697615493266569
  ),
  hmsac = list(
    policy_1 = 1.0,
    entropy_last = 2.291626408251142e-81,
    entropy_first = 4.318720746912598e-08,
    estimate = 20.0
  ),
  hmsae = list(
    recon_error = 0.0171182545653723,
    estimate = 0.0171182545653723
  ),
  hmself = list(
    task_loss_2 = 1.4298103907130839e-30,
    loss = 2.1512894269464675e-29,
    estimate = 2.1512894269464675e-29
  ),
  hmsem = list(
    theta = c(0.9999999999999982, 1.0000000000000009),
    sup_loss = 1.314768175368353e-30,
    estimate = 1.314768175368353e-30
  ),
  hmsenet = list(
    s = c(0.7310585786300049, 0.5),
    n_params = 8,
    estimate = 0.6155292893150024
  ),
  hmsent = list(
    predicted = c(1, 0),
    accuracy = 1.0,
    prob_1 = c(0.8807970779778823, 0.11920292202211755),
    estimate = 1.0
  ),
  hmseq2 = list(
    loss = 1.0986122886681098,
    perplexity = 3.0000000000000004,
    greedy = c(0, 0),
    estimate = 1.0986122886681098
  ),
  hmsft = list(
    loss_curve0 = 0.6931471805599453,
    loss = 0.003351611108214171,
    accuracy = 1.0,
    estimate = 0.003351611108214171
  ),
  hmsgdc = list(
    w = c(0.1, 0.0),
    b = 0.1,
    estimate = 0.8
  ),
  hmsil = list(
    sample0 = 0.9900497512437811,
    silhouette = 0.9899997499937498,
    estimate = 0.9899997499937498
  ),
  hmsslc = list(
    labels = c(0, 0, 0, 1, 1, 1),
    estimate = 0.3333333333333333
  ),
  hmstk = list(
    stacked_mse = 9.79502290649423e-30,
    oof_mse = c(15.0, 7.52704780398382e-30),
    estimate = 9.79502290649423e-30
  ),
  hmstr = list(
    indices = c(1, 2, 4),
    max_share_error = 0.0,
    estimate = 0.0
  ),
  hmstr2 = list(
    output_dim = 55,
    estimate = 55.0
  ),
  hmsup = list(
    theta = c(0.9999999999999994, 1.9999999999999996),
    empirical_risk = 3.470987982972452e-30,
    loo_risk = 9.724924297144239e-30,
    estimate = 3.470987982972452e-30
  ),
  hmsvdp = list(
    theta = c(0.9999999999999997, 1.0),
    rank = 2,
    estimate = 3.0814879110195774e-31
  ),
  hmsvm2 = list(
    exact = TRUE,
    n_params = 6,
    keys = c("b1", "w1"),
    max_diff = 0.0,
    estimate = 6.0
  ),
  hmswin = list(
    n_windows = 4,
    window_tokens = 4,
    shifted_layers = 0,
    Y_00 = c(0.006697844953003346, 0.0036838319638944792, 0.0014667065487241667, 0.00736542853091429),
    estimate = 64.0
  ),
  hmsymd = list(
    derivative = "2 * x",
    value = 5.43656365691809,
    error = 3.6142289161489316e-10,
    estimate = 3.0
  ),
  hmt5 = list(
    lossless = TRUE,
    sentinels = 2,
    n_masked = 3,
    estimate = 0.3333333333333333
  ),
  hmtd3 = list(
    policy_0 = 1,
    policy_updates = 20,
    overestimation_gap_nonneg = TRUE,
    estimate = 18.0
  ),
  hmtfl = list(
    initial_loss = 4.954940078498177,
    final_loss = 0.18531338665273608,
    trainable_params = 2,
    total_params = 6,
    estimate = 0.18531338665273608
  ),
  hmtsc = list(
    n_nodes = 2,
    output = c(1.0, 0.0),
    max_diff = 0.0,
    estimate = 0.0
  ),
  hmtfm = list(
    total_params = 228,
    attn_row0_sums = c(1.0, 1.0, 1.0),
    estimate = 228.0
  ),
  hmtpp = list(
    output = c(6.0, 8.0, 10.0, 12.0),
    max_diff = 0.0,
    comm_elements = 0,
    estimate = 0.0
  ),
  hmtrlf = list(
    loss_curve0 = 0.6931471805599453,
    loss_last = 0.006442950326572737,
    margin = 5.285113166562997,
    estimate = 0.006442950326572737
  ),
  hmtcmp = list(
    n_ops = 3,
    n_compiled = 1,
    output = c(30.0, 30.0),
    max_diff = 0.0,
    estimate = 5.0
  ),
  hmuns = list(
    labels = c(0, 0, 1, 1),
    recon_error = 8.766833106850698e-31,
    estimate = 0.959983993597439
  ),
  hmunsp = list(
    recon_error = 8.217301096052207e-32,
    pretrained_loo = 7.978104964147392e-30,
    estimate = 7.978104964147392e-30
  ),
  hmvgr = list(
    ratios = c(100.00000000000001, 100.0, 100.0),
    geometric_ratio = 0.010000000000000005,
    attenuation = 1e-06,
    estimate = 0.010000000000000005
  ),
  hmvae = list(
    recon_error = 0.7770352602678362,
    kl = 0.9651403146283393,
    loss_curve0 = 5.9627369453305,
    loss_curve_last = 1.6593067846727476,
    estimate = 1.7421755748961756
  ),
  hmvbgm = list(
    n_effective = 2,
    weights = c(0.4999167083125104, 0.0001665833749791771, 0.4999167083125104),
    estimate = 2.0
  ),
  hmvbrt = list(
    n_video = 4,
    n_text = 2,
    attn_row_sums = c(1.0, 1.0, 1.0, 1.0, 1.0, 1.0),
    loss = 1.578354489465859,
    estimate = 1.578354489465859
  ),
  hmvilb = list(
    n_regions = 3,
    n_tokens = 2,
    attn_v2t_row_sums = c(1.0, 1.0, 1.0),
    estimate = 0.5013362816415575
  ),
  hmvit = list(
    n_patches = 4,
    seq_len = 5,
    patch_dim = 4,
    total_params = 287,
    estimate = 287.0
  ),
  hmvqv = list(
    n_codes_used = 2,
    perplexity = 2.0,
    loss_curve0 = 11.288783469378957,
    loss_curve_last = 0.004689282936126142,
    estimate = 0.00250019370357657
  ),
  hmwemb = list(
    n_params = 12,
    sim_diag = c(0.9999999999999999, 0.9999999999999999, 1.0),
    estimate = 12.0
  ),
  hmwpt = list(
    has_double_u = TRUE,
    vocab_len = 14,
    estimate = 14.0
  ),
  hmwrst = list(
    eta = c(0.1, 0.05, 0.1),
    cycle = c(0, 0, 1),
    estimate = 0.1
  ),
  hmxcpt = list(
    trainable_params = 22855952,
    total_params = 22910480,
    n_separable = 34,
    estimate = 22855952.0
  ),
  hmxgb = list(
    predicted = c(1.0, 1.0, 10.0, 10.0),
    base_score = 5.5,
    tree0_gain = 40.5,
    tree0_left_weight = -4.5,
    estimate = 0.0
  ),
  hmxgr = list(
    ratios = c(0.1, 0.1, 0.1),
    geometric_ratio = 10.000000000000002,
    exploding = TRUE,
    estimate = 10.000000000000002
  ),
  hmxln = list(
    permutation_sorted = c(0, 1, 2, 3),
    query_diag_sum = 0.0,
    content_diag_sum = 4.0,
    total_logprob = -4.100062961191966,
    estimate = -4.100062961191966
  ),
  hmyolo = list(
    n_detections = 2,
    box0 = c(0.0, 0.0, 0.5, 0.5),
    classes = c(0, 1),
    score1 = 0.8,
    estimate = 1.0
  ),
  hmzsl = list(
    predicted_label = "positive",
    probabilities = c(0.2689414213699951, 0.7310585786300049),
    margin = 0.4621171572600098,
    estimate = 0.7310585786300049
  ),
  hmspcl = list(
    n_components = 2,
    eigenvalue0 = -2.7163567304413244e-16,
    same_group = TRUE,
    estimate = 1.9215788783046464
  ),
  hmsrnn = list(
    H = c(0.7615941559557649, 0.6420149920119997),
    h_T = c(0.6420149920119997),
    estimate = 0.6420149920119997
  ),
  hmsrp = list(
    R_flat = c(0.707106781187, 0.707106781187, 0.707106781187, 0.707106781187, 0.707106781187, 0.707106781187),
    nnz = 6,
    estimate = 1.0
  ),
  hmssg = list(
    labels = c(0, 1, 0, 1),
    pixel_accuracy = 0.5,
    iou0 = 0.5,
    estimate = 0.25
  ),
  hmtsf = list(
    forecast = c(8.999999999999996, 9.999999999999993, 10.999999999999986),
    train_mse = 3.977173730489268e-30,
    estimate = 10.999999999999986
  ),
  hmtsne = list(
    kl_curve0 = 0.9163014630489551,
    kl_curve_last = 0.006175661946490725,
    P_sum = 1.0,
    estimate = 0.006175661946490725
  ),
  hmumap = list(
    ce_curve0 = 34.399131517490204,
    ce_curve_last = 11.293802741071117,
    rho0 = 0.1,
    estimate = 11.293802741071117
  )
)
