# SPDX-License-Identifier: AGPL-3.0-or-later
# GENERATED by gen_anchors_w4a.py from the real Python morie.fn sources.
# Do not hand-edit; re-run the generator instead.
A4a <- list(
  hmcst = list(
    loss = 0.439890185198797,
    per_anchor_loss_0 = 0.3132616875182228,
    pos_sim_0 = 1.0,
    n_negatives = 1
  ),
  hmdae = list(
    final_loss = 0.018013313414740315,
    passthrough_loss = 0.05020144842600484,
    loss_history_len = 800,
    loss_history_last_below_first = TRUE
  ),
  hmdale = list(
    image_tokens = c(1, 1, 1, 1),
    token_grid = matrix(c(1, 1, 1, 1), nrow=2, ncol=2, byrow=TRUE),
    log_likelihood = -0.026861393956471868
  ),
  hmdbd = list(
    labels = c(0, 1, 0),
    signed_distance = c(-0.707106781, 0.707106781, 0.0),
    on_boundary = c(FALSE, FALSE, TRUE),
    line = c(-1.0, 1.0),
    prob_2 = 0.5
  ),
  hmdbrt = list(
    loss_ce_match = 0.0,
    agreement = 1.0,
    param_reduction = 0.391,
    loss_ce_t1 = 0.692648,
    loss_ce_t2 = 2.61187
  ),
  hmdbs = list(
    labels = c(0, 0, 1, 1, -1),
    n_clusters = 2,
    n_noise = 1,
    cluster_sizes = c(2, 2)
  ),
  hmdcg = list(
    n_layers = 2,
    gen0_params = 1152,
    sample_shape = c(16, 16),
    deconv_outs = c(8, 16),
    conv_outs = c(8, 4)
  ),
  hmdctr = list(
    self_attention = 80,
    ffn = 148,
    layer_norms = 16,
    block_params = 244,
    d_head = 2,
    embedding_params = 72,
    mask = matrix(c(FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE), nrow=3, ncol=3, byrow=TRUE),
    seq_len = 3
  ),
  hmddim = list(
    timesteps = c(4, 1),
    model_calls = 2,
    x0 = 4.0
  ),
  hmdfw = list(
    alpha_bar = c(0.5, 0.25, 0.125),
    snr = 0.142857142857,
    t0_x_t = c(2.0, -1.0)
  ),
  hmdqn = list(
    Q00 = 0.5,
    loss0 = 1.0
  ),
  hmgmm = list(
    means_sorted = c(0.1, 10.0),
    weights_sorted = c(0.5, 0.5),
    monotone = TRUE,
    converged = TRUE
  ),
  hmdrp = list(
    y_p0 = c(1.0, 2.0, 3.0),
    n_dropped_p0 = 0,
    scale_p5 = 2.0,
    y_p5 = c(0.0, 8.0, 8.0, 8.0)
  ),
  hmfa = list(
    output00 = 2.0,
    max_abs_error = 0.0
  ),
  hmddpg = list(
    action0 = 1.0,
    ou_noise0 = 0.0,
    critic_target_polyak = c(0.25, 0.25)
  ),
  hmddpm = list(
    final_below_first = TRUE,
    loss_by_t_len = 4,
    monotone = TRUE,
    sample_shape = c(1, 1)
  ),
  hmddqn = list(
    target0 = -10.0,
    vanilla0 = 10.0,
    gap0 = 20.0,
    Q00 = -10.0
  ),
  hmdeit = list(
    n_patches = 4,
    n_tokens = 6,
    patch_embed_params = 6152,
    distillation_overhead = 44
  ),
  hmdetr = list(
    feature_shape = c(7, 7),
    n_tokens = 49,
    max_detections = 10,
    encoder_attention_cost = 2401
  ),
  hmdino = list(
    loss = 0.693147181,
    teacher_entropy = 0.693147181,
    kl_to_uniform = 0.0
  ),
  hmdld = list(
    batches = list(c(0, 1, 2), c(3, 4, 5), c(6)),
    n_batches = 3,
    last_batch_size = 1,
    dropped = 0,
    shuffled_order = c(4, 3, 6, 5, 2, 0, 1)
  ),
  hmdldqn = list(
    V0 = 1.0,
    A0 = c(0.5, -0.5),
    Q0 = c(1.5, 0.5)
  ),
  hmencox = list(
    block_params = 244,
    seq_len = 5,
    cls_index = 0,
    embedding_params = 80
  ),
  hmdpo = list(
    loss_match_log2 = 0.693147181,
    prob0 = 0.5,
    margin0 = 1.0,
    loss2 = 0.313262,
    acc2 = 1.0
  ),
  hmdqnt = list(
    scale_w = 0.007874015748,
    quant_w = c(-127, 0, 127),
    compression = 4.0,
    zero_point = 0,
    act_scale = 0.015748031496
  ),
  hmdrnn = list(
    outputs1 = c(1.0, 2.0, 3.0),
    final1 = matrix(c(3.0), nrow=1, ncol=1, byrow=TRUE),
    outputs2 = c(1.0, 3.0, 6.0),
    n_params4 = 18
  ),
  hmdrv = list(
    x0_1 = 2.0,
    calls1 = 1,
    x0_2 = 3.0
  ),
  hmdthv = list(
    instability = 0.3,
    variance = 0.05,
    bias2 = 0.0
  ),
  hmdtr = list(
    n_leaves = 1,
    baseline_leaves = 2,
    train_score = 0.5,
    baseline_train_score = 1.0,
    cost = 0.5,
    n_leaves2 = 1,
    saved2 = 1
  ),
  hmdtst = list(
    pred_match = TRUE,
    thr_match = TRUE,
    thresholds = c(2.5),
    scaled_thresholds = c(243.0)
  ),
  hmeaf = list(
    normalized = matrix(c(0.5, 0.5, 0.0, 1.0), nrow=2, ncol=2, byrow=TRUE),
    top0 = c(0, 1, 0.5),
    error_rate = 0.25,
    worst_class = 0
  ),
  hmearl = list(
    best_iter_eq_200 = TRUE,
    theta1_round2 = 2.0,
    u_shaped = TRUE,
    best_lt_200 = TRUE
  ),
  hmeg = list(
    probs = c(0.1, 0.8, 0.1),
    greedy = 1
  ),
  hmelb = list(
    kl0 = 0.0,
    rec0 = -0.918938533,
    kl1 = 0.5
  ),
  hmencd = list(
    enc_block = 244,
    dec_block = 332,
    extra = 88,
    tgt_mask = matrix(c(FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE), nrow=3, ncol=3, byrow=TRUE)
  ),
  hmenet = list(
    mse = 0.0,
    l1 = 1.0,
    l2 = 1.0,
    cost = 2.0
  ),
  hmevr = list(
    evr1 = c(1.0, 0.0),
    evr2 = c(0.8, 0.2),
    var2 = c(5.333333333333, 1.333333333333)
  ),
  hmext = list(
    train_score = 1.0,
    n_trees = 9
  ),
  hmf1 = list(
    precision = 0.666667,
    recall = 1.0,
    f1 = 0.8,
    tp = 2,
    fp = 1,
    fn = 0,
    macro_f1 = 0.733333
  ),
  hmfcn = list(
    out_shape = c(2, 2, 2),
    segmentation = matrix(c(0, 1, 0, 0), nrow=2, ncol=2, byrow=TRUE)
  ),
  hmflmg = list(
    output = matrix(c(2.0, 4.0), nrow=2, ncol=1, byrow=TRUE),
    identity = TRUE,
    output2_0 = c(1.523188)
  ),
  hmfmap = list(
    fmap = matrix(c(6.0, 8.0, 12.0, 14.0), nrow=2, ncol=2, byrow=TRUE),
    sparsity0 = 0.0,
    fmap2 = matrix(c(0.0, 0.0, 3.0, 5.0), nrow=2, ncol=2, byrow=TRUE),
    sparsity2 = 0.5
  ),
  hmfmn = list(
    conv_pool_outs = c(26, 13, 11, 5),
    flatten_dim = 1600,
    total_params = 225034,
    fc_share = 0.916,
    steps_per_epoch = 1875
  ),
  hmfp16 = list(
    value1 = c(1.0),
    rel_error1 = c(0.0),
    eps = 0.0009765625,
    exponent1 = c(0),
    mantissa1 = c(0),
    overflow2 = c(TRUE, FALSE),
    underflow2 = c(FALSE, TRUE),
    rel_error3 = 0.000244141
  ),
  hmfp32 = list(
    sign1 = c(0),
    exp_field1 = c(127),
    mant_field1 = c(0),
    exponent1 = c(0),
    eps = 1.19209e-07,
    kind2 = c("inf", "zero", "subnormal")
  ),
  hmfsf = list(
    prediction = "2",
    zero_shot = "?",
    changed = TRUE,
    prompt2 = "a -> 1
c -> ",
    pred2 = "1"
  ),
  hmfth = list(
    theta1 = 0.6,
    loss1 = 9.0,
    theta2 = 3.0,
    drift2 = 3.0,
    lr_sched4 = c(0.05, 0.1, 0.1, 0.1)
  ),
  hmgan = list(
    value0 = -1.386294,
    equilibrium = -1.386294
  ),
  hmgand = list(
    anomaly_indices = c(6),
    n_anomalies = 1
  ),
  hmgbrt = list(
    init = 5.0,
    predictions = c(4.5, 4.5, 5.5, 5.5),
    predictions2 = c(0.0, 0.0, 10.0, 10.0),
    train_mse2 = 0.0
  ),
  hmgoog = list(
    total_params = 6998552,
    final_feature_map = c(1024, 7, 7),
    mod0_name = "3a",
    mod0_out_ch = 256,
    mod0_params = 163696
  ),
  hmgpt1 = list(
    total_params = 116536320,
    loss2_match_log2 = 0.693147181,
    n_predicted2 = 2,
    ppl2 = 2.0
  ),
  hmgpt2 = list(
    total_small = 124439808,
    totals_msl_xl = c(354823168, 774030080, 1557611200),
    non_embedding = 85056000
  ),
  hmgpt3 = list(
    total_parameters = 174604259328,
    d_head = 128,
    parameters_per_layer = 1812099072,
    token_embedding = 617558016,
    toy_per_layer = 244,
    toy_total = 568
  ),
  hmgrp = list(
    proj_eq_R = TRUE,
    d_in = 2,
    d_out = 3
  ),
  hmgrs = list(
    best_params = list(alpha=0.0),
    best_score = 1.0,
    n_candidates = 3,
    n_fits = 6
  )
)
