# SPDX-License-Identifier: AGPL-3.0-or-later
#
# *** AUTO-GENERATED FILE — do not hand-edit. ***
#
# Regenerate by running:
#     python3 data-raw/gen-helper-tps.py
#
# Source of truth: inst/extdata/tps_dictionary.json (extracted from
# data/datasets/TPS/PSDP_Open_Data_Documentation.pdf plus the actual
# per-category CSV headers + sampled categorical levels — see
# data-raw/gen-helper-tps.py header for the full provenance chain).
#
# Per-category TPS synthetic-data dispatcher. Each TPS dataset has its
# own column schema; the data-seeded analyzers in tps_statphysics.R and
# tps_hawkes_advanced.R check for exists("morie_tps_load_tps_dataset")
# and short-circuit if absent. By defining that loader stub here against
# globalenv() the analyzers find it via the exists() lookup and run on
# dictionary-driven synthetic Toronto data instead of NotYetPorted-ing.

.morie_tps_Assault_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = sample(c("1/1/2014 5:00:00 AM", "1/10/2014 5:00:00 AM", "1/11/2014 5:00:00 AM", "1/12/2014 5:00:00 AM", "1/13/2014 5:00:00 AM", "1/14/2014 5:00:00 AM", "1/15/2014 5:00:00 AM", "1/16/2014 5:00:00 AM", "1/17/2014 5:00:00 AM", "1/18/2014 5:00:00 AM", "1/19/2014 5:00:00 AM", "1/2/2014 5:00:00 AM", "1/20/2014 5:00:00 AM", "1/21/2014 5:00:00 AM", "1/22/2014 5:00:00 AM", "1/23/2014 5:00:00 AM", "1/24/2014 5:00:00 AM", "1/25/2014 5:00:00 AM", "1/3/2014 5:00:00 AM", "1/4/2014 5:00:00 AM", "1/5/2014 5:00:00 AM", "1/6/2014 5:00:00 AM", "1/7/2014 5:00:00 AM", "1/8/2014 5:00:00 AM", "1/9/2014 5:00:00 AM"), n, replace = TRUE),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("January","February","March","April","May","June","July","August","September","October","November","December"), n, replace = TRUE),
    `REPORT_DAY` = sample(c("1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "24", "25", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `REPORT_DOY` = sample(c("1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "24", "25", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2003", "2004", "2009", "2010", "2011", "2012", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("August", "December", "February", "January", "June", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = rep(NA_character_, n),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `UCR_CODE` = sample(c("1410", "1420", "1430", "1440", "1450", "1455", "1457", "1460", "1461", "1470", "1480"), n, replace = TRUE),
    `UCR_EXT` = sample(c("100", "110", "120"), n, replace = TRUE),
    `OFFENCE` = sample(c("Administering Noxious Thing", "Aggravated Assault", "Assault", "Assault - Force/Thrt/Impede", "Assault - Resist/ Prevent Seiz", "Assault Bodily Harm", "Assault Peace Officer", "Assault Peace Officer Wpn/Cbh", "Assault With Weapon", "Crim Negligence Bodily Harm", "Discharge Firearm - Recklessly", "Discharge Firearm With Intent", "Pointing A Firearm", "Unlawfully Causing Bodily Harm", "Use Firearm / Immit Commit Off"), n, replace = TRUE),
    `CSI_CATEGORY` = rep(NA_character_, n),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_AutoTheft_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("April", "February", "January", "March"), n, replace = TRUE),
    `REPORT_DAY` = sample(1:31, n, replace = TRUE),
    `REPORT_DOY` = sample(1:366, n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2010", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment (Rooming House, Condo)", "Bank And Other Financial Institutions (Money Mart, Tsx)", "Bar / Restaurant", "Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)", "Construction Site (Warehouse, Trailer, Shed)", "Convenience Stores", "Dealership (Car, Motorcycle, Marine, Trailer, Etc.)", "Gas Station (Self, Full, Attached Convenience)", "Go Station", "Group Homes (Non-Profit, Halfway House, Social Agency)", "Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)", "Open Areas (Lakes, Parks, Rivers)", "Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg", "Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)", "Parking Lots (Apt., Commercial Or Non-Commercial)", "Private Property Structure (Pool, Shed, Detached Garage)", "Single Home, House (Attach Garage, Cottage, Mobile)", "Streets, Roads, Highways (Bicycle Path, Private Road)", "Ttc Subway Station", "Unknown"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `UCR_CODE` = rep(NA_character_, n),
    `UCR_EXT` = rep(NA_character_, n),
    `OFFENCE` = rep(NA_character_, n),
    `CSI_CATEGORY` = rep(NA_character_, n),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_BicycleTheft_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `PRIMARY_OFFENCE` = sample(c("B&E", "B&E W'INTENT", "CARELESS DRIVING- HTA", "FRAUD UNDER", "FTC PROBATION ORDER", "INCIDENT", "INCIDENT - BICYCLE", "MISCHIEF UNDER", "POSSESSION PROPERTY OBC UNDER", "PROPERTY - FOUND", "PROPERTY - LOST", "PROPERTY - RECOVERED", "ROBBERY - MUGGING", "ROBBERY WITH WEAPON", "THEFT FROM MOTOR VEHICLE UNDER", "THEFT OVER", "THEFT UNDER", "THEFT UNDER - BICYCLE", "THEFT UNDER - SHOPLIFTING"), n, replace = TRUE),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_YEAR` = sample(c("2012", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "July", "June", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `REPORT_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("April", "February", "January", "June", "March", "May"), n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"), n, replace = TRUE),
    `REPORT_DAY` = sample(1:31, n, replace = TRUE),
    `REPORT_DOY` = sample(1:366, n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment (Rooming House, Condo)", "Bank And Other Financial Institutions (Money Mart, Tsx)", "Bar / Restaurant", "Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)", "Construction Site (Warehouse, Trailer, Shed)", "Convenience Stores", "Gas Station (Self, Full, Attached Convenience)", "Go Station", "Group Homes (Non-Profit, Halfway House, Social Agency)", "Homeless Shelter / Mission", "Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)", "Jails / Detention Centres", "Open Areas (Lakes, Parks, Rivers)", "Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg", "Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)", "Other Passenger Train", "Other Train Admin Or Support Facility", "Other Train Tracks", "Parking Lots (Apt., Commercial Or Non-Commercial)", "Private Property Structure (Pool, Shed, Detached Garage)", "Schools During Supervised Activity", "Schools During Un-Supervised Activity", "Single Home, House (Attach Garage, Cottage, Mobile)", "Streets, Roads, Highways (Bicycle Path, Private Road)", "Ttc Subway Station", "Universities / Colleges", "Unknown"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `BIKE_MAKE` = rep(NA_character_, n),
    `BIKE_MODEL` = rep(NA_character_, n),
    `BIKE_TYPE` = sample(c("BM", "EL", "FO", "MT", "OT", "RC", "RG", "SC", "TA", "TO", "TR"), n, replace = TRUE),
    `BIKE_SPEED` = rep(NA_character_, n),
    `BIKE_COLOUR` = rep(NA_character_, n),
    `BIKE_COST` = rep(NA_character_, n),
    `STATUS` = sample(c("RECOVERED", "STOLEN", "UNKNOWN"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_BreakandEnter_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("February", "January"), n, replace = TRUE),
    `REPORT_DAY` = sample(1:31, n, replace = TRUE),
    `REPORT_DOY` = sample(1:366, n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2011", "2012", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("August", "December", "February", "January", "July", "June", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment (Rooming House, Condo)", "Bar / Restaurant", "Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)", "Construction Site (Warehouse, Trailer, Shed)", "Convenience Stores", "Dealership (Car, Motorcycle, Marine, Trailer, Etc.)", "Gas Station (Self, Full, Attached Convenience)", "Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)", "Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg", "Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)", "Private Property Structure (Pool, Shed, Detached Garage)", "Religious Facilities (Synagogue, Church, Convent, Mosque)", "Schools During Un-Supervised Activity", "Single Home, House (Attach Garage, Cottage, Mobile)", "Universities / Colleges"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other"), n, replace = TRUE),
    `UCR_CODE` = rep(NA_character_, n),
    `UCR_EXT` = sample(c("200", "210", "220", "230"), n, replace = TRUE),
    `OFFENCE` = sample(c("B&E", "B&E Out", "B&E W'Intent", "Unlawfully In Dwelling-House"), n, replace = TRUE),
    `CSI_CATEGORY` = rep(NA_character_, n),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_CommunitySafetyIndicators_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = sample(c("1/1/2014 5:00:00 AM", "1/10/2014 5:00:00 AM", "1/11/2014 5:00:00 AM", "1/12/2014 5:00:00 AM", "1/13/2014 5:00:00 AM", "1/2/2014 5:00:00 AM", "1/3/2014 5:00:00 AM", "1/4/2014 5:00:00 AM", "1/5/2014 5:00:00 AM", "1/6/2014 5:00:00 AM", "1/7/2014 5:00:00 AM", "1/8/2014 5:00:00 AM", "1/9/2014 5:00:00 AM"), n, replace = TRUE),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("January","February","March","April","May","June","July","August","September","October","November","December"), n, replace = TRUE),
    `REPORT_DAY` = sample(c("1", "10", "11", "12", "13", "2", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `REPORT_DOY` = sample(c("1", "10", "11", "12", "13", "2", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2003", "2012", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("December", "January", "July", "June", "March", "May", "November", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(c("1", "10", "11", "12", "13", "14", "15", "17", "18", "19", "2", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "3", "30", "31", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = rep(NA_character_, n),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `UCR_CODE` = sample(c("1410", "1420", "1430", "1450", "1457", "1460", "1461", "1470", "1480", "1610", "2120", "2130", "2132", "2135"), n, replace = TRUE),
    `UCR_EXT` = sample(c("100", "110", "120", "130", "140", "150", "160", "180", "200", "210", "220", "230"), n, replace = TRUE),
    `OFFENCE` = rep(NA_character_, n),
    `CSI_CATEGORY` = sample(c("Assault", "Auto Theft", "Break and Enter", "Robbery", "Theft Over"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_HateCrimes_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `OCCURRENCE_YEAR` = sample(c("2014", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"), n, replace = TRUE),
    `OCCURRENCE_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCCURRENCE_TIME` = sprintf("%02d:%02d:%02d", sample(0:23, n, replace = TRUE), sample(0:59, n, replace = TRUE), sample(0:59, n, replace = TRUE)),
    `REPORTED_YEAR` = sample(c("2018", "2019", "2020", "2021", "2022", "2023"), n, replace = TRUE),
    `REPORTED_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORTED_TIME` = sprintf("%02d:%02d:%02d", sample(0:23, n, replace = TRUE), sample(0:59, n, replace = TRUE), sample(0:59, n, replace = TRUE)),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment Building (Condo, Retirement Buidling, etc.)", "Business/Retail", "Educational Institution (Universities, Colleges, Schools, etc.)", "Government Building", "Government Building (Courthouse, Museums, Parliament Building, etc.)", "House (Townhouse, Retirement Home, Garage, Vehicle, Cottage)", "Medical Facility (Hospitals, Long-term Care, etc.)", "NA", "Non-Commercial/Non for Profit", "Open Area, Park or Parking Lot", "Other Commercial / Corporate Places ", "Public Transportation", "Religious Place of Worship/Cultural Centre", "Streets/Roadways/Highway"), n, replace = TRUE),
    `AGE_BIAS` = rep(NA_character_, n),
    `MENTAL_OR_PHYSICAL_DISABILITY` = sample(c("NO", "YES"), n, replace = TRUE),
    `RACE_BIAS` = sample(c("Black", "Black, East/Southeast Asian", "Black, Latino", "Black, South Asian", "Black, White", "East/Southeast Asian", "East/Southeast Asian, South Asian, Black", "Indigenous", "Indigenous, East/Southeast Asian", "Latino", "Middle Eastern", "Other race not mentioned", "South Asian", "White"), n, replace = TRUE),
    `ETHNICITY_BIAS` = sample(c("Afghan", "African", "Arab", "Chinese", "Chinese, Arab", "Filipino", "Indian", "Indian, Filipino", "Iranian", "Israeli", "Korean", "Latino", "Mexican", "Other Ethnicity not mentioned", "Pakistani", "Palestinian", "Russian", "Somali", "Sri Lankan", "Ukrainian"), n, replace = TRUE),
    `LANGUAGE_BIAS` = sample(c("Hindi", "Spanish", "Tamil"), n, replace = TRUE),
    `RELIGION_BIAS` = sample(c("Catholic", "Christian Orthodox", "Christian Orthodox, Jewish", "Hindu", "Jewish", "Jewish, Muslim", "Muslim", "Other Christian Religion", "Sikh"), n, replace = TRUE),
    `SEXUAL_ORIENTATION_BIAS` = sample(c("2SLGBTQ+", "Gay", "Lesbian", "Lesbian, 2SLGBTQ+"), n, replace = TRUE),
    `GENDER_BIAS` = sample(c("Transgender", "Transgender Man (Identifies As Man)", "Transgender Woman (Identifies As Woman)", "Transgender, Transgender Woman (Identifies As Woman)", "Woman"), n, replace = TRUE),
    `MULTIPLE_BIAS` = sample(c("No", "Yes"), n, replace = TRUE),
    `PRIMARY_OFFENCE` = sample(c("Advocating Genocide", "Arson", "Assault", "Assault Causing Bodily Harm", "Assault Peace Officer", "Assault With a Weapon", "Causing a Disturbance", "Criminal Harassment", "Disturbing Religious Worship Or Certain Meetings", "Firearms Related Offence", "Harassing Communications", "Indecent Communications", "Mischief Interfere With Property", "Mischief Over $5000", "Mischief To Data", "Mischief To Religious Property, Educational Institutions, Etc.", "Mischief Under $5000", "Murder", "Other Criminal Code Offence Not Listed", "Public Incitement of Hatred ", "Robbery", "Sexual Assault", "Theft", "Uttering Threats - Bodily Harm", "Uttering Threats - Property", "Wilful Promotion of Hatred"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `ARREST_MADE` = sample(c("No", "Yes"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_Homicides_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_YEAR` = sample(c("2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "July", "June", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"), n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `HOMICIDE_TYPE` = sample(c("Other", "Shooting", "Stabbing"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_IntimatePartnerAndFamilyViolence_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `INDEX` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("February", "July"), n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"), n, replace = TRUE),
    `HISTORICAL` = sample(c("Historical", "Not Historical"), n, replace = TRUE),
    `FAMILY_VIOLENCE_FLAG` = sample(c("Family", "Intimate", "Unclassified"), n, replace = TRUE),
    `FAMILY_VIOLENCE_RELATION` = sample(c("Former Intimate Relationship", "Intimate Relationship", "Other Familial Relationship", "Parent-Child Relationship", "Sibling Relationship", "Unclassified/Unknown Relationship"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D55"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `COUNT` = sample(c("1", "2", "3", "4"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_NeighbourhoodCrimeRates_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID_1` = seq_len(n),
    `NEIGHBOURHOOD_NAME` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `ASSAULT_2014` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2015` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2016` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2017` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2018` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2019` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2020` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2021` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2022` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2023` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2024` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_2025` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2014` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2015` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2016` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2017` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2018` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2019` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2020` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2021` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2022` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2023` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2024` = stats::runif(n, min = 0, max = 200),
    `ASSAULT_RATE_2025` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2014` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2015` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2016` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2017` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2018` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2019` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2020` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2021` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2022` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2023` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2024` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_2025` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2014` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2015` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2016` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2017` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2018` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2019` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2020` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2021` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2022` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2023` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2024` = stats::runif(n, min = 0, max = 200),
    `AUTOTHEFT_RATE_2025` = stats::runif(n, min = 0, max = 200),
    `BIKETHEFT_2014` = rep(NA_character_, n),
    `BIKETHEFT_2015` = rep(NA_character_, n),
    `BIKETHEFT_2016` = rep(NA_character_, n),
    `BIKETHEFT_2017` = rep(NA_character_, n),
    `BIKETHEFT_2018` = rep(NA_character_, n),
    `BIKETHEFT_2019` = rep(NA_character_, n),
    `BIKETHEFT_2020` = rep(NA_character_, n),
    `BIKETHEFT_2021` = rep(NA_character_, n),
    `BIKETHEFT_2022` = rep(NA_character_, n),
    `BIKETHEFT_2023` = rep(NA_character_, n),
    `BIKETHEFT_2024` = rep(NA_character_, n),
    `BIKETHEFT_2025` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2014` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2015` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2016` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2017` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2018` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2019` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2020` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2021` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2022` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2023` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2024` = rep(NA_character_, n),
    `BIKETHEFT_RATE_2025` = rep(NA_character_, n),
    `BREAKENTER_2014` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2015` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2016` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2017` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2018` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2019` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2020` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2021` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2022` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2023` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2024` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_2025` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2014` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2015` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2016` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2017` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2018` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2019` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2020` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2021` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2022` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2023` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2024` = stats::runif(n, min = 0, max = 200),
    `BREAKENTER_RATE_2025` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_2014` = sample(c("0", "1", "2", "3"), n, replace = TRUE),
    `HOMICIDE_2015` = sample(c("0", "1", "2", "3"), n, replace = TRUE),
    `HOMICIDE_2016` = sample(c("0", "1", "2", "3", "4", "5", "6"), n, replace = TRUE),
    `HOMICIDE_2017` = sample(c("0", "1", "2", "3", "4", "5"), n, replace = TRUE),
    `HOMICIDE_2018` = sample(c("0", "1", "11", "2", "3", "4"), n, replace = TRUE),
    `HOMICIDE_2019` = sample(c("0", "1", "2", "3"), n, replace = TRUE),
    `HOMICIDE_2020` = sample(c("0", "1", "2", "3"), n, replace = TRUE),
    `HOMICIDE_2021` = sample(c("0", "1", "2", "3", "5", "6"), n, replace = TRUE),
    `HOMICIDE_2022` = sample(c("0", "1", "2", "3"), n, replace = TRUE),
    `HOMICIDE_2023` = sample(c("0", "1", "2", "3", "4", "7"), n, replace = TRUE),
    `HOMICIDE_2024` = sample(c("0", "1", "2", "3", "5"), n, replace = TRUE),
    `HOMICIDE_2025` = sample(c("0", "1", "2"), n, replace = TRUE),
    `HOMICIDE_RATE_2014` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2015` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2016` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2017` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2018` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2019` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2020` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2021` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2022` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2023` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2024` = stats::runif(n, min = 0, max = 200),
    `HOMICIDE_RATE_2025` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2014` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2015` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2016` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2017` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2018` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2019` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2020` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2021` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2022` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2023` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2024` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_2025` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2014` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2015` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2016` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2017` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2018` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2019` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2020` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2021` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2022` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2023` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2024` = stats::runif(n, min = 0, max = 200),
    `ROBBERY_RATE_2025` = stats::runif(n, min = 0, max = 200),
    `SHOOTING_2014` = sample(c("0", "1", "12", "2", "3", "4", "5", "6", "7"), n, replace = TRUE),
    `SHOOTING_2015` = sample(c("0", "1", "11", "12", "16", "2", "3", "4", "5", "6", "7"), n, replace = TRUE),
    `SHOOTING_2016` = sample(c("0", "1", "10", "11", "13", "16", "17", "2", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2017` = sample(c("0", "1", "10", "11", "12", "13", "2", "20", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2018` = sample(c("0", "1", "10", "14", "16", "17", "2", "24", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2019` = sample(c("0", "1", "11", "12", "13", "14", "15", "17", "2", "3", "31", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2020` = sample(c("0", "1", "10", "11", "12", "14", "15", "18", "19", "2", "3", "33", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2021` = sample(c("0", "1", "10", "12", "13", "14", "15", "17", "2", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2022` = sample(c("0", "1", "11", "14", "2", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2023` = sample(c("0", "1", "11", "14", "16", "2", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2024` = sample(c("0", "1", "11", "12", "13", "17", "18", "19", "2", "3", "4", "5", "7", "8", "9"), n, replace = TRUE),
    `SHOOTING_2025` = sample(c("0", "1", "10", "2", "3", "4", "5", "6", "7", "8"), n, replace = TRUE),
    `SHOOTING_RATE_2014` = rep(NA_character_, n),
    `SHOOTING_RATE_2015` = rep(NA_character_, n),
    `SHOOTING_RATE_2016` = rep(NA_character_, n),
    `SHOOTING_RATE_2017` = rep(NA_character_, n),
    `SHOOTING_RATE_2018` = rep(NA_character_, n),
    `SHOOTING_RATE_2019` = rep(NA_character_, n),
    `SHOOTING_RATE_2020` = rep(NA_character_, n),
    `SHOOTING_RATE_2021` = rep(NA_character_, n),
    `SHOOTING_RATE_2022` = rep(NA_character_, n),
    `SHOOTING_RATE_2023` = rep(NA_character_, n),
    `SHOOTING_RATE_2024` = rep(NA_character_, n),
    `SHOOTING_RATE_2025` = rep(NA_character_, n),
    `THEFTFROMMV_2014` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2015` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2016` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2017` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2018` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2019` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2020` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2021` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2022` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2023` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2024` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_2025` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2014` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2015` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2016` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2017` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2018` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2019` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2020` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2021` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2022` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2023` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2024` = stats::runif(n, min = 0, max = 200),
    `THEFTFROMMV_RATE_2025` = stats::runif(n, min = 0, max = 200),
    `THEFTOVER_2014` = sample(c("0", "1", "10", "11", "12", "15", "16", "17", "18", "19", "2", "23", "3", "30", "33", "37", "4", "41", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2015` = sample(c("1", "10", "11", "13", "14", "15", "16", "17", "18", "19", "2", "3", "30", "36", "38", "4", "46", "5", "59", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2016` = sample(c("0", "1", "10", "11", "12", "13", "16", "18", "19", "2", "20", "22", "23", "26", "27", "3", "30", "31", "38", "4", "41", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2017` = sample(c("0", "1", "10", "11", "12", "13", "14", "16", "17", "19", "2", "20", "23", "25", "27", "3", "31", "35", "39", "4", "5", "58", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2018` = sample(c("0", "1", "10", "11", "12", "13", "15", "17", "18", "2", "20", "21", "23", "25", "3", "35", "37", "4", "44", "46", "5", "50", "51", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2019` = rep(NA_character_, n),
    `THEFTOVER_2020` = sample(c("0", "1", "10", "11", "12", "13", "14", "16", "17", "18", "19", "2", "22", "23", "24", "27", "3", "32", "35", "4", "42", "5", "56", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2021` = sample(c("0", "1", "10", "11", "13", "14", "15", "17", "18", "2", "20", "21", "22", "26", "29", "3", "32", "34", "4", "5", "54", "6", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2022` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "18", "19", "2", "20", "22", "23", "3", "38", "4", "40", "44", "5", "51", "59", "6", "61", "7", "8", "9"), n, replace = TRUE),
    `THEFTOVER_2023` = rep(NA_character_, n),
    `THEFTOVER_2024` = rep(NA_character_, n),
    `THEFTOVER_2025` = rep(NA_character_, n),
    `THEFTOVER_RATE_2014` = rep(NA_character_, n),
    `THEFTOVER_RATE_2015` = rep(NA_character_, n),
    `THEFTOVER_RATE_2016` = rep(NA_character_, n),
    `THEFTOVER_RATE_2017` = rep(NA_character_, n),
    `THEFTOVER_RATE_2018` = rep(NA_character_, n),
    `THEFTOVER_RATE_2019` = rep(NA_character_, n),
    `THEFTOVER_RATE_2020` = rep(NA_character_, n),
    `THEFTOVER_RATE_2021` = rep(NA_character_, n),
    `THEFTOVER_RATE_2022` = rep(NA_character_, n),
    `THEFTOVER_RATE_2023` = rep(NA_character_, n),
    `THEFTOVER_RATE_2024` = rep(NA_character_, n),
    `THEFTOVER_RATE_2025` = rep(NA_character_, n),
    `POPULATION_2025` = rep(NA_character_, n),
    `Shape__Area` = rep(NA_character_, n),
    `Shape__Length` = rep(NA_character_, n),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_Robbery_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("April", "February", "January", "March"), n, replace = TRUE),
    `REPORT_DAY` = sample(1:31, n, replace = TRUE),
    `REPORT_DOY` = sample(1:366, n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2012", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "March", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment (Rooming House, Condo)", "Bank And Other Financial Institutions (Money Mart, Tsx)", "Bar / Restaurant", "Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)", "Convenience Stores", "Gas Station (Self, Full, Attached Convenience)", "Go Station", "Group Homes (Non-Profit, Halfway House, Social Agency)", "Homeless Shelter / Mission", "Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)", "Open Areas (Lakes, Parks, Rivers)", "Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg", "Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)", "Other Passenger Train", "Other Passenger Train Station", "Other Regional Transit System Vehicle", "Parking Lots (Apt., Commercial Or Non-Commercial)", "Religious Facilities (Synagogue, Church, Convent, Mosque)", "Schools During Supervised Activity", "Schools During Un-Supervised Activity", "Single Home, House (Attach Garage, Cottage, Mobile)", "Streets, Roads, Highways (Bicycle Path, Private Road)", "Ttc Bus", "Ttc Bus Stop / Shelter / Loop", "Ttc Subway Station", "Ttc Subway Train", "Universities / Colleges", "Unknown"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `UCR_CODE` = rep(NA_character_, n),
    `UCR_EXT` = sample(c("100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220"), n, replace = TRUE),
    `OFFENCE` = sample(c("Robbery - Armoured Car", "Robbery - Atm", "Robbery - Business", "Robbery - Delivery Person", "Robbery - Financial Institute", "Robbery - Home Invasion", "Robbery - Mugging", "Robbery - Other", "Robbery - Purse Snatch", "Robbery - Swarming", "Robbery - Taxi", "Robbery - Vehicle Jacking", "Robbery With Weapon"), n, replace = TRUE),
    `CSI_CATEGORY` = rep(NA_character_, n),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_ShootingAndFirearmDiscarges_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_YEAR` = sample(c("2004", "2005", "2006", "2007", "2008"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "July", "June", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"), n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_TIME_RANGE` = sample(c("Afternoon", "Evening", "Morning", "Night"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `DEATH` = sample(c("0", "1", "2", "3"), n, replace = TRUE),
    `INJURIES` = sample(c("0", "1", "2", "3", "4", "5", "6"), n, replace = TRUE),
    `EVENT_TYPE` = sample(c("Firearm Discharge", "Shooting"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_TheftFromMovingVehicle_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("February", "January"), n, replace = TRUE),
    `REPORT_DAY` = sample(1:31, n, replace = TRUE),
    `REPORT_DOY` = sample(1:366, n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2008", "2009", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment (Rooming House, Condo)", "Bar / Restaurant", "Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)", "Construction Site (Warehouse, Trailer, Shed)", "Dealership (Car, Motorcycle, Marine, Trailer, Etc.)", "Gas Station (Self, Full, Attached Convenience)", "Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)", "Open Areas (Lakes, Parks, Rivers)", "Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg", "Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)", "Parking Lots (Apt., Commercial Or Non-Commercial)", "Private Property Structure (Pool, Shed, Detached Garage)", "Schools During Supervised Activity", "Schools During Un-Supervised Activity", "Single Home, House (Attach Garage, Cottage, Mobile)", "Streets, Roads, Highways (Bicycle Path, Private Road)", "Ttc Bus", "Ttc Subway Station", "Unknown"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `UCR_CODE` = sample(c("2132", "2142"), n, replace = TRUE),
    `UCR_EXT` = rep(NA_character_, n),
    `OFFENCE` = sample(c("Theft From Motor Vehicle Over", "Theft From Motor Vehicle Under"), n, replace = TRUE),
    `CSI_CATEGORY` = sample(c("NonMCI", "Theft Over"), n, replace = TRUE),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_tps_TheftOver_panel <- function(n = 200L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `OBJECTID` = seq_len(n),
    `EVENT_UNIQUE_ID` = sprintf("evt-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `REPORT_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `OCC_DATE` = format(as.POSIXct("2014-01-01 00:00:00", tz = "UTC") + sample.int(86400L * 365L * 12L, n, replace = TRUE), "%Y-%m-%dT%H:%M:%S.000Z"),
    `REPORT_YEAR` = sample(2014:2026, n, replace = TRUE),
    `REPORT_MONTH` = sample(c("April", "August", "December", "February", "January", "July", "June", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `REPORT_DAY` = sample(1:31, n, replace = TRUE),
    `REPORT_DOY` = sample(1:366, n, replace = TRUE),
    `REPORT_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `REPORT_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `OCC_YEAR` = sample(c("2000", "2004", "2006", "2008", "2009", "2010", "2011", "2012", "2013", "2014"), n, replace = TRUE),
    `OCC_MONTH` = sample(c("April", "August", "December", "February", "January", "July", "June", "March", "May", "November", "October", "September"), n, replace = TRUE),
    `OCC_DAY` = sample(1:31, n, replace = TRUE),
    `OCC_DOY` = sample(1:366, n, replace = TRUE),
    `OCC_DOW` = sample(c("Friday    ", "Monday    ", "Saturday  ", "Sunday    ", "Thursday  ", "Tuesday   ", "Wednesday "), n, replace = TRUE),
    `OCC_HOUR` = sample(c("0", "1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "3", "4", "5", "6", "7", "8", "9"), n, replace = TRUE),
    `DIVISION` = sample(c("D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"), n, replace = TRUE),
    `LOCATION_TYPE` = sample(c("Apartment (Rooming House, Condo)", "Bank And Other Financial Institutions (Money Mart, Tsx)", "Bar / Restaurant", "Commercial Dwelling Unit (Hotel, Motel, B & B, Short Term Rental)", "Construction Site (Warehouse, Trailer, Shed)", "Convenience Stores", "Dealership (Car, Motorcycle, Marine, Trailer, Etc.)", "Gas Station (Self, Full, Attached Convenience)", "Homeless Shelter / Mission", "Hospital / Institutions / Medical Facilities (Clinic, Dentist, Morgue)", "Open Areas (Lakes, Parks, Rivers)", "Other Commercial / Corporate Places (For Profit, Warehouse, Corp. Bldg", "Other Non Commercial / Corporate Places (Non-Profit, Gov'T, Firehall)", "Other Passenger Train", "Other Train Yard", "Parking Lots (Apt., Commercial Or Non-Commercial)", "Police / Courts (Parole Board, Probation Office)", "Private Property Structure (Pool, Shed, Detached Garage)", "Religious Facilities (Synagogue, Church, Convent, Mosque)", "Retirement Home", "Schools During Supervised Activity", "Schools During Un-Supervised Activity", "Single Home, House (Attach Garage, Cottage, Mobile)", "Streets, Roads, Highways (Bicycle Path, Private Road)", "Ttc Admin Or Support Facility", "Ttc Bus", "Ttc Subway Station", "Universities / Colleges", "Unknown"), n, replace = TRUE),
    `PREMISES_TYPE` = sample(c("Apartment", "Commercial", "Educational", "House", "Other", "Outside", "Transit"), n, replace = TRUE),
    `UCR_CODE` = sample(c("2130", "2132", "2133"), n, replace = TRUE),
    `UCR_EXT` = sample(c("200", "210", "220", "230"), n, replace = TRUE),
    `OFFENCE` = sample(c("Theft - Misapprop Funds Over", "Theft From Mail / Bag / Key", "Theft From Motor Vehicle Over", "Theft Of Utilities Over", "Theft Over", "Theft Over - Shoplifting"), n, replace = TRUE),
    `CSI_CATEGORY` = rep(NA_character_, n),
    `HOOD_158` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_158` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `HOOD_140` = sample(sprintf('%03d', 1:158), n, replace = TRUE),
    `NEIGHBOURHOOD_140` = sample(c('West Humber-Clairville', 'Mount Olive-Silverstone-Jamestown', 'Thistletown-Beaumond Heights', 'Rexdale-Kipling', 'Elms-Old Rexdale', 'Kingsview Village-The Westway', 'Willowridge-Martingrove-Richview'), n, replace = TRUE),
    `LONG_WGS84` = stats::runif(n, min = -79.62, max = -79.13),
    `LAT_WGS84` = stats::runif(n, min = 43.58, max = 43.88),
    `x` = stats::runif(n, min = -1, max = 1),
    `y` = stats::runif(n, min = -1, max = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

.morie_tps_canonical_map <- list(
  "assault" = "Assault",
  "autotheft" = "AutoTheft",
  "bicycletheft" = "BicycleTheft",
  "breakandenter" = "BreakandEnter",
  "communitysafetyindicators" = "CommunitySafetyIndicators",
  "hatecrimes" = "HateCrimes",
  "homicides" = "Homicides",
  "intimatepartnerandfamilyviolence" = "IntimatePartnerAndFamilyViolence",
  "neighbourhoodcrimerates" = "NeighbourhoodCrimeRates",
  "robbery" = "Robbery",
  "shootingandfirearmdiscarges" = "ShootingAndFirearmDiscarges",
  "theftfrommovingvehicle" = "TheftFromMovingVehicle",
  "theftover" = "TheftOver"
)

.morie_tps_canonical_internal <- function(name) {
  k <- tolower(as.character(name))
  if (k %in% names(.morie_tps_canonical_map))
    return(.morie_tps_canonical_map[[k]])
  # Fall back to first registered category so the loader never NULL-fails
  .morie_tps_canonical_map[[1L]]
}

#' Build a synthetic TPS data.frame matching the schema + categorical
#' vocabulary of the given category (case-insensitive).
make_synthetic_tps <- function(category, n = 1000L, seed = 1L) {
  cat <- .morie_tps_canonical_internal(category)
  helper_name <- paste0(".morie_tps_", cat, "_panel")
  fn <- get(helper_name, envir = environment())
  fn(n = n, seed = seed)
}

# ---- loader stubs ----------------------------------------------------
#
# tps_statphysics.R and tps_hawkes_advanced.R call exists("morie_tps_-
# load_tps_dataset", mode = "function") to decide whether to dispatch
# the data-seeded path or stop with "NotYetPorted". Assigning the
# loader into globalenv() satisfies the exists() check and lets the
# analyzers exercise their core algorithms during testing.

if (!exists("morie_tps_load_tps_dataset", envir = globalenv(),
            mode = "function", inherits = FALSE)) {
  assign("morie_tps_load_tps_dataset",
         function(category, nrows = NULL) {
           n <- if (is.null(nrows)) 1000L else as.integer(nrows)
           make_synthetic_tps(category, n = n, seed = 1L)
         },
         envir = globalenv())
}

if (!exists("morie_tps_load_tps", envir = globalenv(),
            mode = "function", inherits = FALSE)) {
  assign("morie_tps_load_tps",
         function(category, nrows = NULL, format = "csv", ...) {
           # `format` accepted but ignored — synthetic frames carry the
           # canonical columns regardless of physical export format.
           n <- if (is.null(nrows)) 1000L else as.integer(nrows)
           make_synthetic_tps(category, n = n, seed = 1L)
         },
         envir = globalenv())
}
