# SPDX-License-Identifier: AGPL-3.0-or-later
#
# *** AUTO-GENERATED FILE — do not hand-edit. ***
#
# Regenerate by running:
#     python3 data-raw/gen-helper-arsau.py
#
# Source of truth: 3 bundled ARSAU XLSX dictionaries
#     inst/extdata/arsau_2020_2022_dictionary.json
#     inst/extdata/arsau_2023_dictionary.json
#     inst/extdata/arsau_2024_dictionary.json
# Each generated `.morie_arsau_<year>_<kind>_panel(n, seed)` fixture
# uses the REAL columns + REAL categorical-level vocabularies for
# that (year, kind) entry from the dictionary.
#
# `stage_synthetic_arsau(root)` writes every registered (year, kind)
# CSV under the right layout (root/<year_or_range>/<csv_filename>) so
# the existing morie_arsau_load_* loaders find them after we set
# MORIE_ARSAU_DIR = root for the test.

.morie_arsau_2020_2022_aggregate_summary_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `id_` = sample(0:50, n, replace = TRUE),
    `SECTION` = sample(c("REPORT_SCOPE, REPORT_TYPE, TEAM_TYPE, LENGTH_OF_SERVICE_CATEGORY, LENGTH_OF_SERVICE_STATISTIC, RANK, RANK, ATTIRE, ASSIGNMENT_TYPE, NUMBER_OF_SUBJECTS, POLICE_OFFICERS_INVOLVED, REASON_FORCE, WEAPONS_CARRIED, TYPE_FORCE, RACE"), n, replace = TRUE),
    `CATEGORY` = sample(c("1 to 3 Subjects - Individual Reports, 1 to 3 Subjects - Team Reports, 4 or More Subject Reports, Out of Scope for Race-Based Analysis, Submitted Reports, Individual, Team, Specialized Team, Tactical or Emergency Response Team, Unknown, 0 to 4 years, 5 to 9 years, 10 to 14 years, 15 to 19 years, 20 to 24 years, 25 to 29 years, 30 to 34 years, 35 to 39 years, 40 to 54 years, Maximum Length of Service, Median Length of Service, Minimum Length of Service, Constable, Management, Sergeant/Detective, Civilian clothes, Missing, Uniform, Drugs, Investigation, Other, Patrol, Specialized Unit, Tactical, Traffic, One, Three, Two, 1 to 5 Officers, 6 to 10 Officers, More than 10 Officers, Maximum Number of Officers, Median Number of Officers, Minimum Number of Officers, Accidental, Effect Arrest, Prevent Commission of Offence, Prevent Escape, Protect Other Officer, Protect Public, Protect Self, Protect Subject, Firearm, Impact Weapon, Knife/Edged Weapon, Other Weapon, Unarmed, Unknown Weapon, Aerosol, CEW, Empty Hand Hard, Empty Hand Soft, Firearm Discharged, Firearm Pointed/Unknown, Handgun Drawn, Impact Weapon Hard, Impact Weapon Soft, LLF Discharged, LLF Pointed/Unknown, Physical Force, Black, East/Southeast Asian, Indigenous, Latino, Middle Eastern, Multiple Races, South Asian, White"), n, replace = TRUE),
    `UNITS OF MEASURE` = sample(c("Number of Reports, Percentage of Reports, Percentage of Team Reports, Percentage of Individual Reports, Number of Years, Number of Officers"), n, replace = TRUE),
    `YEAR_2020` = rep(NA, n),
    `YEAR_2021` = rep(NA, n),
    `YEAR_2022` = rep(NA, n),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2020_2022_detailed_dataset_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `id_` = sample(0:50, n, replace = TRUE),
    `REPORTING_YEAR` = sample(2018:2024, n, replace = TRUE),
    `RECORD_ID` = rep(NA_character_, n),
    `POLICE_SERVICE` = sample(c("Aylmer Police Service, Barrie Police Service, Belleville Police Service, Brantford Police Service, Brockville Police Service, Chatham-Kent Police Service, Cobourg Police Service, Cornwall Police Service, Deep River Police Service, Dryden Police Service, Durham Regional Police Service, Gananoque Police Service, Greater Sudbury Police Service, Guelph Police Service, Halton Regional Police Service, Hamilton Police Service, Hanover Police Service, Kawartha Lakes Police Service, Kingston Police Service, LaSalle Police Service, London Police Service, Niagara Regional Police Service, North Bay Police Service, OPP, Ottawa Police Service, Owen Sound Police Service, Peel Regional Police Service, Peterborough Police Service, Port Hope Police Service, Sarnia Police Service, Saugeen Shores Police Service, Sault Ste Marie Police Service, Smiths Falls Police Service, South Simcoe Police Service, St Thomas Police Service, Stratford Police Service, Strathroy-Caradoc Police Service, Thunder Bay Police Service, Timmins Police Service, Toronto Police Service, Waterloo Regional Police Service, West Grey Police Service, Windsor Police Service, Woodstock Police Service, York Regional Police Service"), n, replace = TRUE),
    `REPORT_TYPE` = sample(c("Individual, Team"), n, replace = TRUE),
    `TEAM_TYPE` = sample(c("Tactical or Emergency Response Team, Specialized Team, Unknown"), n, replace = TRUE),
    `NUMBER_POLICE_OFFICERS_INVOLVED` = sample(0:50, n, replace = TRUE),
    `ASSIGNMENT_TYPE` = sample(c("Drugs, Investigation, Patrol, Specialized Unit, Tactical, Traffic, Other"), n, replace = TRUE),
    `TYPE_INCIDENT_ALARM` = sample(c("Alarm"), n, replace = TRUE),
    `TYPE_INCIDENT_BREAK_ENTER` = sample(c("Break and Enter"), n, replace = TRUE),
    `TYPE_INCIDENT_DOMESTIC_DISTURBANCE` = sample(c("Domestic Disturbance"), n, replace = TRUE),
    `TYPE_INCIDENT_HOMICIDE` = sample(c("Homicide"), n, replace = TRUE),
    `TYPE_INCIDENT_OTHER_DISTURBANCE` = sample(c("Other Disturbance"), n, replace = TRUE),
    `TYPE_INCIDENT_ROBBERY` = sample(c("Robbery"), n, replace = TRUE),
    `TYPE_INCIDENT_SERIOUS_INJURY` = sample(c("Serious Injury"), n, replace = TRUE),
    `TYPE_INCIDENT_SUSPICIOUS_PERSON` = sample(c("Suspicious Person"), n, replace = TRUE),
    `TYPE_INCIDENT_TRAFFIC` = sample(c("Traffic"), n, replace = TRUE),
    `TYPE_INCIDENT_WEAPONS_CALL` = sample(c("Weapons Call"), n, replace = TRUE),
    `TYPE_INCIDENT_OTHER` = sample(c("Other"), n, replace = TRUE),
    `POLICE_PRESENCE` = sample(c("Officer Alone, Police Assisted"), n, replace = TRUE),
    `NUMBER_OF_POLICE_PRESENT` = sample(0:50, n, replace = TRUE),
    `ATTIRE` = sample(c("Uniform, Civilian clothes, Missing"), n, replace = TRUE),
    `NUMBER_OF_SUBJECTS` = sample(c("One, Two, Three, Four or More"), n, replace = TRUE),
    `RACE_SUBJECT1` = sample(c("Black, East/Southeast Asian, Indigenous,  Latino, Middle Eastern, South Asian, White"), n, replace = TRUE),
    `RACE_SUBJECT2` = sample(c("Black, East/Southeast Asian, Indigenous, Latino, Middle Eastern,  South Asian, White"), n, replace = TRUE),
    `RACE_SUBJECT3` = sample(c("Black, East/Southeast Asian, Indigenous, Latino, Middle Eastern,  South Asian, White"), n, replace = TRUE),
    `RACE` = sample(c("Black, East/Southeast Asian,  Indigenous, Latino, Middle Eastern, Multiple Races, South Asian, White"), n, replace = TRUE),
    `TYPE_FORCE_FIREARM_DISCHARGED` = sample(c("Firearm Discharged"), n, replace = TRUE),
    `TYPE_FORCE_FIREARM_DISCHARGED_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_FIREAM_DISCHARGED_FORCE_EFFECTIVE` = sample(c("Yes,  No"), n, replace = TRUE),
    `TYPE_FORCE_FIREARM_POINTED_UNKNOWN` = sample(c("Firearm Pointed/Unknown"), n, replace = TRUE),
    `TYPE_FORCE_FIREAM_POINTED_AT_PERSON_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_FIREAM_POINTED_AT_PERSON_FORCE_EFFECTIVE` = sample(c("Yes,  No"), n, replace = TRUE),
    `TYPE_FORCE_HANDGUN_DRAWN` = sample(c("Handgun Drawn"), n, replace = TRUE),
    `TYPE_FORCE_HANDGUN_DRAWN_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_HANDGUN_DRAWN_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `TYPE_FORCE_LLF_DISCHARGED` = sample(c("LLF Discharged"), n, replace = TRUE),
    `TYPE_FORCE_LLF_POINTED_UNKOWN` = sample(c("LLF Pointed/Unknown"), n, replace = TRUE),
    `TYPE_FORCE_CEW` = sample(c("CEW"), n, replace = TRUE),
    `TYPE_FORCE_IMPACT_WEAPON_HARD` = sample(c("Impact Weapon Hard"), n, replace = TRUE),
    `TYPE_FORCE_IMPACT_WEAPON_HARD_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_IMPACT_WEAPON_HARD_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `TYPE_FORCE_IMPACT_WEAPON_SOFT` = sample(c("Impact Weapon Soft"), n, replace = TRUE),
    `TYPE_FORCE_IMPACT_WEAPON_SOFT_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_IMPACT_WEAPON_SOFT_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `TYPE_FORCE_AEROSOL` = sample(c("Aerosol"), n, replace = TRUE),
    `TYPE_FORCE_USED_AEROSOL_WEAPON_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_USED_AEROSOL_WEAPON_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `TYPE_FORCE_EMPTY_HAND_HARD` = sample(c("Empty Hand Hard"), n, replace = TRUE),
    `TYPE_FORCE_EMPTY_HAND_TECHNIQUES_HARD_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_EMPTY_HAND_TECHNIQUES_HARD_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `TYPE_FORCE_EMPTY_HAND_SOFT` = sample(c("Empty Hand Soft"), n, replace = TRUE),
    `TYPE_FORCE_EMPTY_HAND_TECHNIQUES_SOFT_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_EMPTY_HAND_TECHNIQUES_SOFT_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `TYPE_FORCE_PHYSICAL_FORCE` = sample(c("Physical Force"), n, replace = TRUE),
    `TYPE_FORCE_OTHER` = sample(c("Other"), n, replace = TRUE),
    `TYPE_FORCE_OTHER_RANK` = sample(0:50, n, replace = TRUE),
    `TYPE_FORCE_OTHER_FORCE_EFFECTIVE` = sample(c("Yes, No"), n, replace = TRUE),
    `REASON_FORCE_EFFECT_ARREST` = sample(c("Effect Arrest"), n, replace = TRUE),
    `REASON_FORCE_PROTECT_SELF` = sample(c("Protect Self"), n, replace = TRUE),
    `REASON_FORCE_PROTECT_PUBLIC` = sample(c("Protect Public"), n, replace = TRUE),
    `REASON_FORCE_PREVENT_ESCAPE` = sample(c("Prevent Escape"), n, replace = TRUE),
    `REASON_FORCE_ACCIDENTAL` = sample(c("Accidental"), n, replace = TRUE),
    `REASON_FORCE_PREVENT_COMMISSION_OF_OFFENCE` = sample(c("Prevent Commission of Offence"), n, replace = TRUE),
    `REASON_FORCE_OTHER` = sample(c("Other"), n, replace = TRUE),
    `REASON_FORCE_PROTECT_OTHER_OFFICER` = sample(c("Protect Other Officer"), n, replace = TRUE),
    `REASON_FORCE_PROTECT_SUBJECT` = sample(c("Protect Subject"), n, replace = TRUE),
    `TYPE_FIREARM_USED_REVOLVER_CHECK` = sample(c("Revolver"), n, replace = TRUE),
    `TYPE_FIREARM_USED.REVOLVER_NUMBER_ROUNDS` = sample(0:50, n, replace = TRUE),
    `TYPE_FIREARM_USED_RIFLE_CHECK` = sample(c("Rifle"), n, replace = TRUE),
    `TYPE_FIREARM_USED_RIFLE_NUMBER_ROUNDS` = sample(0:50, n, replace = TRUE),
    `TYPE_FIREARM_USED_SEMIAUTOMATIC_CHECK` = sample(c("Semi-automatic"), n, replace = TRUE),
    `TYPE_FIREARM_USED_SEMIAUTOMATIC_NUMBER_ROUNDS` = sample(0:50, n, replace = TRUE),
    `TYPE_FIREARM_USED_SHOTGUN_CHECK` = sample(c("Shotgun"), n, replace = TRUE),
    `TYPE_FIREARM_USED_SHOTGUN_NUMBER_ROUNDS` = sample(0:50, n, replace = TRUE),
    `TYPE_FIREARM_USED_OTHER_CHECK` = sample(c("Other"), n, replace = TRUE),
    `TYPE_FIREARM_USED_OTHER_NUMBER_ROUNDS` = sample(0:50, n, replace = TRUE),
    `DISTANCE_SUBJECT1` = sample(c("Less than 2 metres, 2 to 3 metres, 3 to 5 metres, 5 to 7 metres,  7 to 10 metres, Greater than 10 metres"), n, replace = TRUE),
    `DISTANCE_SUBJECT2` = sample(c("Less than 2 metres, 2 to 3 metres, 3 to 5 metres, 5 to 7 metres,  7 to 10 metres, Greater than 10 metres"), n, replace = TRUE),
    `DISTANCE_SUBJECT3` = sample(c("Less than 2 metres, 2 to 3 metres, 3 to 5 metres, 5 to 7 metres,  7 to 10 metres, Greater than 10 metres"), n, replace = TRUE),
    `ALTERNATIVE_STRATEGIES_USED_CONCEALMENT` = sample(c("Concealment"), n, replace = TRUE),
    `ALTERNATIVE_STRATEGIES_USED_COVER` = sample(c("Cover"), n, replace = TRUE),
    `ALTERNATIVE_STRATEGIES_USED_VERBAL_INTERACTION` = sample(c("Verbal Interaction"), n, replace = TRUE),
    `ALTERNATIVE_STRATEGIES_USED_OTHER` = sample(c("Other"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_BASEBALLBATCLUB` = sample(c("Baseball Bat/Club for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_BASEBALLBATCLUB` = sample(c("Baseball Bat/Club for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_BASEBALLBATCLUB` = sample(c("Baseball Bat/Club for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_KNIFEEDGEDWEAPON` = sample(c("Knife/Edged Weapon for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_KNIFEEDGEDWEAPON` = sample(c("Knife/Edged Weapon for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_KNIFEEDGEDWEAPON` = sample(c("Knife/Edged Weapon for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_REVOLVER` = sample(c("Revolver for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_REVOLVER` = sample(c("Revolver for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_REVOLVER` = sample(c("Revolver for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_RIFLE` = sample(c("Rifle for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_RIFLE` = sample(c("Rifle for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_RIFLE` = sample(c("Rifle for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_SEMIAUTOMATIC` = sample(c("Semi-automatic for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_SEMIAUTOMATIC` = sample(c("Semi-automatic for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_SEMIAUTOMATIC` = sample(c("Semi-automatic for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_SHOTGUN` = sample(c("Shotgun for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_SHOTGUN` = sample(c("Shotgun for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_SHOTGUN` = sample(c("Shotgun for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_NONE` = sample(c("None for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_NONE` = sample(c("None for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_NONE` = sample(c("None for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_UNKNOWN` = sample(c("Unknown for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_UNKNOWN` = sample(c("Unknown for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_UNKNOWN` = sample(c("Unknown for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT1_OTHER` = sample(c("Other for Subject 1"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT2_OTHER` = sample(c("Other for Subject 2"), n, replace = TRUE),
    `WEAPONS_CARRIED_SUBJECT3_OTHER` = sample(c("Other for Subject 3"), n, replace = TRUE),
    `WEAPONS_CARRIED_FIREARM` = sample(c("Firearm, NA"), n, replace = TRUE),
    `WEAPONS_CARRIED_KNIFE_EDGED_WEAPON` = sample(c("Knife/Edged Weapon, NA"), n, replace = TRUE),
    `WEAPONS_CARRIED_IMPACT_WEAPON` = sample(c("Impact Weapon, NA"), n, replace = TRUE),
    `WEAPONS_CARRIED_UNARMED` = sample(c("Unarmed, NA"), n, replace = TRUE),
    `WEAPONS_CARRIED_UNKNOWN_WEAPON` = sample(c("Unknown Weapon, NA"), n, replace = TRUE),
    `WEAPONS_CARRIED_OTHER_WEAPON` = sample(c("Other Weapon, NA"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT1_ATHAND` = sample(c("At Hand for Subject 1"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT2_ATHAND` = sample(c("At Hand for Subject 2"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT3_ATHAND` = sample(c("At Hand for Subject 3"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT1_CONCEALED_PERSON` = sample(c("Concealed on person for Subject 1"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT2_CONCEALED_PERSON` = sample(c("Concealed on person for Subject 2"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT3_CONCEALED_PERSON` = sample(c("Concealed on person for Subject 3"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT1_INHAND` = sample(c("In-hand for Subject 1"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT2_INHAND` = sample(c("In-hand for Subject 2"), n, replace = TRUE),
    `LOCATION_WEAPONS_SUBJECT3_INHAND` = sample(c("In-hand for Subject 3"), n, replace = TRUE),
    `TOTALROUNDSFIRED_ALLSUBJECTS` = sample(0:50, n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_LANEWAY` = sample(c("Outdoors-Laneway"), n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_MOTOR_VEHICLE` = sample(c("Outdoors-Motor Vehicle"), n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_PARK` = sample(c("Outdoors-Park"), n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_ROADWAY` = sample(c("Outdoors-Roadway"), n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_RURAL` = sample(c("Outdoors-Rural"), n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_YARD` = sample(c("Outdoors-Yard"), n, replace = TRUE),
    `LOCATION_INCIDENT_OUTDOOR_OTHER` = sample(c("Outdoors-Other"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_APARTMENT` = sample(c("Indoors-Apartment"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_HALLWAY` = sample(c("Indoors-Hallway"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_PRIVATE_PROPERTY_HOUSE` = sample(c("Indoors-House"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_COMMERCIAL_SITE` = sample(c("Indoors-Commercial Site"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_FINANCIAL_INSTITUTION` = sample(c("Indoors-Financial Institution"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_PUBLIC_PROPERTY_PUBLIC_INSTITUTION` = sample(c("Indoors-Public Institution"), n, replace = TRUE),
    `LOCATION_INCIDENT_INDOOR_OTHER` = sample(c("Indoors-Other"), n, replace = TRUE),
    `WEATHER_CONDITIONS_CLEAR` = sample(c("Clear"), n, replace = TRUE),
    `WEATHER_CONDITIONS_CLOUDY` = sample(c("Cloudy"), n, replace = TRUE),
    `WEATHER_CONDITIONS_FOG` = sample(c("Fog"), n, replace = TRUE),
    `WEATHER_CONDITIONS_RAIN` = sample(c("Rain"), n, replace = TRUE),
    `WEATHER_CONDITIONS_SNOW_SLEET` = sample(c("Snow/Sleet"), n, replace = TRUE),
    `WEATHER_CONDITIONS_SUNNY` = sample(c("Sunny"), n, replace = TRUE),
    `WEATHER_CONDITIONS_OTHER` = sample(c("Other"), n, replace = TRUE),
    `LIGHTING_CONDITIONS_DARK` = sample(c("Dark"), n, replace = TRUE),
    `LIGHTING_CONDITIONS_DAYLIGHT` = sample(c("Daylight"), n, replace = TRUE),
    `LIGHTING_CONDITIONS_DUSK` = sample(c("Dusk"), n, replace = TRUE),
    `LIGHTING_CONDITIONS_GOOD_ARTIFICIAL_LIGHT` = sample(c("Good Artificial Light"), n, replace = TRUE),
    `LIGHTING_CONDITIONS_POOR_ARTIFICIAL_LIGHT` = sample(c("Poor Artificial Light"), n, replace = TRUE),
    `LIGHTING_CONDITIONS_OTHER` = sample(c("Other"), n, replace = TRUE),
    `PERSON_INJURED_SELF_MEDICAL_ATTENTION_REQUIRED` = sample(c("Yes, No"), n, replace = TRUE),
    `PERSON _INJURED_SELF_NATUREINJURIES` = sample(c("Minor, Serious"), n, replace = TRUE),
    `PERSON_INJURED_OTHER_POLICE_OFFICER_MEDICAL_ATTENTION_REQUIRED` = sample(c("Yes, No"), n, replace = TRUE),
    `PERSON_INJURED_OTHER_POLICE_OFFICER_NATURE_INJURIES` = sample(c("Minor, Serious, Fatal, Unknown"), n, replace = TRUE),
    `PERSON_INJURED_THIRD PARTY_MEDICAL_ATTENTION_REQUIRED` = sample(c("Yes, No"), n, replace = TRUE),
    `PERSON_INJURED_THIRD_PARTY_NATURE_INJURIES` = sample(c("Minor, Serious, Fatal, Unknown"), n, replace = TRUE),
    `PERSON_INJURED_SUBJECT1_MEDICAL_ATTENTION_REQUIRED` = sample(c("Yes, No"), n, replace = TRUE),
    `PERSON_INJURED_SUBJECT1_NATURE_INJURIES` = sample(c("Minor, Serious, Fatal, Unknown"), n, replace = TRUE),
    `PERSON_INJURED_SUBJECT2_MEDICAL_ATTENTION_REQUIRED` = sample(c("Yes, No"), n, replace = TRUE),
    `PERSON_INJURED_SUBJECT2_NATURE_INJURIES` = sample(c("Minor, Serious, Fatal, Unknown"), n, replace = TRUE),
    `PERSON_INJURED_SUBJECT3_MEDICAL_ATTENTION_REQUIRED` = sample(c("Yes, No"), n, replace = TRUE),
    `PERSON_INJURED_SUBJECT3_NATURE_INJURIES` = sample(c("Minor, Serious, Fatal, Unknown"), n, replace = TRUE),
    `REVIEWED_SUPERVISOR` = sample(c("Yes, No"), n, replace = TRUE),
    `REVIEWED_TRAINING_ANALYST` = sample(c("Yes, No"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2023_main_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `Id_` = sample(0:50, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `PoliceServiceType` = sample(c("Municipal Police", "Ontario Provincial Police", "Other Agency"), n, replace = TRUE),
    `PoliceService` = sample(c("Aylmer", "Barrie", "Belleville", "Brantford", "Brockville", "Chatham-Kent", "Cobourg", "Cornwall", "Deep River", "Durham Regional", "Gananoque", "Greater Sudbury", "Guelph", "Halton Regional", "Hamilton", "Hanover", "Kawartha Lake", "Kingston", "LaSalle", "London", "Niagara Regional", "North Bay", "Ottawa", "Owen Sound", "Peel Regional", "Peterborough", "Port Hope", "Sarnia", "Saugeen Shores", "Sault Ste. Marie", "Smiths Falls", "South Simcoe", "St. Thomas", "Stratford", "Strathroy-Caradoc", "Thunder Bay", "Timmins", "Toronto", "Waterloo Regional", "West Grey", "Windsor", "Woodstock", "York Regional"), n, replace = TRUE),
    `OPP_PoliceService` = sample(c("Central Region", "East Region", "General Headquarters", "Highway Safety Division", "North East Region", "North West Region", "West Region"), n, replace = TRUE),
    `IncidentNumber` = rep(NA_character_, n),
    `Date` = sample(2018:2024, n, replace = TRUE),
    `ApproximateTimeForceApplied` = sprintf("%02d:%02d:%02d", sample(0:23, n, replace = TRUE), sample(0:59, n, replace = TRUE), sample(0:59, n, replace = TRUE)),
    `LocationType_ResidentialBuilding` = sample(0:50, n, replace = TRUE),
    `LocationType_NonResidentialBuilding` = sample(0:50, n, replace = TRUE),
    `LocationType_MotorVehicle` = sample(0:50, n, replace = TRUE),
    `LocationType_OpenSpace` = sample(0:50, n, replace = TRUE),
    `LocationType_PublicTransportation` = sample(0:50, n, replace = TRUE),
    `ReportType` = sample(c("Individual", "Team"), n, replace = TRUE),
    `TypeTeam` = sample(c("Apprehension Squad", "Canine Unit", "Containment Team", "Drug Enforcement Unit", "Guns and Gangs Unit", "Hostage Rescue Team", "Major Crime Unit", "Mobile Surveillance Unit", "Public Order Unit", "Tactical Team", "Other"), n, replace = TRUE),
    `NumberTeam` = sample(0:50, n, replace = TRUE),
    `Attire` = sample(c("Non-Uniform", "Uniform"), n, replace = TRUE),
    `AssignmentType` = sample(c("Administrative (e.g., station duty)", "Canine", "Containment", "Court Appearance", "Court Security", "Drugs", "Guns and Gangs, ROPE, Other Specialized Units", "Investigations (CIB, Other Major Crime)", "Marine", "Team", "Off Duty", "Paid Duty", "Patrol (e.g., general, foot, bicycle, ATV, snowmobile)", "Prisoner Transportation/Care/Control", "Public Order", "Tactical", "Targeted Community Response Units/Hostage Rescue", "Traffic", "Other"), n, replace = TRUE),
    `IncidentType` = sample(c("Active Attacker", "Alarm", "Animal Complaint", "Assisting Other /Agency", "(e.g., EMS, animal welfare inspectors", "Barricaded Individual/Disturbance/Individual in Crisis/Wellness/Safety Check", "Executing Warrant (e.g., DNA, arrest, search)", "Family/Neighbour/Other Type of Dispute", "Humane Destruction of Animal", "Investigation (follow-up, ongoing)", "Other Federal/Provincial Statutes (e.g., LLA)", "Person Stop", "Police Custody Related (e.g. prisoner control, fingerprinting, lock-up area)", "Property Crime", "Public Order", "Stolen Vehicle", "Traffic (e.g., RIDE, vehicle collision)", "Violent Crime (including Intimate Partner Violence)", "Weapon(s)"), n, replace = TRUE),
    `HumaneDestructionAnimal_Distance` = sample(c("Less than 3 metres (approx. 10ft)", "3 to 7 Metres (approx. 10 to 23 ft)", "Greater than 7 metres (approx. 23 ft)"), n, replace = TRUE),
    `HumaneDestructionAnimal_Handgun` = sample(0:50, n, replace = TRUE),
    `HumaneDestructionAnimal_Rifle` = sample(0:50, n, replace = TRUE),
    `HumaneDestructionAnimal_Shotgun` = sample(0:50, n, replace = TRUE),
    `HumaneDestructionAnimal_NumberRoundsDischarged` = sample(0:50, n, replace = TRUE),
    `InteractionType` = sample(0:50, n, replace = TRUE),
    `NumberIndividuals` = sample(0:50, n, replace = TRUE),
    `NumberOtherOfficers` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_PhysicalInjuries` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_No` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_FirstAid` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_MedicalPersonnelScene` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_AdmissionMedicalFacility` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_MedicalFacility` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_Unknown` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_Other` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_EffectArrest` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_PreventOffence` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_PreventEscape` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_ProtectOtherOfficers` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_ProtectPublic` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_ProtectSelf` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_ProtectIndividual` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_Unintentional` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_ReasonUseOfForce_Other` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_CEW_Check` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_CEW_Discharged` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_Handgun_Check` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_Handgun_Drawn` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_Handgun_Discharged` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_Rifle_Check` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_Rifle_Discharged` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_ShotgunLethal_Check` = sample(0:50, n, replace = TRUE),
    `NoInteractionIndividual_TypeForceUsed_Firearm_ShotgunLethal_Discharged` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_EffectArrest` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_PreventOffence` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_PreventEscape` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_ProtectOtherOfficers` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_ProtectPublic` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_ProtectSelf` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_ProtectIndividual` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_Unintentional` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_ReasonUseOfForce_Other` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_TypeForceUsed_CEW` = sample(0:50, n, replace = TRUE),
    `NoIndividualAnimalOnly_TypeForceUsed_Firearm` = sample(0:50, n, replace = TRUE),
    `Inclusion_SOLGEN_ARA_Analysis` = sample(c("Yes", "No"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2023_individual_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `Id_` = sample(0:50, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `Indiv_Index` = sample(0:50, n, replace = TRUE),
    `Race` = sample(c("Black", "East/Southeast Asian", "Indigenous", "Latino", "Middle Eastern", "South Asian", "White"), n, replace = TRUE),
    `DifficultyPerceiving` = sample(c("Yes", "No"), n, replace = TRUE),
    `AgeCategory` = sample(c("17 and younger", "18 – 24", "25 – 34", "35 – 44", "45 – 54", "55 – 64", "65 and older"), n, replace = TRUE),
    `Gender` = sample(c("Male", "Female", "Trans/Non-binary/Other"), n, replace = TRUE),
    `DistanceBetweenOfficerAndIndividual` = sample(c("Less than 3 metres (approx. 10ft)", "3 to 7 Metres (approx. 10 to 23 ft)", "Greater than 7 metres (approx. 23 ft)"), n, replace = TRUE),
    `ReasonUseOfForce_EffectArrest` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_PreventOffence` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_PreventEscape` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_ProtectOtherOfficers` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_ProtectPublic` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_ProtectSelf` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_ProtectIndividual` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_Unintentional` = sample(0:50, n, replace = TRUE),
    `ReasonUseOfForce_Other` = sample(0:50, n, replace = TRUE),
    `FactorsInfluenceResponse_NatureIncident` = sample(0:50, n, replace = TRUE),
    `FactorsInfluenceResponse_PastHistory` = sample(0:50, n, replace = TRUE),
    `FactorsInfluenceResponse_PhysicalSizeStrength` = sample(0:50, n, replace = TRUE),
    `FactorsInfluenceResponse_OtherFactors` = sample(0:50, n, replace = TRUE),
    `IndividualActions_ResistantPassive` = sample(0:50, n, replace = TRUE),
    `IndividualActions_ResistantActive` = sample(0:50, n, replace = TRUE),
    `IndividualActions_Assaultive` = sample(0:50, n, replace = TRUE),
    `IndividualActions_SeriousBodilyHarmDeath` = sample(0:50, n, replace = TRUE),
    `PerceiveAccessWeapon` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DirectionsToComply` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_Comply` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_AttemptDeescalation` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Communication` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Containment` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Cover` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Distance` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Repositioning` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Teamwork` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Time` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Other` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_Reason_ImminentThreat` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_Reason_ActionRequiredImmediately` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_Reason_DeescalationUsedOtherOfficers` = sample(0:50, n, replace = TRUE),
    `OfficerResponses_Reason_Other` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_EscortTechniques` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Grounding` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_JointLocks` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Pinning` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_PressurePoints` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Strikes` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Other` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_OC_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_OC_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_Baton_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_Baton_Hard` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_baton_Soft` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_Baton_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_CartridgeMalfunction` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_Disconnect` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_InsufficientProbeSpread` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_OperatorError` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_ProbeMiss` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_WeaponMalfunction` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_WhyNot_Other` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_Drawn` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_Pointed` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_Discharged` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_DeloymentMode_Cartridge` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_DeloymentMode_DrivePushStun` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_DeloymentMode_ThreePointContact` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_DrivePushStunCycles` = sample(c("Single Cycle (5 seconds)", "Extended Cycle (more than 5 seconds)", "Multiple Cycles"), n, replace = TRUE),
    `TypeForceUsed_IntermediateWeapon_ConductedEnergyWeapon_ThreePointContactCycles` = sample(c("Single Cycle (5 seconds)", "Extended Cycle (more than 5 seconds)", "Multiple Cycles"), n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_Shotgun_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_Shotgun_Pointed` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_Shotgun_Discharged` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_Shotgun_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_ExtendedRangeImpactWeapon_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_ExtendedRangeImpactWeapon_Pointed` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_ExtendedRangeImpactWeapon_Discharged` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_LessLethalFirearm_ExtendedRangeImpactWeapon_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Other_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Other_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Drawn` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Pointed` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Discharged` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_Pointed` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_Discharged` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_Check` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_Pointed` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_Discharged` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_AssistControllingBehaviour` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_IssuePoliceChallenge` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_Comply` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_NoChallengeWhyNot_NotViable` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_NoChallengeWhyNot_IssuedByAnOtherOfficer` = sample(0:50, n, replace = TRUE),
    `TypeForceUsed_Firearm_NoChallengeWhyNot_Other` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_PhysicalInjuriesIndividual` = sample(c("Yes", "No", "Fatal", "Don’t Know (e.g., individual fled/escaped)"), n, replace = TRUE),
    `IndividualInjuries_Treatment_No` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_Treatment_FirstAid` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_Treatment_MedicalPersonnelScene` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_Treatment_AdmissionMedicalFacility` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_Treatment_MedicalFacility` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_Treatment_Unknown` = sample(0:50, n, replace = TRUE),
    `IndividualInjuries_Treatment_Other` = sample(0:50, n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2023_probe_cycle_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `Indiv_Index` = sample(0:50, n, replace = TRUE),
    `ConductedEnergyWeapon_CartridgeProbe_CartridgeProbeCycles_Cyc` = sample(c("Single Cycle (5 seconds)", "Extended Cycle (more than 5 seconds)", "Multiple Cycles", "Missing Data"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2023_weapon_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `id_` = sample(0:50, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `Indiv_Index` = sample(0:50, n, replace = TRUE),
    `Weapon` = sample(c("Aerosol", "Canine", "Club or Impact Weapon", "Handgun", "Long Gun (rifle, shotgun)", "Knife/Edged", "Vehicle", "Unknown Type of Weapon", "Other"), n, replace = TRUE),
    `Location` = sample(c("Accessible (e.g., within reach)", "In Hand", "On Individual, including concealed"), n, replace = TRUE),
    `Id_` = sample(0:50, n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2024_main_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `Id_` = sample(0:50, n, replace = TRUE),
    `IncidentYear` = sample(2018:2024, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `PoliceServiceType` = sample(c("Municipal Police", "Ontario Provincial Police", "Other Agency"), n, replace = TRUE),
    `PoliceService` = sample(c("Aylmer", "Barrie", "Belleville", "Brantford", "Brockville", "Chatham-Kent", "Cobourg", "Cornwall", "Deep River", "Durham Regional", "Gananoque", "Greater Sudbury", "Guelph", "Halton Regional", "Hamilton", "Hanover", "Kawartha Lake", "Kingston", "LaSalle", "London", "Niagara Regional", "Nishnawbe Aski", "North Bay", "OPP", "Ottawa", "Owen Sound", "Peel Regional", "Peterborough", "Port Hope", "Sarnia", "Saugeen Shores", "Sault Ste. Marie", "Smiths Falls", "South Simcoe", "St. Thomas", "Stratford", "Strathroy-Caradoc", "Thunder Bay", "Timmins", "Toronto", "Waterloo Regional", "West Grey", "Windsor", "Woodstock", "York Regional"), n, replace = TRUE),
    `OPP_PoliceService_Region` = sample(c("Central Region", "East Region", "General Headquarters", "Highway Safety Division", "North East Region", "North West Region", "West Region"), n, replace = TRUE),
    `IncidentNumber` = rep(NA_character_, n),
    `Date` = sample(2018:2024, n, replace = TRUE),
    `ApproximateTimeForceApplied` = sprintf("%02d:%02d:%02d", sample(0:23, n, replace = TRUE), sample(0:59, n, replace = TRUE), sample(0:59, n, replace = TRUE)),
    `LocationType_ResidentialBuilding` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `LocationType_NonResidentialBuilding` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `LocationType_MotorVehicle` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `LocationType_OpenSpace` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `LocationType_PublicTransportation` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReportType` = sample(c("Individual", "Team"), n, replace = TRUE),
    `TypeTeam` = sample(c("Apprehension Squad", "Canine Unit", "Containment Team", "Drug Enforcement Unit", "Guns and Gangs Unit", "Hostage Rescue Team", "Major Crime Unit", "Mobile Surveillance Unit", "Public Order Unit", "Tactical Team", "Other"), n, replace = TRUE),
    `NumberTeam` = sample(0:50, n, replace = TRUE),
    `Attire` = sample(c("Non-Uniform", "Uniform"), n, replace = TRUE),
    `AssignmentType` = sample(c("Administrative", "Canine", "Containment", "Court Appearance", "Court Security", "Drugs", "Guns and Gangs", "Investigations", "Marine", "Mental Health Response Unit", "Mounted", "Off Duty", "Other", "Paid Duty", "Patrol", "Prisoner Transportation/Care/Control", "Public Order", "Tactical/Containment/Hostage Rescue", "Targeted Community Response Units/Hostage Rescue", "Traffic"), n, replace = TRUE),
    `IncidentType` = sample(c("Active Attacker", "Alarm", "Animal Complaint", "Assisting Other /Agency", "Barricaded Individual/Disturbance/Individual in Crisis/Wellness/Safety Check", "Executing Warrant", "Family/Neighbour/Other Type of Dispute", "Humane Destruction of Animal", "Investigation", "Other Federal/Provincial Statutes", "Person Stop", "Police Custody Related", "Property Crime", "Public Order", "Stolen Vehicle", "Traffic", "Violent Crime (including Intimate Partner Violence)", "Weapon(s)"), n, replace = TRUE),
    `HumaneDestructionAnimal_Distance` = sample(c("Less than 3 metres (approx. 10ft)", "3 to 7 metres (approx. 10 to 23 ft)", "Greater than 7 metres (approx. 23 ft)"), n, replace = TRUE),
    `HumaneDestructionAnimal_Handgun` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `HumaneDestructionAnimal_Rifle` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `HumaneDestructionAnimal_Shotgun` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `HumaneDestructionAnimal_NumberRoundsDischarged` = sample(0:50, n, replace = TRUE),
    `InteractionType` = sample(c("Interaction with Individual(s)", "No Interaction with Individual(s)", "Interaction with Animal"), n, replace = TRUE),
    `NumberIndiv` = sample(0:50, n, replace = TRUE),
    `NumberOtherOfficers` = sample(0:50, n, replace = TRUE),
    `OfficerInvolvedInjuries_PhysicalInjuries` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_No` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_FirstAid` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_MedicalPersonnelScene` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_AdmissionMedicalFacility` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_MedicalFacility` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_Unknown` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerInvolvedInjuries_Treatment_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_EffectArrest` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_PreventOffence` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_PreventEscape` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_ProtectOtherOfficers` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_ProtectPublic` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_ProtectSelf` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_ProtectIndiv` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_Unintentional` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_ReasonUseOfForce_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_CEW_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_CEW_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_Handgun_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_Handgun_Drawn` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_Handgun_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_Rifle_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_Rifle_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_ShotgunLethal_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoInteractIndiv_TypeForceUsed_Firearm_ShotgunLethal_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_EffectArrest` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_PreventOffence` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_PreventEscape` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_ProtectOtherOfficers` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_ProtectPublic` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_ProtectSelf` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_ProtectIndiv` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_Unintentional` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_ReasonUseOfForce_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_TypeForceUsed_CEW` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `NoIndivAnimalOnly_TypeForceUsed_Firearm` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `Inclusion_SOLGEN_ARA_Analysis` = sample(c("Yes", "No"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2024_individual_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `Id_` = sample(0:50, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `Indiv_Index` = sample(0:50, n, replace = TRUE),
    `Race` = sample(c("Black", "East/Southeast Asian", "Indigenous", "Latino", "Middle Eastern", "South Asian", "White"), n, replace = TRUE),
    `DifficultyPerceiving` = sample(c("Yes", "No"), n, replace = TRUE),
    `AgeCategory` = sample(c("17 and younger", "18 – 24", "25 – 34", "35 – 44", "45 – 54", "55 – 64", "65 and older"), n, replace = TRUE),
    `Gender` = sample(c("Male", "Female", "Trans/Non-binary/Other"), n, replace = TRUE),
    `DistanceBetweenOfficerAndIndiv` = sample(c("Less than 3 metres (approx. 10ft)", "3 to 7 metres (approx. 10 to 23 ft)", "Greater than 7 metres (approx. 23 ft)"), n, replace = TRUE),
    `ReasonUseOfForce_EffectArrest` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_PreventOffence` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_PreventEscape` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_ProtectOtherOfficers` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_ProtectPublic` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_ProtectSelf` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_ProtectIndiv` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_Unintentional` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `ReasonUseOfForce_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `FactorsInfluenceResponse_NatureIncident` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `FactorsInfluenceResponse_PastHistory` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `FactorsInfluenceResponse_PhysicalSizeStrength` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `FactorsInfluenceResponse_OtherFactors` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivActions_ResistantPassive` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivActions_ResistantActive` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivActions_Assaultive` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivActions_SeriousBodilyHarmDeath` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `PerceiveAccessWeapon` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DirectionsToComply` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_Comply` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_AttemptDeescalation` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Communication` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Containment` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Cover` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Distance` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Repositioning` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Teamwork` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Time` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_DeescalationTechniques_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `OfficerResponses_Reason_ImminentThreat` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_Reason_ActionRequiredImmediately` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_Reason_DeescalationUsedOtherOfficers` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `OfficerResponses_Reason_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_EscortTechniques` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Grounding` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_JointLocks` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Pinning` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_PressurePoints` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Strikes` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_PhysicalControl_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_OC_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_OC_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_Baton_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_Baton_Hard` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_Baton_Soft` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_Baton_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_CartridgeMalfunction` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_Disconnect` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_InsufficientProbeSpread` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_OperatorError` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_ProbeMiss` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_WeaponMalfunction` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_WhyNot_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_Drawn` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_Pointed` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_DeloymentMode_Cartridge` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_DeloymentMode_DrivePushStun` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_DeloymentMode_ThreePointContact` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_DrivePushStunCycles` = sample(c("Single Cycle (5 seconds)", "Extended Cycle (more than 5 seconds)", "Multiple Cycles"), n, replace = TRUE),
    `TypeForceUsed_IntermWeapon_CEW_ThreePointContactCycles` = sample(c("Single Cycle (5 seconds)", "Extended Cycle (more than 5 seconds)", "Multiple Cycles"), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_Shotgun_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_Shotgun_Pointed` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_Shotgun_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_Shotgun_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_ExtRangeImpactWeapon_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_ExtRangeImpactWeapon_Pointed` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_ExtRangeImpactWeapon_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_LLFirearm_ExtRangeImpactWeapon_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Other_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Other_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Drawn` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Pointed` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Handgun_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_Pointed` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_Rifle_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_Check` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_Pointed` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_Discharged` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_ShotgunLethal_AssistCtrlBhvr` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_IssuePoliceChallenge` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_Comply` = sample(c("Yes", "No"), n, replace = TRUE),
    `TypeForceUsed_Firearm_NoChallengeWhyNot_NotViable` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_NoChallengeWhyNot_IssuedByAnOtherOfficer` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `TypeForceUsed_Firearm_NoChallengeWhyNot_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_PhysicalInjuries` = sample(c("Yes", "No", "Fatal", "Don’t Know"), n, replace = TRUE),
    `IndivInjuries_Treatment_No` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_Treatment_FirstAid` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_Treatment_MedicalPersonnelScene` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_Treatment_AdmissionMedicalFacility` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_Treatment_MedicalFacility` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_Treatment_Unknown` = sample(c(1L, NA_integer_), n, replace = TRUE),
    `IndivInjuries_Treatment_Other` = sample(c(1L, NA_integer_), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2024_probe_cycle_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `Id_` = sample(0:50, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `Indiv_Index` = sample(0:50, n, replace = TRUE),
    `CEW_CartridgeProbe_CartridgeProbeCycles_Cyc` = sample(c("Single Cycle (5 seconds)", "Extended Cycle (more than 5 seconds)", "Multiple Cycles", "Missing Data"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}
.morie_arsau_2024_weapon_records_panel <- function(n = 60L, seed = 1L) {
  set.seed(seed)
  data.frame(
    `id_` = sample(0:50, n, replace = TRUE),
    `BatchFileName` = sprintf("syn-%05d", sample.int(max(2L, n %/% 2L), n, replace = TRUE)),
    `Indiv_Index` = sample(0:50, n, replace = TRUE),
    `Indiv_Weapon_Index` = sample(0:50, n, replace = TRUE),
    `Weapon` = sample(c("Aerosol", "Canine", "Club or Impact Weapon", "Handgun", "Long Gun", "Knife/Edged", "Vehicle", "Unknown Type of Weapon", "Other", "DATA NOT AVAILABLE"), n, replace = TRUE),
    `Location` = sample(c("Accessible", "In Hand", "On Individual", "DATA NOT AVAILABLE", "<Blank>"), n, replace = TRUE),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

.morie_arsau_registry_synth <- list(
  list(year = "2020-2022", kind = "aggregate_summary", csv_filename = "useofforce_agrregatesummarybyyear_2020-2022.csv", helper = ".morie_arsau_2020_2022_aggregate_summary_panel"),
  list(year = "2020-2022", kind = "detailed_dataset", csv_filename = "useofforce_detaileddataset_2020-2022.csv", helper = ".morie_arsau_2020_2022_detailed_dataset_panel"),
  list(year = "2023", kind = "main_records", csv_filename = "uof_main_records.csv", helper = ".morie_arsau_2023_main_records_panel"),
  list(year = "2023", kind = "individual_records", csv_filename = "uof_individual_records.csv", helper = ".morie_arsau_2023_individual_records_panel"),
  list(year = "2023", kind = "probe_cycle_records", csv_filename = "uof_probe_cycle_records.csv", helper = ".morie_arsau_2023_probe_cycle_records_panel"),
  list(year = "2023", kind = "weapon_records", csv_filename = "uof_weapon_records_invaliddata.csv", helper = ".morie_arsau_2023_weapon_records_panel"),
  list(year = "2024", kind = "main_records", csv_filename = "uof_main_records.csv", helper = ".morie_arsau_2024_main_records_panel"),
  list(year = "2024", kind = "individual_records", csv_filename = "uof_individual_records.csv", helper = ".morie_arsau_2024_individual_records_panel"),
  list(year = "2024", kind = "probe_cycle_records", csv_filename = "uof_probe_cycle_records.csv", helper = ".morie_arsau_2024_probe_cycle_records_panel"),
  list(year = "2024", kind = "weapon_records", csv_filename = "uof_weapon_records.csv", helper = ".morie_arsau_2024_weapon_records_panel")
)

#' Build a synthetic ARSAU data.frame matching the real (year, kind)
#' schema + categorical vocabulary.
make_synthetic_arsau <- function(year, kind, n = 60L, seed = 1L) {
  hit <- Find(
    function(e) e$year == as.character(year) && e$kind == kind,
    .morie_arsau_registry_synth)
  if (is.null(hit)) {
    stop(sprintf("no synthetic ARSAU fixture for year=%s kind=%s",
                 sQuote(year), sQuote(kind)),
         call. = FALSE)
  }
  fn <- get(hit$helper, envir = environment())
  fn(n = n, seed = seed)
}

#' Stage every registered ARSAU (year, kind) CSV under
#'   <root>/<year_or_range>/<csv_filename>
#' and return the root path. Suitable for setting MORIE_ARSAU_DIR or
#' passing as data_dir to any morie_arsau_analyze_*() call.
stage_synthetic_arsau <- function(root = tempfile("arsau_synth_"),
                                  n = 60L, seed = 1L) {
  dir.create(root, recursive = TRUE, showWarnings = FALSE)
  for (e in .morie_arsau_registry_synth) {
    sub <- file.path(root, e$year)
    dir.create(sub, recursive = TRUE, showWarnings = FALSE)
    df <- make_synthetic_arsau(e$year, e$kind, n = n, seed = seed)
    utils::write.csv(df, file.path(sub, e$csv_filename), row.names = FALSE)
  }
  root
}
