# Coverage for the meta-analysis shelf part 2 (Hartung-Knapp and HKSJ,
# I^2 with the Higgins-Thompson interval, influence diagnostics, L'Abbe,
# log OR / RR, Mantel-Haenszel, continuity correction, node splitting,
# network MA, Bucher), the Mann-Kendall test, Manski bounds and the regex
# escaper; checked against metafor, trend and base R.

yh <- c(0.1, 0.8, -0.3, 0.6, 1.1, 0.4)
vh <- c(0.04, 0.02, 0.09, 0.05, 0.03, 0.06)

test_that("mahks, mahsj and mai2", {
  skip_if_not_installed("metafor")
  f <- metafor::rma(yh, vh, method = "DL", test = "knha")
  r <- mahks(yh, vh)
  expect_equal(c(r$estimate, r$se, r$ci_lower, r$ci_upper), c(f$b[1], f$se, f$ci.lb, f$ci.ub), tolerance = 1e-9)
  expect_equal(r$p_value, f$pval, tolerance = 1e-9)
  expect_equal(morie_mahks(yh, vh)$inflation, f$se / metafor::rma(yh, vh, method = "DL")$se, tolerance = 1e-9)
  s <- mahsj(yh, vh, level = 0.9)
  sp <- sqrt(f$tau2 + f$se^2)
  expect_equal(c(s$pi_lower, s$pi_upper), f$b[1] + c(-1, 1) * qt(0.95, 5) * sp, tolerance = 1e-9)
  expect_equal(morie_mahsj(yh, vh)$pi_spread, sp, tolerance = 1e-9)
  i2 <- mai2(yh, vh)
  Q <- f$QE
  expect_equal(i2$estimate, 100 * (Q - 5) / Q, tolerance = 1e-9)
  expect_equal(i2$estimate, f$I2, tolerance = 1e-9)
  se <- if (Q > 6) (log(Q) - log(5)) / (2 * (sqrt(2 * Q) - sqrt(9))) else sqrt(1 / 8 * (1 - 1 / 48))
  H <- sqrt(Q / 5)
  hl <- max(1, exp(log(H) - qnorm(0.975) * se))
  expect_equal(i2$ci_lower, 100 * (hl^2 - 1) / hl^2, tolerance = 1e-9)
  expect_equal(morie_mai2(yh, vh)$H, H, tolerance = 1e-12)
})

test_that("mainf and morie_mainf match metafor's leave-one-out influence", {
  skip_if_not_installed("metafor")
  f <- metafor::rma(yh, vh, method = "DL")
  inf <- metafor::influence.rma.uni(f)$inf
  r <- mainf(yh, vh)
  expect_equal(r$rstudent, unname(inf$rstudent), tolerance = 1e-9)
  expect_equal(r$dffits, unname(inf$dffits), tolerance = 1e-9)
  expect_equal(r$tau2_del, unname(inf$tau2.del), tolerance = 1e-9)
  expect_equal(r$Q_del, unname(inf$QE.del), tolerance = 1e-9)
  loo <- metafor::leave1out(f)
  expect_equal(r$estimate_del, unname(loo$estimate), tolerance = 1e-9)
  expect_equal(morie_mainf(yh, vh)$cook_d, (f$b[1] - loo$estimate)^2 / f$se^2, tolerance = 1e-9)
})

test_that("malab, malor, malrr, Mamh, Mhors and Contcorr", {
  a <- c(12, 5, 0, 8)
  b <- c(38, 45, 20, 32)
  c <- c(6, 9, 3, 4)
  d <- c(44, 41, 17, 36)
  lb <- malab(a, a + b, c, c + d)
  n <- a + b + c + d
  expect_equal(lb$estimate, sum(a * (c + d) / n) / sum(c * (a + b) / n), tolerance = 1e-12)
  expect_equal(morie_malab(a, a + b, c, c + d)$y, a / (a + b), tolerance = 1e-12)
  skip_if_not_installed("metafor")
  eo <- metafor::escalc("OR", ai = a, bi = b, ci = c, di = d)
  lo <- malor(a, b, c, d)
  expect_equal(lo$estimate, as.numeric(eo$yi), tolerance = 1e-12)
  expect_equal(lo$variance, as.numeric(eo$vi), tolerance = 1e-12)
  expect_equal(morie_malor(a, b, c, d)$corrected, 1L)
  er <- metafor::escalc("RR", ai = a, bi = b, ci = c, di = d)
  lr <- malrr(a, b, c, d)
  expect_equal(lr$estimate, as.numeric(er$yi), tolerance = 1e-12)
  expect_equal(morie_malrr(a, b, c, d)$variance, as.numeric(er$vi), tolerance = 1e-12)
  mh <- metafor::rma.mh(ai = a, bi = b, ci = c, di = d, measure = "OR")
  m <- Mamh(a, b, c, d)
  expect_equal(m$estimate, exp(unname(mh$b[1])), tolerance = 1e-9)
  expect_equal(m$se, mh$se, tolerance = 1e-9)
  expect_equal(Mhors(cbind(a, b, c, d), 0.9)$ci_upper, exp(unname(mh$b[1]) + qnorm(0.95) * mh$se), tolerance = 1e-9)
  expect_error(Mamh(a, b, c, d[-1]), "equal length")
  cc <- Contcorr(0, 10, 4, 6)
  expect_equal(cc$estimate, log(0.5 * 6.5 / (10.5 * 4.5)), tolerance = 1e-12)
  expect_true(cc$applied)
  expect_false(Contcorr(1, 2, 3, 4)$applied)
  expect_equal(Contcorr(1, 2, 3, 4, always = TRUE)$cc, 0.5)
})

test_that("Manlmm fits the contrast-based network model and Manh2h splits a node", {
  D <- rbind(c(1, 2), c(1, 2), c(1, 3), c(2, 3), c(1, 3), c(2, 3), c(1, 2))
  y <- c(0.5, 0.6, 1.1, 0.4, 0.9, 0.7, 0.4)
  v <- c(0.04, 0.05, 0.06, 0.05, 0.08, 0.07, 0.06)
  X <- cbind(ifelse(D[, 2] == 2, 1, 0) - ifelse(D[, 1] == 2, 1, 0),
             ifelse(D[, 2] == 3, 1, 0) - ifelse(D[, 1] == 3, 1, 0))
  f0 <- lm(y ~ 0 + X, weights = 1 / v)
  QE <- sum(residuals(f0)^2 / v)
  cv0 <- solve(crossprod(X / sqrt(v)))
  den <- sum(1 / v) - sum(diag(cv0 %*% crossprod(X / v)))
  t2 <- max(0, (QE - 5) / den)
  f1 <- lm(y ~ 0 + X, weights = 1 / (v + t2))
  r <- Manlmm(y, v, D)
  expect_equal(r$QE, QE, tolerance = 1e-9)
  expect_equal(r$tau2, t2, tolerance = 1e-9)
  expect_equal(r$theta, c(0, unname(coef(f1))), tolerance = 1e-9)
  expect_equal(r$se_theta[-1], unname(sqrt(diag(solve(crossprod(X / sqrt(v + t2)))))), tolerance = 1e-9)
  ns <- Manh2h(y, v, D, c(1, 2))
  di <- which(D[, 1] == 1 & D[, 2] == 2)
  dir <- sum(y[di] / v[di]) / sum(1 / v[di])
  Xr <- X[-di, , drop = FALSE]
  br <- solve(crossprod(Xr / sqrt(v[-di])), crossprod(Xr / v[-di], y[-di]))
  expect_equal(ns$direct, dir, tolerance = 1e-12)
  expect_equal(ns$indirect, br[1], tolerance = 1e-9)
  expect_equal(ns$v_indirect, solve(crossprod(Xr / sqrt(v[-di])))[1, 1], tolerance = 1e-9)
  expect_error(Manh2h(y, v, D, c(1, 1)), "distinct")
  expect_error(Manh2h(y, v, D, c(1, 4)), "no study makes")
})

test_that("Bucherind, Mktest and escape_regex", {
  b <- Bucherind(0.4, 0.02, -0.1, 0.03, alpha = 0.1)
  expect_equal(c(b$estimate, b$se), c(0.5, sqrt(0.05)), tolerance = 1e-12)
  expect_equal(b$ci_upper, 0.5 + qnorm(0.95) * sqrt(0.05), tolerance = 1e-12)
  expect_error(Bucherind(0, 0, 0, 0), "positive")
  x <- c(1.2, 1.5, 1.4, 2.0, 1.9, 2.4, 2.4, 3.1, 2.8, 3.5)
  m <- Mktest(x)
  S <- sum(vapply(2:10, function(j) sum(sign(x[j] - x[1:(j - 1)])), 0))
  vS <- (10 * 9 * 25 - 2 * 1 * 9) / 18
  expect_equal(m$S, S)
  expect_equal(m$varS, vS, tolerance = 1e-12)
  expect_equal(m$statistic, (S - 1) / sqrt(vS), tolerance = 1e-12)
  skip_if_not_installed("trend")
  tk <- trend::mk.test(x)
  expect_equal(m$statistic, unname(tk$statistic), tolerance = 1e-9)
  expect_equal(m$p_value, tk$p.value, tolerance = 1e-9)
  s <- "a.b*(c)[d]{e}+f?^g$h|i\\j"
  expect_true(grepl(paste0("^", escape_regex(s), "$"), s))
  expect_false(grepl(escape_regex("a.b"), "axb"))
})

test_that("morie_manski, morie_manskif and Manskif give worst-case bounds", {
  y <- c(3, 5, 2, 8, 4, 6)
  D <- c(1, 1, 0, 1, 0, 0)
  r <- morie_manski(y, D, 0, 10)
  p <- mean(D)
  lo1 <- mean(y[D == 1]) * p
  hi1 <- lo1 + 10 * (1 - p)
  lo0 <- mean(y[D == 0]) * (1 - p)
  hi0 <- lo0 + 10 * p
  expect_equal(c(r$ate_lower, r$ate_upper), c(lo1 - hi0, hi1 - lo0), tolerance = 1e-12)
  expect_equal(r$ate_width, 10, tolerance = 1e-12)
  obs <- c(TRUE, TRUE, FALSE, TRUE, FALSE, TRUE)
  m <- morie_manskif(y, obs, c(0, 10))
  q <- mean(obs)
  expect_equal(c(m$lower, m$upper), mean(y[obs]) * q + c(0, 10) * (1 - q), tolerance = 1e-12)
  expect_equal(Manskif(y, obs, c(0, 10))$upper, m$upper, tolerance = 1e-12)
  expect_error(morie_manskif(y, obs, c(10, 0)), "K0 < K1")
})
