# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for the Alammar/Vaswani DL shelf (W2).
#
# Anchors generated by running the Python core, not recalled. The
# LCG-driven modules (sampler, LDA, TSDAE) must reproduce Python's
# draws token for token, which is the strongest available check on a
# stochastic port.

test_that("scaled dot-product attention matches Python", {
  o <- morie_alammar_sdp_attention(rbind(c(1, 0)),
                                   rbind(c(1, 0), c(0, 1)),
                                   rbind(5, -5))
  expect_equal(o$output[1, 1], 1.6976154932665688, tolerance = 1e-14)
  expect_equal(o$attention[1, 1], 0.6697615493266569, tolerance = 1e-14)
  expect_equal(rowSums(o$attention), 1)
  m <- rbind(c(TRUE, FALSE))
  o2 <- morie_alammar_sdp_attention(rbind(c(1, 0)),
                                    rbind(c(1, 0), c(0, 1)),
                                    rbind(7, 0), mask = m)
  expect_equal(o2$attention[1, ], c(1, 0))
  expect_error(morie_alammar_sdp_attention(rbind(1), rbind(c(1, 2)),
                                           rbind(1)), "share d_k")
})

test_that("multi-head with identity projections reduces to SDP", {
  set.seed(1)
  X <- matrix(stats::rnorm(6), 3, 2)
  I2 <- diag(2)
  mh <- morie_alammar_multi_head_attention(X, X, X, list(I2), list(I2),
                                           list(I2), I2, 1)
  sdp <- morie_alammar_sdp_attention(X, X, X)
  expect_equal(mh$output, sdp$output, tolerance = 1e-14)
  expect_error(morie_alammar_multi_head_attention(
    X, X, X, list(I2), list(I2), list(I2), I2, 2), "one per head")
})

test_that("GQA limits recover MQA and full per-head attention", {
  set.seed(2)
  Qh <- lapply(1:4, function(i) matrix(stats::rnorm(6), 3, 2))
  Ks <- matrix(stats::rnorm(6), 3, 2)
  Vs <- matrix(stats::rnorm(6), 3, 2)
  mqa <- morie_alammar_multi_query_attention(Qh, Ks, Vs, 4)
  gqa1 <- morie_alammar_grouped_query_attention(Qh, list(Ks), list(Vs),
                                                4, 1)
  expect_equal(mqa$output, gqa1$output, tolerance = 1e-14)
  Kg <- lapply(1:4, function(i) matrix(stats::rnorm(6), 3, 2))
  Vg <- lapply(1:4, function(i) matrix(stats::rnorm(6), 3, 2))
  gqaH <- morie_alammar_grouped_query_attention(Qh, Kg, Vg, 4, 4)
  per <- do.call(cbind, lapply(1:4, function(i) {
    morie_alammar_sdp_attention(Qh[[i]], Kg[[i]], Vg[[i]])$output
  }))
  expect_equal(gqaH$output, per, tolerance = 1e-14)
  expect_error(morie_alammar_grouped_query_attention(Qh, list(Ks),
                                                     list(Vs), 4, 3),
               "divisible")
})

test_that("the sliding window is zero outside the band", {
  set.seed(3)
  X <- matrix(stats::rnorm(12), 6, 2)
  o <- morie_alammar_sliding_window_attention(X, X, X, 2)
  A <- o$attention
  for (i in 1:6) {
    for (j in 1:6) {
      if (j > i || j < i - 1) expect_equal(A[i, j], 0)
    }
  }
  expect_equal(rowSums(A), rep(1, 6))
})

test_that("the KV-cache step equals full attention recomputed", {
  set.seed(4)
  K <- matrix(stats::rnorm(12), 4, 3)
  V <- matrix(stats::rnorm(8), 4, 2)
  k5 <- matrix(stats::rnorm(3), 1, 3)
  v5 <- matrix(stats::rnorm(2), 1, 2)
  q <- matrix(stats::rnorm(3), 1, 3)
  cached <- morie_alammar_kv_cache_lookup(K, V, k5, v5, q)
  full <- morie_alammar_sdp_attention(q, rbind(K, k5), rbind(V, v5))
  expect_equal(cached$output, as.numeric(full$output[1, ]),
               tolerance = 1e-14)
  expect_equal(cached$cache_length, 5)
})

test_that("heads, lookups and pooling match Python", {
  h <- morie_alammar_classification_head(c(1, 2), rbind(c(1, 0), c(0, 1)),
                                         c(0, 0))
  expect_equal(h$predicted_class, 1L)
  expect_equal(sum(h$probabilities), 1)
  ner <- morie_alammar_ner_token_head(rbind(c(1, 0), c(0, 1)),
                                      rbind(c(2, 0), c(0, 2)), c(0, 0),
                                      c(0, 1))
  expect_equal(ner$predicted_tags, c(0L, 1L))
  expect_equal(ner$cross_entropy, -log(exp(2) / (exp(2) + 1)),
               tolerance = 1e-12)
  lk <- morie_alammar_token_embedding_lookup(c(1, 0),
                                             rbind(c(1, 2), c(3, 4)))
  expect_equal(lk$embeddings, rbind(c(3, 4), c(1, 2)))
  expect_error(morie_alammar_token_embedding_lookup(2, rbind(1, 2)),
               "vocabulary")
  pool <- morie_alammar_document_embedding_pool(rbind(2, 4, 99),
                                                c(1, 1, 0))
  expect_equal(pool$embedding, 3)
  expect_error(morie_alammar_document_embedding_pool(rbind(1), 0),
               "all-padding")
})

test_that("contextual extraction and ViT patches match Python", {
  L <- array(0, dim = c(2, 2, 2))
  L[1, 1, ] <- c(1, 0); L[1, 2, ] <- c(1, 0)
  L[2, 1, ] <- c(1, 1); L[2, 2, ] <- c(2, 2)
  o <- morie_alammar_contextualized_embedding(L, -1, 1)
  expect_equal(o$embedding, c(2, 2))
  img <- matrix(0:15, 4, 4, byrow = TRUE)
  v <- morie_alammar_vit_patch_embedding(img, 2, diag(4))
  expect_equal(v$n_patches, 4)
  expect_equal(as.numeric(v$sequence[1, ]), c(0, 1, 4, 5))
  expect_error(morie_alammar_vit_patch_embedding(matrix(0, 5, 4), 2,
                                                 diag(4)), "tile")
})

test_that("the loss family matches Python", {
  i <- morie_alammar_infonce_loss(c(1, 0), c(1, 0),
                                  rbind(c(0, 1), c(-1, 0)), 0.1)
  expect_equal(i$estimate, 4.5400960276609226e-05, tolerance = 1e-12)
  A <- rbind(c(1, 0), c(0, 1))
  mnr <- morie_alammar_multiple_negatives_ranking(A, A, tau = 1)
  manual <- -log(exp(1) / (exp(1) + 1))
  expect_equal(mnr$estimate, manual, tolerance = 1e-14)
  expect_equal(morie_alammar_simcse_dropout_aug(A, A, tau = 1)$estimate,
               manual, tolerance = 1e-14)
  cl <- morie_alammar_openclip_contrastive(A, A, tau = 0.5)
  expect_equal(cl$image_to_text_loss, cl$text_to_image_loss)
  t <- morie_alammar_sbert_triplet_loss(rbind(0), rbind(0.5), rbind(0.6),
                                        margin = 1)
  expect_equal(t$losses, 0.9, tolerance = 1e-12)
  sg <- morie_alammar_negative_sampling_skipgram(100, 1, rbind(-1))
  expect_lt(abs(sg$estimate), 1e-8)
  bt <- morie_alammar_reward_model_bt(c(2, 0), c(0, 1))
  expect_equal(bt$pair_accuracy, 0.5)
  expect_equal(bt$losses[1], log(1 + exp(-2)), tolerance = 1e-12)
  expect_equal(bt$losses[2], log(1 + exp(1)), tolerance = 1e-12)
})

test_that("metrics match Python", {
  expect_equal(morie_alammar_mean_reciprocal_rank(
    list(c(3, 1), 9), list(1, 7))$estimate, 0.25)
  expect_equal(morie_alammar_recall_at_k(c(1, 2, 3), c(2, 9), 2)$estimate,
               0.5)
  expect_equal(morie_alammar_ndcg_at_k(c(3, 2, 3, 0, 1, 2), 6)$estimate,
               0.9488107485678985, tolerance = 1e-12)
  expect_error(morie_alammar_ndcg_at_k(c(0, 0), 2), "undefined")
  m <- morie_alammar_mteb_benchmark_score(
    list(a = 1, b = 1, c = 0), list(a = "x", b = "x", c = "y"))
  expect_equal(m$estimate, 0.5)
  expect_equal(m$flat_task_mean, 2 / 3, tolerance = 1e-12)
  expect_true(m$weighting_matters)
})

test_that("decoding matches Python token for token", {
  g <- morie_alammar_greedy_decoding(rbind(c(1, 1, 0), c(0, 2, 1)))
  expect_equal(g$tokens, c(0L, 1L))
  expect_equal(g$had_ties, c(TRUE, FALSE))
  s <- morie_alammar_sampling_decoding(
    matrix(rep(c(1, 0), 10), 10, 2, byrow = TRUE), seed = 7)
  expect_equal(s$tokens, c(0L, 1L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 1L))
})

test_that("text utilities match Python", {
  b <- morie_alammar_bag_of_words(c("a", "b", "a", "z"), c("a", "b", "c"))
  expect_equal(b$bow_vector, c(2L, 1L, 0L))
  expect_equal(b$oov_count, 1L)
  ct <- morie_alammar_c_tfidf(rbind(c(4, 0), c(0, 4)))
  expect_equal(as.integer(ct$top_term_per_class), c(0L, 1L))
  bio <- morie_alammar_bio_tagging(c("a", "b", "c"),
                                   list(list(0, 2, "PER")),
                                   scheme = "BIOES")
  expect_equal(bio$tags, c("B-PER", "E-PER", "O"))
  expect_error(morie_alammar_bio_tagging(
    c("a", "b"), list(list(0, 2, "X"), list(1, 2, "Y"))), "overlap")
  expect_equal(morie_alammar_tokenizer_vocab_overlap(
    c("a", "b"), c("b", "c"))$estimate, 1 / 3, tolerance = 1e-12)
})

test_that("chunking reassembles when every tier fires", {
  text <- "aa bb. cc dd. ee ff gg. hh"
  out <- morie_alammar_recursive_chunking(text,
                                          separators = c(". ", " "),
                                          target_size = 4)
  expect_true(all(nchar(out$chunks) <= 4))
  expect_equal(paste(out$chunks, collapse = ""),
               gsub(" ", "", gsub(". ", "", text, fixed = TRUE)))
  simple <- morie_alammar_recursive_chunking("aa bb. cc dd. ee",
                                             separators = c(". ", " "),
                                             target_size = 6)
  expect_equal(simple$chunks, c("aa bb", "cc dd", "ee"))
})

test_that("memory, templates and preference records match Python", {
  m <- morie_alammar_conversation_buffer_memory(
    list(c("u1", "a1"), c("u2", "a2")), 1)
  expect_equal(m$memory[[1]], c("u2", "a2"))
  expect_equal(m$turns_forgotten, 1L)
  ch <- morie_alammar_chat_template(list(c("user", "hi")),
                                    list(user = c("<u>", "</u>")))
  expect_equal(ch$prompt, "<u>hi</u>")
  expect_error(morie_alammar_chat_template(list(c("robot", "x")),
                                           list(user = c("", ""))),
               "no template tokens")
  expect_error(morie_alammar_chosen_rejected_template("p", "x", "x"),
               "no preference")
  it <- morie_alammar_instruction_data_template(
    list(list(instruction = "add", input = "2 2", output = "four")))
  sp <- it$output_spans[[1]]
  expect_equal(substr(it$texts[1], sp[1] + 1, sp[2]), "four")
})

test_that("the WordPiece pipeline matches Python", {
  v <- c("[CLS]", "[SEP]", "[UNK]", "un", "##happy", "dog")
  out <- morie_alammar_tokenization_pipeline("Unhappy dog", v)
  expect_equal(out$tokens, c("[CLS]", "un", "##happy", "dog", "[SEP]"))
  expect_error(morie_alammar_tokenization_pipeline("x",
                                                   c("[CLS]", "[SEP]")),
               "UNK")
})

test_that("HDBSCAN finds the planted blobs and flags the outlier", {
  X <- rbind(c(0, 0), c(0.1, 0), c(0, 0.1), c(5, 5), c(5.1, 5),
             c(5, 5.1), c(20, 20))
  out <- morie_alammar_hdbscan_cluster(X, 3, 2)
  expect_equal(out$n_clusters, 2L)
  expect_equal(out$labels[7], -1L)
  expect_equal(out$labels[1], out$labels[2])
  expect_equal(out$labels[4], out$labels[5])
  expect_false(out$labels[1] == out$labels[4])
})

test_that("UMAP reduces its own objective from the same LCG start", {
  X <- rbind(c(0, 0), c(0.2, 0), c(0, 0.2), c(8, 8), c(8.2, 8),
             c(8, 8.2))
  out <- morie_alammar_umap_projection(X, n_neighbors = 2, n_steps = 500,
                                       learning_rate = 0.1)
  expect_true(out$objective_decreased)
  Z <- out$embedding
  intra <- sqrt(sum((Z[1, ] - Z[2, ])^2))
  inter <- sqrt(sum((Z[1, ] - Z[4, ])^2))
  expect_gt(inter, intra)
})

test_that("LDA walks Python's chain and recovers the planted split", {
  docs <- c(rep(list(c("cat", "dog", "cat", "dog")), 3),
            rep(list(c("stock", "bond", "stock", "bond")), 3))
  out <- morie_alammar_lda_topic_distribution(docs, 2, n_iter = 300,
                                              seed = 3)
  th <- out$theta
  expect_equal(rowSums(th), rep(1, 6), tolerance = 1e-9)
  animal <- which.max(th[1, ])
  finance <- which.max(th[4, ])
  expect_false(animal == finance)
  for (i in 1:3) expect_equal(which.max(th[i, ]), animal)
  for (i in 4:6) expect_equal(which.max(th[i, ]), finance)
})

test_that("BERTopic names the planted topics", {
  docs <- list(c("cat", "dog", "cat"), c("dog", "cat"),
               c("stock", "bond", "stock"), c("bond", "stock", "bond"))
  out <- morie_alammar_bertopic_pipeline(docs,
                                         rbind(c(0, 0), c(0.1, 0.1),
                                               c(5, 5), c(5.1, 5.1)), 2)
  expect_equal(out$n_topics, 2L)
  words <- unlist(out$topic_top_word)
  expect_true(any(words %in% c("cat", "dog")))
  expect_true(any(words %in% c("stock", "bond")))
})

test_that("the classifier and SetFit head learn a separable problem", {
  X <- rbind(c(0, 0), c(0.2, 0.1), c(0.1, 0.2), c(5, 5), c(5.2, 5.1),
             c(5.1, 5.2))
  y <- c(0, 0, 0, 1, 1, 1)
  out <- morie_alammar_embedding_classifier(X, y)
  expect_equal(out$train_accuracy, 1)
  expect_equal(out$predictions, as.integer(y))
  sf <- morie_alammar_setfit_twostep(rbind(c(0, 0), c(0.1, 0), c(5, 5),
                                           c(5.1, 5)), c(0, 0, 1, 1))
  expect_equal(sf$n_positive, 2L)
  expect_equal(sf$n_negative, 4L)
  expect_equal(sf$head_train_accuracy, 1)
})

test_that("the ANN search measures its own accuracy", {
  pts <- rbind(c(0, 0), c(1, 0), c(2, 0), c(3, 0), c(4, 0), c(5, 0),
               c(50, 50))
  nbrs <- list(1L, c(0L, 2L), c(1L, 3L), c(2L, 4L), c(3L, 5L),
               c(4L, 6L), 5L)
  out <- morie_alammar_ann_search(c(4.4, 0), list(points = pts,
                                                  neighbors = nbrs,
                                                  entry = 0))
  expect_true(out$found_exact)
  expect_equal(out$nearest, 4L)
  nbrs2 <- list(1L, 0L, 1L, 2L, 3L, 4L, integer(0))
  out2 <- morie_alammar_ann_search(c(0, 0), list(points = pts,
                                                 neighbors = nbrs2,
                                                 entry = 6),
                                   ef_search = 1)
  expect_false(out2$found_exact)
})

test_that("zero-shot, T5 and judge orchestration match Python", {
  nli <- function(p, h) if (grepl("sport", h) && grepl("goal", p)) 5 else 0
  z <- morie_alammar_zero_shot_classification("a late goal won it",
                                              c("sport", "finance"), nli)
  expect_equal(z$predicted_label, "sport")
  t5 <- morie_alammar_t5_classify("good film", c("positive", "negative"),
                                  function(i, l) {
                                    if (l == "positive" &&
                                        grepl("good", i)) 0 else -3
                                  })
  expect_equal(t5$predicted_label, "positive")
  expect_equal(sum(unlist(t5$probabilities)), 1, tolerance = 1e-12)
  judge <- function(r, resp, s) {
    if (resp == "a") c(1, 3)[s + 1] else c(2, 2)[s + 1]
  }
  j <- morie_alammar_llm_as_judge(c("a", "b"), "rubric", judge,
                                  n_samples = 2)
  expect_equal(j$scores, c(2, 2))
  expect_gt(j$judge_sd[1], j$judge_sd[2])
})

test_that("the verification gate and prompt chain behave", {
  expect_error(morie_alammar_output_verification(
    "x", c("ok", "hmm"),
    function(r, c) if (c == "ok") "PASS" else "maybe"),
    "only 'PASS' or")
  out <- morie_alammar_output_verification(
    "x", c("ok", "hard"),
    function(r, c) if (c == "hard") "FAIL" else "PASS")
  expect_false(out$passed)
  expect_equal(out$failed_criteria, "hard")
  chain <- morie_alammar_chain_prompting(
    "3", list(function(y, x) paste("double", x),
              function(y, x) paste("add one to", y)),
    function(p) {
      v <- as.integer(sub(".* ", "", p))
      if (grepl("double", p)) as.character(v * 2) else
        as.character(v + 1)
    })
  expect_equal(chain$final_output, "7")
})

test_that("multi-query retrieval and the ReAct loop match Python", {
  corpus <- list(q = c(1, 2), q0 = c(2, 3), q1 = 4)
  out <- morie_alammar_multi_query_retrieval(
    "q", 2, function(q) corpus[[q]],
    function(q, i) paste0(q, i))
  expect_equal(out$documents, c(1, 2, 3, 4))
  expect_equal(out$added_per_query, c(2L, 1L, 1L))
  model <- function(ctx) {
    last <- ctx[[length(ctx)]]
    if (!is.null(last$query)) {
      list(thought = "look up", action = "search", action_input = "x")
    } else {
      list(thought = "answer", final = last$observation)
    }
  }
  r <- morie_alammar_react_agent_loop("what is x",
                                      list(search = function(q) "42"),
                                      model)
  expect_equal(r$answer, "42")
  expect_false(r$exhausted)
  r2 <- morie_alammar_react_agent_loop(
    "x", list(), function(c) list(thought = "t", action = "nope"),
    max_steps = 2)
  expect_true(r2$exhausted)
  expect_null(r2$answer)
  expect_true(grepl("ERROR", r2$trace[[1]]$observation))
})

test_that("captioning, freezing, pretraining, SBERT and TSDAE cohere", {
  cap <- morie_alammar_image_captioning(
    "img", function(im) c(1, 2), rbind(c(1, 0)),
    function(z, p) "cap")
  expect_equal(cap$projected, 1)
  expect_error(morie_alammar_image_captioning(
    "img", function(im) c(1, 2, 3), rbind(c(1, 0)),
    function(z, p) "x"), "columns")
  fr <- morie_alammar_layer_freezing(6, 3)
  expect_equal(fr$trainable_per_stage, c(2L, 4L, 6L))
  for (i in seq_len(2)) {
    expect_true(all(!fr$masks[[i]] | fr$masks[[i + 1]]))
  }
  cp <- morie_alammar_continued_pretraining(
    "doc", function(docs, s) 1 / (s + 1), 5)
  expect_equal(cp$mlm_loss_curve, c(1, 0.5, 1 / 3, 0.25, 0.2))
  expect_true(cp$mlm_improved)
  aug <- morie_alammar_augmented_sbert(
    list(c("x", "x"), c("x", "y")),
    function(a, b) if (a == b) 1 else 0,
    gold_pairs = list(c("p", "p"), c("p", "q"), c("r", "r"),
                      c("r", "s")),
    gold_labels = c(1, 0, 1, 0))
  expect_equal(aug$n_silver, 2L)
  expect_equal(aug$cross_encoder_gold_agreement, 1)
  ts <- morie_alammar_tsdae_objective(strsplit("abcdefghij", "")[[1]],
                                      seed = 5)
  expect_equal(ts$corrupted, c("b", "d", "e", "j"))
  expect_equal(ts$deleted, c("a", "c", "f", "g", "h", "i"))
  ts2 <- morie_alammar_tsdae_objective(strsplit("abcdefghij", "")[[1]],
                                       seed = 5,
                                       reconstruction_logprob = rep(-0.1,
                                                                    10))
  expect_equal(ts2$loss, 1, tolerance = 1e-12)
  expect_error(morie_alammar_tsdae_objective(
    strsplit("abcd", "")[[1]], seed = 5,
    reconstruction_logprob = rep(-0.1, 2)), "ORIGINAL")
})
