test_that("clustering algorithms recover blobs and recompute", {
  X <- rbind(c(0, 0), c(1, 0.5), c(0.3, 1.2), c(7, 7), c(8, 6.5), c(7.5, 8.2), c(3.5, 3.9), c(4.2, 3.1))
  D <- as.matrix(dist(X))
  best <- min(combn(8, 2, function(m) sum(apply(D[, m], 1, min))))
  expect_equal(Clarans(X, 2, numlocal = 5, seed = 2)$cost, best, tolerance = 1e-12)
  D4 <- rbind(c(0, 1, 5, 6), c(1, 0, 4, 5), c(5, 4, 0, 1), c(6, 5, 1, 0))
  r <- Diana(D4, 2)
  expect_identical(r$cluster, c(1L, 1L, 2L, 2L))
  expect_equal(r$dc, 1 - 1 / 6, tolerance = 1e-15)
  expect_identical(CureClustering(X, 3)$cluster, c(1L, 1L, 1L, 2L, 2L, 2L, 3L, 3L))
  ap <- AffinityPropagation(X)
  expect_equal(length(ap$exemplars), max(ap$cluster))
  expect_identical(Chameleon(X, 2, n_neighbors = 2, min_size = 3)$n_clusters, 2L)
})
