# Coverage tests for R/dssm_native.R (Huang et al. 2013): letter n-gram
# word hashing, collision counts, cosine similarity and the smoothed
# clickthrough posterior.

test_that("letter n-grams with boundary marks", {
  expect_equal(morie_dssm_letter_ngrams("Good"), c("#go", "goo", "ood", "od#"))
  expect_equal(morie_dssm_letter_ngrams("ab", n = 2, boundary = "$"), c("$a", "ab", "b$"))
  expect_equal(morie_dssm_letter_ngrams("a", n = 5), "#a#")
  expect_identical(morie_dssm, morie_dssm_letter_ngrams)
  expect_error(morie_dssm_letter_ngrams("a", n = 0), "at least 1")
  expect_error(morie_dssm_letter_ngrams("a", n = 1:2), "single integer")
  expect_error(morie_dssm_letter_ngrams("a", boundary = NA), "single character")
})

test_that("word hashing counts n-grams, including outside a vocabulary", {
  h <- morie_dssm_word_hash(c("ab", "ab", "b"), n = 2)
  keys <- sort(c("#a", "ab", "b#", "#b"))
  cnt <- c("#a" = 2, "ab" = 2, "b#" = 3, "#b" = 1)
  expect_equal(h$vector, unname(cnt[keys]))
  expect_equal(h$dimension, 4L)
  expect_equal(h$unseen_ngrams, 0L)
  v <- morie_dssm_word_hash(c("ab", "ab"), n = 2, vocabulary = c("zz", "ab", "#a"))
  vk <- sort(c("zz", "ab", "#a"))
  expect_equal(v$vector, unname(c("#a" = 2, "ab" = 2, "zz" = 0)[vk]))
  expect_equal(v$unseen_ngrams, 1L)
  expect_equal(v$dimension, 3L)
  expect_error(morie_dssm_word_hash(character(0)), "words is empty")
})

test_that("collision rate groups words with the same n-gram multiset", {
  r <- morie_dssm_collision_rate(c("ab", "ba", "abc"), n = 1)
  expect_equal(r$collisions, 2L)
  expect_equal(r$collision_rate, 2 / 3)
  expect_equal(r$ngram_dimension, 4L)
  expect_equal(r$reduction, 3 / 4)
  expect_equal(unname(r$colliding_groups), list(c("ab", "ba")))
  t3 <- morie_dssm_collision_rate(c("ab", "ba", "abc"))
  expect_equal(t3$collisions, 0L)
  expect_equal(t3$ngram_dimension, length(unique(c("#ab", "ab#", "#ba", "ba#", "#ab", "abc", "bc#"))))
  expect_error(morie_dssm_collision_rate(character(0)), "vocabulary is empty")
})

test_that("cosine similarity and the clickthrough posterior", {
  q <- c(1, 2, 0, 1)
  d1 <- c(1, 1, 1, 0)
  d2 <- c(0, 0, 3, 1)
  cs <- function(a, b) sum(a * b) / sqrt(sum(a^2) * sum(b^2))
  expect_equal(morie_dssm_cosine_similarity(q, d1), cs(q, d1), tolerance = 1e-12)
  expect_equal(morie_dssm_cosine_similarity(as.list(q), list(d1)), cs(q, d1), tolerance = 1e-12)
  expect_error(morie_dssm_cosine_similarity(q, d1[-1]), "differ in width")
  expect_error(morie_dssm_cosine_similarity(q, 0 * d1), "zero vector")
  p <- morie_dssm_click_posterior(q, d1, list(d2, q), gamma = 5)
  s <- c(cs(q, d1), cs(q, d2), 1)
  post <- exp(5 * s) / sum(exp(5 * s))
  expect_equal(p$posterior, post, tolerance = 1e-12)
  expect_equal(p$estimate, post[1], tolerance = 1e-12)
  expect_equal(p$loss, -log(post[1]), tolerance = 1e-12)
  expect_equal(p$similarities, s, tolerance = 1e-12)
  expect_equal(p$n_negatives, 2L)
  one <- morie_dssm_click_posterior(q, d1, NULL)
  expect_equal(one$posterior, 1)
  expect_equal(one$loss, 0)
  expect_error(morie_dssm_click_posterior(q, d1, list(d2), gamma = 0), "must be positive")
})
