# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for geron_ml2_native.R.
#
# Every `A[[...]]` anchor in anchors.R was GENERATED by running the
# canonical Python from the repository root:
#
#   cd <repo> && MORIE_NO_UPDATE_CHECK=1 PYTHONPATH=src \
#     python3 tools/gen_anchors.py > anchors.R
#
# and the generator asserts `module.__file__` contains "/src/morie/fn/"
# before reading a single value, so a stale installed morie cannot
# silently supply the numbers.
#
# Beyond value-for-value parity, each family is also checked against an
# INDEPENDENT route computed here in R: parameter counts against layer
# algebra, Gini against the hand formula, the exact value function
# against iterated policy evaluation, activation derivatives against
# central finite differences, and the tabular RL updates replayed
# draw-for-draw.

TOL <- 1e-9

expect_close <- function(object, expected, tol = TOL) {
  testthat::expect_equal(as.numeric(object), as.numeric(expected),
                         tolerance = tol)
}

test_that("ELU, SELU, GELU, leaky ReLU, sigmoid, tanh, swish match Python", {
  zs <- c(-2, -1, -0.5, 0, 0.5, 1, 2, 3.5)
  r <- morie_geron_elu(zs, alpha = 1.5)
  expect_close(r$a, A[["elu.a"]])
  expect_close(r$derivative, A[["elu.d"]])
  expect_close(r$estimate, A[["elu.est"]])
  expect_false(r$is_c1)

  r <- morie_geron_selu(zs)
  expect_close(r$a, A[["selu.a"]])
  expect_close(r$grad, A[["selu.grad"]])
  expect_close(r$var, A[["selu.var"]])

  r <- morie_geron_gelu(zs)
  expect_close(r$exact, A[["gelu.exact"]])
  expect_close(r$approx, A[["gelu.approx"]])
  expect_close(r$derivative, A[["gelu.deriv"]])
  expect_close(r$max_abs_gap, A[["gelu.gap"]])

  r <- morie_geron_heaviside(c(-1, 0, 2), at_zero = 0.5)
  expect_close(r$activation, A[["hev.a"]])
  expect_close(r$n_active, A[["hev.n_active"]])

  r <- morie_geron_leaky_relu(zs, alpha = 0.05)
  expect_close(r$activation, A[["lrel.a"]])
  expect_close(r$derivative, A[["lrel.d"]])
  expect_close(r$n_leaky, A[["lrel.n_leaky"]])

  r <- morie_geron_sigmoid(zs)
  expect_close(r$a, A[["sigm.a"]])
  expect_close(r$grad, A[["sigm.grad"]])

  r <- morie_geron_tanh(zs)
  expect_close(r$a, A[["tanh.a"]])
  expect_close(r$grad, A[["tanh.grad"]])

  r <- morie_geron_swish(zs, beta = 1.3)
  expect_close(r$a, A[["swi.a"]])
  expect_close(r$grad, A[["swi.grad"]])
  expect_close(r$gate, A[["swi.gate"]])
})

test_that("activation derivatives survive central finite differences", {
  # INDEPENDENT ROUTE: the analytic derivative each module returns is
  # checked against (f(z+h) - f(z-h)) / 2h, never against Python.
  h <- 1e-6
  zs <- c(-2, -1, -0.5, 0.5, 1, 2, 3.5)   # 0 excluded: leaky ReLU kinks there
  fd <- function(f) (f(zs + h) - f(zs - h)) / (2 * h)

  expect_close(morie_geron_elu(zs, alpha = 1.5)$derivative,
               fd(function(z) morie_geron_elu(z, alpha = 1.5)$a), tol = 1e-6)
  expect_close(morie_geron_selu(zs)$grad,
               fd(function(z) morie_geron_selu(z)$a), tol = 1e-6)
  expect_close(morie_geron_gelu(zs)$derivative,
               fd(function(z) morie_geron_gelu(z)$exact), tol = 1e-6)
  expect_close(morie_geron_sigmoid(zs)$grad,
               fd(function(z) morie_geron_sigmoid(z)$a), tol = 1e-6)
  expect_close(morie_geron_tanh(zs)$grad,
               fd(function(z) morie_geron_tanh(z)$a), tol = 1e-6)
  expect_close(morie_geron_swish(zs, beta = 1.3)$grad,
               fd(function(z) morie_geron_swish(z, beta = 1.3)$a), tol = 1e-6)
  expect_close(morie_geron_leaky_relu(zs, alpha = 0.05)$derivative,
               fd(function(z) morie_geron_leaky_relu(z, alpha = 0.05)$activation),
               tol = 1e-6)

  # GELU really is non-monotone: the derivative dips below zero.
  expect_true(any(morie_geron_gelu(seq(-2, -0.2, by = 0.1))$derivative < 0))
})

test_that("TLU, softmax and softmax scores match Python", {
  r <- morie_geron_tlu(matrix(c(1, -2, 0.5, 0.5, -1, -1), nrow = 3, byrow = TRUE),
                       c(1, 1), b = 0.25)
  expect_close(r$y, A[["tlu.y"]])
  expect_close(r$z, A[["tlu.z"]])

  r <- morie_geron_softmax_function(c(1, 2, 0.5))
  expect_close(r$p, A[["sftm.p"]])
  expect_close(r$jacobian, A[["sftm.jac"]])
  expect_equal(r$argmax, as.integer(A[["sftm.argmax"]]))
  expect_close(sum(r$p), 1)

  r <- morie_geron_softmax_function(matrix(c(1, 2, 0.5, 0, 0, 3), nrow = 2, byrow = TRUE))
  expect_close(r$p, A[["sftm.P2"]])
  expect_equal(as.integer(r$argmax), as.integer(A[["sftm.am2"]]))
  expect_close(rowSums(r$p), c(1, 1))

  r <- morie_geron_softmax_score(matrix(c(1, 2, 0.5, -1), nrow = 2, byrow = TRUE),
                                 matrix(c(0.3, -0.2, 0.5, 1, 0.4, -0.7), nrow = 2,
                                        byrow = TRUE))
  expect_close(r$scores, A[["sfts.scores"]])
  expect_close(r$p, A[["sfts.p"]])
  expect_equal(as.integer(r$predicted), as.integer(A[["sfts.pred"]]))
  expect_close(r$estimate, A[["sfts.est"]])
  # softmax is monotone, so argmax score == argmax probability
  expect_equal(as.integer(r$predicted), apply(r$p, 1, which.max) - 1L)
})

test_that("Gini and entropy match Python and the hand formula", {
  y <- c(0, 0, 1, 1, 1, 2)
  g <- morie_geron_gini_impurity(y)
  expect_close(g$gini, A[["gini.g"]])
  expect_close(g$proportions, A[["gini.p"]])
  expect_close(g$max_possible, A[["gini.max"]])
  # INDEPENDENT ROUTE: 1 - sum p^2 spelled out by hand.
  p <- c(2, 3, 1) / 6
  expect_close(g$gini, 1 - sum(p^2))

  e <- morie_geron_entropy_impurity(y)
  expect_close(e$entropy, A[["ent.h"]])
  expect_close(e$entropy_nats, A[["ent.nats"]])
  expect_close(e$max_possible, A[["ent.max"]])
  expect_close(e$entropy, -sum(p * log2(p)))
  expect_close(e$entropy_nats, e$entropy * log(2))
  # pure node: both impurities are exactly zero
  expect_close(morie_geron_gini_impurity(rep(1, 5))$gini, 0)
  expect_close(morie_geron_entropy_impurity(rep(1, 5))$entropy, 0)
})

test_that("RMSE and MAE match Python and their own definitions", {
  yt <- c(1, 2, 3, 4); yp <- c(1.5, 1, 3.2, 7)
  r <- morie_geron_rmse(yt, yp)
  expect_close(r$rmse, A[["rms.rmse"]])
  expect_close(r$mse, A[["rms.mse"]])
  expect_close(r$mae, A[["rms.mae"]])
  expect_close(r$rmse, sqrt(mean((yp - yt)^2)))

  m <- morie_geron_mae(yt, yp)
  expect_close(m$mae, A[["mae.mae"]])
  expect_close(m$ratio, A[["mae.ratio"]])
  expect_close(m$median_absolute_error, A[["mae.med"]])
  expect_true(m$rmse >= m$mae)   # l2 dominates l1
})

test_that("linear-model costs, OLS and ridge match Python", {
  X <- matrix(c(1, 0.5, 1, 1.5, 1, 2.5, 1, 4), nrow = 4, byrow = TRUE)
  y <- c(1, 2.2, 2.8, 4.4)

  r <- morie_geron_linreg_mse_cost(X, y, c(0.5, 0.8))
  expect_close(r$cost, A[["msec.cost"]])
  expect_close(r$gradient, A[["msec.grad"]])
  expect_close(r$residuals, A[["msec.resid"]])

  r <- morie_geron_normal_equation(X, y)
  expect_close(r$theta, A[["neq.theta"]])
  expect_close(r$rss, A[["neq.rss"]])
  expect_close(r$cond, A[["neq.cond"]], tol = 1e-7)
  # INDEPENDENT ROUTE: at the OLS solution the MSE gradient vanishes.
  expect_close(morie_geron_linreg_mse_cost(X, y, r$theta)$gradient, c(0, 0), tol = 1e-8)

  r <- morie_geron_ridge_cost(X, y, c(0.5, 0.8), 0.4)
  expect_close(r$cost, A[["ridg.cost"]])
  expect_close(r$penalty, A[["ridg.pen"]])
  expect_close(r$gradient, A[["ridg.grad"]])

  r <- morie_geron_ridge_normal(X, y, 0.4)
  expect_close(r$theta, A[["ridn.theta"]])
  expect_close(r$effective_df, A[["ridn.edf"]])
  expect_close(r$rss, A[["ridn.rss"]])
  # INDEPENDENT ROUTE: the ridge cost gradient is zero at the closed
  # form -- but ONLY after rescaling alpha. hmridg penalises a MEAN
  # squared error with (alpha/2)||theta||^2, while hmridn adds alpha to
  # the RSS normal equations, so the same nominal alpha is a different
  # amount of shrinkage in the two modules; the equivalent cost-form
  # alpha is 2*alpha/m. This convention gap is a property of the Python
  # modules, reproduced faithfully here rather than papered over.
  m <- nrow(X)
  expect_close(morie_geron_ridge_cost(X, y, r$theta, 2 * 0.4 / m)$gradient,
               c(0, 0), tol = 1e-8)
  # and the shrinkage is real: |theta_ridge| < |theta_ols| off the intercept
  expect_true(abs(r$theta[2]) < abs(morie_geron_normal_equation(X, y)$theta[2]))
})

test_that("L1, max-norm and gradient clipping match Python", {
  r <- morie_geron_l1_regularization(c(1.5, -0.3, 0.05, 0), 0.2, skip_bias = TRUE)
  expect_close(r$penalty, A[["l1r.pen"]])
  expect_close(r$gradient, A[["l1r.grad"]])
  expect_close(r$prox, A[["l1r.prox"]])
  expect_close(r$n_zero, A[["l1r.nzero"]])

  W <- matrix(c(3, 4, 0.3, 0.4), nrow = 2, byrow = TRUE)
  r <- morie_geron_max_norm(W, 2, axis = 1)
  expect_close(r$w, A[["mnr.w"]])
  expect_close(r$norm_before, A[["mnr.before"]])
  expect_close(r$norm_after, A[["mnr.after"]])
  expect_close(r$n_clipped, A[["mnr.nclip"]])
  # projection preserves direction exactly
  expect_close(r$w[1, ] / sqrt(sum(r$w[1, ]^2)), W[1, ] / sqrt(sum(W[1, ]^2)))

  r <- morie_geron_max_norm(c(3, 4), 2)
  expect_close(r$w, A[["mnr.flatw"]])
  expect_close(r$norm_before, A[["mnr.flatbefore"]])

  r <- morie_geron_gradient_clipping(c(3, 4), 2.5)
  expect_close(r$clipped, A[["gcl.clipped"]])
  expect_close(r$total_norm, A[["gcl.total"]])
  expect_close(r$scale, A[["gcl.scale"]])
  expect_close(r$new_norm, 2.5)
  expect_close(morie_geron_gradient_clipping(c(3, 4), 2.5, norm_type = Inf)$total_norm,
               A[["gcl.inf_total"]])
})

test_that("learning-rate schedules match Python", {
  r <- morie_geron_lr_exponential(0.1, 0.9, c(0, 1, 5, 10))
  expect_close(r$eta, A[["lrex.eta"]])
  expect_close(r$steps_per_decade, A[["lrex.spd"]])
  expect_true(is.infinite(morie_geron_lr_exponential(0.1, 1, 3)$steps_per_decade))

  r <- morie_geron_learning_rate_schedule(c(0, 1, 4), 1, 2)
  expect_close(r$eta, A[["lrs.eta"]])
  expect_close(r$schedule, A[["lrs.sched"]])
  expect_close(r$sum_eta, A[["lrs.sum"]])
  expect_close(r$sum_eta_squared, A[["lrs.sum2"]])

  r <- morie_geron_cosine_annealing(c(0, 3, 10), 10, 0.5, 0.05)
  expect_close(r$eta, A[["lcos.eta"]])
  expect_close(r$schedule, A[["lcos.sched"]])
  # endpoints are exact by construction
  expect_close(r$schedule[1], 0.5)
  expect_close(r$schedule[11], 0.05)
})

test_that("capacity heuristics match Python and layer algebra", {
  r <- morie_geron_neurons_per_layer(5, n_layers = 3, n_outputs = 2)
  expect_close(r$width, A[["npl.width"]])
  expect_close(r$n_parameters, A[["npl.params"]])
  expect_close(r$parameters_per_layer, A[["npl.per"]])
  # INDEPENDENT ROUTE: count the parameters layer by layer by hand.
  d <- 5; w <- 10; L <- 3; k <- 2
  by_hand <- (d * w + w) + 2 * (w * w + w) + (w * k + k)
  expect_close(r$n_parameters, by_hand)

  r <- morie_geron_overfitting(c(0.4, 0.3, 0.2, 0.1), c(0.5, 0.35, 0.36, 0.45),
                               tol = 0.02)
  expect_close(r$gap, A[["ovf.gap"]])
  expect_close(r$best_epoch, A[["ovf.best"]])
  expect_close(r$epochs_past_best, A[["ovf.past"]])
  expect_close(r$ratio, A[["ovf.ratio"]])
  expect_true(r$overfitting)
  expect_equal(r$verdict, A[["ovf.verdict"]])

  r <- morie_geron_underfitting(c(0.9, 0.85, 0.84, 0.84), threshold = 0.2,
                                val_err = c(0.95, 0.9, 0.87, 0.86))
  expect_equal(r$diagnosis, A[["uf.diag"]])
  expect_close(r$plateau_slope, A[["uf.slope"]], tol = 1e-8)
  expect_close(r$gap, A[["uf.gap"]])
  expect_true(r$converged)

  r <- morie_geron_curse_dimensionality(10, 1000)
  expect_close(r$nn_distance, A[["cod.nn"]])
  expect_close(r$mean_pairwise_distance, A[["cod.mean"]])
  expect_close(r$border_fraction, A[["cod.border"]])
  expect_close(r$sparsity_factor, A[["cod.sparse"]])
  expect_close(r$n_for_density, A[["cod.ndens"]], tol = 1e-6)

  r <- morie_geron_johnson_lindenstrauss(1000, 0.2)
  expect_close(r$d_min, A[["jl.dmin"]])
  expect_close(r$d_min_exact, A[["jl.exact"]])
  expect_close(morie_geron_johnson_lindenstrauss(1000, c(0.1, 0.3))$d_min,
               A[["jl.dminv"]])
})

test_that("standardization, encodings and imputation match Python", {
  X <- matrix(c(1, 10, 2, 20, 4, 25, 5, 45), nrow = 4, byrow = TRUE)
  r <- morie_geron_standardization(X)
  expect_close(r$X_std, A[["stz.Z"]])
  expect_close(r$mean, A[["stz.mu"]])
  expect_close(r$scale, A[["stz.sd"]])
  # ddof = 0 is the POPULATION sd, not R's sd()
  expect_close(r$scale, apply(X, 2, function(c) sqrt(mean((c - mean(c))^2))))
  expect_close(morie_geron_standardization(X, ddof = 1)$scale, A[["stz.sd1"]])
  expect_close(morie_geron_standardization(X, ddof = 1)$scale, apply(X, 2, sd))

  cats <- matrix(c("a", "x", "b", "x", "a", "y"), nrow = 3, byrow = TRUE)
  r <- morie_geron_one_hot_encoding(cats)
  expect_close(r$encoded, A[["ohe.enc"]])
  expect_equal(r$names, A[["ohe.names"]])
  expect_close(r$n_columns, A[["ohe.ncol"]])
  r <- morie_geron_one_hot_encoding(cats, drop_first = TRUE)
  expect_close(r$encoded, A[["ohe.enc1"]])
  expect_close(r$n_columns, A[["ohe.ncol1"]])

  r <- morie_geron_ordinal_encoding(matrix(c("c", "x", "a", "y", "b", "x"),
                                           nrow = 3, byrow = TRUE))
  expect_close(r$encoded, A[["ord.enc"]])
  expect_close(r$n_categories, A[["ord.ncat"]])

  r <- morie_geron_imputation_median(matrix(c(1, 10, NA, 20, 3, NA, 5, 40),
                                            nrow = 4, byrow = TRUE))
  expect_close(r$X_imputed, A[["imp.X"]])
  expect_close(r$statistics, A[["imp.stats"]])
  expect_close(r$n_missing, A[["imp.nmiss"]])
  expect_close(r$missing_fraction, A[["imp.frac"]])
})

test_that("Glorot init reproduces the LCG stream draw for draw", {
  r <- morie_geron_glorot_init(3, 4, seed = 7)
  expect_close(r$W, A[["xav.W"]])
  expect_close(r$limit, A[["xav.limit"]])
  expect_close(r$variance, A[["xav.var"]])
  expect_true(all(abs(r$W) <= r$limit))
  r <- morie_geron_glorot_init(3, 4, seed = 7, distribution = "normal")
  expect_close(r$W, A[["xav.Wn"]])
  expect_close(r$std, A[["xav.std"]])
})

test_that("optimiser steps match Python", {
  g <- c(0.5, -1.5, 0.25)
  r <- morie_geron_momentum(g, v = c(0.1, 0, -0.2), beta = 0.8, eta = 0.05,
                            theta = c(1, 1, 1))
  expect_close(r$theta, A[["mom.theta"]])
  expect_close(r$v, A[["mom.v"]])
  expect_close(r$terminal_step, A[["mom.term"]])
  expect_close(morie_geron_momentum(g, v = c(0.1, 0, -0.2), beta = 0.8,
                                    eta = 0.05, theta = c(1, 1, 1),
                                    nesterov = TRUE)$theta,
               A[["mom.theta_nes"]])

  r <- morie_geron_nesterov(g, v = c(0.1, 0, -0.2), beta = 0.8, eta = 0.05,
                            theta = c(1, 1, 1))
  expect_close(r$theta, A[["nag.theta"]])
  expect_close(r$lookahead, A[["nag.look"]])
  expect_close(r$v, A[["nag.v"]])
  # the callable arm evaluates the gradient AT the look-ahead point
  rc <- morie_geron_nesterov(function(th) th * 0 + g, v = c(0.1, 0, -0.2),
                             beta = 0.8, eta = 0.05, theta = c(1, 1, 1))
  expect_close(rc$theta, A[["nag.theta"]])

  r <- morie_geron_nadam(g, m = c(0.05, 0, 0), v = c(0.01, 0.02, 0),
                         eta = 0.01, t = 3, theta = c(1, 1, 1))
  expect_close(r$theta, A[["nadm.theta"]])
  expect_close(r$m_hat, A[["nadm.mhat"]])
  expect_close(r$v_hat, A[["nadm.vhat"]])
  expect_close(r$step, A[["nadm.step"]])
})

test_that("SGD and mini-batch GD match Python", {
  X <- matrix(c(1, 0.5, 1, 1.5, 1, 2.5, 1, 4), nrow = 4, byrow = TRUE)
  y <- c(1, 2.2, 2.8, 4.4)
  r <- morie_geron_sgd_update(X, y, c(0.5, 0.8), eta = 0.05, seed = 11)
  expect_close(r$index, A[["sgdu.index"]])
  expect_close(r$theta, A[["sgdu.theta"]])
  expect_close(r$gradient, A[["sgdu.grad"]])
  expect_close(r$batch_gradient, A[["sgdu.bgrad"]])
  expect_close(r$residual, A[["sgdu.resid"]])
  # explicit index must reproduce the LCG-picked row exactly
  expect_close(morie_geron_sgd_update(X, y, c(0.5, 0.8), eta = 0.05,
                                      index = A[["sgdu.index"]])$theta,
               A[["sgdu.theta"]])

  # HONEST DIVERGENCE: numpy's default_rng(3).permutation cannot be
  # reproduced in R, so the permutation is an anchor and is fed in.
  r <- morie_geron_minibatch_gd(X, y, c(0.5, 0.8), 0.05, 2,
                                order = A[["mbgd.perm"]], n_steps = 2)
  expect_close(r$theta, A[["mbgd.theta"]])
  expect_close(r$gradient, A[["mbgd.grad"]])
  expect_close(r$full_gradient, A[["mbgd.full"]])
  expect_close(r$mse, A[["mbgd.mse"]])
  expect_close(r$batch_indices, A[["mbgd.idx"]])
  # b = m reduces to batch GD: one step equals the full-gradient step
  rb <- morie_geron_minibatch_gd(X, y, c(0.5, 0.8), 0.05, 4, n_steps = 1)
  full0 <- (2 / 4) * as.numeric(t(X) %*% (X %*% c(0.5, 0.8) - y))
  expect_close(rb$theta, c(0.5, 0.8) - 0.05 * full0)
})

test_that("logistic probability, cost and gradient match Python", {
  X <- matrix(c(1, 0, 1, 1, 1, 2, 1, 3), nrow = 4, byrow = TRUE)
  y <- c(0, 0, 1, 1)
  th <- c(-1.5, 1)
  r <- morie_geron_logistic_probability(X, th)
  expect_close(r$p_hat, A[["logp.p"]])
  expect_close(r$logits, A[["logp.logits"]])
  expect_close(r$prediction, A[["logp.pred"]])

  r <- morie_geron_logistic_cost(X, y, th)
  expect_close(r$cost, A[["logcl.cost"]])
  expect_close(r$per_instance, A[["logcl.per"]])
  expect_close(r$baseline_cost, A[["logcl.base"]])
  # INDEPENDENT ROUTE: the naive -y log p - (1-y) log(1-p) form.
  p <- morie_geron_logistic_probability(X, th)$p_hat
  expect_close(r$cost, mean(-(y * log(p) + (1 - y) * log(1 - p))))

  r <- morie_geron_logistic_gradient(X, y, th)
  expect_close(r$gradient, A[["logg.grad"]])
  expect_close(r$hessian, A[["logg.hess"]])
  # INDEPENDENT ROUTE: finite differences on the cost.
  h <- 1e-6
  fd <- vapply(seq_along(th), function(j) {
    up <- th; dn <- th; up[j] <- up[j] + h; dn[j] <- dn[j] - h
    (morie_geron_logistic_cost(X, y, up)$cost -
       morie_geron_logistic_cost(X, y, dn)$cost) / (2 * h)
  }, numeric(1))
  expect_close(r$gradient, fd, tol = 1e-6)
  # Hessian is PSD, which is what makes the cost convex
  expect_true(all(eigen(r$hessian, only.values = TRUE)$values >= -1e-12))
})

test_that("perceptron, Hebb and residual block match Python", {
  r <- morie_geron_perceptron(matrix(c(2, 1, 3, 2, -1, -2, -2, -1), nrow = 4,
                                     byrow = TRUE),
                              c(1, 1, 0, 0), eta = 0.5, n_iter = 20)
  expect_close(r$w, A[["pcpt.w"]])
  expect_close(r$bias, A[["pcpt.b"]])
  expect_close(r$accuracy, A[["pcpt.acc"]])
  expect_close(r$mistakes_per_epoch, A[["pcpt.mist"]])
  expect_true(r$converged)
  # XOR is not linearly separable: the perceptron never converges
  rx <- morie_geron_perceptron(matrix(c(0, 0, 0, 1, 1, 0, 1, 1), nrow = 4,
                                      byrow = TRUE),
                               c(0, 1, 1, 0), eta = 1, n_iter = 6)
  expect_false(rx$converged)
  expect_close(rx$accuracy, A[["pcpt.xor_acc"]])

  r <- morie_geron_hebb_rule(matrix(c(1, 0.5, 0, 2), nrow = 2, byrow = TRUE),
                             matrix(c(1, 0.5), ncol = 1), eta = 0.2)
  expect_close(r$dW, A[["hebb.dW"]])
  expect_close(r$norm_after, A[["hebb.after"]])
  expect_true(length(r$warnings) > 0)   # unbounded growth is flagged

  r <- morie_geron_resnet(c(1, 2, 3), function(a) a * 0.5)
  expect_close(r$y, A[["resn.y"]])
  expect_close(r$residual_fraction, A[["resn.frac"]])
  expect_close(r$y, c(1, 2, 3) + c(1, 2, 3) * 0.5)
})

test_that("positional encoding matches Python and its rotation identity", {
  r <- morie_geron_positional_encoding(c(0, 1, 2, 7), 6)
  expect_close(r$pe, A[["pe.pe"]])
  expect_close(r$rotation_check, A[["pe.rot"]], tol = 1e-12)
  expect_close(r$wavelengths, A[["pe.wav"]])
  # INDEPENDENT ROUTE: PE(p+1) really is a fixed rotation of PE(p).
  expect_true(r$rotation_check < 1e-12)
  expect_close(morie_geron_positional_encoding(3, 4)$pe, A[["pe.scalar"]])
})

test_that("value function matches Python and iterated policy evaluation", {
  P <- A[["mdp.P"]]
  R <- A[["mdp.R"]]
  r <- morie_geron_value_function(1, c(0, 1, 0), 0.9, P = P, R = R)
  expect_close(r$V, A[["vf.V"]])
  expect_close(r$value, A[["vf.value"]])
  expect_close(r$r_pi, A[["vf.rpi"]])
  expect_close(r$P_pi, A[["vf.Ppi"]])
  expect_close(r$residual, A[["vf.resid"]], tol = 1e-10)

  # INDEPENDENT ROUTE: iterated policy evaluation, no linear solve.
  V <- rep(0, 3)
  for (it in seq_len(4000)) {
    V <- r$r_pi + 0.9 * as.numeric(r$P_pi %*% V)
  }
  expect_close(r$V, V, tol = 1e-8)

  rs <- morie_geron_value_function(0, A[["mdp.pi"]], 0.85, P = P, R = R)
  expect_close(rs$V, A[["vf.Vstoch"]])
})

test_that("tabular RL replays draw for draw", {
  r <- morie_geron_td_learning(c(0, 0, 0), c(0, 1, 0, 2), c(1, 0, 2, -1),
                              c(1, 2, 1, 2), alpha = 0.5, gamma = 0.9,
                              terminal = c(FALSE, FALSE, FALSE, TRUE))
  expect_close(r$V, A[["td.V"]])
  expect_close(r$td_error, A[["td.err"]])
  expect_close(r$target, A[["td.target"]])
  # INDEPENDENT ROUTE: replay the four transitions by hand, in order.
  V <- c(0, 0, 0); a <- 0.5; g <- 0.9
  V[1] <- V[1] + a * (1 + g * V[2] - V[1])
  V[2] <- V[2] + a * (0 + g * V[3] - V[2])
  V[1] <- V[1] + a * (2 + g * V[2] - V[1])
  V[3] <- V[3] + a * (-1 - V[3])          # terminal: no bootstrap
  expect_close(r$V, V)

  Q <- matrix(c(0, 1, 2, -1), nrow = 2, byrow = TRUE)
  r <- morie_geron_q_learning(Q, 0, 1, 0.5, 1, 0.5, 0.9)
  expect_close(r$Q, A[["ql.Q"]])
  expect_close(r$td_error, A[["ql.td"]])
  expect_close(r$target, A[["ql.target"]])
  expect_close(r$max_next, A[["ql.maxnext"]])
  expect_close(r$target, 0.5 + 0.9 * max(Q[2, ]))
  rd <- morie_geron_q_learning(Q, 0, 1, 0.5, 1, 0.5, 0.9, done = TRUE)
  expect_close(rd$td_error, A[["ql.td_done"]])
  expect_true(is.nan(rd$max_next))

  r <- morie_geron_credit_assignment(c(1, 0, 2, -1), gamma = 0.9, lam = 0.5)
  expect_close(r$raw_returns, A[["crd.ret"]])
  expect_close(r$eligibility, A[["crd.elig"]])
  expect_close(r$credit, A[["crd.credit"]])
  expect_close(r$discounted_rewards, A[["crd.disc"]])
  expect_close(r$total_return, A[["crd.total"]])
  # INDEPENDENT ROUTE: the return at t = 0 is the discounted sum.
  expect_close(r$total_return, sum(0.9^(0:3) * c(1, 0, 2, -1)))
  rn <- morie_geron_credit_assignment(c(1, 0, 2, -1), gamma = 0.9,
                                      normalize = TRUE)
  expect_close(rn$returns, A[["crd.norm"]])
})

test_that("hard voting matches Python with smallest-label tie-breaking", {
  models <- list(function(X) c(0, 1, 1, 0),
                 function(X) c(0, 1, 0, 0),
                 function(X) c(1, 1, 0, 1))
  r <- morie_geron_voting_hard(models, matrix(c(0, 1, 2, 3), ncol = 1),
                               y_true = c(0, 1, 0, 0))
  expect_close(r$predicted, A[["vth.pred"]])
  expect_close(r$votes, A[["vth.votes"]])
  expect_close(r$accuracy, A[["vth.acc"]])
  expect_close(r$member_accuracy, A[["vth.member"]])
  expect_close(r$agreement, A[["vth.agree"]])
  # identical members give an ensemble exactly as good as one of them
  same <- list(function(X) c(0, 1, 1, 0), function(X) c(0, 1, 1, 0))
  rs <- morie_geron_voting_hard(same, matrix(c(0, 1, 2, 3), ncol = 1),
                                y_true = c(0, 1, 0, 0))
  expect_close(rs$accuracy, rs$member_accuracy[1])
})

test_that("CART and the classification tree match Python", {
  XT <- matrix(c(1, 2, 3, 4), ncol = 1)
  r <- morie_geron_cart_algorithm(XT, c(0, 0, 1, 1))
  expect_close(r$tree$feature, A[["cart.feature"]])
  expect_close(r$tree$threshold, A[["cart.threshold"]])
  expect_close(r$n_leaves, A[["cart.leaves"]])
  expect_close(r$depth, A[["cart.depth"]])
  expect_close(r$train_accuracy, A[["cart.acc"]])
  expect_close(r$predictions, A[["cart.pred"]])
  expect_close(r$feature_importances, A[["cart.imp"]])
  # greedy CART cannot represent XOR at depth 1 but can at depth 2
  XX <- matrix(c(0, 0, 0, 1, 1, 0, 1, 1), nrow = 4, byrow = TRUE)
  YX <- c(0, 1, 1, 0)
  expect_close(morie_geron_cart_algorithm(XX, YX, max_depth = 1)$train_accuracy,
               A[["cart.xor1"]])
  expect_close(morie_geron_cart_algorithm(XX, YX, max_depth = 2)$train_accuracy,
               A[["cart.xor2"]])
  r2 <- morie_geron_cart_algorithm(XT, c(1, 1, 5, 5), criterion = "mse",
                                   max_depth = 1)
  expect_close(r2$predictions, A[["cart.mse_pred"]])
  expect_close(r2$train_mse, A[["cart.mse"]])

  XC <- matrix(c(1, 5, 2, 4, 3, 6, 6, 1, 7, 2, 8, 0.5), nrow = 6, byrow = TRUE)
  YC <- c(0, 0, 1, 1, 2, 2)
  r <- morie_geron_classification_tree(XC, YC, criterion = "entropy",
                                       max_depth = 3)
  expect_close(r$probabilities, A[["cdt.proba"]])
  expect_close(r$classes, A[["cdt.classes"]])
  expect_close(r$train_accuracy, A[["cdt.acc"]])
  expect_close(r$n_leaves, A[["cdt.leaves"]])
  expect_close(r$feature_importances, A[["cdt.imp"]])
  # leaf frequencies are probabilities: every row sums to one
  expect_close(rowSums(r$probabilities), rep(1, 6))
})

test_that("softmax cross-entropy, its gradient and the MLP match Python", {
  XE <- matrix(c(1, 0.5, 0.5, 2, -1, 1, 2, -0.5), nrow = 4, byrow = TRUE)
  THE <- matrix(c(0.4, -0.3, 0.1, 0.2, 0.7, -0.6), nrow = 2, byrow = TRUE)
  YE <- c(0, 1, 2, 0)
  r <- morie_geron_cross_entropy_cost(XE, YE, THE)
  expect_close(r$cost, A[["cec.cost"]])
  expect_close(r$probabilities, A[["cec.P"]])
  expect_close(r$per_sample_cost, A[["cec.per"]])
  expect_close(r$accuracy, A[["cec.acc"]])
  expect_close(r$chance_cost, A[["cec.chance"]])
  expect_close(rowSums(r$probabilities), rep(1, 4))

  g <- morie_geron_cross_entropy_gradient(XE, YE, THE)
  expect_close(g$gradient, A[["ceg.G"]])
  expect_close(g$grad_norm, A[["ceg.norm"]])
  expect_close(g$column_sum_max_abs, A[["ceg.colsum"]], tol = 1e-12)
  # softmax is over-parameterised: each gradient row sums to zero
  expect_close(rowSums(g$gradient), rep(0, 2), tol = 1e-12)
  # INDEPENDENT ROUTE: finite differences on the cost surface.
  h <- 1e-6
  fd <- THE * 0
  for (i in seq_len(2)) for (j in seq_len(3)) {
    up <- THE; dn <- THE
    up[i, j] <- up[i, j] + h; dn[i, j] <- dn[i, j] - h
    fd[i, j] <- (morie_geron_cross_entropy_cost(XE, YE, up)$cost -
                   morie_geron_cross_entropy_cost(XE, YE, dn)$cost) / (2 * h)
  }
  expect_close(g$gradient, fd, tol = 1e-6)

  XC <- matrix(c(1, 5, 2, 4, 3, 6, 6, 1, 7, 2, 8, 0.5), nrow = 6, byrow = TRUE)
  YC <- c(0, 0, 1, 1, 2, 2)
  m <- morie_geron_classification_mlp(XC, YC, hidden_sizes = 3, epochs = 40,
                                      lr = 0.2, seed = 5)
  expect_close(m$loss_history, A[["clsn.hist"]])
  expect_close(m$final_loss, A[["clsn.final"]])
  expect_close(m$accuracy, A[["clsn.acc"]])
  expect_close(m$n_params, A[["clsn.params"]])
  expect_close(m$weights[[1]], A[["clsn.W0"]])
  expect_close(m$weights[[2]], A[["clsn.W1"]])
  expect_close(m$probabilities, A[["clsn.P"]])
  # INDEPENDENT ROUTE: parameter count against the layer algebra.
  expect_close(m$n_params, (2 * 3 + 3) + (3 * 3 + 3))
})

test_that("confusion matrix matches Python for integer and string labels", {
  r <- morie_geron_confusion_matrix_labeled(c(0, 1, 2, 1, 0, 2),
                                            c(0, 2, 2, 1, 0, 1))
  expect_close(r$matrix, A[["cfm.M"]])
  expect_close(r$accuracy, A[["cfm.acc"]])
  expect_close(r$precision, A[["cfm.prec"]])
  expect_close(r$recall, A[["cfm.rec"]])
  expect_close(r$f1, A[["cfm.f1"]])
  expect_close(r$macro_f1, A[["cfm.macro"]])
  expect_close(r$predicted_totals, A[["cfm.ptot"]])
  # INDEPENDENT ROUTE: accuracy is the trace over the total.
  expect_close(r$accuracy, sum(diag(r$matrix)) / sum(r$matrix))

  r <- morie_geron_confusion_matrix_labeled(c("cat", "dog", "cat", "fox"),
                                            c("cat", "cat", "cat", "fox"))
  expect_close(r$matrix, A[["cfm.M2"]])
  expect_equal(r$labels, A[["cfm.lab2"]])
  expect_close(r$accuracy, A[["cfm.acc2"]])
})

test_that("cross-attention and CLIP match Python", {
  r <- morie_geron_cross_attention_report(A[["catt.D"]], A[["catt.E"]],
                                          A[["catt.WQ"]], A[["catt.WK"]],
                                          A[["catt.WV"]])
  expect_close(r$attention_weights, A[["catt.A"]])
  expect_close(r$output, A[["catt.out"]])
  expect_close(r$entropy, A[["catt.ent"]])
  expect_close(r$max_entropy, A[["catt.maxent"]])
  expect_close(r$argmax, A[["catt.argmax"]])
  expect_close(r$d_k, A[["catt.dk"]])
  # attention rows are distributions and entropy respects its ceiling
  expect_close(rowSums(r$attention_weights), c(1, 1))
  expect_true(all(r$entropy <= r$max_entropy + 1e-12))

  r <- morie_geron_clip(A[["clip.I"]], A[["clip.T"]], tau = 0.2,
                        class_prompts = A[["clip.P"]])
  expect_close(r$loss, A[["clip.loss"]])
  expect_close(r$similarity, A[["clip.S"]])
  expect_close(r$matched_similarity, A[["clip.match"]])
  expect_close(r$chance_loss, A[["clip.chance"]])
  expect_close(r$zero_shot$similarity, A[["clip.zs"]])
  expect_close(r$zero_shot$predictions, A[["clip.zpred"]])
  expect_close(r$chance_loss, log(3))
})

test_that("classification + localization matches Python", {
  OUTM <- A[["clc.out"]]
  r <- morie_geron_classification_localization(NULL, function(im) OUTM,
                                               gt_class = c(0, 1),
                                               gt_box = A[["clc.gtb"]],
                                               alpha = 0.01)
  expect_close(r$class_probs, A[["clc.P"]])
  expect_close(r$predicted_class, A[["clc.pred"]])
  expect_close(r$iou, A[["clc.iou"]])
  expect_close(r$loss_class, A[["clc.lcls"]])
  expect_close(r$loss_box, A[["clc.lbox"]])
  expect_close(r$loss, A[["clc.loss"]])
  expect_close(r$box_corners, A[["clc.corners"]])
  # INDEPENDENT ROUTE: the combined loss is the weighted sum of the heads.
  expect_close(r$loss, r$loss_class + 0.01 * r$loss_box)
  expect_true(all(r$iou >= 0 & r$iou <= 1))
})

test_that("computational graph matches Python and its own finite differences", {
  expr <- list("mul", list("add", "x", 2), list("sin", "y"))
  r <- morie_geron_computational_graph(expr, list(x = 1.5, y = 0.7))
  expect_close(r$value, A[["cgrf.value"]])
  expect_close(r$grad$x, A[["cgrf.gx"]])
  expect_close(r$grad$y, A[["cgrf.gy"]])
  expect_close(r$fd_check$x, A[["cgrf.fdx"]])
  expect_close(r$fd_check$y, A[["cgrf.fdy"]])
  expect_close(r$n_nodes, A[["cgrf.nodes"]])
  # INDEPENDENT ROUTE: reverse mode against the module's own central
  # differences, and against the closed form.
  expect_close(r$grad$x, r$fd_check$x, tol = 1e-6)
  expect_close(r$grad$y, r$fd_check$y, tol = 1e-6)
  expect_close(r$grad$x, sin(0.7))
  expect_close(r$grad$y, (1.5 + 2) * cos(0.7))

  expr2 <- list("log", list("add", list("square", "x"), 1))
  r <- morie_geron_computational_graph(expr2, list(x = 2))
  expect_close(r$value, A[["cgrf2.value"]])
  expect_close(r$grad$x, A[["cgrf2.gx"]])
  expect_close(r$fd_check$x, A[["cgrf2.fdx"]])
  expect_close(r$grad$x, 2 * 2 / (2^2 + 1))
})

test_that("character RNN matches Python draw for draw", {
  r <- morie_geron_char_rnn("abcabcabc", hidden = 4, epochs = 20, lr = 0.5,
                            seed = 2, generate = 4)
  expect_close(r$loss_history, A[["chrn.hist"]])
  expect_close(r$final_loss, A[["chrn.final"]])
  expect_close(r$chance_loss, A[["chrn.chance"]])
  expect_close(r$perplexity, A[["chrn.ppl"]])
  expect_equal(r$vocab, A[["chrn.vocab"]])
  expect_equal(r$generated, A[["chrn.gen"]])
  expect_close(r$weights$Wxh, A[["chrn.Wxh"]])
  expect_close(r$weights$Whh, A[["chrn.Whh"]])
  expect_close(r$weights$Why, A[["chrn.Why"]])
  # the model beats the uniform baseline log V
  expect_true(r$final_loss < r$chance_loss)
  expect_close(r$perplexity, exp(r$final_loss))
})

test_that("trained conv autoencoder matches Python", {
  r <- morie_geron_conv_autoencoder_trained(A[["cae.img"]], filters = 2,
                                            epochs = 15, lr = 0.02, seed = 1,
                                            patch = 2)
  expect_close(r$loss_history, A[["cae.hist"]])
  expect_close(r$final_loss, A[["cae.final"]])
  expect_close(r$encoder, A[["cae.enc"]])
  expect_close(r$decoder, A[["cae.dec"]])
  expect_close(r$reconstruction[[1]], A[["cae.recon"]])
  expect_close(r$compression_ratio, A[["cae.ratio"]])
  expect_close(r$n_patches, A[["cae.npatch"]])
  expect_close(r$grcae_check$loss, A[["cae.check_loss"]])
  # the bottleneck really is narrower than the patch
  expect_true(r$compression_ratio > 1)
})
