# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for the Kamath Ch 2 shelf (W3 tranche 1).
#
# Anchors generated by running the Python core, not recalled. The
# attention chain must compose to the shared alammar core's output;
# the losses to hand log-sums; Eq 2.19's mask-inside-scaling must
# genuinely differ from Vaswani's for finite masks and agree at -Inf.

test_that("the recurrences and context mappings match Python", {
  expect_equal(morie_kamath_encoder_state(0.5, 0.5)$h, tanh(1),
               tolerance = 1e-12)  # both arms agree to 12 digits; 1e-13 is summation order
  expect_equal(morie_kamath_encoder_state(1, 2,
                                          f = function(h, x) h * x)$h, 2)
  expect_equal(morie_kamath_decoder_state(0.1, 0.2, 0.3)$s, tanh(0.6),
               tolerance = 1e-14)
  H <- rbind(c(1, 2), c(3, 4))
  expect_equal(morie_kamath_context_vector(H, "mean")$context, c(2, 3))
  expect_equal(morie_kamath_context_vector(H, "last")$context, c(3, 4))
  out <- morie_kamath_context_simplest(c(3, 4), all_states = H)
  expect_true(out$agrees_with_eq22)
  expect_error(morie_kamath_context_simplest(c(9, 9), all_states = H),
               "disagree")
})

test_that("the decoder distribution and seq2seq CE match Python", {
  out <- morie_kamath_decoder_token_distribution(
    0.1, 0.2, 0.3, W = rbind(c(1, 0, 0), c(0, 0, 5)))
  expect_equal(sum(out$distribution), 1, tolerance = 1e-12)
  expect_equal(out$predicted_token, 1L)
  ce <- morie_kamath_seq2seq_cross_entropy(c(0, 1),
                                           rbind(c(0.5, 0.5),
                                                 c(0.25, 0.75)))
  expect_equal(ce$estimate, 0.9808292530117262, tolerance = 1e-14)
  expect_error(morie_kamath_seq2seq_cross_entropy(0, rbind(c(0.5, 0.6))),
               "distribution")
  expect_error(morie_kamath_seq2seq_cross_entropy(0, rbind(1), U = 5),
               "does not match")
})

test_that("the attention chain composes to the shared core", {
  q <- c(1, 0)
  K <- rbind(c(1, 0), c(0, 1))
  V <- rbind(5, -5)
  scores <- vapply(1:2, function(i) {
    morie_kamath_attention_score(q, K[i, ])$estimate
  }, numeric(1))
  w <- morie_kamath_attention_softmax(scores)$weights
  o <- morie_kamath_attention_output(w, V)$output
  full <- morie_kamath_scaled_dot_attention(rbind(q), K, V)$output
  expect_equal(o, as.numeric(full[1, ]), tolerance = 1e-14)
  expect_equal(o, 1.6976154932665688, tolerance = 1e-14)
})

test_that("Eq 2.9 is an element of Eq 2.8 and refuses strangers", {
  a <- c(0.3, -1.2, 2)
  full <- morie_kamath_attention_softmax(a)$weights
  for (i in 1:3) {
    expect_equal(morie_kamath_softmax_element(a[i], a)$estimate, full[i],
                 tolerance = 1e-14)
  }
  expect_error(morie_kamath_softmax_element(99, a), "not one of")
})

test_that("scores and delegation refuse contradictory d_k", {
  q <- c(0.3, -0.7)
  k <- c(1.1, 0.4)
  expect_equal(morie_kamath_scaled_dot_score(q, k)$estimate,
               sum(q * k) / sqrt(2), tolerance = 1e-14)
  expect_error(morie_kamath_scaled_dot_score(q, k, d_k = 7),
               "contradicts")
  expect_error(morie_kamath_scaled_dot_attention(rbind(q), rbind(k),
                                                 rbind(1), d_k = 9),
               "contradicts")
})

test_that("heads and concat reproduce the alammar core", {
  set.seed(5)
  X <- matrix(stats::rnorm(6), 3, 2)
  W <- lapply(1:3, function(i) matrix(stats::rnorm(4), 2, 2))
  h1 <- morie_kamath_multihead_head_i(X, X, X, W[[1]], W[[2]],
                                      W[[3]])$head
  direct <- morie_alammar_sdp_attention(X %*% W[[1]], X %*% W[[2]],
                                        X %*% W[[3]])$output
  expect_equal(h1, direct, tolerance = 1e-14)
  Wo <- matrix(stats::rnorm(4), 2, 2)
  out <- morie_kamath_multihead_concat(list(h1), Wo)$output
  expect_equal(out, h1 %*% Wo, tolerance = 1e-14)
})

test_that("the book's mask-inside-scaling splits from Vaswani on finite masks", {
  set.seed(6)
  Q <- matrix(stats::rnorm(4), 2, 2)
  K <- matrix(stats::rnorm(4), 2, 2)
  V <- matrix(stats::rnorm(2), 2, 1)
  M <- rbind(c(0, 3), c(0, 0))
  book <- morie_kamath_masked_attention(Q, K, V, M)$output
  vasw <- morie_alammar_sdp_attention(Q, K, V, mask = M)$output
  expect_false(isTRUE(all.equal(book, vasw)))
  Minf <- rbind(c(0, -Inf), c(0, 0))
  Ab <- morie_kamath_masked_attention(Q, K, V, Minf)$attention
  expect_equal(Ab[1, 2], 0)
})

test_that("positional encodings satisfy sin^2 + cos^2 = 1", {
  for (i in c(0, 3, 17)) {
    for (j in c(0, 1)) {
      s <- morie_kamath_positional_sin(i, j, 6)$estimate
      cc <- morie_kamath_positional_cos(i, j, 6)$estimate
      expect_equal(s^2 + cc^2, 1, tolerance = 1e-14)
    }
  }
  expect_error(morie_kamath_positional_sin(0, 3, 6), "below d")
})

test_that("FFN and layer norm match Python", {
  out <- morie_kamath_ffn_relu(rbind(c(1, -1)),
                               rbind(c(1, 0), c(0, 1)),
                               rbind(1, 1), c(0, 0), 0.5)
  expect_equal(out$output[1, 1], 1.5)
  expect_equal(out$hidden[1, ], c(1, 0))
  ln <- morie_kamath_layer_norm(c(2, 4, 6))
  expect_equal(ln$normalised,
               c(-1.2247448713913593, 0, 1.2247448713913593),  # eps = 1e-12 inside the sqrt, as in Python
               tolerance = 1e-14)
  pinned <- morie_kamath_layer_norm(c(2, 4), mu = 3, sigma = 1, g = 2)
  expect_equal(pinned$output, c(-2, 2))
  expect_error(morie_kamath_layer_norm(c(5, 5)), "constant vector")
})

test_that("the loss family matches Python's hand sums", {
  p <- c(0.5, 1, 0.25, 1)
  mlm <- morie_kamath_mlm_loss(p, c(0, 2))
  expect_equal(mlm$estimate, (log(2) + log(4)) / 2, tolerance = 1e-14)
  p2 <- c(0.5, 1e-9, 0.25, 1e-9)
  expect_equal(morie_kamath_mlm_loss(p2, c(0, 2))$estimate, mlm$estimate)
  expect_error(morie_kamath_mlm_loss(p, c(0, 0)), "duplicates")
  expect_error(morie_kamath_mlm_loss(p, integer(0)), "empty")
  expect_equal(morie_kamath_clm_loss(c(0.5, 0.25))$estimate,
               (log(2) + log(4)) / 2, tolerance = 1e-14)
  rtd <- morie_kamath_rtd_loss(c(0.9, 0.9), c(1, 0))
  expect_equal(rtd$per_token, c(-log(0.9), -log(0.1)),
               tolerance = 1e-12)
  expect_equal(rtd$accuracy, 0.5)
  tlm <- morie_kamath_tlm_loss(c(0.5, 1), 0.25, 0, 0)
  expect_equal(tlm$estimate, log(2) + log(4), tolerance = 1e-14)
  expect_equal(morie_kamath_nsp_loss(0.8, "y", 0)$estimate, -log(0.2),
               tolerance = 1e-14)
  span <- morie_kamath_span_loss(c(1e-9, 0.5, 0.25, 1e-9), "x", 1, 2)
  expect_equal(span$estimate, (log(2) + log(4)) / 2, tolerance = 1e-14)
  expect_error(morie_kamath_span_loss(c(0.5), "x", 0, 5),
               "inside the sequence")
  expect_equal(morie_kamath_ssl_loss(c(1, 2), c(2, 0.5))$estimate, 3)
  expect_error(morie_kamath_ssl_loss(1, -1), "negative")
})

test_that("GPT objectives compose and MoE matches Python", {
  l1 <- morie_kamath_gpt_unsupervised(c(0.5, 0.5))$estimate
  expect_equal(l1, -2 * log(2), tolerance = 1e-14)
  l3 <- morie_kamath_gpt_combined(l1, log(0.8), 0.5)
  expect_equal(l3$estimate, log(0.8) + 0.5 * l1, tolerance = 1e-14)
  boom <- function(x) stop("expert ran")
  out <- morie_kamath_moe_output(1, c(1, 0),
                                 list(function(x) x * 3, boom))
  expect_equal(out$output, 3)
  expect_equal(out$experts_evaluated, 1L)
  g <- morie_kamath_moe_topk_gating(1, rbind(c(3, 1, 2, 0.5)), k = 2)
  expect_equal(g$weights, c(0.7310585786300049, 0, 0.2689414213699951, 0),
               tolerance = 1e-14)
  expect_equal(g$selected_experts, c(0L, 2L))
  mix <- morie_kamath_mixtral_moe(1, rbind(c(3, 1, 2)))
  expect_equal(mix$output, 1, tolerance = 1e-12)   # identity experts
  W1 <- rbind(1)
  W3 <- rbind(1)
  W2 <- rbind(1)
  sw <- morie_kamath_mixtral_moe(2, rbind(c(3, 1)),
                                 expert_weights = list(
                                   list(W1, W3, W2), list(W1, W3, W2)))
  expect_equal(sw$output, (2 / (1 + exp(-2))) * 2, tolerance = 1e-12)
  expect_error(morie_kamath_mixtral_moe(1, rbind(c(1, 2)),
                                        expert_weights = list(
                                          list(W1, W3, W2))),
               "triple per expert")
})
