# Coverage for the multi-trait mixed model, meta-path counts, summary-data
# Mendelian randomisation, Manski-Pepper MTR/MTS bounds, matrix games,
# multinomial expansions, two-stage sampling, parallel mediators, plug-in
# mutual information and MuY; recomputed from the definitions in the test
# body with base R.

test_that("Mtlmmfit is the GLS BLUE/BLUP of the Kronecker multi-trait model", {
  set.seed(1)
  J <- 5
  nt <- 2
  Y <- matrix(rnorm(J * nt, 3), J)
  L <- matrix(rnorm(J * J), J)
  G <- crossprod(L) / J + diag(J)
  St <- matrix(c(1, 0.4, 0.4, 2), 2)
  Rt <- matrix(c(0.5, 0.1, 0.1, 0.7), 2)
  Z <- diag(J)
  gls <- function(X) {
    y <- as.numeric(t(Y))
    Zm <- kronecker(Z, diag(nt))
    Sg <- kronecker(G, St)
    Vi <- solve(Zm %*% Sg %*% t(Zm) + kronecker(diag(J), Rt))
    b <- solve(t(X) %*% Vi %*% X, t(X) %*% Vi %*% y)
    list(beta = as.numeric(b), u = as.numeric(Sg %*% t(Zm) %*% Vi %*% (y - X %*% b)))
  }
  r <- Mtlmmfit(Y, Z, G, St, Rt)
  e <- gls(kronecker(matrix(1, J, 1), diag(nt)))
  expect_equal(r$beta, e$beta, tolerance = 1e-9)
  expect_equal(r$mu, e$beta[1:2], tolerance = 1e-9)
  expect_equal(r$b, e$u, tolerance = 1e-9)
  expect_equal(c(r$J, r$T), c(J, nt))
  xc <- seq(-1, 1, length.out = J * nt)
  r2 <- Mtlmmfit(Y, Z, G, St, Rt, X = matrix(xc))
  e2 <- gls(cbind(kronecker(matrix(1, J, 1), diag(nt)), xc))
  expect_equal(r2$beta, e2$beta, tolerance = 1e-9)
})

test_that("Metapath multiplies type-masked adjacency blocks", {
  W <- matrix(0, 5, 5)
  W[1, 3] <- W[3, 1] <- 1
  W[1, 4] <- W[4, 1] <- 2
  W[2, 4] <- W[4, 2] <- 1
  W[2, 5] <- W[5, 2] <- 1
  W[3, 4] <- W[4, 3] <- 1
  ty <- c("A", "A", "P", "P", "P")
  msk <- function(a, b) W * outer(ty == a, ty == b)
  r <- Metapath(W, ty, c("A", "P", "A"))
  M <- msk("A", "P") %*% msk("P", "A")
  expect_equal(r$M, M, tolerance = 1e-12)
  expect_equal(r$estimate, sum(M[1:2, 1:2]), tolerance = 1e-12)
  expect_true(r$symmetric)
  expect_equal(r$pathsim[1:2, 1:2], 2 * M[1:2, 1:2] / outer(diag(M)[1:2], diag(M)[1:2], "+"), tolerance = 1e-12)
  expect_true(all(is.nan(r$pathsim[3:5, ])))
  expect_equal(r$counts, rowSums(M), tolerance = 1e-12)
  a <- Metapath(W, ty, c("A", "P"))
  expect_false(a$symmetric)
  expect_equal(a$estimate, sum(msk("A", "P")), tolerance = 1e-12)
  expect_true(all(is.nan(a$pathsim)))
  d <- Metapath(W)
  expect_equal(d$estimate, sum(W), tolerance = 1e-12)
})

test_that("morie_mtr2sx reproduces IVW, multiplicative and DerSimonian-Laird MR", {
  bx <- c(0.12, 0.08, -0.15, 0.2, 0.05)
  sx <- c(0.01, 0.012, 0.015, 0.02, 0.008)
  by <- c(0.03, 0.025, -0.02, 0.07, 0.004)
  sy <- c(0.01, 0.008, 0.012, 0.015, 0.006)
  rt <- by / bx
  v <- sy^2 / bx^2
  w <- 1 / v
  est <- sum(w * rt) / sum(w)
  Q <- sum(w * (rt - est)^2)
  f <- lm(by ~ bx - 1, weights = 1 / sy^2)
  r <- morie_mtr2sx(bx, sx, by, sy)
  expect_equal(r$estimate, est, tolerance = 1e-12)
  expect_equal(r$estimate, unname(coef(f)), tolerance = 1e-10)
  expect_equal(r$regression_estimate, unname(coef(f)), tolerance = 1e-10)
  expect_equal(r$Q, Q, tolerance = 1e-12)
  expect_equal(r$phi_multiplicative, max(1, sqrt(Q / 4)), tolerance = 1e-12)
  expect_equal(r$se, sqrt(1 / sum(w)) * max(1, sqrt(Q / 4)), tolerance = 1e-12)
  expect_equal(r$I2, max(0, (Q - 4) / Q), tolerance = 1e-12)
  expect_equal(r$p_value, 2 * pnorm(-abs(est / r$se)), tolerance = 1e-12)
  fx <- morie_mtr2sx(bx, sx, by, sy, model = "fixed")
  expect_equal(fx$se, sqrt(1 / sum(w)), tolerance = 1e-12)
  expect_equal(fx$regression_se_fixed, sqrt(1 / sum(bx^2 / sy^2)), tolerance = 1e-12)
  tau2 <- max(0, (Q - 4) / (sum(w) - sum(w^2) / sum(w)))
  ad <- morie_mtr2sx(bx, sx, by, sy, model = "additive")
  expect_equal(ad$tau2, tau2, tolerance = 1e-12)
  expect_equal(ad$estimate, sum(rt / (v + tau2)) / sum(1 / (v + tau2)), tolerance = 1e-12)
  s2 <- morie_mtr2sx(bx, sx, by, sy, weights = "second_order", theta = 0.1)
  expect_equal(s2$variances, v + by^2 * sx^2 / bx^4 - 2 * 0.1 * by * sy * sx / bx^3, tolerance = 1e-12)
  one <- morie_mtr2sx(bx[1], sx[1], by[1], sy[1])
  expect_equal(c(one$df, one$tau2, one$I2, one$phi_multiplicative), c(0, 0, 0, 1))
  expect_error(morie_mtr2sx(bx, sx, by, sy, model = "x"), "model must be one of")
  expect_error(morie_mtr2sx(bx, sx, by, sy, weights = "x"), "weights must be one of")
  expect_error(morie_mtr2sx(bx[-1], sx, by, sy), "same length")
  expect_error(morie_mtr2sx(numeric(0), numeric(0), numeric(0), numeric(0)), "no genetic variants")
  expect_error(morie_mtr2sx(c(0, bx[-1]), sx, by, sy), "undefined ratio")
  expect_error(morie_mtr2sx(bx, sx, by, -sy), "must be positive")
  expect_error(morie_mtr2sx(bx, sx, by, sy, weights = "second_order", theta = 50), "non-positive")
})

test_that("Mtrbnd, Mtsbnd and Mtsmtv follow Manski-Pepper", {
  y <- c(2, 5, 3, 8, 6, 4, 7, 1)
  z <- c(0, 1, 2, 1, 2, 0, 1, 2)
  lo <- 0
  hi <- 10
  d <- 1
  r <- Mtrbnd(y, z, d = d, y_min = lo, y_max = hi)
  expect_equal(c(r$lower, r$upper), c(mean(ifelse(z <= d, y, lo)), mean(ifelse(z >= d, y, hi))), tolerance = 1e-12)
  expect_equal(r$nfixed, sum(z == d))
  dr <- Mtrbnd(y, z, direction = "decreasing", d = d, y_min = lo, y_max = hi)
  expect_equal(c(dr$lower, dr$upper), c(mean(ifelse(z >= d, y, lo)), mean(ifelse(z <= d, y, hi))), tolerance = 1e-12)
  df <- Mtrbnd(y, z)
  expect_equal(c(df$lower, df$upper, df$d), c(mean(ifelse(z <= 2, y, 1)), mean(ifelse(z >= 2, y, 8)), 2), tolerance = 1e-12)
  expect_error(Mtrbnd(y, z, direction = "up"), "direction")
  expect_error(Mtrbnd(y, z[-1]), "same length")
  expect_error(Mtrbnd(numeric(0), numeric(0)), "empty")
  cm <- mean(y[z == d])
  pb <- mean(z < d)
  pa <- mean(z > d)
  pt <- mean(z == d)
  s <- Mtsbnd(y, z, d = d, ymin = lo, ymax = hi)
  expect_equal(c(s$lower, s$upper), c(pb * lo + (pt + pa) * cm, (pb + pt) * cm + pa * hi), tolerance = 1e-12)
  sn <- Mtsbnd(y, z, monotone = FALSE, d = d, ymin = lo, ymax = hi)
  expect_equal(c(sn$lower, sn$upper), c((pb + pt) * cm + pa * lo, pb * hi + (pt + pa) * cm), tolerance = 1e-12)
  expect_equal(sn$condmean, cm, tolerance = 1e-12)
  expect_error(Mtsbnd(y, z, d = 5), "no unit is observed")
  expect_error(Mtsbnd(y, z[-1]), "same length")
  expect_error(Mtsbnd(numeric(0), numeric(0)), "empty")
  b <- Mtsmtv(y, z, lo, hi, d = d)
  lb <- max(s$lower, r$lower)
  ub <- min(s$upper, r$upper)
  expect_equal(c(b$lower, b$upper, b$width), c(lb, ub, ub - lb), tolerance = 1e-12)
  expect_equal(b$empty, as.numeric(lb > ub))
  expect_equal(Mtsmtv(y, z, lo, hi)$d, 2)
  expect_error(Mtsmtv(y, z, 5, 4), "y_min must not exceed")
  expect_error(Mtsmtv(y, z[-1], lo, hi), "same length")
  expect_error(Mtsmtv(numeric(0), numeric(0), lo, hi), "empty")
})

test_that("Matgame finds saddle points and brackets the mixed value", {
  A <- rbind(c(3, 1, 4), c(2, 0, 1))
  s <- Matgame(A)
  expect_equal(c(s$value, s$saddle), c(1, 1))
  expect_equal(s$row_strategy, c(1, 0))
  expect_equal(s$col_strategy, c(0, 1, 0))
  B <- rbind(c(2, -1), c(-1, 1))
  v <- (2 * 1 - 1) / (2 + 1 + 1 + 1)
  g <- Matgame(B, iters = 3000)
  expect_equal(g$saddle, 0)
  expect_equal(g$lower, min(as.numeric(g$row_strategy %*% B)), tolerance = 1e-12)
  expect_equal(g$upper, max(as.numeric(B %*% g$col_strategy)), tolerance = 1e-12)
  expect_equal(g$value, (g$lower + g$upper) / 2, tolerance = 1e-12)
  expect_lte(g$lower, v)
  expect_gte(g$upper, v)
  expect_equal(sum(g$row_strategy), 1, tolerance = 1e-12)
  expect_error(Matgame(matrix(numeric(0), 0, 2)), "non-empty")
})

test_that("MultiExp and Multinom are multinomial-coefficient identities", {
  r <- MultiExp(c(0.5, 2, -1), 4)
  expect_equal(r$expansion, 1.5^4, tolerance = 1e-12)
  expect_equal(r$direct_power, 1.5^4, tolerance = 1e-12)
  expect_equal(r$n_terms, choose(6, 2))
  expect_equal(r$max_coefficient, factorial(4) / 2)
  expect_equal(MultiExp(3, 0)$expansion, 1)
  expect_error(MultiExp(numeric(0), 2), "non-empty")
  expect_error(MultiExp(1:2, -1), "non-negative")
  m <- Multinom(c(2, 3, 1))
  expect_equal(m$coefficient, factorial(6) / (2 * 6 * 1))
  expect_equal(Multinom(c(2, 3, 1), 8)$coefficient, factorial(8) / (2 * 6 * 1 * 2))
  expect_error(Multinom(c(2, 3), 4), "exceeds N")
  expect_error(Multinom(c(-1, 2)), "integers >= 0")
  expect_error(Multinom(1, NA), "N must be")
})

test_that("Twostage is Cochran's two-stage ratio estimator", {
  Y <- list(c(3, 5, 4), c(8, 6, 7, 9), c(2, 1, 3))
  Nl <- c(10, 12, 8)
  M <- 20
  N <- 220
  r <- Twostage(Y, Nl, M, N)
  yb <- vapply(Y, mean, 0)
  s2 <- vapply(Y, var, 0)
  nl <- lengths(Y)
  est <- sum(Nl * yb) / sum(Nl)
  bt <- (1 - 3 / M) * sum((Nl * yb - Nl * est)^2) / (3 * 2)
  wt <- sum(Nl^2 * (1 - nl / Nl) * s2 / nl) / (3 * M)
  v <- (M / N)^2 * (bt + wt)
  expect_equal(r$estimate, est, tolerance = 1e-12)
  expect_equal(r$se, sqrt(v), tolerance = 1e-12)
  expect_equal(c(r$ci_lower, r$ci_upper), est + c(-1, 1) * qnorm(0.975) * sqrt(v), tolerance = 1e-12)
  expect_equal(r$between_term + r$within_term, v, tolerance = 1e-12)
  expect_error(Twostage(Y[1], Nl[1], M, N), "at least two PSUs")
  expect_error(Twostage(Y, Nl[-1], M, N), "one entry per sampled PSU")
  expect_error(Twostage(Y, Nl, 2, N), "M must be at least")
  expect_error(Twostage(list(1, 2:3), c(5, 5), M, N), "at least two elements")
  expect_error(Twostage(Y, c(2, 12, 8), M, N), "cannot exceed its population")
})

test_that("MultM matches the lm mediator and outcome regressions", {
  set.seed(2)
  n <- 30
  x <- rnorm(n)
  cv <- rnorm(n)
  m1 <- 0.5 * x + 0.2 * cv + rnorm(n)
  m2 <- -0.3 * x + rnorm(n)
  y <- 0.4 * x + 0.7 * m1 - 0.2 * m2 + 0.1 * cv + rnorm(n)
  r <- MultM(y, x, rbind(m1, m2), C = cv)
  a <- c(coef(lm(m1 ~ x + cv))[["x"]], coef(lm(m2 ~ x + cv))[["x"]])
  fy <- coef(lm(y ~ x + m1 + m2 + cv))
  expect_equal(r$a, a, tolerance = 1e-10)
  expect_equal(r$b, unname(fy[c("m1", "m2")]), tolerance = 1e-10)
  expect_equal(r$direct, fy[["x"]], tolerance = 1e-10)
  expect_equal(r$indirect_total, sum(a * fy[c("m1", "m2")]), tolerance = 1e-10)
  expect_equal(r$total, r$direct + r$indirect_total, tolerance = 1e-12)
  r0 <- MultM(y, x, cbind(m1, m2))
  expect_equal(r0$a[1], coef(lm(m1 ~ x))[["x"]], tolerance = 1e-10)
  expect_error(MultM(y[1:5], x[1:5], cbind(m1, m2)[1:5, ]), "too few observations")
  expect_error(MultM(y, x[-1], cbind(m1, m2)), "share their first dimension")
  expect_error(MultM(y, x, cbind(m1, m2), C = cv[-1]), "wrong number of rows")
})

test_that("Mutinfo is the plug-in mutual information with Miller-Madow", {
  a <- c("u", "u", "v", "w", "v", "u", "w", "w", "v", "u")
  b <- c(1, 2, 1, 2, 2, 1, 1, 2, 1, 1)
  P <- table(a, b) / 10
  px <- rowSums(P)
  py <- colSums(P)
  nz <- P > 0
  mi <- sum(P[nz] * log(P[nz] / outer(px, py)[nz]))
  r <- Mutinfo(a, b)
  expect_equal(r$mi, mi, tolerance = 1e-12)
  expect_equal(r$bits, mi / log(2), tolerance = 1e-12)
  expect_equal(r$hx, -sum(px * log(px)), tolerance = 1e-12)
  expect_equal(r$hxy, -sum(P[nz] * log(P[nz])), tolerance = 1e-12)
  expect_equal(r$mi, r$hx + r$hy - r$hxy, tolerance = 1e-12)
  expect_equal(r$mm, mi - (sum(nz) - 3 - 2 + 1) / 20, tolerance = 1e-12)
  expect_equal(Mutinfo(NULL, a, b)$mi, mi, tolerance = 1e-12)
  expect_true(is.nan(Mutinfo(character(0), character(0))$mm))
})

test_that("MuY is the linear mean composition", {
  expect_equal(MuY(2, 3, -1)$mu_y, 5)
  expect_error(MuY(1:2, 3, 1), "single values")
})
