test_that("integral, Fredholm, ARE and custody recompute", {
  r <- definite_integral("x*exp(2*x)", "x", 0, 1)
  expect_equal(r$estimate, (exp(2) + 1) / 4, tolerance = 1e-12)
  expect_equal(definite_integral("sin(x)", "x", 0, pi)$estimate, 2, tolerance = 1e-12)
  K <- rbind(c(1, 0.5, 0.2), c(0.5, 1, 0.5), c(0.2, 0.5, 1), c(0.1, 0.3, 0.8))
  g <- c(0.5, -1, 2)
  expect_equal(horowitz_fredholm_eq(as.vector(K %*% g), K, alpha = 1e-12)$g_hat, g, tolerance = 1e-8)
  expect_equal(gibbons_are_scale_tests()$are_mood_f, 15 / (2 * pi^2))
  expect_equal(custody_days_credit(c(10, 30, 45))$credited, c(15, 45, 67.5))
  expect_error(custody_days_credit(10, 2))
})

test_that("variances, shocks, PMM, TD3 and CV2 recompute", {
  C <- cbind(sin(0:24), 2 * cos(1.7 * (0:24)), 0.1 * (0:24))
  expect_equal(irt_variance_legislator(C)$value, unname(apply(C, 2, var)))
  u <- .morie_random_uniform(50, seed = 4, stream = 0)
  expect_equal(simulate_utility_shocks(50, 2, "gumbel", 4)$value, -2 * log(-log(u)))
  expect_equal(stats::pnorm(simulate_utility_shocks(50, 1, "normal", 4)$value), u, tolerance = 1e-12)
  X <- cbind(sin(0.9 * (0:29)), 0.1 * (0:29))
  y <- 1 + 2 * X[, 1] - X[, 2] + 0.2 * cos(2.3 * (0:29))
  R <- as.numeric((0:29) %% 4 != 1)
  p <- mi_pmm(y, X, R, K = 3, seed = 2)
  expect_equal(p$imputed[p$missing + 1], y[p$donors + 1])
  bandit <- list(n_states = 1L, n_actions = 2L, reset = function() 0L, step = function(a) list(0L, as.numeric(a), FALSE))
  expect_equal(td3(bandit, epochs = 40)$policy, morie_geron_td3(bandit, epochs = 40)$policy)
  M <- t(vapply(0:9, function(i) sin(1.1 * i + 0:3), numeric(4)))
  yy <- as.vector(M[rep(1:10, 2), ] %*% (1:4)) + rep(c(0, 0.5), each = 10) + 0.1 * cos(3 * (0:19))
  cv <- cv2_genomic(yy, M[rep(1:10, 2), ], rep(0:1, each = 10), n_folds = 4, lam = 0.3, seed = 5)
  expect_equal(sort(tabulate(cv$folds + 1)), rep(5L, 4))
  expect_equal(cv$pa, mean(cv$pa_folds))
})
