# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for analytic combinatorics.
#
# Anchors generated by running the Python core, not recalled.
#
# Exact integer sequences are compared as DECIMAL STRINGS -- Fibonacci
# leaves the double-exact range at n = 79 and a numeric comparison past
# that point would test the rounding, not the recurrence. Doubles from
# closed-form asymptotics are pinned at 1e-12 or tighter; the bisection
# root agrees to the last representable digit because both languages
# run the same 200 halvings of the same bracket.

test_that("Fibonacci comes out of its generating function, exactly", {
  out <- morie_rational_gf_coefficients(c(0, 1), c(1, -1, -1), 300)
  expect_true(out$is_exact)
  expect_true(out$all_integral)
  expect_equal(out$exact_coefficients[1:8],
               c("0", "1", "1", "2", "3", "5", "8", "13"))
  expect_equal(out$exact_coefficients[81], "23416728348467685")
  expect_equal(out$exact_coefficients[300], paste0(
    "1373470805771631154320257717102791318457002752127674672646",
    "10201"))
})

test_that("the recurrence agrees with direct addition at every index", {
  ex <- morie_rational_gf_coefficients(c(0, 1), c(1, -1, -1), 120)
  s <- ex$exact_coefficients
  for (i in 3:120) {
    expect_equal(morie_big_cmp(
      morie_bigint(s[i]),
      morie_big_add(morie_bigint(s[i - 1]), morie_bigint(s[i - 2]))), 0L)
  }
})

test_that("powers of two and unit-shifted Fibonacci expand exactly", {
  expect_equal(
    morie_rational_gf_coefficients(1, c(1, -2), 10)$coefficients,
    2^(0:9))
  expect_equal(
    morie_rational_gf_coefficients(1, c(1, -1, -1), 10)$coefficients,
    c(1, 1, 2, 3, 5, 8, 13, 21, 34, 55))
})

test_that("a non-unit leading denominator drops to doubles and says so", {
  out <- morie_rational_gf_coefficients(1, c(2, -1), 5)
  expect_false(out$is_exact)
  expect_equal(out$coefficients, 1 / 2^(1:5))
  expect_true(grepl("doubles", out$warnings))
})

test_that("generating function validation", {
  expect_error(morie_rational_gf_coefficients(1, c(0, 1), 5),
               "constant term")
  expect_error(morie_rational_gf_coefficients(1, c(1, -1), 0),
               "must be positive")
})

# ------------------------------------------------------------------
# Dominant singularity
# ------------------------------------------------------------------

test_that("the Fibonacci growth rate is the golden ratio", {
  out <- morie_dominant_singularity_growth(c(1, -1, -1))
  expect_equal(out$growth_rate, 1.6180339887498947, tolerance = 1e-15)
  expect_equal(out$radius, (sqrt(5) - 1) / 2, tolerance = 1e-12)
})

test_that("the measured ratio approaches the predicted rate", {
  fib <- morie_rational_gf_coefficients(c(0, 1), c(1, -1, -1),
                                        40)$coefficients
  out <- morie_dominant_singularity_growth(c(1, -1, -1), fib)
  expect_lt(out$relative_gap, 1e-12)
})

test_that("a simple pole is found exactly", {
  expect_equal(morie_dominant_singularity_growth(c(1, -3))$growth_rate, 3,
               tolerance = 1e-12)
})

test_that("a denominator with no positive root is refused", {
  expect_error(morie_dominant_singularity_growth(c(1, 0, 1)), "Pringsheim")
})

# ------------------------------------------------------------------
# Transfer theorem
# ------------------------------------------------------------------

test_that("the transfer theorem matches Python", {
  t1 <- morie_singularity_transfer(0.5, 10)
  expect_equal(t1$exact_coefficient, 0.17619705200195312, tolerance = 1e-15)
  expect_equal(t1$ratio, 0.9875829288261563, tolerance = 1e-12)
  expect_equal(t1$corrected_ratio, 1.0000839785581328, tolerance = 1e-12)
  t2 <- morie_singularity_transfer(0.5, 100)
  expect_equal(t2$exact_coefficient, 0.056348479009256436,
               tolerance = 1e-13)
  expect_equal(t2$ratio, 0.9987507861262519, tolerance = 1e-12)
  t3 <- morie_singularity_transfer(1.5, 50)
  expect_equal(t3$exact_coefficient, 8.038512976105052, tolerance = 1e-13)
  expect_equal(t3$corrected_ratio, 0.9999783579103279, tolerance = 1e-12)
})

test_that("integer alpha reduces to binomials", {
  for (n in c(1, 5, 20)) {
    expect_equal(morie_singularity_transfer(2, n)$exact_coefficient, n + 1,
                 tolerance = 1e-12)
  }
  expect_equal(morie_singularity_transfer(1, 50)$exact_coefficient, 1,
               tolerance = 1e-12)
})

test_that("the transfer ratio converges to one", {
  gaps <- vapply(c(10, 100, 1000), function(n) {
    abs(morie_singularity_transfer(0.5, n)$ratio - 1)
  }, numeric(1))
  expect_true(all(diff(gaps) < 0))
  expect_lt(gaps[3], 2e-4)
})

test_that("the first-order correction earns its name", {
  for (n in c(10, 100)) {
    t <- morie_singularity_transfer(0.5, n)
    expect_lt(abs(t$corrected_ratio - 1), abs(t$ratio - 1) / 50)
  }
})

test_that("transfer validation", {
  expect_error(morie_singularity_transfer(0, 10), "non-positive integer")
  expect_error(morie_singularity_transfer(0.5, 0), "n must be positive")
})

# ------------------------------------------------------------------
# Stirling's series
# ------------------------------------------------------------------

test_that("the Stirling series matches Python", {
  s <- morie_stirling_series_error(10, 3)
  expect_equal(s$series_value, 15.10441257313422, tolerance = 1e-14)
  expect_equal(s$error, 5.870504082849948e-11, tolerance = 1e-6)
  expect_equal(s$bound, 5.952380952380953e-11, tolerance = 1e-14)
  s2 <- morie_stirling_series_error(5, 3)
  expect_equal(s2$series_value, 4.787491750004922, tolerance = 1e-14)
  expect_equal(s2$bound, 7.61904761904762e-09, tolerance = 1e-14)
})

test_that("the error bound holds at every n and term count", {
  for (n in c(1, 2, 5, 10, 50, 170, 1000)) {
    for (k in 0:4) {
      expect_true(morie_stirling_series_error(n, k)$error_within_bound)
    }
  }
})

test_that("more terms help until the double floor", {
  errs <- vapply(0:4, function(k) {
    morie_stirling_series_error(10, k)$error
  }, numeric(1))
  expect_true(all(diff(errs[1:4]) < 0))
})

test_that("the series is sharp, not just valid", {
  s <- morie_stirling_series_error(5, 3)
  expect_gt(s$error, 0.5 * s$bound)
})

test_that("Stirling validation", {
  expect_error(morie_stirling_series_error(0), "must be positive")
  expect_error(morie_stirling_series_error(10, 5), "B12")
})

# ------------------------------------------------------------------
# Derangements
# ------------------------------------------------------------------

test_that("derangement exact values match Python", {
  ref <- list(c(0, "1"), c(1, "0"), c(4, "9"), c(10, "1334961"),
              c(20, "895014631192902121"))
  for (r in ref) {
    expect_equal(morie_derangement_rounding(as.integer(r[1]))$exact, r[2])
  }
  expect_equal(morie_derangement_rounding(50)$exact, paste0(
    "1118871961078248050463025807075773432401",
    "1354208865721592720336801"))
})

test_that("the two exact routes agree for every n to 60", {
  for (n in 0:60) {
    out <- morie_derangement_rounding(n)
    expect_true(out$routes_agree)
    expect_length(out$warnings, 0L)
  }
})

test_that("the rounding claims match Python, including n = 0", {
  # D_0 = 1 but 0!/e is about 0.37, so 1 is NOT its nearest integer;
  # the identity starts at n = 1 and both languages say so
  expect_false(morie_derangement_rounding(0)$is_nearest_integer)
  for (n in 1:30) {
    out <- morie_derangement_rounding(n)
    expect_true(out$is_nearest_integer)
    expect_true(out$within_theoretical_bound)
  }
})

test_that("the recurrence agrees with the enumerative shelf", {
  # morie_derangements returns a morie_bigint; compare decimal strings
  for (n in 0:30) {
    expect_equal(morie_derangement_rounding(n)$exact,
                 as.character(morie_derangements(n)))
  }
})

test_that("derangement validation", {
  expect_error(morie_derangement_rounding(-1), "non-negative")
})

# ------------------------------------------------------------------
# Hardy-Ramanujan
# ------------------------------------------------------------------

test_that("exact partition counts match Python as strings", {
  expect_equal(morie_hardy_ramanujan_partitions(10)$exact, "42")
  expect_equal(morie_hardy_ramanujan_partitions(100)$exact, "190569292")
  expect_equal(morie_hardy_ramanujan_partitions(500)$exact,
               "2300165032574323995027")
  expect_equal(morie_hardy_ramanujan_partitions(1000)$exact,
               "24061467864032622473692149727991")
})

test_that("the asymptotic ratio matches Python", {
  expect_equal(morie_hardy_ramanujan_partitions(10)$ratio,
               1.1453406861243047, tolerance = 1e-12)
  expect_equal(morie_hardy_ramanujan_partitions(100)$ratio,
               1.0457135630736354, tolerance = 1e-12)
})

test_that("the relative error decays but slowly, always positive", {
  errs <- vapply(c(10, 100, 1000), function(n) {
    morie_hardy_ramanujan_partitions(n)$relative_error
  }, numeric(1))
  expect_true(all(errs > 0))
  expect_true(all(diff(errs) < 0))
  expect_gt(errs[2], 0.04)
})

test_that("Hardy-Ramanujan validation", {
  expect_error(morie_hardy_ramanujan_partitions(0), "must be positive")
})
