test_that("Cholesky toolkit recomputes", {
  sph <- list(model = "Sph", psill = 1, range = 2.5)
  A <- outer(1:10, 1:10, function(i, j) KrigingCovariance(abs(i - j), sph)) + diag(0.1, 10)
  expect_equal(BandedCholesky(A, 2)$L, t(chol(A)), tolerance = 1e-14)
  expect_lt(IncompleteCholesky(A)$relative_error, 1e-14)
  expect_equal(WendlandTaper(c(0, 1.2), 1, 2, 2), c(1, 0))
  P <- rbind(c(0, 0), c(1, 0), c(0, 2))
  m <- list(model = "Exp", psill = 1, range = 1)
  s <- SimulationSensitivity(P, m, sills = c(1, 4))
  expect_equal(s$simulations[[2]], 2 * s$simulations[[1]], tolerance = 1e-15)
  G <- outer(1:12, 1:12, function(i, j) exp(-((i - j) / 3)^2)) + diag(1e-8, 12)
  r <- RefinedSolve(G, sin(1:12))
  expect_lte(r$residual_norms[4], 100 * .Machine$double.eps * max(rowSums(abs(G))) * max(abs(r$x)) * 12)
  expect_equal(BlockLuSimulate(0:3, 0:1, m, block = 2, halo = 0)$n_blocks, 2L)
})
