# Coverage for VariogramExtras .. vinfer exports. Every expectation is
# recomputed in the test body.

test_that("ZonalSemivariance, VgmCorrelogram and SelectVariogramModel", {
  m <- list(model = "Exp", psill = 2, range = 1.5, nugget = 0.2)
  z <- list(model = "Sph", psill = 0.5, range = 3)
  h <- c(1, 0.5, 2)
  r <- ZonalSemivariance(h, m, z, axis = 3)
  hn <- sqrt(sum(h^2))
  expect_equal(r, 2 * (1 - exp(-hn / 1.5)) + 0.2 + 0.5 * (1.5 * 2 / 3 - 0.5 * (2 / 3)^3), tolerance = 1e-12)
  hh <- c(0, 0.7, 4)
  expect_equal(VgmCorrelogram(hh, m), 1 - ifelse(hh == 0, 0, 2 * (1 - exp(-hh / 1.5)) + 0.2) / 2.2, tolerance = 1e-12)
  P <- cbind(c(0, 1, 2, 0.5, 1.5, 2.5, 0.2, 1.8), c(0, 0.5, 0, 1.2, 1, 1.4, 2.0, 2.2))
  zz <- c(1.2, 0.4, -0.3, 0.8, 0.1, 0.6, 1.0, -0.2)
  mods <- list(list(model = "Exp", psill = 1, range = 1), list(model = "Gau", psill = 1, range = 1))
  s <- SelectVariogramModel(zz, P, mods)
  aic <- vapply(mods, function(mm) Likfit(zz, P, mm, nugget = 0.1)$AIC, 0)
  expect_equal(s$AIC, aic, tolerance = 1e-12)
  expect_equal(s$best, which.min(aic))
})

test_that("Svgp is the Titsias collapsed bound", {
  X <- matrix(c(0.1, 0.5, 0.9, 1.4, 2.0, 2.6), ncol = 1)
  y <- c(0.2, 0.6, 0.9, 0.7, 0.1, -0.4)
  Z <- matrix(c(0.3, 1.5, 2.4), ncol = 1)
  r <- Svgp(X, y, Z = Z, gamma = 0.8, sigma2 = 0.05, X_test = matrix(c(1, 3), ncol = 1))
  k <- function(a, b) exp(-0.8 * outer(a[, 1], b[, 1], "-")^2)
  Kmm <- k(Z, Z) + diag(1e-8, 3)
  Knm <- k(X, Z)
  Q <- Knm %*% solve(Kmm, t(Knm))
  S <- Q + diag(0.05, 6)
  fit <- -0.5 * (6 * log(2 * pi) + as.numeric(determinant(S)$modulus) + sum(y * solve(S, y)))
  tr <- sum(1 - diag(Q))
  expect_equal(r$fit_term, fit, tolerance = 1e-9)
  expect_equal(r$trace, tr, tolerance = 1e-9)
  expect_equal(r$elbo, fit - 0.5 * tr / 0.05, tolerance = 1e-9)
  Xt <- matrix(c(1, 3), ncol = 1)
  qs <- k(Xt, Z) %*% solve(Kmm, t(Knm))
  expect_equal(r$pred, as.numeric(qs %*% solve(S, y)), tolerance = 1e-9)
  expect_equal(r$var, 1 - rowSums(qs * t(solve(S, t(qs)))), tolerance = 1e-9)
  full <- Svgp(X, y, gamma = 0.8, sigma2 = 0.05)
  Kf <- k(X, X)
  # with Z = X the bound is the exact GP marginal likelihood up to jitter
  expect_equal(full$trace, 0, tolerance = 1e-6)
  expect_equal(full$fit_term, -0.5 * (6 * log(2 * pi) + as.numeric(determinant(Kf + diag(0.05, 6))$modulus) +
                                         sum(y * solve(Kf + diag(0.05, 6), y))), tolerance = 1e-6)
})

test_that("VarSum, VarXbar and Vbinfp", {
  v <- VarSum(c(1, 2.5, 0.5))
  expect_equal(v$var_sum, 4)
  expect_equal(v$partial_sums, c(1, 3.5, 4))
  expect_error(VarSum(-1), "non-empty and >= 0")
  expect_equal(VarXbar(3, 9)$var_mean, 1)
  expect_error(VarXbar(3, 1.5), "integer >= 1")
  expect_error(VarXbar(-1, 2), "single value >= 0")
  X <- c(1, 1, 2, 2, 3, 1, 2, 3, 3, 1)
  Y <- c("a", "a", "b", "b", "b", "a", "a", "b", "b", "b")
  r <- Vbinfp(X, Y)
  J <- table(Y, X) / 10
  px <- colSums(J)
  py <- rowSums(J)
  hx <- -sum(px * log(px))
  cond <- J / py
  hxy <- -sum(J[J > 0] * log(cond[J > 0]))
  expect_equal(r$entropy_x, hx, tolerance = 1e-12)
  expect_equal(r$plugin_mi, hx - hxy, tolerance = 1e-12)
  expect_equal(r$gap, 0, tolerance = 1e-12)
  q <- rbind(c(0.5, 0.3, 0.2), c(0.2, 0.4, 0.4))
  rq <- Vbinfp(X, Y, q = q)
  expect_equal(rq$bound, hx + sum(J * log(q)), tolerance = 1e-12)
  expect_gte(rq$gap, 0)
  expect_error(Vbinfp(X, Y, q = q[, 1:2]), "ny-by-nx")
  expect_error(Vbinfp(X, Y, q = rbind(c(1, 0, 0), c(0.2, 0.4, 0.4))), "zero probability")
  expect_error(Vbinfp(X, Y, q = q * 2), "sum to one")
})

test_that("Vinfer and Vbnopt reach the mean-field Normal-Gamma fixed point", {
  x <- c(2.1, 1.7, 2.9, 2.4, 1.2, 3.0, 2.2)
  r <- Vinfer(x = x)
  ss <- sum((x - mean(x))^2)
  # with lambda0 = 0 the fixed point of E[tau] = a_n / b_n is closed form
  et <- (7 / 2) / (ss / 2)
  expect_equal(r$e_tau, et, tolerance = 1e-10)
  expect_equal(r$mu_n, mean(x), tolerance = 1e-12)
  expect_equal(r$var_mu, 1 / (7 * et), tolerance = 1e-10)
  expect_equal(r$a_n, 4)
  expect_equal(r$converged, 1)
  expect_equal(r$elbo_monotone, 1)
  p <- Vinfer(x = x, mu0 = 1, lambda0 = 2, a0 = 1, b0 = 0.5)
  e <- p$e_tau
  mun <- (2 + 7 * mean(x)) / 9
  bn <- 0.5 + 0.5 * (ss + 7 * (mean(x) - mun)^2 + 7 / (9 * e) + 2 * ((mun - 1)^2 + 1 / (9 * e)))
  expect_equal(e, (1 + 4) / bn, tolerance = 1e-10)
  expect_equal(Vbnopt(x = x)$e_tau, r$e_tau, tolerance = 1e-12)
  expect_error(Vinfer("poisson", x = x), "only the normal-gamma")
  expect_error(Vinfer(q_family = "full", x = x), "only the mean-field")
  expect_error(Vinfer(x = 1), "at least two")
})
