# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for geometric combinatorics.
#
# Anchors generated by running the Python core, not recalled.
#
# All quantities here are exact integers (cross products, shoelace
# doubles, gcd boundary counts), so equality is equality -- no
# tolerances. Pick's theorem is verified against interior points
# counted one by one on a fuzz family of star-shaped polygons whose
# simplicity is guaranteed by construction: the angular sort runs
# around the vertex centroid, because sorting around a point OUTSIDE
# the hull produces self-intersecting polygons, and Pick correctly
# rejects those rather than passing them.

test_that("the lattice hull matches Python", {
  out <- morie_lattice_convex_hull(rbind(c(0, 0), c(2, 0), c(1, 1),
                                         c(2, 2), c(0, 2)))
  expect_equal(out$hull, rbind(c(0, 0), c(2, 0), c(2, 2), c(0, 2)))
  expect_equal(out$twice_area, 8)
  out2 <- morie_lattice_convex_hull(rbind(c(-3, 1), c(4, -2), c(0, 5),
                                          c(2, 3), c(1, 1), c(-1, -1),
                                          c(4, 4)))
  expect_equal(out2$hull, rbind(c(-3, 1), c(-1, -1), c(4, -2), c(4, 4),
                                c(0, 5)))
  expect_equal(out2$twice_area, 69)
})

test_that("collinear boundary points are dropped", {
  out <- morie_lattice_convex_hull(rbind(c(0, 0), c(1, 0), c(2, 0),
                                         c(2, 2), c(0, 2)))
  expect_equal(out$n_vertices, 4)
})

test_that("the hull is idempotent and contains every point", {
  set.seed(11)
  for (rep in seq_len(60L)) {
    p <- cbind(sample(-20:20, 30, replace = TRUE),
               sample(-20:20, 30, replace = TRUE))
    out <- tryCatch(morie_lattice_convex_hull(p), error = function(e) NULL)
    if (is.null(out)) next
    hm <- out$hull
    again <- morie_lattice_convex_hull(hm)$hull
    expect_equal(hm[order(hm[, 1], hm[, 2]), ],
                 again[order(again[, 1], again[, 2]), ])
    nh <- nrow(hm); nxt <- c(2:nh, 1L)
    for (i in seq_len(nrow(p))) {
      crosses <- vapply(seq_len(nh), function(k) {
        .morie_cross3(hm[k, ], hm[nxt[k], ], p[i, ])
      }, numeric(1))
      expect_true(all(crosses >= 0))
    }
  }
})

test_that("hull validation", {
  expect_error(morie_lattice_convex_hull(rbind(c(0, 0), c(1, 1))),
               "at least 3 distinct")
  expect_error(morie_lattice_convex_hull(rbind(c(0, 0), c(1, 1), c(2, 2),
                                               c(3, 3))), "collinear")
})

# ------------------------------------------------------------------
# Pick's theorem
# ------------------------------------------------------------------

test_that("Pick matches Python on worked polygons", {
  p <- morie_pick_theorem(rbind(c(0, 0), c(4, 0), c(4, 3), c(0, 3)))
  expect_equal(p$interior, 6)
  expect_equal(p$boundary, 14)
  expect_equal(p$twice_area, 24)
  expect_true(p$verified)

  p2 <- morie_pick_theorem(rbind(c(0, 0), c(7, 2), c(5, 6), c(-2, 4),
                                 c(-3, 1)))
  expect_equal(p2$interior, 35)
  expect_equal(p2$boundary, 6)
  expect_equal(p2$twice_area, 74)
  expect_true(p2$verified)
})

test_that("the fundamental triangle has no interior points", {
  p <- morie_pick_theorem(rbind(c(0, 0), c(1, 0), c(0, 1)))
  expect_equal(p$twice_area, 1)
  expect_equal(p$boundary, 3)
  expect_equal(p$interior, 0)
  expect_true(p$verified)
})

test_that("Pick verified by enumeration on star-shaped fuzz polygons", {
  set.seed(7)
  tried <- 0L
  for (rep in seq_len(150L)) {
    n <- sample(3:12, 1)
    raw <- unique(cbind(sample(-12:12, n * 2, replace = TRUE),
                        sample(-12:12, n * 2, replace = TRUE)))[seq_len(n), ,
                                                                drop = FALSE]
    raw <- unique(raw)
    if (nrow(raw) < 3L) next
    cx <- mean(raw[, 1]); cy <- mean(raw[, 2])
    ang <- atan2(raw[, 2] - cy, raw[, 1] - cx)
    rad <- (raw[, 1] - cx)^2 + (raw[, 2] - cy)^2
    ord <- order(ang, rad)
    v <- raw[ord, , drop = FALSE]
    # drop later points sharing a ray from the centroid (angle ties)
    keepers <- !duplicated(round(ang[ord], 12))
    v <- v[keepers, , drop = FALSE]
    if (nrow(v) < 3L) next
    out <- tryCatch(morie_pick_theorem(v), error = function(e) NULL)
    if (is.null(out)) next
    tried <- tried + 1L
    expect_true(out$verified)
  }
  expect_gt(tried, 80L)
})

test_that("a self-intersecting polygon is caught, not passed", {
  out <- morie_pick_theorem(rbind(c(0, 0), c(4, 0), c(4, 3), c(2, -2)))
  expect_false(out$verified)
  expect_equal(out$interior, -3)
  expect_true(any(grepl("self-intersecting", out$warnings)))
})

test_that("the enumeration cap reports rather than passes", {
  out <- morie_pick_theorem(rbind(c(0, 0), c(2000, 0), c(2000, 2000),
                                  c(0, 2000)), enumeration_cap = 100)
  expect_true(is.na(out$verified))
  expect_true(any(grepl("NOT verified", out$warnings)))
  expect_equal(out$interior, 1999^2)
})

test_that("orientation does not matter", {
  cw <- morie_pick_theorem(rbind(c(0, 3), c(4, 3), c(4, 0), c(0, 0)))
  ccw <- morie_pick_theorem(rbind(c(0, 0), c(4, 0), c(4, 3), c(0, 3)))
  expect_equal(cw$interior, ccw$interior)
  expect_equal(cw$area, ccw$area)
})

test_that("Pick validation", {
  expect_error(morie_pick_theorem(rbind(c(0, 0), c(1, 1))), "at least 3")
  expect_error(morie_pick_theorem(rbind(c(0, 0), c(1, 1), c(2, 2))),
               "degenerate")
})

# ------------------------------------------------------------------
# Erdos-Szekeres
# ------------------------------------------------------------------

test_that("monotone lengths match Python on the worked sequence", {
  out <- morie_erdos_szekeres_check(c(3, 1, 4, 1.5, 5, 9, 2, 6),
                                    r = 3, s = 4)
  expect_equal(out$longest_increasing, 4L)
  expect_equal(out$longest_decreasing, 2L)
  expect_equal(out$threshold, 7L)
  expect_true(out$applies)
  expect_true(out$guarantee_met)
})

test_that("the guarantee holds on every permutation at threshold", {
  perms <- function(v) {
    if (length(v) <= 1L) return(list(v))
    out <- list()
    for (i in seq_along(v)) {
      for (rest in perms(v[-i])) out[[length(out) + 1L]] <- c(v[i], rest)
    }
    out
  }
  for (w in perms(1:5)) {
    expect_true(morie_erdos_szekeres_check(w, r = 3, s = 3)$guarantee_met)
  }
})

test_that("the extremal sequence escapes at length below threshold", {
  for (rs in list(c(3, 3), c(4, 4), c(3, 5), c(5, 3))) {
    r <- rs[1]; s <- rs[2]
    seq_ <- unlist(lapply(seq.int(s - 1, 1), function(block) {
      block * 100 + seq.int(0, r - 2)
    }))
    out <- morie_erdos_szekeres_check(seq_, r = r, s = s)
    expect_equal(length(seq_), (r - 1) * (s - 1))
    expect_false(out$applies)
    expect_equal(out$longest_increasing, r - 1L)
    expect_equal(out$longest_decreasing, s - 1L)
  }
})

test_that("the guarantee holds on random sequences at threshold", {
  set.seed(3)
  for (rep in seq_len(120L)) {
    r <- sample(2:5, 1); s <- sample(2:5, 1)
    n <- (r - 1) * (s - 1) + 1
    expect_true(morie_erdos_szekeres_check(sample(1000, n), r = r,
                                           s = s)$guarantee_met)
  }
})

test_that("Erdos-Szekeres validation", {
  expect_error(morie_erdos_szekeres_check(numeric(0)), "empty")
  expect_error(morie_erdos_szekeres_check(c(1, 2, 1)), "distinct")
  expect_error(morie_erdos_szekeres_check(1:3, r = 1, s = 3), "at least 2")
})

# ------------------------------------------------------------------
# Happy ending
# ------------------------------------------------------------------

test_that("the witness quadrilateral matches Python", {
  out <- morie_happy_ending_quadrilateral(rbind(c(0, 0), c(4, 0), c(2, 1),
                                                c(1, 4), c(3, 5)))
  expect_true(out$found)
  expect_equal(out$witness, rbind(c(0, 0), c(4, 0), c(3, 5), c(1, 4)))
  expect_true(out$every_five_subset)
})

test_that("the witness really is convex", {
  out <- morie_happy_ending_quadrilateral(rbind(c(0, 0), c(4, 0), c(2, 1),
                                                c(1, 4), c(3, 5)))
  w <- out$witness
  signs <- vapply(1:4, function(i) {
    .morie_cross3(w[i, ], w[i %% 4 + 1, ], w[(i + 1) %% 4 + 1, ])
  }, numeric(1))
  expect_true(all(signs > 0) || all(signs < 0))
})

test_that("every 5-subset of random general-position points", {
  set.seed(5)
  checked <- 0L
  for (rep in seq_len(60L)) {
    p <- unique(cbind(sample(-15:15, 12, replace = TRUE),
                      sample(-15:15, 12, replace = TRUE)))[seq_len(6), ,
                                                           drop = FALSE]
    if (nrow(unique(p)) < 6L) next
    out <- tryCatch(morie_happy_ending_quadrilateral(p),
                    error = function(e) NULL)
    if (is.null(out)) next
    checked <- checked + 1L
    expect_true(out$every_five_subset)
  }
  expect_gt(checked, 15L)
})

test_that("happy ending validation", {
  expect_error(morie_happy_ending_quadrilateral(rbind(c(0, 0), c(1, 0),
                                                      c(0, 1), c(1, 1))),
               "5 or more")
  expect_error(morie_happy_ending_quadrilateral(rbind(c(0, 0), c(1, 1),
                                                      c(2, 2), c(5, 0),
                                                      c(0, 5))),
               "collinear")
  expect_error(morie_happy_ending_quadrilateral(rbind(c(0, 0), c(0, 0),
                                                      c(1, 4), c(5, 1),
                                                      c(3, 3))),
               "distinct")
})

# ------------------------------------------------------------------
# Helly on the line
# ------------------------------------------------------------------

test_that("Helly matches Python", {
  out <- morie_helly_intervals(rbind(c(0, 3), c(1, 5), c(2, 4)))
  expect_true(out$pairwise_intersecting)
  expect_true(out$common_point_exists)
  expect_equal(out$witness, c(2, 3))
  out2 <- morie_helly_intervals(rbind(c(0, 1), c(2, 3), c(0, 5)))
  expect_false(out2$pairwise_intersecting)
  expect_equal(out2$disjoint_pair, c(0L, 1L))
  expect_false(out2$common_point_exists)
})

test_that("the implication holds on random families", {
  set.seed(9)
  saw <- 0L
  for (rep in seq_len(300L)) {
    k <- sample(2:8, 1)
    a <- stats::runif(k, 0, 10)
    iv <- cbind(a, a + stats::runif(k, 0, 6))
    out <- morie_helly_intervals(iv)
    expect_true(out$helly_holds)
    if (out$pairwise_intersecting) {
      saw <- saw + 1L
      expect_true(out$common_point_exists)
    }
  }
  expect_gt(saw, 10L)
})

test_that("touching intervals share exactly one point", {
  out <- morie_helly_intervals(rbind(c(0, 2), c(2, 5)))
  expect_true(out$common_point_exists)
  expect_equal(out$witness, c(2, 2))
})

test_that("Helly validation", {
  expect_error(morie_helly_intervals(matrix(numeric(0), ncol = 2)),
               "no intervals")
  expect_error(morie_helly_intervals(rbind(c(3, 1))), "a <= b")
})
