# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for topological combinatorics.
#
# Anchors generated by running the Python core, not recalled.
#
# The fixtures themselves are not recalled either: the torus is
# generated as the 7-vertex quotient {i, i+1, i+3} + {i, i+2, i+3}
# mod 7, and the 6-vertex projective plane came out of a backtracking
# search over K6 triangles for every-edge-in-exactly-two, certified by
# the homology itself (1, 1, 1 over F_2 with chi = 1 pins RP^2).
# Sperner labellings are driven by the shared LCG so both languages
# see the same 120 labellings bit for bit.

torus_complex <- function() {
  c(lapply(0:6, function(i) sort(c(i %% 7, (i + 1) %% 7, (i + 3) %% 7))),
    lapply(0:6, function(i) sort(c(i %% 7, (i + 2) %% 7, (i + 3) %% 7))))
}

rp2_complex <- function() {
  list(c(0, 1, 2), c(0, 1, 3), c(0, 2, 4), c(0, 3, 5), c(0, 4, 5),
       c(1, 2, 5), c(1, 3, 4), c(1, 4, 5), c(2, 3, 4), c(2, 3, 5))
}

sphere_complex <- function() {
  list(c(0, 1, 2), c(0, 1, 3), c(0, 2, 3), c(1, 2, 3))
}

circle_complex <- function() list(c(0, 1), c(1, 2), c(0, 2))

test_that("face closure of a triangle matches Python", {
  faces <- morie_simplicial_complex_faces(list(c(0, 1, 2)))
  expect_equal(faces[["0"]], list(0L, 1L, 2L))
  expect_equal(faces[["1"]], list(c(0L, 1L), c(0L, 2L), c(1L, 2L)))
  expect_equal(faces[["2"]], list(c(0L, 1L, 2L)))
})

test_that("Euler characteristics of the classics match Python", {
  expect_equal(morie_euler_characteristic(list(0:3))$chi, 1)
  expect_equal(morie_euler_characteristic(sphere_complex())$chi, 2)
  expect_equal(morie_euler_characteristic(circle_complex())$chi, 0)
  expect_equal(morie_euler_characteristic(torus_complex())$chi, 0)
  expect_equal(morie_euler_characteristic(rp2_complex())$chi, 1)
})

test_that("the torus f-vector is the minimal one", {
  expect_equal(morie_euler_characteristic(torus_complex())$f_vector,
               c(7L, 21L, 14L))
})

test_that("face validation", {
  expect_error(morie_simplicial_complex_faces(list()), "no simplices")
  expect_error(morie_simplicial_complex_faces(list(integer(0))),
               "empty simplices")
})

# ------------------------------------------------------------------
# Betti numbers over F_2
# ------------------------------------------------------------------

test_that("Betti numbers of the classical surfaces match Python", {
  expect_equal(morie_betti_numbers_gf2(circle_complex())$betti, c(1L, 1L))
  expect_equal(morie_betti_numbers_gf2(sphere_complex())$betti,
               c(1L, 0L, 1L))
  expect_equal(morie_betti_numbers_gf2(torus_complex())$betti,
               c(1L, 2L, 1L))
  # over F_2 the projective plane has full homology 1, 1, 1: the
  # Z-torsion in H_1 becomes a genuine F_2 class, and b_2 = 1 because
  # orientability is invisible mod 2
  expect_equal(morie_betti_numbers_gf2(rp2_complex())$betti, c(1L, 1L, 1L))
})

test_that("a contractible complex has trivial homology", {
  expect_equal(morie_betti_numbers_gf2(list(0:3))$betti, c(1L, 0L, 0L, 0L))
})

test_that("disconnected components add in b0", {
  expect_equal(morie_betti_numbers_gf2(list(c(0, 1), c(2, 3)))$betti[1], 2L)
  two_circles <- c(circle_complex(), list(c(3, 4), c(4, 5), c(3, 5)))
  expect_equal(morie_betti_numbers_gf2(two_circles)$betti, c(2L, 2L))
})

test_that("a wedge of two circles has b1 of 2", {
  wedge <- list(c(0, 1), c(1, 2), c(0, 2), c(0, 3), c(3, 4), c(0, 4))
  expect_equal(morie_betti_numbers_gf2(wedge)$betti, c(1L, 2L))
})

test_that("the boundary map squares to zero everywhere", {
  for (cx in list(sphere_complex(), torus_complex(), rp2_complex(),
                  list(0:3), list(0:4))) {
    out <- morie_betti_numbers_gf2(cx)
    expect_true(out$boundary_squared_zero)
    expect_length(out$warnings, 0L)
  }
})

test_that("the Euler-Poincare identity holds on every fixture", {
  for (cx in list(circle_complex(), sphere_complex(), torus_complex(),
                  rp2_complex(), list(0:3), list(c(0, 1), c(2, 3)))) {
    out <- morie_betti_numbers_gf2(cx)
    expect_true(out$euler_poincare_holds)
    expect_equal(out$chi_from_faces, out$chi_from_betti)
  }
})

test_that("filling the circle kills b1", {
  expect_equal(morie_betti_numbers_gf2(circle_complex())$betti, c(1L, 1L))
  expect_equal(morie_betti_numbers_gf2(list(c(0, 1, 2)))$betti,
               c(1L, 0L, 0L))
})

test_that("the RP2 fixture really is a closed surface", {
  counts <- new.env(parent = emptyenv())
  for (t in rp2_complex()) {
    pr <- utils::combn(t, 2L)
    for (e in seq_len(ncol(pr))) {
      key <- paste(pr[, e], collapse = ",")
      assign(key, (if (exists(key, envir = counts))
        get(key, envir = counts) else 0L) + 1L, envir = counts)
    }
  }
  vals <- unlist(mget(ls(counts), envir = counts))
  expect_length(vals, 15L)
  expect_true(all(vals == 2L))
})

# ------------------------------------------------------------------
# Sperner's lemma
# ------------------------------------------------------------------

test_that("the rainbow count is odd at every subdivision", {
  for (k in 1:12) {
    out <- morie_sperner_lemma_triangle(k)
    expect_true(out$is_odd)
    expect_equal(out$n_cells, k * k)
  }
})

test_that("oddness survives 120 LCG-driven admissible labellings", {
  lcg_labels <- function(k, seed) {
    s <- seed
    lab <- list()
    for (i in 0:k) {
      for (j in 0:(k - i)) {
        allowed <- integer(0)
        if (k - i - j > 0L) allowed <- c(allowed, 0L)
        if (i > 0L) allowed <- c(allowed, 1L)
        if (j > 0L) allowed <- c(allowed, 2L)
        s <- (1664525 * s + 1013904223) %% 2^32
        lab[[paste0(i, ",", j)]] <- allowed[(s %% length(allowed)) + 1L]
      }
    }
    lab
  }
  for (seed in 0:119) {
    k <- 2L + seed %% 7L
    out <- morie_sperner_lemma_triangle(k, lcg_labels(k, seed))
    expect_true(out$is_odd)
  }
})

test_that("an improper labelling is refused, not computed", {
  k <- 2L
  labels <- list()
  for (i in 0:k) {
    for (j in 0:(k - i)) {
      allowed <- integer(0)
      if (k - i - j > 0L) allowed <- c(allowed, 0L)
      if (i > 0L) allowed <- c(allowed, 1L)
      if (j > 0L) allowed <- c(allowed, 2L)
      labels[[paste0(i, ",", j)]] <- allowed[1]
    }
  }
  labels[[paste0(k, ",", 0)]] <- 0L
  expect_error(morie_sperner_lemma_triangle(k, labels), "not admissible")
})

test_that("a missing label is an error", {
  expect_error(morie_sperner_lemma_triangle(2, list("0,0" = 0L)),
               "no label supplied")
})

test_that("Sperner validation", {
  expect_error(morie_sperner_lemma_triangle(0), "must be positive")
})
