# Coverage for cmuit.R, cmuti_native.R, cncpat.R, ddimst.R, deftef.R,
# deitsr.R, diffP.R, diripr.R, divcd.R, divgvs.R and divLst.R:
# information measures from contingency tables, ControlNet and DiffPool
# replayed on their SplitMix64 normal streams, the DDIM step and
# Dirichlet-multinomial marginal from their formulas.

mi_tab <- function(a, b) {
  P <- table(a, b) / length(a)
  E <- outer(rowSums(P), colSums(P))
  sum(ifelse(P > 0, P * log(P / E), 0))
}

test_that("Condmi averages the within-stratum mutual information", {
  a <- c(1, 1, 2, 2, 1, 2, 3, 3, 1, 2)
  b <- c("u", "u", "v", "v", "v", "u", "u", "v", "u", "v")
  z <- c(0, 0, 0, 0, 0, 1, 1, 1, 1, 2)
  r <- Condmi(a, b, z = z)
  cmi <- 0.5 * mi_tab(a[1:5], b[1:5]) + 0.4 * mi_tab(a[6:9], b[6:9])
  expect_equal(r$cmi, cmi, tolerance = 1e-12)
  expect_equal(r$mi, mi_tab(a, b), tolerance = 1e-12)
  expect_equal(r$interaction, mi_tab(a, b) - cmi, tolerance = 1e-12)
  expect_equal(r$per_level[[3]], c(0.1, 0))
  expect_equal(r$bits, cmi / log(2), tolerance = 1e-12)
  alt <- Condmi("ignored", x = a, y2 = b)
  expect_equal(alt$cmi, mi_tab(a, b), tolerance = 1e-12)
})

test_that("morie_cmuti is the Gaussian-copula mutual information", {
  x <- c(0.3, 1.2, -0.5, 2.2, 0.9, 0.9, -1.1, 1.7)
  y <- c(1.1, 2.0, 0.2, 2.1, 0.7, 1.5, -0.3, 2.9)
  r <- morie_cmuti(x, y)
  rho <- cor(qnorm(rank(x) / 9), qnorm(rank(y) / 9))
  expect_equal(r$rho, rho, tolerance = 1e-12)
  expect_equal(r$estimate, -0.5 * log(1 - rho^2), tolerance = 1e-12)
  expect_equal(r$linfoot_r, abs(rho), tolerance = 1e-12)
  expect_equal(morie_cmuti(1:5, 1:5)$rho, 1 - 1e-12)
  expect_error(morie_cmuti(1:5, 1:4), "paired")
  expect_error(morie_cmuti(rep(1, 5), 1:5), "degenerate")
})

test_that("Cncpat adds a zero-initialised GELU control branch", {
  B <- rbind(c(1, 2, 3), c(0, -1, 0.5))
  Cm <- rbind(c(0.2, 0.4, -0.1), c(1, 0, 0.3))
  w <- matrix(.ghc_norm(.ghc_rng(9), 9L, 0, 0.5), 3, 3, byrow = TRUE)
  Cp <- Cm[c(1, 1:2, 2), c(1, 1:3, 3)]
  ctrl <- matrix(0, 2, 3)
  for (i in 1:2) for (j in 1:3) {
    s <- sum(Cp[i:(i + 2), j:(j + 2)] * w)
    ctrl[i, j] <- s * pnorm(s)
  }
  r <- Cncpat(B, Cm, zero_conv_weight = 0.3, seed = 9)
  expect_equal(r$control, ctrl, tolerance = 1e-12)
  expect_equal(r$out, B + 0.3 * ctrl, tolerance = 1e-12)
  expect_equal(r$delta_norm, 0.3 * sqrt(sum(ctrl^2)), tolerance = 1e-12)
  z <- Cncpat(B, Cm)
  expect_equal(c(z$is_identity, z$estimate), c(1, mean(B)))
  expect_error(Cncpat(matrix(0, 0, 2), Cm), "no rows")
  expect_error(Cncpat(B, Cm[, 1:2]), "same shape")
})

test_that("Ddimst takes one DDIM reverse step", {
  x <- c(0.5, -1, 0.2)
  e <- c(0.1, 0.3, -0.4)
  f <- function(u) cos((u / 1000 + 0.008) / 1.008 * pi / 2)^2
  at <- f(500) / f(0)
  ap <- f(499) / f(0)
  x0 <- (x - sqrt(1 - at) * e) / sqrt(at)
  r <- Ddimst(x, 500, e)
  expect_equal(r$x_prev, sqrt(ap) * x0 + sqrt(1 - ap) * e, tolerance = 1e-12)
  expect_equal(r$x0_pred, x0, tolerance = 1e-12)
  expect_equal(r$sigma, 0)
  s <- Ddimst(x, 1, e, eta = 0.5, alpha_bar_t = 0.8, alpha_bar_prev = 0.9)
  sg <- 0.5 * sqrt(0.1 / 0.2) * sqrt(1 - 0.8 / 0.9)
  x0b <- (x - sqrt(0.2) * e) / sqrt(0.8)
  expect_equal(s$sigma, sg, tolerance = 1e-12)
  expect_equal(s$x_prev, sqrt(0.9) * x0b + sqrt(0.1 - sg^2) * e, tolerance = 1e-12)
  expect_equal(s$estimate, mean(s$x_prev), tolerance = 1e-12)
  expect_error(Ddimst(numeric(0), 1, numeric(0)), "no entries")
  expect_error(Ddimst(x, 1, e[-1]), "same length")
  expect_error(Ddimst(x, 0, e), "at least 1")
  expect_error(Ddimst(x, 1, e, eta = 2), "eta")
  expect_error(Ddimst(x, 1, e, alpha_bar_t = 0), "cumulative alphas")
})

test_that("Deftef and Deitkd", {
  d <- Deftef(c(2, 3.5), c(1, 2))
  expect_equal(d$deff, c(2, 1.75))
  expect_equal(d$deft, sqrt(c(2, 1.75)), tolerance = 1e-12)
  expect_equal(d$estimate, 1.875)
  expect_equal(Deftef(3, c(1, 1.5))$deff, c(3, 2))
  expect_equal(Deftef(3, 2)$estimate, 1.5)
  expect_true(is.nan(Deftef(-1, 1)$deft))
  expect_error(Deftef(numeric(0), 1), "both variances")
  expect_error(Deftef(1:2, 1:3), "same length")
  expect_error(Deftef(1, 0), "strictly positive")

  zs <- c(1, 2, 0.5)
  zt <- c(0.2, 0.1, 3)
  ls <- zs - log(sum(exp(zs)))
  h <- Deitkd(zs, zt, y = 1)
  expect_equal(h$ce, -ls[2], tolerance = 1e-12)
  expect_equal(h$y_teacher, 2L)
  expect_equal(h$estimate, 0.5 * (-ls[2]) + 0.5 * (-ls[3]), tolerance = 1e-12)
  s <- Deitkd(zs, zt, y = 1, mode = "soft", lam = 0.3, tau = 2)
  ps <- exp(zs / 2) / sum(exp(zs / 2))
  pt <- exp(zt / 2) / sum(exp(zt / 2))
  kl <- sum(pt * log(pt / ps))
  expect_equal(s$kd, 0.3 * 4 * kl, tolerance = 1e-12)
  expect_equal(s$estimate, 0.7 * (-ls[2]) + 0.3 * 4 * kl, tolerance = 1e-12)
  expect_equal(Deitkd(zs)$ce, -ls[1], tolerance = 1e-12)
})

test_that("DiffP pools the graph through a soft assignment", {
  A <- rbind(c(0, 1, 1, 0), c(1, 0, 0, 1), c(1, 0, 0, 1), c(0, 1, 1, 0))
  X <- rbind(c(1, 0), c(0, 1), c(1, 1), c(2, 0))
  L <- matrix(.ghc_norm(.ghc_rng(4), 8L), 4, 2, byrow = TRUE)
  S <- exp(L) / rowSums(exp(L))
  r <- DiffP(A, X, K_clusters = 2, seed = 4)
  expect_equal(r$S, S, tolerance = 1e-12)
  expect_equal(r$A_pool, t(S) %*% A %*% S, tolerance = 1e-12)
  expect_equal(r$H_pool, t(S) %*% X, tolerance = 1e-12)
  expect_equal(r$link_loss, sqrt(sum((A - S %*% t(S))^2)) / 4, tolerance = 1e-12)
  expect_equal(r$entropy_loss, -sum(S * log(S)) / 4, tolerance = 1e-12)
  hard <- DiffP(A, X, 2, S = cbind(c(50, 0, 0, 50), c(0, 50, 50, 0)))
  expect_equal(hard$A_pool, matrix(c(0, 4, 4, 0), 2), tolerance = 1e-12)
  expect_error(DiffP(matrix(0, 0, 0), X), "no rows")
  expect_error(DiffP(A[, 1:3], X), "square")
  expect_error(DiffP(A, X[1:3, ]), "one row per node")
  expect_error(DiffP(A, X, 0), "at least 1")
  expect_error(DiffP(A, X, 2, S = matrix(0, 4, 3)), "n x K")
})

test_that("Diripr is the Dirichlet-multinomial conjugate update", {
  y <- c(3, 0, 5, 2)
  a <- c(1, 0.5, 2, 1)
  r <- Diripr(y, a)
  post <- a + y
  expect_equal(r$post_mean, post / 14.5, tolerance = 1e-12)
  expect_equal(r$post_var, post * (14.5 - post) / (14.5^2 * 15.5), tolerance = 1e-12)
  lm <- lfactorial(10) - sum(lfactorial(y)) + lgamma(4.5) - lgamma(14.5) +
    sum(lgamma(post) - lgamma(a))
  expect_equal(r$log_marginal, lm, tolerance = 1e-12)
  expect_equal(Diripr(y)$post_alpha, y + 1)
  expect_error(Diripr(numeric(0)), "no categories")
  expect_error(Diripr(-y), "non-negative")
  expect_error(Diripr(y, 1:2), "one value per category")
  expect_error(Diripr(y, 0), "strictly positive")
  skip_if_not_installed("extraDistr")
  expect_equal(r$log_marginal, extraDistr::ddirmnom(y, 10, a, log = TRUE), tolerance = 1e-10)
})

test_that("Divrate, Divgvs and Intradiv", {
  M <- rbind(c(0, 1, 0, 0), c(1, 1, 0, 0))
  d <- Divrate(M)
  expect_equal(c(d$count, d$rate, d$n), c(3, 3 / 8, 8))
  expect_equal(d$per_chain_rate, c(0.25, 0.5))
  l <- Divrate(list(c(0, 0), c(1, 0, 1)))
  expect_equal(l$per_chain, c(0, 2))
  expect_false(Divrate(c(0, 0, 0))$any)
  R <- rbind(c(1, 0.6, -0.8), c(0.6, 1, 0.3), c(-0.8, 0.3, 1))
  ave <- c(0.5, 0.49, 0.7)
  g <- Divgvs(ave, R)
  m <- outer(sqrt(ave), rep(1, 3)) - abs(R)
  diag(m) <- Inf
  expect_equal(g$estimate, min(m), tolerance = 1e-12)
  expect_equal(g$pass_factor, as.integer(apply(m, 1, min) > 0))
  expect_equal(g$n_violations, sum(m <= 0))
  expect_equal(g$discriminant, 0L)
  one <- Divgvs(0.4, matrix(1))
  expect_true(is.nan(one$estimate) && one$pass_factor == 1L)
  expect_error(Divgvs(numeric(0), R), "no AVE")
  expect_error(Divgvs(ave, R[1:2, 1:2]), "k x k")
  expect_error(Divgvs(ave + 1, R), "\\[0, 1\\]")
  S <- rbind(c(1, 0.2, 0.9, 0.4), c(0.2, 1, 0.1, 0.5), c(0.9, 0.1, 1, 0.3), c(0.4, 0.5, 0.3, 1))
  iv <- Intradiv(c(0, 2, 3), S)
  ps <- c(S[1, 3], S[1, 4], S[3, 4])
  expect_equal(c(iv$estimate, iv$ils, iv$min_pair_sim, iv$max_pair_sim),
               c(mean(1 - ps), sum(ps), min(ps), max(ps)), tolerance = 1e-12)
  expect_true(is.nan(Intradiv(1, S)$estimate))
})
