# Coverage for the probability-primer helpers (Binom*, Coin*, Die*, Exp*,
# Cov*, Dens*, Diff*, Esum*, Bayes*, Best*, Book*, Bimid, ChiDep): each
# value is recomputed with base R's distribution functions or the
# textbook identity it states.

test_that("binomial pmf, moments and peaks", {
  expect_equal(BinomPmf(3, 10, 0.3)$probability, dbinom(3, 10, 0.3), tolerance = 1e-12)
  expect_equal(BinomPmf(700, 2000, 0.35)$probability, dbinom(700, 2000, 0.35),
               tolerance = 1e-9)
  expect_equal(BinomPmf(11, 10, 0.3)$probability, 0)
  expect_equal(BinomPmf(0, 5, 0)$probability, 1)
  expect_equal(BinomPmf(5, 5, 1)$probability, 1)
  expect_error(BinomPmf(-1, 5, 0.5), "k must")
  expect_error(BinomPmf(1, 1.5, 0.5), "n must")
  expect_error(BinomPmf(1, 5, 2), "p must")
  expect_equal(BinomMean(12, 0.4)$series_mean, sum(0:12 * dbinom(0:12, 12, 0.4)),
               tolerance = 1e-12)
  expect_equal(BinomMean(12, 0.4)$mean, 4.8, tolerance = 1e-12)
  expect_error(BinomMean(-1, 0.4), "n must")
  expect_error(BinomMean(3, -0.4), "p must")
  expect_equal(BinomMom2(12, 0.4)$second_moment, sum((0:12)^2 * dbinom(0:12, 12, 0.4)),
               tolerance = 1e-12)
  expect_error(BinomMom2(1.5, 0.4), "n must")
  expect_error(BinomMom2(3, 2), "p must")
  expect_equal(BinomVar(12, 0.4)$variance, 12 * 0.4 * 0.6, tolerance = 1e-12)
  expect_error(BinomVar(-2, 0.4), "n must")
  expect_error(BinomVar(3, NA), "p must")
  pk <- BinomPeak(20, 0.33)
  expect_equal(pk$k, 7L)
  expect_equal(pk$PB, dbinom(7, 20, 0.33), tolerance = 1e-12)
  expect_error(BinomPeak(-1, 0.3), "need n")
  pe <- BinomPeq(9)
  expect_equal(pe$p, 0.1)
  expect_equal(pe$P0, dbinom(0, 9, 0.1), tolerance = 1e-12)
  expect_equal(pe$P1, dbinom(1, 9, 0.1), tolerance = 1e-12)
  expect_error(BinomPeq(0), "n must")
  expect_equal(BinomDie(2, 6, 6)$probability, dbinom(2, 6, 1 / 6), tolerance = 1e-12)
  expect_error(BinomDie(2, 6, 0.5), "b must")
  expect_equal(CoinPmf(4, 10)$probability, dbinom(4, 10, 0.5), tolerance = 1e-12)
  bp <- BinPoisLim(3, 500, 2)
  expect_equal(bp$binomial, dbinom(3, 500, 2 / 500), tolerance = 1e-12)
  expect_equal(bp$poisson, dpois(3, 2), tolerance = 1e-12)
  expect_error(BinPoisLim(1, 0, 1), "n must")
})

test_that("binomial counting identities", {
  b <- BinomCoef(9, 4)
  expect_equal(b$count, choose(9, 4))
  expect_equal(b$ordered_count, factorial(9) / factorial(5))
  expect_error(BinomCoef(-1, 0), "non-negative")
  expect_error(BinomCoef(3, 4), "cannot exceed")
  expect_equal(BinomCtr(2, 5)$probability, dbinom(7, 10, 0.5), tolerance = 1e-12)
  expect_equal(BinomCtr(6, 5)$probability, 0)
  expect_error(BinomCtr(1, -1), "n must")
  expect_error(BinomCtr(1.5, 3), "x must")
  expect_equal(BinomCtrF(-3, 5)$probability, choose(10, 2) / 4^5, tolerance = 1e-12)
  expect_equal(BinomCtrF(-6, 5)$probability, 0)
  expect_error(BinomCtrF(1, 0.5), "n must")
  expect_error(BinomCtrF(NA, 3), "x must")
  e <- BinomExp(1.3, 5, 0.2)
  expect_equal(e$terms, choose(5, 0:5) * 1.3^(5:0) * 0.2^(0:5), tolerance = 1e-12)
  expect_equal(e$sum, 1.5^5, tolerance = 1e-12)
  expect_error(BinomExp(c(1, 2), 3, 1), "x must")
  expect_error(BinomExp(1, 3, NA), "delta must")
  expect_error(BinomExp(1, -3, 1), "n must")
})

test_that("small expectation and variance facts", {
  expect_equal(CoinVar()$variance, 0.25)
  d <- DieVar(8)
  expect_equal(d$variance, mean(((1:8) - 4.5)^2), tolerance = 1e-12)
  expect_equal(d$variance, (8^2 - 1) / 12, tolerance = 1e-12)
  expect_error(DieVar(0), "sides")
  expect_equal(ExpMean(2.5)$mean, 2.5)
  expect_error(ExpMean(0), "tau")
  m2 <- ExpMom2(1.7)
  f <- function(x) x^2 * dexp(x, 1 / 1.7)
  expect_equal(m2$second_moment, stats::integrate(f, 0, Inf, rel.tol = 1e-12)$value,
               tolerance = 1e-9)
  expect_equal(m2$variance, 1.7^2, tolerance = 1e-12)
  expect_error(ExpMom2(-1), "tau")
  ei <- ExpIntP(1.2, 0.01, 0.8)
  expect_equal(ei$probability, dexp(1.2, 0.8) * 0.01, tolerance = 1e-12)
  expect_error(ExpIntP(-1, 0.1, 1), "lambda")
  la <- ExpLinApx(0.05)
  expect_equal(la$abs_error, exp(0.05) - 1.05, tolerance = 1e-12)
  expect_error(ExpLinApx(c(1, 2)), "single")
  tl <- ExpTaylor(1.5, terms = 6)
  expect_equal(tl$partial_sums, cumsum(1.5^(0:5) / factorial(0:5)), tolerance = 1e-12)
  expect_equal(ExpTaylor(2)$final_error, 0, tolerance = 1e-12)
  expect_error(ExpTaylor(NA), "x must")
  expect_error(ExpTaylor(1, 0), "terms")
  expect_equal(EsumIid(1.5, 4)$e_sum, 6)
  expect_error(EsumIid(NA, 2), "e_x")
  expect_error(EsumIid(1, -2), "non-negative")
  ec <- EsumConv(c(0, 1, 3), c(0.2, 0.5, 0.3), c(1, 2), c(0.6, 0.4))
  expect_equal(ec$e_sum, 1.4 + 1.4, tolerance = 1e-12)
  expect_error(EsumConv(1:2, 1, 1, 1), "equal-length")
  expect_error(EsumConv(1:2, c(0.2, 0.2), 1, 1), "sum to 1")
  dq <- DiffQuot2(1.5, 0.1)
  expect_equal(dq$quotient, (1.6^2 - 1.5^2) / 0.1, tolerance = 1e-12)
  expect_error(DiffQuot2(1, 0), "nonzero")
  expect_error(DiffQuot2(NA, 1), "x must")
  dn <- DiffQuotN(2, 4, 1e-3)
  expect_equal(dn$quotient, (2.001^4 - 16) / 1e-3, tolerance = 1e-9)
  expect_equal(dn$derivative, 32)
  expect_equal(DiffQuotN(2, 0, 1)$derivative, 0)
  expect_error(DiffQuotN(2, -1, 1), "n must")
  expect_error(DiffQuotN(2, 1, 0), "nonzero")
  expect_error(DiffQuotN(NA, 1, 1), "x must")
})

test_that("covariance identities, Bayes, best constant, book means", {
  x <- c(1, 4, 2, 8, 5)
  y <- c(2, 3, 1, 9, 6)
  expect_equal(CovShort(x, y)$cov, cov(x, y) * 4 / 5, tolerance = 1e-12)
  expect_error(CovShort(1, 1), "n >= 2")
  ci <- CovIndep(x, y, tol = 1)
  expect_false(ci$near_zero)
  expect_true(CovIndep(c(1, -1, 1, -1), c(1, 1, -1, -1))$near_zero)
  expect_error(CovIndep(x, y, tol = -1), "tol")
  xz <- x - mean(x)
  yz <- y - mean(y)
  expect_equal(CovZMean(xz, yz)$cov, mean(xz * yz), tolerance = 1e-12)
  expect_error(CovZMean(x, y), "zero-mean")
  expect_error(CovZMean(1:2, 1), "equal-length")
  expect_equal(BayesExp()$posterior, 0.95 * 0.02 / (0.95 * 0.02 + 0.1 * 0.98),
               tolerance = 1e-12)
  expect_error(BayesExp(p_a = 2), "\\[0, 1\\]")
  expect_error(BayesExp(p_a = 0, p_z_given_not_a = 0), "impossible")
  bc <- BestConst(y)
  expect_equal(bc$best_prediction, mean(y))
  expect_equal(bc$mse, mean((y - mean(y))^2), tolerance = 1e-12)
  expect_error(BestConst(numeric(0)), "non-empty")
  bm <- BookMeans()
  expect_equal(c(bm$xbar, bm$ybar), c(4, 3))
  expect_equal(BookMeans(x, y)$ybar, mean(y))
  expect_error(BookMeans(numeric(0)), "non-empty")
})

test_that("DensProb and DensProbC integrate a tabulated density", {
  g <- seq(-6, 6, length.out = 2001)
  r <- DensProb(g, dnorm(g), -1, 1.5)
  xs <- seq(-1, 1.5, length.out = 513)
  ys <- approx(g, dnorm(g), xs)$y
  expect_equal(r$probability, sum(diff(xs) * (ys[-1] + ys[-513]) / 2), tolerance = 1e-12)
  expect_equal(r$probability, pnorm(1.5) - pnorm(-1), tolerance = 1e-5)
  c2 <- DensProbC(g, dnorm(g), center = 0.5, width = 1)
  expect_equal(c2$probability, DensProb(g, dnorm(g), 0, 1)$probability, tolerance = 1e-12)
  expect_error(DensProb(1:3, 1:2, 1, 2), "equal-length")
  expect_error(DensProb(c(1, 3, 2), c(1, 1, 1), 1, 2), "increasing")
  expect_error(DensProb(g, -dnorm(g), 0, 1), ">= 0")
  expect_error(DensProb(g, 2 * dnorm(g), 0, 1), "integrates")
  expect_error(DensProb(g, dnorm(g), 1, 0), "a <= b")
})

test_that("Bimid is the Wilcox biweight midvariance", {
  x <- c(2.1, 3.4, 1.9, 5.6, 2.8, 30, 3.1, 2.5, 4.2, 3.9)
  r <- Bimid(x)
  M <- median(x)
  mad <- median(abs(x - M))
  u <- (x - M) / (9 * mad)
  a <- abs(u) < 1
  num <- sum(((x - M)^2 * (1 - u^2)^4)[a])
  den <- abs(sum(((1 - u^2) * (1 - 5 * u^2))[a]))
  expect_equal(r$estimate, 10 * num / den^2, tolerance = 1e-12)
  expect_equal(r$n_used, 9L)
  expect_error(Bimid(1), "at least 2")
  expect_error(Bimid(c(1, NA)), "missing")
  expect_error(Bimid(c(1, 1, 1, 2)), "zero")
})

test_that("ChiDep is the empirical tail-dependence chi(u)", {
  x <- c(0.3, 1.2, -0.5, 2.2, 0.8, 1.9, -1.1, 0.1, 2.7, 1.4)
  y <- c(0.1, 1.5, -0.2, 2.0, 0.4, 2.3, -0.9, 0.5, 2.1, 0.9)
  rx <- rank(x) / 11
  ry <- rank(y) / 11
  u <- 0.8
  j <- min(max(mean(rx < u & ry < u), 1 / 20), 1 - 1 / 20)
  expect_equal(ChiDep(x, y, u)$estimate, min(max(2 - log(j) / log(u), 0), 1),
               tolerance = 1e-12)
  expect_error(ChiDep(1:3, 1:3), "n >= 4")
})
