test_that("salience measures follow their definitions", {
  u <- .morie_random_uniform(40, seed = 3)
  ser <- lapply(0:2, function(k) 1 + 5 * u[8 * k + 1:8])
  r <- AttentionPunctuation(ser)
  x <- sort(r$changes)
  pr <- utils::combn(x, 2)
  expect_equal(r$l_moments[2], mean(pr[2, ] - pr[1, ]) / 2, tolerance = 1e-12)
  X <- cbind(c(1, -1, 0), c(0, 0.5, -0.5))
  v <- ValenceConvergence(X, c(0, 1, 1.5), 1)
  rho1 <- 1 / (1 + exp(1) + exp(1.5))
  expect_equal(v$c, 2 * (1 - 2 * rho1) * (2 / 3 + 1 / 6), tolerance = 1e-12)
  expect_false(v$local_equilibrium)
  X2 <- rbind(c(3, -1), c(1, 4), c(2, 0), c(5, 2), c(0, 1))
  expect_equal(StructureInducedEquilibrium(X2), c(2, 1))
  expect_equal(StructureInducedEquilibrium(X2, c(5, 1, 1, 1, 1)), c(3, -1))
})
