# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for the Burkov Hundred-Page LM shelf.
#
# Anchors generated by running the Python core, not recalled. The
# autodiff gradients are pinned both to Python's values and to central
# finite differences computed HERE, so the two languages and the
# numerics all have to agree.

test_that("the linear model, errors and cost cohere and match Python", {
  expect_equal(morie_burkov_linear_function(c(1, 2), 3, -1)$predictions,
               c(2, 5))
  expect_equal(morie_burkov_squared_error(3, 1)$estimate, 4)
  expect_equal(morie_burkov_mse_cost(2, 0, c(1, 2), c(2, 4))$cost, 0)
  x <- c(1, 2, 3)
  y <- c(1.5, 3, 5)
  pred <- morie_burkov_linear_function(x, 1.5, 0)$predictions
  errs <- morie_burkov_squared_error(pred, y)$errors
  expect_equal(morie_burkov_mse_cost(1.5, 0, x, y)$cost, mean(errs))
  expect_error(morie_burkov_mse_cost(1, 0, c(1, 2), c(1, 2), N = 5),
               "dataset size")
})

test_that("the MSE cost is minimised at the least-squares solution", {
  s <- 1
  u <- numeric(40)
  for (i in 1:40) {
    s <- (1664525 * s + 1013904223) %% 2^32
    u[i] <- (s + 0.5) / 2^32
  }
  x <- u[1:20] * 10
  y <- 2.5 * x - 1 + (u[21:40] - 0.5)
  fit <- stats::lm(y ~ x)
  b_star <- coef(fit)[1]
  w_star <- coef(fit)[2]
  j_star <- morie_burkov_mse_cost(w_star, b_star, x, y)$cost
  for (d in list(c(0.05, 0), c(-0.05, 0), c(0, 0.05), c(0, -0.05))) {
    expect_gt(morie_burkov_mse_cost(w_star + d[1], b_star + d[2],
                                    x, y)$cost, j_star)
  }
})

test_that("cosine similarity matches Python and its properties", {
  expect_equal(morie_burkov_cosine_similarity(c(1, 0), c(0, 1))$estimate, 0)
  expect_equal(morie_burkov_cosine_similarity(c(1, 2), c(2, 4))$estimate, 1,
               tolerance = 1e-12)
  a <- c(1, 2, -1)
  b <- c(0.5, -1, 2)
  expect_equal(morie_burkov_cosine_similarity(a, b)$estimate,
               morie_burkov_cosine_similarity(7 * a, 0.1 * b)$estimate,
               tolerance = 1e-12)
  expect_error(morie_burkov_cosine_similarity(c(0, 0), c(1, 1)),
               "zero vector")
})

test_that("the two-layer network composes and relu clips", {
  y1 <- morie_burkov_layer1_output(rbind(c(1, -1), c(0.5, 0.5)),
                                   c(2, 1), c(0.1, -0.1),
                                   phi = "tanh")$output
  y2 <- morie_burkov_layer2_output(c(1, 2), y1, 0.3,
                                   phi = "sigmoid")$estimate
  z <- y1[1] + 2 * y1[2] + 0.3
  expect_equal(y2, 1 / (1 + exp(-z)), tolerance = 1e-14)
  out <- morie_burkov_layer1_output(rbind(1, -1), 2, c(0, 0),
                                    phi = "relu")
  expect_equal(out$output, c(2, 0))
  expect_equal(out$preactivation, c(2, -2))
})

test_that("logistic regression and BCE match Python", {
  out <- morie_burkov_logistic(c(1, -2), c(3, 1), 0.5)
  expect_equal(out$logit, 1.5)
  expect_equal(out$estimate, 1 / (1 + exp(-1.5)), tolerance = 1e-14)
  expect_equal(morie_burkov_binary_cross_entropy(0.5, 1)$estimate,
               0.6931471806, tolerance = 1e-9)
  expect_equal(morie_burkov_binary_cross_entropy(1, 1)$estimate, 0)
  expect_equal(morie_burkov_binary_cross_entropy(0, 1)$estimate, Inf)
  expect_error(morie_burkov_binary_cross_entropy(0.5, 0.7), "targets")
})

test_that("BCE gradients match Python and finite differences", {
  out <- morie_burkov_bce_gradients(c(0.8, 0.3, 0.6), c(1, 0, 1),
                                    rbind(c(1, 2), c(0.5, -1), c(2, 0)))
  expect_equal(out$grad_w, c(-0.2833333333333333, -0.2333333333333333),
               tolerance = 1e-12)
  expect_equal(out$grad_b, -0.1, tolerance = 1e-12)
  # against central differences on the mean BCE of a logistic model
  set.seed(2)
  X <- matrix(stats::runif(40, -2, 2), 20, 2)
  y <- as.numeric(stats::runif(20) > 0.5)
  w <- c(0.3, -0.7)
  b <- 0.2
  mean_bce <- function(wv, bv) {
    p <- 1 / (1 + exp(-(X %*% wv + bv)))
    mean(-(y * log(p) + (1 - y) * log(1 - p)))
  }
  p <- as.numeric(1 / (1 + exp(-(X %*% w + b))))
  out2 <- morie_burkov_bce_gradients(p, y, X)
  h <- 1e-6
  for (j in 1:2) {
    e <- c(0, 0)
    e[j] <- h
    num <- (mean_bce(w + e, b) - mean_bce(w - e, b)) / (2 * h)
    expect_equal(out2$grad_w[j], num, tolerance = 1e-5)
  }
  numb <- (mean_bce(w, b + h) - mean_bce(w, b - h)) / (2 * h)
  expect_equal(out2$grad_b, numb, tolerance = 1e-5)
})

test_that("categorical cross-entropy matches Python, 0-based class", {
  expect_equal(morie_burkov_categorical_cross_entropy(c(0.7, 0.2, 0.1),
                                                      0)$estimate,
               0.3566749439, tolerance = 1e-9)
  expect_error(morie_burkov_categorical_cross_entropy(c(1, 1), 0),
               "probability distribution")
  expect_error(morie_burkov_categorical_cross_entropy(c(0.5, 0.5), 2),
               "out of range")
})

test_that("the next-token bigram MLE matches Python", {
  out <- morie_burkov_next_token("b", c("a", "b", "a", "c", "a", "b"))
  expect_equal(out$context, "b")
  expect_equal(out$estimate, 0)
  expect_equal(sum(unlist(out$distribution)), 1)
  expect_equal(morie_burkov_next_token("b",
                                       c("a", "b", "a", "c", "a"))$estimate,
               0.5)
  expect_equal(morie_burkov_next_token("b", c("a", "b", "a"))$estimate, 1)
  expect_error(morie_burkov_next_token("x", c("a", "b")), "undefined")
})

test_that("n-gram estimators match Python and sum to one", {
  expect_equal(morie_burkov_ngram_mle(3, 4)$estimate, 0.75)
  expect_error(morie_burkov_ngram_mle(0, 0), "undefined")
  expect_error(morie_burkov_ngram_mle(5, 4), "impossible")
  counts <- c(7, 3, 0)
  lap <- vapply(counts, function(c) {
    morie_burkov_laplace(c, 10, 3)$estimate
  }, numeric(1))
  expect_equal(sum(lap), 1)
  addk <- vapply(counts, function(c) {
    morie_burkov_add_k(c, 10, 3, k = 0.25)$estimate
  }, numeric(1))
  expect_equal(sum(addk), 1)
  expect_equal(morie_burkov_add_k(2, 9, 5, k = 1)$estimate,
               morie_burkov_laplace(2, 9, 5)$estimate)
  expect_gt(lap[3], 0)
  expect_lt(lap[1], 0.7)
})

test_that("interpolation and backoff match Python", {
  expect_equal(morie_burkov_interpolation(c(0.9, 0.1, 0.5),
                                          c(0.6, 0.3, 0.1))$estimate,
               0.9 * 0.6 + 0.1 * 0.3 + 0.5 * 0.1, tolerance = 1e-12)
  expect_error(morie_burkov_interpolation(c(0.5, 0.5), c(0.9, 0.3)),
               "sum to 1")
  expect_equal(morie_burkov_backoff(list(c(2, 4), c(9, 10)))$order_used, 0L)
  out <- morie_burkov_backoff(list(c(0, 5), c(0, 8), c(3, 10)),
                              alpha = 0.5)
  expect_equal(out$order_used, 2L)
  expect_equal(out$estimate, 0.5 * 0.5 * 0.3, tolerance = 1e-12)
  expect_error(morie_burkov_backoff(list(c(0, 5), c(0, 8))),
               "nowhere left")
})

test_that("Kneser-Ney matches Python and closes over a vocabulary", {
  expect_equal(morie_burkov_kneser_ney(2, 4, c(2, 3, 10), 0.75)$estimate,
               0.425, tolerance = 1e-12)
  prefix <- 10
  d <- 0.75
  follows <- c(cat = 6, dog = 3, fish = 1)
  cont <- c(cat = 3, dog = 4, fish = 1)
  total_types <- 8
  n_after <- 3
  total_norm <- sum(vapply(names(follows), function(w) {
    morie_burkov_kneser_ney(follows[[w]], prefix,
                            c(n_after,
                              cont[[w]] / sum(cont) * total_types,
                              total_types), d)$estimate
  }, numeric(1)))
  expect_equal(total_norm, 1, tolerance = 1e-12)
})

test_that("bits per character matches Python", {
  out <- morie_burkov_bits_per_character(2, 100, 400)
  expect_equal(out$estimate, 2 * 100 / (log(2) * 400), tolerance = 1e-14)
  expect_equal(morie_burkov_bits_per_character(log(2), 100, 100)$estimate,
               1, tolerance = 1e-12)
})

test_that("dot, norm, unit and cosine cohere", {
  a <- c(3, 4)
  b <- c(4, 3)
  dot <- morie_burkov_dot_product(a, b)$estimate
  na <- morie_burkov_vector_norm(a)$estimate
  nb <- morie_burkov_vector_norm(b)$estimate
  expect_equal(morie_burkov_cosine_similarity(a, b)$estimate,
               dot / (na * nb), tolerance = 1e-14)
  ua <- morie_burkov_unit_vector(a)$unit
  expect_equal(morie_burkov_vector_norm(ua)$estimate, 1, tolerance = 1e-14)
  expect_equal(ua, c(0.6, 0.8))
  expect_error(morie_burkov_unit_vector(c(0, 0)), "zero vector")
})

test_that("TF and TF-IDF match Python", {
  expect_equal(morie_burkov_term_frequency("a", c("a", "b", "a"))$estimate,
               2)
  expect_equal(morie_burkov_term_frequency("a", c("a", "b", "a"),
                                           normalise = TRUE)$estimate,
               2 / 3, tolerance = 1e-14)
  corpus <- list(c("a", "b"), c("b", "c"), c("b", "d"))
  expect_equal(morie_burkov_tf_idf("b", c("a", "b"), corpus)$estimate, 0)
  out <- morie_burkov_tf_idf("a", c("a", "a", "b"), corpus)
  expect_equal(out$tf, 2)
  expect_equal(out$estimate, 2 * log(3), tolerance = 1e-12)
  expect_error(morie_burkov_tf_idf("z", "z", corpus), "no corpus document")
})

test_that("the repetition penalty lowers odds against unpenalised tokens", {
  logits <- c(2, -1, 0.5)
  out <- morie_burkov_repetition_penalty(logits, c(0, 1), penalty = 1.5)
  expect_equal(out$penalised, c(2 / 1.5, -1.5, 0.5), tolerance = 1e-12)
  p_before <- exp(logits) / sum(exp(logits))
  p_after <- exp(out$penalised) / sum(exp(out$penalised))
  for (t in 1:2) {
    expect_lt(p_after[t] / p_after[3], p_before[t] / p_before[3])
  }
  expect_gt(p_after[3], p_before[3])
  expect_error(morie_burkov_repetition_penalty(logits, 5), "out of range")
})

test_that("weight tying matches an explicit matrix product", {
  E <- rbind(c(1, 2), c(3, -1), c(0, 1))
  out <- morie_burkov_weight_tying(c(0.5, -0.5), E)
  expect_equal(out$logits, as.numeric(E %*% c(0.5, -0.5)))
  expect_equal(out$vocab_size, 3)
  expect_error(morie_burkov_weight_tying(c(1, 2, 3), E), "columns to")
})

test_that("the Elman step matches Python", {
  out <- morie_burkov_elman_rnn(c(1, 0.5), c(0.2, -0.1),
                                rbind(c(0.5, 0), c(0, 0.5)),
                                rbind(c(1, 0), c(0, 1)),
                                rbind(c(1, 1)), c(0, 0), 0.1)
  expect_equal(out$h, c(0.8004990217606297, 0.4218990052500079),
               tolerance = 1e-14)
  expect_equal(out$y, 1.3223980270106377, tolerance = 1e-14)
})

test_that("autodiff matches Python and central differences", {
  g <- list(list(name = "wx", op = "mul", args = c("w", "x")),
            list(name = "z", op = "add", args = c("wx", "b")),
            list(name = "a", op = "sigmoid", args = "z"),
            list(name = "d", op = "sub", args = c("a", "y")),
            list(name = "loss", op = "square", args = "d"))
  inputs <- list(w = 0.7, x = 1.3, b = -0.2, y = 1.0)
  out <- morie_burkov_computational_graph(g, inputs)
  expect_equal(out$output, 0.10863539545533897, tolerance = 1e-14)
  expect_equal(out$gradients$w, -0.18935616728484128, tolerance = 1e-13)
  expect_equal(out$gradients$x, -0.10196101315337606, tolerance = 1e-13)
  expect_equal(out$gradients$b, -0.14565859021910868, tolerance = 1e-13)
  expect_equal(out$gradients$y, 0.6591976803822628, tolerance = 1e-13)
  h <- 1e-6
  for (k in names(inputs)) {
    up <- inputs
    up[[k]] <- up[[k]] + h
    dn <- inputs
    dn[[k]] <- dn[[k]] - h
    num <- (morie_burkov_computational_graph(g, up)$output -
              morie_burkov_computational_graph(g, dn)$output) / (2 * h)
    expect_equal(out$gradients[[k]], num, tolerance = 1e-5)
  }
})

test_that("autodiff fan-out accumulates and bad graphs are refused", {
  g <- list(list(name = "sq", op = "mul", args = c("x", "x")),
            list(name = "out", op = "add", args = c("sq", "x")))
  out <- morie_burkov_computational_graph(g, list(x = 3))
  expect_equal(out$output, 12)
  expect_equal(out$gradients$x, 7)
  expect_error(morie_burkov_computational_graph(
    list(list(name = "a", op = "add", args = c("a2", "x"))),
    list(x = 1)), "topologically")
  expect_error(morie_burkov_computational_graph(
    list(list(name = "a", op = "pow", args = c("x", "x"))),
    list(x = 1)), "unknown op")
})
