# Coles shelf: R-side tests + 10-significant-digit Python parity
# anchors (generated by morie/fn/_evt_core on the same fixed data).

x20 <- c(4.1, 5.3, 3.9, 6.8, 5.0, 4.4, 7.2, 5.9, 4.7, 6.1,
         5.5, 4.0, 8.3, 5.2, 4.9, 6.5, 5.7, 4.3, 7.0, 5.1)
y20 <- c(0.4, 1.7, 0.2, 2.9, 0.8, 1.1, 3.5, 0.6, 1.9, 0.3,
         2.2, 0.9, 4.1, 1.4, 0.5, 2.6, 1.0, 0.7, 3.0, 1.2)

test_that("GEV closed forms match the Python anchors to 10 digits", {
  expect_equal(morie_evt_gev_loglik(x20, 5.0, 1.5, 0.1),
               -33.4685914523, tolerance = 1e-9)
  expect_equal(morie_evt_gev_loglik(x20, 5.0, 1.5, 0.0),
               -33.2143159295, tolerance = 1e-9)
  expect_equal(morie_evt_gev_cdf(6.0, 5.0, 1.5, 0.1),
               0.5918746094, tolerance = 1e-9)
  expect_equal(morie_evt_gev_quantile(0.9, 5.0, 1.5, 0.1),
               8.7855307741, tolerance = 1e-9)
  expect_equal(morie_evt_return_level(5.0, 1.5, 0.1, 100),
               13.7614643569, tolerance = 1e-9)
})

test_that("GPD closed forms match the Python anchors to 10 digits", {
  expect_equal(morie_evt_gpd_loglik(y20, 1.2, 0.15),
               -29.7995012142, tolerance = 1e-9)
  expect_equal(morie_evt_gpd_cdf(2.0, 1.2, 0.15),
               0.7740911490, tolerance = 1e-9)
  expect_equal(morie_evt_gpd_quantile(0.95, 1.2, 0.15),
               4.5384683013, tolerance = 1e-9)
  expect_equal(morie_evt_return_level_pot(5.0, 1.2, 0.15, 0.05, 365),
               9.3674287580, tolerance = 1e-9)
})

test_that("ML fits agree with the Python optimizer", {
  f <- morie_evt_gev_mle(x20)
  expect_equal(f$mu,    4.946375, tolerance = 2e-4)
  expect_equal(f$sigma, 0.927168, tolerance = 2e-4)
  expect_equal(f$xi,    0.007480, tolerance = 5e-3)
  expect_equal(f$loglik, -30.26655382, tolerance = 1e-5)
  g <- morie_evt_gpd_mle(y20)
  expect_equal(g$sigma, 2.455341, tolerance = 2e-3)
  expect_equal(g$xi,   -0.546814, tolerance = 5e-3)
  expect_equal(g$loglik, -27.02902492, tolerance = 1e-5)
})

test_that("quantile/cdf round-trips are exact for all shape regimes", {
  for (xi in c(-0.3, 0, 0.2, 0.7)) {
    for (p in c(0.05, 0.5, 0.9, 0.99)) {
      z <- morie_evt_gev_quantile(p, 1, 2, xi)
      expect_equal(morie_evt_gev_cdf(z, 1, 2, xi), p,
                   tolerance = 1e-10)
      q <- morie_evt_gpd_quantile(p, 2, xi)
      expect_equal(morie_evt_gpd_cdf(q, 2, xi), p,
                   tolerance = 1e-10)
    }
  }
})

test_that("return-level CI brackets the point estimate", {
  set.seed(1)
  # GEV sample via inverse CDF
  u <- runif(600)
  x <- morie_evt_gev_quantile(u, 10, 2, 0.1)
  r <- morie_evt_return_level_ci(x, 50)
  expect_lt(r$ci_lo, r$z_T)
  expect_gt(r$ci_hi, r$z_T)
  true_z <- morie_evt_return_level(10, 2, 0.1, 50)
  expect_gt(true_z, r$ci_lo)
  expect_lt(true_z, r$ci_hi)
})

test_that("chi ordering: dependent > independent, bounds hold", {
  set.seed(2)
  x <- rnorm(800)
  y_dep <- x + rnorm(800, 0, 0.3)
  y_ind <- rnorm(800)
  expect_gt(morie_evt_chi(x, y_dep, 0.9),
            morie_evt_chi(x, y_ind, 0.9))
  expect_gte(morie_evt_chi(x, y_ind, 0.9), 0)
  cb <- morie_evt_chibar(x, x)
  expect_gt(tail(cb, 1), 0.8)
  expect_true(all(cb >= -1 & cb <= 1))
})

test_that("profile interval brackets the MLE and the truth", {
  set.seed(3)
  x <- morie_evt_gev_quantile(runif(800), 10, 2, 0.15)
  r <- morie_evt_xi_ci_profile(x)
  expect_lt(r$ci_lo, 0.15)
  expect_gt(r$ci_hi, 0.15)
  expect_lt(r$ci_lo, r$xi_hat)
  expect_gt(r$ci_hi, r$xi_hat)
})

test_that("Bayesian GEV posterior centres on the truth", {
  set.seed(4)
  x <- morie_evt_gev_quantile(runif(600), 10, 2, 0.1)
  r <- morie_evt_bayes_gev(x, n_draws = 1500, seed = 5)
  expect_lt(abs(mean(r$draws[, 1]) - 10), 0.5)
  expect_lt(abs(mean(r$draws[, 3]) - 0.1), 0.15)
  expect_gt(r$accept_rate, 0.1)
  expect_lt(r$accept_rate, 0.8)
})

test_that("trend model recovers a real slope and rejects a null one", {
  set.seed(6)
  base <- morie_evt_gev_quantile(runif(300), 5, 1, 0.1)
  x <- base + 0.02 * (seq_along(base) - 1)
  r <- morie_evt_gev_trend(x)
  expect_lt(abs(r$beta1 - 0.02), 0.008)
  expect_gt(r$lr_vs_stationary, qchisq(0.95, 1))
  r0 <- morie_evt_gev_trend(base)
  expect_lt(abs(r0$beta1), 0.01)
})
