test_that("DelaunayTriangulation gives the analytic and Python-arm triangles", {
  r <- DelaunayTriangulation(rbind(c(0, 0), c(1, 0), c(0, 1), c(1, 1), c(0.5, 0.4)))
  expect_identical(r$triangles * 1, rbind(c(1, 2, 5), c(2, 4, 5), c(3, 1, 5), c(4, 3, 5)))
  expect_lt(abs(r$circumradii[1] - sqrt(0.26265625)), 1e-15)
  e <- DelaunayTriangulation(rbind(c(0, 0), c(1, 0), c(0.5, sqrt(3) / 2)))
  expect_lt(abs(e$quality - 1), 1e-15)
  U <- .morie_random_uniform(120, seed = 21, stream = 0)
  P <- cbind(2 * U[seq(1, 119, 2)], U[seq(2, 120, 2)])
  r <- DelaunayTriangulation(P)
  expect_identical(nrow(r$triangles), 108L)
  expect_identical(r$empty_circle_violations, 0L)
  s <- DelaunayTriangulation(sweep(P, 2, c(-1e6, 2e6)))
  expect_identical(s$triangles, r$triangles)
})
