# Coverage tests for R/hiatus_native.R (Gog and Grenfell 2002): R0, the
# single-strain endemic equilibrium, the status-based derivatives, one
# RK4 step by hand, convergence and the strain-space cross-immunity.

test_that("reproduction numbers and the endemic equilibrium", {
  expect_equal(basic_reproduction_numbers(c(2, 0.5), c(0.9, 0.4), 0.1), c(2, 1))
  expect_equal(basic_reproduction_numbers(c(2, 3), 0.9, 0.1), c(2, 3))
  expect_error(basic_reproduction_numbers(1, 0, 0), "never leaves the infectious class")
  e <- endemic_equilibrium(c(2, 0.5), 0.9, 0.1)
  expect_equal(c(e$S, e$I), c(0.5, 0.1 * 0.5 / 1))
  d <- derivatives(e$S, e$I, 2, 0.9, 0.1, matrix(1))
  expect_equal(c(d$dS, d$dI), c(0, 0), tolerance = 1e-15)
  expect_equal(endemic_equilibrium(c(2, 0.5), 0.9, 0.1, strain = 1)$I, 0)
})

test_that("status-based derivatives", {
  b <- c(1.5, 2)
  nu <- c(0.5, 0.7)
  sg <- rbind(c(1, 0.3), c(0.6, 1))
  S <- c(0.7, 0.5)
  I <- c(0.02, 0.05)
  d <- derivatives(S, I, b, nu, 0.02, sg)
  expect_equal(d$dI, b * S * I - (nu + 0.02) * I, tolerance = 1e-15)
  expect_equal(d$dS, 0.02 - S * as.numeric(sg %*% (b * I)) - 0.02 * S, tolerance = 1e-15)
  expect_error(derivatives(S[1], I, b, nu, 0.02, sg), "one entry per strain")
  expect_error(derivatives(S, I, b, nu[1:2], 0.02, sg[1, , drop = FALSE]), "sigma must be 2 by 2")
  expect_error(derivatives(S, I, c(1, -1), nu, 0.02, sg), "transmission rates must be positive")
  expect_error(derivatives(S, I, b, c(-1, 1), 0.02, sg), "recovery rates must be non-negative")
  expect_error(derivatives(S, I, b, nu, -1, sg), "birth/death rate")
  expect_error(derivatives(S, I, b, 1:3, 0.02, sg), "3 recovery rates for 2 strains")
  expect_error(derivatives(S, I, b, nu, 0.02, sg * 2), "must lie in \\[0, 1\\]")
})

test_that("one RK4 step by hand, and convergence to equilibrium", {
  b <- c(1.5, 2)
  nu <- c(0.5, 0.7)
  sg <- rbind(c(1, 0.3), c(0.6, 1))
  S0 <- c(0.9, 0.8)
  I0 <- c(0.01, 0.02)
  r <- morie_hiatus(b, nu, 0.02, sg, S0, I0, t_end = 0.1, dt = 0.1, record_every = 1)
  f <- function(S, I) derivatives(S, I, b, nu, 0.02, sg)
  k1 <- f(S0, I0)
  k2 <- f(S0 + 0.05 * k1$dS, I0 + 0.05 * k1$dI)
  k3 <- f(S0 + 0.05 * k2$dS, I0 + 0.05 * k2$dI)
  k4 <- f(S0 + 0.1 * k3$dS, I0 + 0.1 * k3$dI)
  expect_equal(r$S, S0 + 0.1 / 6 * (k1$dS + 2 * k2$dS + 2 * k3$dS + k4$dS), tolerance = 1e-14)
  expect_equal(r$I, I0 + 0.1 / 6 * (k1$dI + 2 * k2$dI + 2 * k3$dI + k4$dI), tolerance = 1e-14)
  expect_equal(r$t, c(0, 0.1))
  one <- morie_hiatus(2, 0.9, 0.1, matrix(1), t_end = 400, dt = 0.1)
  expect_equal(c(one$S, one$I), c(0.5, 0.05), tolerance = 1e-8)
  expect_equal(one$surviving, 0L)
  expect_equal(one$n_variables_history_based, "2^1 = 2")
  m <- morie_hiatus(c(2, 2, 2), 0.9, 0.1, linear_strain_space(3), t_end = 5, dt = 0.1, mutation = 0.1)
  expect_equal(m$n_variables, 6L)
  expect_identical(twostrainhiatus, .hiatus_simulate)
  expect_identical(hiatus_model, .hiatus_simulate)
  expect_identical(hiatusmodel, .hiatus_simulate)
  expect_match(.hiatus_cheatsheet(), "2n variables")
  expect_error(morie_hiatus(2, 0.9, 0.1, matrix(1), dt = 0), "dt must be positive")
  expect_error(morie_hiatus(2, 0.9, 0.1, matrix(1), mutation = 1), "mutation must lie")
  expect_error(morie_hiatus(2, 0.9, 0.1, matrix(1), S0 = c(1, 1)), "one entry per strain")
})

test_that("strain-space cross-immunity kernel", {
  s <- linear_strain_space(4, width = 1.5, floor = 0.1)
  ref <- pmax(exp(-outer(1:4, 1:4, "-")^2 / 2.25), 0.1)
  expect_equal(s, ref, tolerance = 1e-15)
  expect_error(linear_strain_space(0), "at least 1")
  expect_error(linear_strain_space(3, width = 0), "width must be positive")
})
