# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for the probabilistic method.
#
# Anchors generated by running the Python core, not recalled.
#
# These are one-sided bounds, so there are two properties worth testing
# and both are: the bound must never be violated by the exact
# probability, and it must not be vacuous. A bound of 1 holds
# universally and says nothing, so "it holds" alone is not a passing
# grade.

test_that("the first-moment Ramsey bound matches Python", {
  for (kv in list(c(4, 6), c(6, 17), c(10, 100), c(15, 792), c(20, 5817))) {
    expect_equal(morie_first_moment_ramsey(kv[1])$bound, kv[2])
  }
  expect_equal(morie_first_moment_ramsey(10)$expected_at_bound,
               0.98397717104255578, tolerance = 1e-12)
})

test_that("the expected count at the bound is below one", {
  for (k in c(4, 6, 10, 20)) {
    expect_lt(morie_first_moment_ramsey(k)$expected_at_bound, 1)
  }
})

test_that("a capped search reports the cap rather than a bound", {
  expect_false(morie_first_moment_ramsey(20)$search_capped)
  big <- morie_first_moment_ramsey(30)
  expect_true(big$search_capped)
  expect_true(any(grepl("CEILING", big$warnings)))
})

test_that("the alteration bound matches Python exactly", {
  ref <- list(c(4, 5, 6, -1), c(6, 17, 17, 0), c(10, 115, 100, 15),
              c(15, 979, 792, 187), c(20, 7446, 5817, 1629))
  for (r in ref) {
    a <- morie_alteration_ramsey(r[1])
    expect_equal(a$bound, r[2])
    expect_equal(a$first_moment_bound, r[3])
    expect_equal(a$improvement, r[4])
  }
})

test_that("alteration beats the union bound for moderate k", {
  for (k in c(8, 10, 15, 20)) {
    a <- morie_alteration_ramsey(k)
    expect_gt(a$bound, a$first_moment_bound)
  }
})

test_that("alteration is NOT uniformly better and reports the maximum", {
  a4 <- morie_alteration_ramsey(4)
  expect_equal(a4$improvement, -1)
  expect_equal(a4$best_bound, 6)
  expect_equal(morie_alteration_ramsey(6)$improvement, 0)
  for (k in 3:21) {
    a <- morie_alteration_ramsey(k)
    expect_equal(a$best_bound, max(a$bound, a$first_moment_bound))
  }
})

test_that("both Ramsey bounds lie below the truth where it is known", {
  for (k in c(3, 4)) {
    expect_lt(morie_first_moment_ramsey(k)$bound,
              morie_ramsey_number(k, k)$value)
    expect_lt(morie_alteration_ramsey(k)$best_bound,
              morie_ramsey_number(k, k)$value)
  }
})

# ------------------------------------------------------------------
# Lovasz Local Lemma
# ------------------------------------------------------------------

test_that("the Local Lemma condition matches Python", {
  l <- morie_lovasz_local_lemma(0.01, 20)
  expect_equal(l$condition_value, 0.57083918397639954, tolerance = 1e-12)
  expect_true(l$applies)
  expect_equal(l$max_degree_at_p, 35)
  expect_equal(l$max_probability_at_d, 0.017518068627211541,
               tolerance = 1e-12)
  expect_false(morie_lovasz_local_lemma(0.1, 20)$applies)
})

test_that("the Local Lemma succeeds where the union bound cannot", {
  # the union bound scales with the NUMBER of events; the Local Lemma
  # does not care how many there are, only how entangled each is
  expect_false(morie_union_bound_exists(100000, 0.01)$exists)
  expect_true(morie_lovasz_local_lemma(0.01, 20)$applies)
})

test_that("the reported maximum degree is the largest that works", {
  for (p in c(0.001, 0.01, 0.05)) {
    dmax <- morie_lovasz_local_lemma(p, 1)$max_degree_at_p
    expect_true(morie_lovasz_local_lemma(p, dmax)$applies)
    expect_false(morie_lovasz_local_lemma(p, dmax + 1)$applies)
  }
})

test_that("the reported maximum probability is the boundary", {
  for (d in c(5, 20, 100)) {
    pmax <- morie_lovasz_local_lemma(0.001, d)$max_probability_at_d
    expect_true(morie_lovasz_local_lemma(pmax, d)$applies)
    expect_false(morie_lovasz_local_lemma(pmax * 1.001, d)$applies)
  }
})

# ------------------------------------------------------------------
# Chernoff
# ------------------------------------------------------------------

test_that("the Chernoff bounds match Python", {
  # The BOUNDS are closed-form exponentials and agree to 1e-12. The
  # exact tails are summed by different routes -- R's dbinom against
  # Python's explicit comb * p^i * (1-p)^(n-i) -- so they agree to
  # about 1e-15 relative, roughly five units in the last place, and
  # not bit for bit. Demanding more than the arithmetic offers would
  # be a test of the summation order, not of the mathematics.
  up <- morie_chernoff_bound(100, 0.5, 70)
  expect_equal(up$bound, 0.028636975014075406, tolerance = 1e-12)
  expect_equal(up$exact_tail, 3.9250698227968341e-05, tolerance = 1e-12)
  lo <- morie_chernoff_bound(100, 0.5, 30, tail = "lower")
  expect_equal(lo$bound, 0.018315638888734179, tolerance = 1e-12)
  expect_equal(lo$exact_tail, 3.9250698227968355e-05, tolerance = 1e-12)
  # the two tails are exactly symmetric for p = 1/2, which IS exact
  expect_identical(up$exact_tail, lo$exact_tail)
})

test_that("the upper bound is never violated", {
  set.seed(21)
  for (i in seq_len(200L)) {
    n <- sample.int(191, 1) + 9L
    p <- stats::runif(1) * 0.9 + 0.05
    t <- n * p * (1 + stats::runif(1) * 1.5)
    out <- morie_chernoff_bound(n, p, t, "upper")
    expect_true(out$holds)
    expect_gte(out$bound, out$exact_tail - 1e-12)
  }
})

test_that("the lower bound is never violated", {
  set.seed(22)
  for (i in seq_len(200L)) {
    n <- sample.int(191, 1) + 9L
    p <- stats::runif(1) * 0.9 + 0.05
    t <- n * p * stats::runif(1) * 0.95
    expect_true(morie_chernoff_bound(n, p, t, "lower")$holds)
  }
})

test_that("a vacuous bound is flagged rather than reported as useful", {
  out <- morie_chernoff_bound(100, 0.5, 50)
  expect_true(out$vacuous)
  expect_true(any(grepl("says nothing", out$warnings)))
})

test_that("the bound tightens as the deviation grows", {
  bounds <- vapply(c(0.1, 0.2, 0.3, 0.4), function(d) {
    morie_chernoff_bound(200, 0.5, 100 * (1 + d))$bound
  }, numeric(1))
  expect_true(all(diff(bounds) < 0))
})

# ------------------------------------------------------------------
# Azuma
# ------------------------------------------------------------------

test_that("the Azuma bound matches Python", {
  expect_equal(morie_azuma_bound(100, 1, 30)$bound, 0.022217993076484612,
               tolerance = 1e-12)
})

test_that("Azuma bounds a simulated random walk", {
  set.seed(23)
  n <- 100L; reps <- 4000L
  walks <- vapply(seq_len(reps), function(i) {
    sum(sample(c(-1, 1), n, replace = TRUE))
  }, numeric(1))
  for (t in c(20, 30, 40)) {
    empirical <- mean(abs(walks) >= t)
    expect_gte(morie_azuma_bound(n, 1, t)$bound, empirical)
  }
})

test_that("Azuma is conservative, as a step-size-only bound must be", {
  set.seed(24)
  n <- 100L; reps <- 4000L; t <- 30
  walks <- vapply(seq_len(reps), function(i) {
    sum(sample(c(-1, 1), n, replace = TRUE))
  }, numeric(1))
  b <- morie_azuma_bound(n, 1, t)$bound
  expect_gt(b, mean(abs(walks) >= t))
  expect_lt(b, 1)
})

test_that("the typical deviation is c root n", {
  out <- morie_azuma_bound(100, 2, 40)
  expect_equal(out$typical_deviation, 20)
  expect_equal(out$deviations_out, 2)
})

# ------------------------------------------------------------------
# Second moment
# ------------------------------------------------------------------

test_that("the second moment bound matches Python", {
  out <- morie_second_moment_threshold(100, 50)
  expect_equal(out$p_zero_bound, 0.005, tolerance = 1e-15)
  expect_true(out$positive_whp)
})

test_that("a large relative variance gives nothing", {
  out <- morie_second_moment_threshold(10, 200)
  expect_equal(out$p_zero_bound, 1)
  expect_true(out$vacuous)
  expect_false(out$positive_whp)
})

test_that("the bound never exceeds one", {
  for (p in list(c(1, 1e6), c(10, 1000), c(100, 1))) {
    expect_lte(morie_second_moment_threshold(p[1], p[2])$p_zero_bound, 1)
  }
})

test_that("probabilistic method input validation", {
  expect_error(morie_union_bound_exists(-1, 0.5), "non-negative")
  expect_error(morie_union_bound_exists(10, 1.5), "must lie")
  expect_error(morie_first_moment_ramsey(1), "at least 2")
  expect_error(morie_lovasz_local_lemma(1.5, 3), "must lie")
  expect_error(morie_lovasz_local_lemma(0.1, -1), "non-negative")
  expect_error(morie_chernoff_bound(0, 0.5, 1), "must be positive")
  expect_error(morie_azuma_bound(10, 0, 1), "c must be positive")
  expect_error(morie_second_moment_threshold(1, -1), "non-negative")
  expect_error(morie_second_moment_threshold(0, 1), "must be positive")
})
