# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for algebraic combinatorics.
#
# Anchors generated by running the Python core, not recalled.
#
# Two of these are bijections, which admits a stronger check than a
# count: RSK is round-tripped over every permutation of n <= 6 in both
# languages, and the corollary sum (f^lambda)^2 = n! is checked as an
# identity. Counts past 2^53 are compared as DECIMAL STRINGS -- a
# double cannot hold 44261486084874072183645699204710400 and comparing
# them numerically would test the rounding, not the mathematics.

test_that("partition counts match Python", {
  expect_equal(vapply(0:8, function(n) length(morie_partitions_of(n)),
                      integer(1)),
               c(1L, 1L, 2L, 3L, 5L, 7L, 11L, 15L, 22L))
})

test_that("every partition is weakly decreasing and sums right", {
  for (n in 1:9) {
    for (p in morie_partitions_of(n)) {
      expect_equal(sum(p), n)
      if (length(p) > 1L) expect_true(all(diff(p) <= 0L))
    }
  }
})

test_that("partitions of 5 are in Python's order", {
  got <- morie_partitions_of(5)
  expect_equal(got[[1]], 5L)
  expect_equal(got[[2]], c(4L, 1L))
  expect_equal(got[[3]], c(3L, 2L))
  expect_equal(got[[7]], rep(1L, 5))
})

# ------------------------------------------------------------------
# Hook lengths
# ------------------------------------------------------------------

test_that("hook lengths match Python", {
  h <- morie_hook_lengths(c(3, 2))
  expect_equal(h$hooks[[1]], c(4L, 3L, 1L))
  expect_equal(h$hooks[[2]], c(2L, 1L))
  expect_equal(h$product, 24)
  expect_equal(h$conjugate, c(2L, 2L, 1L))

  h2 <- morie_hook_lengths(c(4, 3, 1))
  expect_equal(h2$hooks[[1]], c(6L, 4L, 3L, 1L))
  expect_equal(h2$hooks[[2]], c(4L, 2L, 1L))
  expect_equal(h2$hooks[[3]], 1L)
  expect_equal(h2$product, 576)
  expect_equal(h2$conjugate, c(3L, 2L, 2L, 1L))
})

test_that("a single row and a single column count down", {
  expect_equal(morie_hook_lengths(5)$hooks[[1]], 5:1)
  h <- morie_hook_lengths(c(1, 1, 1))
  expect_equal(unlist(h$hooks), 3:1)
})

test_that("hook lengths reject a non-partition", {
  expect_error(morie_hook_lengths(c(2, 3)), "weakly decreasing")
  expect_error(morie_hook_lengths(c(3, 0)), "must be positive")
})

# ------------------------------------------------------------------
# The hook length formula
# ------------------------------------------------------------------

test_that("the hook length formula matches Python", {
  ref <- list(list(c(3, 2), "5", "24"), list(c(2, 2), "2", "12"),
              list(c(3, 2, 1), "16", "45"), list(c(4, 3, 1), "70", "576"),
              list(c(5, 4, 3, 2, 1), "292864", "4465125"),
              list(c(4, 4, 4, 4), "24024", "870912000"))
  for (r in ref) {
    out <- morie_standard_tableaux_count(r[[1]])
    expect_equal(out$exact, r[[2]])
    expect_equal(out$exact_hook_product, r[[3]])
    expect_true(out$divides_exactly)
    expect_equal(out$remainder, 0)
  }
})

test_that("counts far past 2^53 match Python exactly, as strings", {
  # a double cannot hold these, so the comparison is decimal, not
  # numeric. This is the whole reason the bigint layer exists.
  out <- morie_standard_tableaux_count(10:1)
  expect_equal(out$n, 55)
  expect_equal(out$exact, "44261486084874072183645699204710400")
  expect_equal(out$exact_hook_product,
               "286849911214281324754704976473779296875")
  expect_equal(out$exact_factorial, paste0(
    "126964033536582759259651008475665169595803210514494367622758",
    "40000000000000"))
  expect_false(out$fits_double)

  out2 <- morie_standard_tableaux_count(c(15, 15, 15))
  expect_equal(out2$exact, "24584089974896430")
  expect_equal(out2$exact_hook_product,
               "4865838881472941301945316933632000000000")

  out3 <- morie_standard_tableaux_count(rep(8, 8))
  expect_equal(out3$n, 64)
  expect_equal(out3$exact, "22081374992701950398847674830857600")
  expect_equal(out3$exact_hook_product, paste0(
    "5746332926632566442385615219551212618645504000000000000"))
})

test_that("the hook product always divides n! exactly", {
  for (n in 1:10) {
    for (shape in morie_partitions_of(n)) {
      out <- morie_standard_tableaux_count(shape)
      expect_true(out$divides_exactly)
      expect_length(out$warnings, 0L)
    }
  }
})

test_that("a single row or column has exactly one tableau", {
  for (n in 1:8) {
    expect_equal(morie_standard_tableaux_count(n)$exact, "1")
    expect_equal(morie_standard_tableaux_count(rep(1L, n))$exact, "1")
  }
})

test_that("the RSK corollary sum of squares is n factorial", {
  # every permutation maps to a distinct (P, Q) pair of the same shape,
  # so the squares of the tableau counts must total n!
  for (n in 1:9) {
    total <- morie_bigint(0)
    for (shape in morie_partitions_of(n)) {
      f <- morie_bigint(morie_standard_tableaux_count(shape)$exact)
      total <- morie_big_add(total, morie_big_mul(f, f))
    }
    expect_equal(as.character(total),
                 as.character(morie_big_factorial(n)))
  }
})

# ------------------------------------------------------------------
# Robinson-Schensted
# ------------------------------------------------------------------

test_that("row insertion bumps as Python does", {
  # NOTE the row index is 1-based here and 0-based in Python, by
  # design; the anchors below are Python's plus one
  a <- morie_rsk_insert(list(c(1, 3, 5)), 4)
  expect_equal(a$tableau[[1]], c(1, 3, 4))
  expect_equal(a$tableau[[2]], 5)
  expect_equal(a$row, 2L)

  b <- morie_rsk_insert(list(c(1, 3, 5)), 6)
  expect_equal(b$tableau[[1]], c(1, 3, 5, 6))
  expect_equal(b$row, 1L)

  cc <- morie_rsk_insert(list(c(1, 3, 5), c(2, 4)), 2)
  expect_equal(cc$tableau[[1]], c(1, 2, 5))
  expect_equal(cc$tableau[[2]], c(2, 3))
  expect_equal(cc$tableau[[3]], 4)
  expect_equal(cc$row, 3L)
})

test_that("RSK matches Python on worked permutations", {
  o <- morie_rsk_correspondence(1:5)
  expect_equal(o$shape, 5L)
  expect_equal(o$longest_increasing, 5L)
  expect_equal(o$longest_decreasing, 1L)

  o2 <- morie_rsk_correspondence(5:1)
  expect_equal(o2$shape, rep(1L, 5))
  expect_equal(o2$longest_increasing, 1L)
  expect_equal(o2$longest_decreasing, 5L)

  o3 <- morie_rsk_correspondence(c(3, 1, 4, 2, 5))
  expect_equal(o3$shape, c(3L, 2L))
  expect_equal(o3$p_tableau[[1]], c(1, 2, 5))
  expect_equal(o3$p_tableau[[2]], c(3, 4))
  expect_equal(o3$q_tableau[[1]], c(1, 3, 5))
  expect_equal(o3$q_tableau[[2]], c(2, 4))

  o4 <- morie_rsk_correspondence(c(2, 7, 1, 5, 3, 6, 4))
  expect_equal(o4$shape, c(3L, 3L, 1L))
  expect_equal(o4$p_tableau[[1]], c(1, 3, 4))
  expect_equal(o4$p_tableau[[2]], c(2, 5, 6))
  expect_equal(o4$p_tableau[[3]], 7)
  expect_equal(o4$q_tableau[[1]], c(1, 2, 6))
  expect_equal(o4$q_tableau[[2]], c(3, 4, 7))
  expect_equal(o4$q_tableau[[3]], 5)
})

test_that("RSK round-trips every permutation of n <= 6", {
  perms <- function(v) {
    if (length(v) <= 1L) return(list(v))
    out <- list()
    for (i in seq_along(v)) {
      for (rest in perms(v[-i])) out[[length(out) + 1L]] <- c(v[i], rest)
    }
    out
  }
  for (n in 1:6) {
    for (w in perms(seq_len(n))) {
      o <- morie_rsk_correspondence(w)
      expect_true(o$same_shape)
      expect_equal(morie_rsk_inverse(o$p_tableau, o$q_tableau),
                   as.integer(w))
    }
  }
})

test_that("the shape gives the longest monotone subsequences", {
  lm <- function(w, increasing) {
    best <- 0L
    for (r in seq_along(w)) {
      cmb <- utils::combn(w, r, simplify = FALSE)
      for (cv in cmb) {
        ok <- if (increasing) all(diff(cv) > 0) else all(diff(cv) < 0)
        if (ok) best <- max(best, r)
      }
    }
    best
  }
  perms <- function(v) {
    if (length(v) <= 1L) return(list(v))
    out <- list()
    for (i in seq_along(v)) {
      for (rest in perms(v[-i])) out[[length(out) + 1L]] <- c(v[i], rest)
    }
    out
  }
  for (w in perms(1:5)) {
    o <- morie_rsk_correspondence(w)
    expect_equal(o$longest_increasing, lm(w, TRUE))
    expect_equal(o$longest_decreasing, lm(w, FALSE))
  }
})

test_that("RSK input validation", {
  expect_error(morie_rsk_correspondence(c(1, 1, 2)), "expected a permutation")
  expect_error(morie_rsk_inverse(list(c(1, 2)), list(1)), "same shape")
})

# ------------------------------------------------------------------
# Burnside
# ------------------------------------------------------------------

rot_group <- function(n) {
  lapply(seq.int(0L, n - 1L), function(s) (seq.int(0L, n - 1L) + s) %% n)
}

test_that("Burnside matches Python across cyclic groups", {
  ref <- list(
    c(1, 2, 2, 2), c(1, 3, 3, 3), c(2, 2, 3, 6), c(2, 3, 6, 12),
    c(3, 2, 4, 12), c(3, 3, 11, 33), c(4, 2, 6, 24), c(4, 3, 24, 96),
    c(5, 2, 8, 40), c(5, 3, 51, 255), c(6, 2, 14, 84), c(6, 3, 130, 780))
  for (r in ref) {
    out <- morie_burnside_orbit_count(rot_group(r[1]), r[2])
    expect_equal(out$orbits, r[3])
    expect_equal(out$sum_fixed, r[4])
    expect_true(out$divides_exactly)
  }
})

test_that("fixed points and cycle counts match Python", {
  out <- morie_burnside_orbit_count(rot_group(6), 2)
  expect_equal(out$cycle_counts, c(6L, 1L, 2L, 3L, 2L, 1L))
  expect_equal(out$fixed_points, c(64, 2, 4, 8, 4, 2))
  expect_equal(out$total_colourings, 64)
})

test_that("Burnside matches orbits counted directly", {
  for (n in 1:6) {
    for (k in 2:3) {
      g <- rot_group(n)
      grid <- as.matrix(expand.grid(rep(list(seq.int(0L, k - 1L)), n)))
      seen <- character(0)
      orbits <- 0L
      for (i in seq_len(nrow(grid))) {
        key <- paste(grid[i, ], collapse = ",")
        if (key %in% seen) next
        orbits <- orbits + 1L
        for (el in g) {
          seen <- c(seen, paste(grid[i, ][el + 1L], collapse = ","))
        }
      }
      expect_equal(morie_burnside_orbit_count(g, k)$orbits, orbits)
    }
  }
})

test_that("dividing by the group order is wrong", {
  # the naive "divide by the symmetry" fails whenever some arrangements
  # have symmetry of their own
  out <- morie_burnside_orbit_count(rot_group(4), 2)
  expect_equal(out$orbits, 6)
  expect_equal(out$naive_division, 4)
  expect_true(out$naive_is_wrong)
})

test_that("the trivial group leaves every colouring distinct", {
  out <- morie_burnside_orbit_count(list(0:2), 3)
  expect_equal(out$orbits, 27)
  expect_false(out$naive_is_wrong)
})

test_that("Burnside rejects a non-permutation", {
  expect_error(morie_burnside_orbit_count(list(c(0, 0)), 2),
               "not a permutation")
  expect_error(morie_burnside_orbit_count(list(0:1, 0:2), 2), "same set")
  expect_error(morie_burnside_orbit_count(list(), 2), "at least the identity")
})

# ------------------------------------------------------------------
# Necklaces
# ------------------------------------------------------------------

test_that("necklace counts match Python for k = 2, 3, 4", {
  ref <- list(c(2, 3, 4), c(3, 6, 10), c(4, 11, 24), c(6, 24, 70),
              c(8, 51, 208), c(14, 130, 700), c(20, 315, 2344),
              c(36, 834, 8230), c(60, 2195, 29144), c(108, 5934, 104968),
              c(188, 16107, 381304), c(352, 44368, 1398500))
  for (n in seq_along(ref)) {
    for (j in 1:3) {
      out <- morie_cycle_index_necklaces(n, j + 1L)
      expect_equal(out$count, ref[[n]][j])
      expect_true(out$agrees)
      expect_equal(out$count, out$direct_burnside)
    }
  }
})

test_that("the cyclic sum always divides by n", {
  for (n in 1:14) {
    for (k in c(2, 3, 5)) {
      expect_true(morie_cycle_index_necklaces(n, k)$divides_exactly)
    }
  }
})

test_that("one bead gives one orbit per colour", {
  for (k in c(1, 2, 5)) {
    expect_equal(morie_cycle_index_necklaces(1, k)$count, k)
  }
})

test_that("necklace validation", {
  expect_error(morie_cycle_index_necklaces(0, 2), "n must be positive")
  expect_error(morie_cycle_index_necklaces(3, 0), "k must be positive")
})
