# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for the Schabenberger & Gotway spatial shelf.
# Anchors are the values printed by the Python core to full double
# precision, and the Example 4.3 figures are the book's own.
#
# The fixture is built from a linear congruential generator using only
# exact integer arithmetic and a division by a power of two, so R doubles
# and Python integers agree bit for bit. No qnorm: R's AS241 and Python's
# Acklam inverse-normal disagree in the last ulp, which is enough on its
# own to break a ten-significant-digit anchor.

# Example 4.3, pp. 157 and 161. Z([3,4]) = 20 is the outlier and it
# contributes to four of the five lag classes.
EX_COORDS <- rbind(c(1, 1), c(1, 4), c(2, 2), c(3, 1), c(3, 4))
EX_Z <- c(1, 4, 2, 3, 20)

test_that("Matheron reproduces the book's Example 4.3", {
  out <- morie_matheron_estimator(EX_COORDS, EX_Z, exact = TRUE)
  expect_equal(round(out$gamma, 1), c(0.5, 65, 82, 74.5, 90.5))
  expect_equal(out$n_pairs, rep(2L, 5L))
})

test_that("Cressie-Hawkins reproduces the book's Example 4.3", {
  out <- morie_cressie_hawkins(EX_COORDS, EX_Z, exact = TRUE)
  # printed p. 161: 0.71, 38.14, 45.5, 52.2, 36.6
  expect_equal(round(out$gamma, 1), c(0.7, 38.1, 45.5, 52.2, 36.6))
})

test_that("the printed bias factor omits the third term", {
  # the derivation on p. 160 carries 0.457 + 0.494/|N| + 0.045/|N|^2 and
  # equation (4.26) then drops the last term. The worked example's 0.704
  # at |N(h)| = 2 settles which one the book actually evaluates.
  expect_equal(0.457 + 0.494 / 2, 0.704)
  plain <- morie_cressie_hawkins(EX_COORDS, EX_Z, exact = TRUE)
  full <- morie_cressie_hawkins(EX_COORDS, EX_Z, exact = TRUE,
                                full_correction = TRUE)
  expect_equal(round(plain$gamma[2], 2), 38.14)
  expect_false(isTRUE(all.equal(plain$gamma[2], full$gamma[2])))
})

test_that("the robust estimator suppresses but does not remove the outlier", {
  ch <- morie_cressie_hawkins(EX_COORDS, EX_Z, exact = TRUE)
  mat <- morie_matheron_estimator(EX_COORDS, EX_Z, exact = TRUE)
  expect_true(all(ch$gamma[-1] < mat$gamma[-1]))
  # its breakdown point is still zero, so the contamination survives
  expect_gt(ch$gamma[2], 30)
})

test_that("the Matheron variance is equation (4.25)", {
  out <- morie_matheron_estimator(EX_COORDS, EX_Z, exact = TRUE)
  expect_equal(out$variance, 2 * out$gamma^2 / out$n_pairs)
})

# --------------------------------------------------------------------
# shared fixture: a block-structured field with a real nugget and a real
# bounded sill, generated by exact arithmetic so both languages agree
# --------------------------------------------------------------------

schaben_fixture <- function(n = 120L, seed = 20260728) {
  s <- seed
  nxt <- function() {
    s <<- (1664525 * s + 1013904223) %% 4294967296
    (s + 0.5) / 4294967296
  }
  cell <- vapply(seq_len(25L), function(i) 2 * nxt() - 1, numeric(1))
  P <- matrix(0, n, 2L); z <- numeric(n)
  for (i in seq_len(n)) {
    x <- 10 * nxt(); y <- 10 * nxt()
    P[i, ] <- c(x, y)
    ci <- min(floor(x / 2), 4)
    cj <- min(floor(y / 2), 4)
    z[i] <- 3 * cell[ci * 5 + cj + 1] + 0.5 * (2 * nxt() - 1)
  }
  list(P = P, z = z)
}

test_that("the fixture is bit-identical across languages", {
  fx <- schaben_fixture()
  # if any of these drift, every anchor below is meaningless and the
  # fault is in the generator, not in the estimator
  expect_equal(sum(fx$P[, 1]), 593.73951468616724, tolerance = 1e-12)
  expect_equal(sum(fx$P[, 2]), 558.73202862218022, tolerance = 1e-12)
  expect_equal(sum(fx$z), 78.51558708306402, tolerance = 1e-12)
})

test_that("morie_matheron_estimator matches the Python core exactly", {
  fx <- schaben_fixture()
  out <- morie_matheron_estimator(fx$P, fx$z, bins = 8L)
  expect_equal(out$n_pairs, c(127L, 298L, 543L, 613L, 745L, 789L, 826L, 715L))
  expect_equal(out$gamma[1], 0.64405496505803128, tolerance = 1e-10)
  expect_equal(out$gamma[8], 2.1867423356721494, tolerance = 1e-10)
})

test_that("morie_cressie_hawkins matches the Python core exactly", {
  fx <- schaben_fixture()
  out <- morie_cressie_hawkins(fx$P, fx$z, bins = 8L)
  expect_equal(out$gamma[1], 0.27612658128944412, tolerance = 1e-10)
  expect_equal(out$gamma[8], 2.1073809858097867, tolerance = 1e-10)
})

test_that("the composite likelihood agrees with the Python core", {
  fx <- schaben_fixture()
  out <- morie_variogram_composite_likelihood(fx$P, fx$z)
  expect_true(out$converged)
  expect_equal(out$n_pairs, 120L * 119L / 2L)
  # both sides run Nelder-Mead on the same objective from the same start,
  # but R's simplex and the hand-written one differ in their contraction
  # schedule, so this is agreement on the ANSWER, not on the iterates
  expect_equal(out$sill, 2.6192442402537157, tolerance = 5e-3)
  expect_equal(out$range, 5.0048921397028545, tolerance = 5e-2)
})

test_that("the composite likelihood fits the cloud, not lag classes", {
  fx <- schaben_fixture()
  a <- morie_variogram_composite_likelihood(fx$P, fx$z)
  # no binning argument exists to change, which is the point of (4.44)
  expect_equal(a$n_pairs, length(fx$z) * (length(fx$z) - 1L) / 2L)
})

test_that("an unbounded variogram is reported, not returned as a sill", {
  # a pure linear trend makes the semivariance climb without settling
  # (eq 5.35), so no bounded model fits and the range runs away. Measured
  # on this design: range 1.02e11 against a largest separation of 13.
  s <- 20260728
  nxt <- function() {
    s <<- (1664525 * s + 1013904223) %% 4294967296
    (s + 0.5) / 4294967296
  }
  n <- 90L
  P <- matrix(0, n, 2L); z <- numeric(n)
  for (i in seq_len(n)) P[i, ] <- c(10 * nxt(), 10 * nxt())
  for (i in seq_len(n)) z[i] <- 2 * nxt() - 1 + 0.3 * P[i, 1]
  out <- morie_variogram_composite_likelihood(P, z)
  expect_false(out$converged)
  expect_true(grepl("bounded sill", out$diverged_note))
})

test_that("the Prasad-Rao correction only ever increases the error", {
  fx <- schaben_fixture()
  out <- morie_kriging_pred_error(fx$P, fx$z,
                                  rbind(c(5, 5), c(2, 8)))
  expect_true(all(out$mse >= out$mse_plugin - 1e-12))
  expect_true(all(out$correction >= -1e-12))
  expect_true(out$parameters_estimated)
})

test_that("known covariance parameters skip the estimation step", {
  fx <- schaben_fixture()
  out <- morie_kriging_pred_error(fx$P, fx$z, rbind(c(5, 5)),
                                  nugget = 0.3, psill = 2.0, rng = 5.0)
  expect_false(out$parameters_estimated)
  expect_equal(out$parameters$nugget, 0.3)
  expect_true(all(out$mse_plugin > 0))
})

test_that("kriging honours the data at an observed location", {
  fx <- schaben_fixture()
  out <- morie_kriging_pred_error(fx$P, fx$z, fx$P[4, , drop = FALSE],
                                  nugget = 1e-8, psill = 2.0, rng = 5.0)
  # with no nugget the predictor interpolates
  expect_lt(abs(out$prediction[1] - fx$z[4]), 0.05)
})

test_that("the two estimators agree when there is no contamination", {
  fx <- schaben_fixture()
  mat <- morie_matheron_estimator(fx$P, fx$z, bins = 8L)
  ch <- morie_cressie_hawkins(fx$P, fx$z, bins = 8L)
  # on a clean field the robust estimator buys nothing and the two track
  # each other; the ratio is reported so that is visible
  expect_true(all(abs(ch$ratio - 1) < 0.6))
})
