# Coverage tests for R/morin_native.R (Morin 2016, chapters 1-7).
# Expected values come from base R combinatorics and distributions.

test_that("counting: permutations, multinomials, stars and bars, hockey stick", {
  expect_equal(morie_partial_permutations(7, 3), factorial(7) / factorial(4))
  expect_equal(morie_partial_permutations(5, 0), 1)
  expect_error(morie_partial_permutations(3, 4), "n <= N")
  expect_equal(morie_multinomial_coef(c(2, 3, 4)), factorial(9) / (2 * 6 * 24))
  expect_equal(morie_multinomial_coef(c(2, 3), N = 7), factorial(7) / (2 * 6 * 2))
  expect_error(morie_multinomial_coef(c(4, 4), N = 7), "exceeds")
  expect_equal(morie_stars_bars(5, 3), choose(7, 2))
  expect_error(morie_stars_bars(2, 0), "N >= 1")
  h <- morie_hockey_stick(9, 4)
  expect_equal(h$sum, sum(choose(3:8, 3)))
  expect_equal(h$binomial, choose(9, 4))
  expect_true(h$holds)
  expect_error(morie_hockey_stick(3, 5), "k <= n")
})

test_that("probability rules and Bayes' theorem", {
  r <- morie_prob_rules(0.5, 0.4, 0.2)
  expect_equal(r$or_general, 0.7)
  expect_true(r$independent)
  expect_false(r$exclusive)
  expect_true(morie_prob_rules(0.3, 0.2, 0)$exclusive)
  expect_error(morie_prob_rules(0.3, 0.2, 0.25), "cannot exceed")
  b <- morie_bayes(c(0.01, 0.99), c(0.95, 0.05))
  pz <- 0.01 * 0.95 + 0.99 * 0.05
  expect_equal(b$p_z, pz, tolerance = 1e-12)
  expect_equal(b$posteriors, c(0.0095, 0.0495) / pz, tolerance = 1e-12)
  expect_error(morie_bayes(c(0.5, 0.4), c(1, 1)), "sum to 1")
  expect_error(morie_bayes(c(0.5, 0.5), c(0, 0)), "P\\(Z\\) = 0")
})

test_that("pmf moments, convolution and data variance", {
  v <- c(1, 2, 3, 6)
  p <- c(0.1, 0.4, 0.3, 0.2)
  m <- morie_pmf_moments(v, p)
  expect_equal(m$mean, sum(v * p), tolerance = 1e-12)
  expect_equal(m$variance, sum(p * (v - sum(v * p))^2), tolerance = 1e-12)
  expect_error(morie_pmf_moments(v, p * 2), "sum to 1")
  d6 <- rep(1 / 6, 6)
  cv <- morie_pmf_convolve(1:6, d6, 1:6, d6)
  expect_equal(cv$values, 2:12)
  expect_equal(cv$probs, c(1:6, 5:1) / 36, tolerance = 1e-12)
  expect_error(morie_pmf_convolve(1:2, c(0.5, 0.6), 1, 1), "sum to 1")
  x <- c(2, 4, 4, 5, 7, 9)
  dv <- morie_data_variance(x)
  expect_equal(dv$sample_variance, var(x), tolerance = 1e-12)
  expect_equal(dv$population_variance, var(x) * 5 / 6, tolerance = 1e-12)
  expect_error(morie_data_variance(1), "n >= 2")
})

test_that("standard deviation forms for scaled sums and means", {
  s <- morie_sd_forms(c(2, 3, 6), a = -4)
  expect_equal(s$scaled, 8)
  expect_equal(s$sd_sum, 7)
  expect_equal(s$sd_iid_sum, 2 * sqrt(3), tolerance = 1e-12)
  expect_equal(s$sd_mean, 2 / sqrt(3), tolerance = 1e-12)
  expect_equal(s$sd_mean_hetero, 7 / 3, tolerance = 1e-12)
  expect_error(morie_sd_forms(-1), ">= 0")
})

test_that("binomial, Poisson and hypergeometric distributions", {
  b <- morie_binomial_dist(12, 0.3, k = 4)
  expect_equal(b$pmf, dbinom(4, 12, 0.3), tolerance = 1e-12)
  expect_equal(b$variance, 12 * 0.21, tolerance = 1e-12)
  expect_equal(b$second_moment, 12 * 0.21 + 3.6^2, tolerance = 1e-12)
  expect_equal(morie_binomial_dist(2000, 0.4, k = 790)$pmf, dbinom(790, 2000, 0.4), tolerance = 1e-10)
  expect_equal(morie_binomial_dist(5, 1, k = 5)$pmf, 1)
  expect_equal(morie_binomial_dist(5, 0.5, k = 7)$pmf, 0)
  expect_error(morie_binomial_dist(5, 2), "p in")
  po <- morie_poisson_dist(3.5, k = 2)
  expect_equal(po$pmf, dpois(2, 3.5), tolerance = 1e-12)
  expect_equal(po$mean, 3.5, tolerance = 1e-12)
  expect_equal(po$variance, 3.5, tolerance = 1e-10)
  expect_equal(po$mode, 3)
  expect_equal(morie_poisson_dist(0, k = 0)$pmf, 1)
  expect_error(morie_poisson_dist(-1), ">= 0")
  hg <- morie_hypergeometric_dist(2, 20, 6, 5)
  expect_equal(hg$pmf, dhyper(2, 6, 14, 5), tolerance = 1e-12)
  expect_equal(hg$binomial_limit, dbinom(2, 5, 0.3), tolerance = 1e-12)
  expect_equal(morie_hypergeometric_dist(6, 20, 6, 5)$pmf, 0)
  expect_error(morie_hypergeometric_dist(1, 5, 6, 2), "K <= N")
})

test_that("exponential distribution and the crossing time", {
  e <- morie_exponential_dist(0.5, t = 2, dt = 0.01, rate_slow = 0.2, ratio = 3)
  expect_equal(e$density, dexp(2, 0.5), tolerance = 1e-12)
  expect_equal(e$interval_probability, dexp(2, 0.5) * 0.01, tolerance = 1e-12)
  expect_equal(e$variance, 4)
  expect_equal(e$crossing_time, log(3) / 0.3, tolerance = 1e-12)
  # the crossing time solves ratio exp(-lam t) = exp(-rate_slow t)
  tc <- e$crossing_time
  expect_equal(exp(-0.5 * tc) * 3, exp(-0.2 * tc), tolerance = 1e-12)
  expect_error(morie_exponential_dist(0.5, rate_slow = 0.6, ratio = 2), "lam > rate_slow")
  expect_error(morie_exponential_dist(0), "lambda > 0")
})

test_that("Gaussian approximations to the binomial and Poisson", {
  x <- c(-2, 0, 3)
  expect_equal(morie_gaussian_approx(x, n = 50), exp(-x^2 / 50) / sqrt(50 * pi), tolerance = 1e-12)
  expect_equal(morie_gaussian_approx(x, n = 50, form = "n"), dnorm(x, sd = sqrt(50 / 4)), tolerance = 1e-12)
  expect_equal(morie_gaussian_approx(x, n = 40, p = 0.3, form = "biased"), dnorm(x, sd = sqrt(8.4)), tolerance = 1e-12)
  expect_equal(morie_gaussian_approx(x, a = 6, form = "poisson"), dnorm(x, sd = sqrt(6)), tolerance = 1e-12)
  expect_error(morie_gaussian_approx(x, form = "poisson"), "a > 0")
  expect_error(morie_gaussian_approx(x, n = 5, p = 1, form = "biased"), "npq")
})

test_that("linear correlation model and least squares", {
  lc <- morie_linear_corr_model(0.8, 2, 1.5, mu_x = 1, mu_z = 0.5)
  sy <- sqrt(0.64 * 4 + 2.25)
  expect_equal(lc$sigma_y, sy, tolerance = 1e-12)
  expect_equal(lc$r, 1.6 / sy, tolerance = 1e-12)
  expect_equal(lc$mu_y, 1.3, tolerance = 1e-12)
  expect_equal(lc$excess_factor, sqrt((1 - 1.6 / sy) / (1 + 1.6 / sy)), tolerance = 1e-12)
  expect_error(morie_linear_corr_model(0, 1, 0), "degenerate")
  x <- c(1, 2, 3, 4, 6)
  y <- c(2.2, 2.9, 4.1, 4.8, 7.3)
  ls <- morie_least_squares(x, y)
  expect_equal(c(ls$B, ls$A), unname(coef(lm(y ~ x))), tolerance = 1e-12)
  expect_equal(ls$r, cor(x, y), tolerance = 1e-12)
  expect_equal(ls$C, unname(coef(lm(x ~ y))[2]), tolerance = 1e-12)
  expect_equal(ls$slope_product, cor(x, y)^2, tolerance = 1e-12)
  expect_equal(ls$S, sum(residuals(lm(y ~ x))^2), tolerance = 1e-12)
  expect_error(morie_least_squares(c(1, 1), c(1, 2)), "identical")
})

test_that("density of a sum by convolution", {
  g <- seq(-8, 8, by = 0.01)
  r <- morie_sum_density(g, dnorm(g, sd = 1), g, dnorm(g, sd = 2), z = 0.7, sigma_x = 1, sigma_y = 2)
  expect_equal(r$gaussian_closed_form, dnorm(0.7, sd = sqrt(5)), tolerance = 1e-12)
  # trapezoid on a 0.01 grid of a smooth product: error well below 1e-6
  expect_equal(r$density, r$gaussian_closed_form, tolerance = 1e-6)
  u <- seq(0, 1, by = 0.001)
  tri <- morie_sum_density(u, rep(1, length(u)), u, rep(1, length(u)), z = 0.5)
  # uniform + uniform: the integrand is a step, so the trapezoid rule adds
  # half of the last grid interval to the exact 0.5
  expect_equal(tri$density, 0.5 + 0.001 / 2, tolerance = 1e-12)
  expect_null(tri$gaussian_closed_form)
})

test_that("approximation ladder for (1 + a)^n", {
  r <- morie_approx_ladder(0.01, 100, order = 1, x = 2, delta = 1e-3, power = 3)
  expect_equal(r$exact, 1.01^100, tolerance = 1e-12)
  expect_equal(r$approx, exp(1), tolerance = 1e-12)
  expect_equal(r$validity, 0.01, tolerance = 1e-12)
  expect_equal(r$quotient, (2.001^3 - 8) / 1e-3, tolerance = 1e-9)
  expect_equal(r$derivative, 12)
  r2 <- morie_approx_ladder(0.01, 100, order = 2)
  expect_equal(r2$approx, exp(1 - 0.005), tolerance = 1e-12)
  expect_lt(abs(r2$approx - r2$exact), abs(r$approx - r$exact))
  expect_error(morie_approx_ladder(0.1, 2, order = 3), "order")
  expect_error(morie_approx_ladder(-1, 2), "a > -1")
})
