# SPDX-License-Identifier: AGPL-3.0-or-later
# Bad input meets a plain-language message naming the argument, not an
# R-internal one from deep in the body ("missing value where TRUE/FALSE
# needed", "non-numeric argument to binary operator", ...). The functions are
# the ones the round-8 bad-input sweep flagged; the inputs are the sweep's.

test_that(".morie_arg says what the argument must be and what arrived", {
  f <- function(epsilon) rmorie:::.morie_arg(epsilon, "n1")
  expect_error(f(NA), "`epsilon` must be a single number \\(got NA\\)")
  expect_error(f("abc"), "\\(got \"abc\"\\)")
  expect_error(f(NULL), "\\(got NULL\\)")
  expect_identical(f(2), 2)
  m <- matrix(1:4, 2)
  expect_identical(rmorie:::.morie_arg(m, "m"), m)              # nothing is coerced
  expect_error(rmorie:::.morie_arg(data.frame(), "m"), "data frame with 0 columns")
  expect_error(rmorie:::.morie_arg(2.5, "i1"), "single whole number")
  expect_error(rmorie:::.morie_arg(1, "cls:morie_spatial"), "a morie_spatial object")
  expect_error(rmorie:::.morie_arg(1, "nope"), "unknown argument kind")
})

test_that("the swept functions refuse bad input in plain words", {
  internal <- paste(c("missing value where TRUE/FALSE needed", "non-numeric argument",
                      "subscript out of bounds", "operator is invalid", "is not TRUE",
                      "requires numeric/complex", "replacement has length zero",
                      "could not find function", "invalid 'type'", "invalid 'times'",
                      "incorrect number of dimensions", "undefined columns",
                      "non-conformable", "object '.*' not found", "argument is not",
                      "invalid 'file'", "invalid 'length'", "invalid argument to unary"),
                    collapse = "|")
  fns <- c(
  "Advcmp",
  "AitchisonBiplot",
  "Amalgam",
  "AnisotropicLag",
  "ArmaAcf",
  "AtgpEndmembers",
  "BandPca",
  "Bfc2",
  "BiDomain",
  "BlockBootstrapGrid",
  "BreachDepressions",
  "BrownianMotion",
  "BudykoOlr",
  "BwAnalog",
  "BwLpDft",
  "BymVarianceFraction",
  "CalculateInteractionPower",
  "ClassicalMds",
  "CoherentFields",
  "CompositionalPielou",
  "Conti",
  "Contse",
  "Crp",
  "CrtnRoadNoise",
  "Dexp",
  "DftRI",
  "Dimensionality",
  "DiopT",
  "Disproportionality",
  "Dpineq",
  "FlameClustering",
  "FpeOrder",
  "GeodeticToEcef",
  "Ghosalbpcont",
  "Ghosalgpadaptthm",
  "Ghosalinfdimbvm",
  "Ghosalntrdef",
  "Gpreg",
  "HabitatSuitabilityIndex",
  "Hampw",
  "HannW",
  "HexagonalGridSample",
  "Hillq",
  "Infcrt",
  "Jarow",
  "Keggp",
  "Kpmnci",
  "KrigeLognormal",
  "Kvmse",
  "Lacgetg",
  "LemR",
  "LogitModeShares",
  "MatrixSymbolic",
  "McConvergence",
  "Mdppol",
  "Metapath",
  "MlFac",
  "Msm002",
  "Msm003",
  "Msm026",
  "Msm238",
  "Msm320",
  "Msm329",
  "MvNormDens",
  "Netbtw",
  "NmixtureModel",
  "Notch60",
  "OlcAssembly",
  "Otemd",
  "Otunbal",
  "PanterDiteBound",
  "Parseval",
  "PivotedCholesky",
  "Ppoclip",
  "Qbwcheck",
  "Qexp",
  "QrsHpLpTf",
  "RadiometricCorrection",
  "RasterMask",
  "RhoBounds",
  "Rmsnorm",
  "STCovariance",
  "SerialCorrelation",
  "Sfbnds",
  "SgcRidge",
  "Siaepi",
  "SimulateWalk",
  "SpatialKde",
  "Srfintp",
  "Srvcov2",
  "StGetisOrd",
  "StarmaForecast",
  "Survip",
  "SymbolicLimit",
  "ToroidalShiftTest",
  "Tqorth",
  "TruncatedProductPvalue",
  "Tukeyw",
  "UStatisticSensitivity",
  "Voronoi",
  "VoteTrading",
  "WindowFn",
  "alfRap",
  "alfSmax",
  "binomial_pmf_vector",
  "coefficient_of_variation",
  "d_to_r",
  "dwnmn",
  "e_value_hr",
  "factor_analysis_ml",
  "fit_stages",
  "folkrank",
  "fzmrb",
  "gamma_generation_time",
  "gibbons_are_scale_tests",
  "gwrsur",
  "m_step",
  "mafft_alignment",
  "matern52",
  "mhmcmc",
  "miexp",
  "morie_aci",
  "morie_alammar_instruction_data_template",
  "morie_alammar_recursive_chunking",
  "morie_approx_ladder",
  "morie_bayes_compare",
  "morie_boot_basic_ci",
  "morie_chemsc_hbond",
  "morie_conditional_prior_uniform",
  "morie_crsfmr_two_stage_attention",
  "morie_crypto_hqc_encaps",
  "morie_crypto_mlkem768_decaps",
  "morie_datasets_vancouver_community_centres",
  "morie_dp_kmeans",
  "morie_dsp_complex_cepstrum",
  "morie_dsp_hjorth",
  "morie_dsp_myopulse_rate",
  "morie_dsp_psd_to_db",
  "morie_dsp_slope_sign_changes",
  "morie_dsp_waveform_length_norm",
  "morie_esl_aic_score",
  "morie_evt_gev_trend",
  "morie_experiment_anova",
  "morie_fauzi_cov_surv_est2",
  "morie_fauzi_mrl_boundary_free",
  "morie_fauzi_quantile_bw_condition",
  "morie_fda_bic",
  "morie_funcal",
  "morie_genemt_ld_principal_components",
  "morie_geron_batch_size_heuristic",
  "morie_geron_conv_output_size",
  "morie_geron_t5",
  "morie_geron_transformer",
  "morie_geron_vq_vae",
  "morie_goodman_minimum",
  "morie_greg_variance",
  "morie_hadcrut_weights",
  "morie_impFB",
  "morie_inverse_haldane",
  "morie_iv_2sls",
  "morie_jsonlt_validate",
  "morie_kamath_ch9_flamingo_factorized",
  "morie_kamath_rtd_loss",
  "morie_karpV_depth",
  "morie_laniyonu_actuarial_risk_disparity",
  "morie_latin_square",
  "morie_logistic_effects",
  "morie_longrd_align",
  "morie_madn",
  "morie_matching_common_support",
  "morie_metropolis_hastings",
  "morie_mhatf_multi_head_attention_full",
  "morie_momento_task_mask",
  "morie_multi_head_attention_full",
  "morie_mxetA",
  "morie_otis_make_pair_b",
  "morie_otis_rc_trends",
  "morie_otis_rctrnd",
  "morie_otis_tps_per_region_rollup",
  "morie_pmpfit_tail",
  "morie_poissp_rho_bounds",
  "morie_ramsey_lower_bound_probabilistic",
  "morie_rank_exact_null",
  "morie_rdp_sampled_gaussian",
  "morie_scfhop",
  "morie_sd_forms",
  "morie_sentpc_unescape_whitespace",
  "morie_sgtcoml",
  "morie_siu_report_url",
  "morie_siu_strip_boilerplate",
  "morie_slbpdg_weights",
  "morie_snmcox_blip_down",
  "morie_spatial_cluster",
  "morie_spatial_transform",
  "morie_spatial_voting_smacof_unfolding",
  "morie_survnnr_baseline_hazard",
  "morie_tlhaltm",
  "morie_tps_analyze_bicycletheft",
  "morie_tps_analyze_one",
  "morie_tps_analyze_robbery",
  "morie_tps_category_correlation_matrix",
  "morie_tps_getis_ord_g_star",
  "morie_tps_local_morans_i",
  "morie_tps_temporal_summary",
  "morie_tqang",
  "morie_transformer_block",
  "morie_trfbl_transformer_block",
  "morie_trmRew_normal_form",
  "morie_turboquant_angle_quantization",
  "morie_unclr_alr_inv",
  "morie_vepan_pick",
  "morie_weight_ow",
  "morie_wrd2v_subsample_probability",
  "morie_zonal_ebm",
  "mrm_clt_demo",
  "mrm_tps_load_hawkes_refit",
  "mrm_uof_region_locality",
  "naive_reuse",
  "permutations_count",
  "policy_walk",
  "rRD",
  "relative_utility",
  "sasimi_nearest_neighbours",
  "sgtcoml",
  "sgthits",
  "singular_value_adjust",
  "skewness_coeff",
  "spcsr",
  "spnsr",
  "spsph",
  "subscale_er_ave",
  "surepi_c3_ultra",
  "swpower",
  "to_approx_dp")
  inputs <- list(NULL_ = NULL, NA_ = NA, chr = "abc", emptydf = data.frame())
  ns <- asNamespace("rmorie")
  # a valid-looking string sends these two over the network: their checks are
  # covered by the NULL/NA/data-frame cases in the .morie_arg test above
  for (fn in fns) {
    f <- get(fn, envir = ns)
    for (nm in names(inputs)) {
      msg <- tryCatch({
        setTimeLimit(elapsed = 20, transient = TRUE)
        on.exit(setTimeLimit(elapsed = Inf), add = TRUE)
        suppressWarnings(suppressMessages(if (is.null(inputs[[nm]])) f(NULL) else f(inputs[[nm]])))
        ""
      }, error = function(e) conditionMessage(e))
      expect_false(grepl(internal, msg), info = sprintf("%s(%s): %s", fn, nm, msg))
    }
  }
})
