x <- c(2.5, -1, 4.25, 0.5, 3, -2.75, 1.5, 6)
d <- x - mean(x)

test_that("moments recompute", {
  expect_equal(sample_mean(x)$value, sum(x) / 8)
  expect_equal(raw_moment(x, 3)$value, sum(x^3) / 8)
  expect_equal(central_moment(x, 4)$value, sum(d^4) / 8)
  expect_equal(skewness_coeff(x)$value, (sum(d^3) / 8) / (sum(d^2) / 8)^1.5)
  expect_equal(kurtosis_coeff(c(-1, 1))$value, -2)
  expect_equal(rms_value(c(3, -4))$value, sqrt(12.5))
  y <- x + 0.1 * (0:7)
  expect_equal(mean_squared_error(x, y)$value, sum((0.1 * (0:7))^2) / 8)
  expect_equal(root_mean_squared_error(x, y)$value, sqrt(sum((0.1 * (0:7))^2) / 8))
  S <- rbind(x, x / 2, x - 1)
  expect_equal(unname(ensemble_average(S)$value), (x + x / 2 + x - 1) / 3)
  expect_equal(unname(ensemble_variance(S)$value), apply(S, 2, function(v) sum((v - mean(v))^2) / 2))
  expect_equal(esl_total_sum_squares(x)$estimate, sum(d^2))
  expect_equal(popvar(1e9 + x)$variance, sum(d^2) / 8, tolerance = 1e-6)
})
