# Ghosal shelf: R-side tests + 10-significant-digit Python parity
# anchors (generated by the morie Python gh_* modules on fixed data).

test_that("stick breaking and hazard invert exactly (eq 3.2-3.3)", {
  V <- c(1/2, 1/3, 1/4, 1/5)
  p <- morie_gh_stick_breaking(V)
  expect_equal(p, c(1/2, 1/6, 1/12, 1/20), tolerance = 1e-12)
  expect_equal(morie_gh_discrete_hazard(p), V, tolerance = 1e-12)
})

test_that("DP posterior moments match anchors (eq 4.10-4.12)", {
  r <- morie_gh_dp_posterior(0.5, 2, 6, 8)
  expect_equal(r$mean, 0.7, tolerance = 1e-9)
  expect_equal(r$var, 0.01909090909, tolerance = 1e-9)
})

test_that("distinct-value moments match anchors (Prop 4.8)", {
  r <- morie_gh_dp_ndistinct(50, 2)
  expect_equal(r$mean, 7.037626363, tolerance = 1e-8)
  expect_equal(r$var, 4.535557558, tolerance = 1e-8)
})

test_that("eps-DP support size matches anchor (Prop 4.20)", {
  expect_equal(morie_gh_eps_dp_size(0.01, 2), 11.21034037,
               tolerance = 1e-8)
})

test_that("median-Dirichlet CDF matches anchor (Thm 4.25)", {
  expect_equal(morie_gh_dp_median_cdf(0.7, 5), 0.8395312413,
               tolerance = 1e-8)
})

test_that("Ewens and PY EPPF log-probabilities match anchors", {
  expect_equal(morie_gh_ewens_log(c(1, 2, 0, 0, 1), 1.5),
               -3.375389163, tolerance = 1e-8)
  expect_equal(morie_gh_py_eppf_log(c(3, 2, 1), 0.25, 1),
               -5.96639091, tolerance = 1e-8)
  # PY at d = 0 reduces to the DP EPPF
  dp <- morie_gh_py_eppf_log(c(2, 1), 0, 1)
  expect_equal(exp(dp), 1/6, tolerance = 1e-12)
})

test_that("white-noise conjugate posterior matches anchors (eq 8.1)", {
  r <- morie_gh_wn_posterior(c(0.8, -0.3), 200, c(1, 0.04))
  expect_equal(r$mean, c(0.7960199005, -0.2666666667),
               tolerance = 1e-9)
  expect_equal(r$var, c(0.004975124378, 0.004444444444),
               tolerance = 1e-9)
})

test_that("Polya tree posterior density matches anchor (eq 3.23)", {
  d <- c(0.31, 0.29, 0.33, 0.27, 0.62, 0.15)
  expect_equal(morie_gh_pt_posterior_density(0.3, d, 4L),
               2.303030303, tolerance = 1e-8)
  # no data: prior mean density is exactly 1
  expect_equal(morie_gh_pt_posterior_density(0.3, numeric(0), 4L),
               1, tolerance = 1e-12)
})

test_that("divergences match anchors (App B)", {
  P <- c(0.5, 0.3, 0.2)
  Q <- c(0.25, 0.5, 0.25)
  expect_equal(morie_gh_hellinger2(P, Q), 0.03554147704,
               tolerance = 1e-9)
  expect_equal(morie_gh_kl(P, Q), 0.1486971929, tolerance = 1e-9)
  expect_equal(morie_gh_renyi(P, Q, 0.5), 0.07237690245,
               tolerance = 1e-9)
  # Pinsker
  tv <- 0.5 * sum(abs(P - Q))
  expect_lte(tv^2, morie_gh_kl(P, Q) / 2)
})

test_that("Dirichlet moments match anchors (App G)", {
  r <- morie_gh_dirichlet_moments(c(2, 3, 5), 1, 2)
  expect_equal(r$mean, 0.2, tolerance = 1e-12)
  expect_equal(r$var, 0.01454545455, tolerance = 1e-9)
  expect_equal(r$cov, -0.005454545455, tolerance = 1e-9)
})

test_that("CRM/NCRM Laplace functionals match anchors (App J)", {
  expect_equal(morie_gh_crm_laplace_gamma(1, 2), 1.386294361,
               tolerance = 1e-8)
  expect_equal(morie_gh_ncrm_laplace(1, 2, 1), 0.2824535639,
               tolerance = 1e-9)
})

test_that("predictive weights and IBP dish count are exact", {
  r <- morie_gh_dp_predictive(2, 3)
  expect_equal(r$weight_fresh, 0.4, tolerance = 1e-12)
  expect_equal(r$weight_per_obs, 0.2, tolerance = 1e-12)
  expect_equal(morie_gh_ibp_expected_dishes(4, 3),
               3 * (1 + 1/2 + 1/3 + 1/4), tolerance = 1e-12)
})
