# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cross-language parity for matroids and combinatorial optimisation.
#
# Every anchor below was generated by running the Python core and
# copying the printed output, never recalled. Four hand-typed anchors
# earlier in this series were wrong while the code was right, so the
# rule now is: anchors come from a run.
#
# R indexes from 1 and Python from 0, so ground sets and vertex labels
# are shifted by one. The VALUES -- ranks, counts, weights, matching
# and cover sizes, flows -- are index-free and must agree exactly.

NON_MAT_GROUND <- c(1L, 2L, 3L)
NON_MAT_IND <- list(integer(0), 1L, 2L, 3L, c(2L, 3L))
K4E <- list(c(1, 2), c(2, 3), c(3, 4), c(4, 1), c(1, 3))

# ------------------------------------------------------------------
# Matroid axioms
# ------------------------------------------------------------------

test_that("uniform matroids satisfy both axioms", {
  for (n in 1:5) {
    for (k in 0:n) {
      u <- morie_uniform_matroid(n, k)
      expect_true(morie_is_matroid(u$ground, u$independent)$is_matroid)
    }
  }
})

test_that("graphic matroids satisfy both axioms", {
  g <- morie_graphic_matroid(K4E, 4)
  expect_true(morie_is_matroid(g$ground, g$independent)$is_matroid)
  g2 <- morie_graphic_matroid(list(c(1, 2), c(3, 4)), 4)
  expect_true(morie_is_matroid(g2$ground, g2$independent)$is_matroid)
})

test_that("a non-matroid is identified with its witness", {
  out <- morie_is_matroid(NON_MAT_GROUND, NON_MAT_IND)
  expect_false(out$is_matroid)
  expect_true(out$hereditary)
  expect_false(out$exchange)
  expect_equal(out$exchange_violation[[1]], 1L)
  expect_equal(out$exchange_violation[[2]], c(2L, 3L))
  expect_true(any(grepl("Exchange fails", out$warnings)))
})

test_that("a non-hereditary system is rejected before exchange", {
  out <- morie_is_matroid(c(1L, 2L), list(integer(0), c(1L, 2L)))
  expect_false(out$hereditary)
  expect_false(out$is_matroid)
  expect_true(any(grepl("Heredity fails", out$warnings)))
})

# ------------------------------------------------------------------
# Structure: matches the Python core exactly
# ------------------------------------------------------------------

test_that("U(2,4) structure matches Python", {
  u <- morie_uniform_matroid(4, 2)
  expect_equal(morie_matroid_rank(u$ground, u$independent), 2L)
  expect_equal(length(morie_matroid_bases(u$ground, u$independent)), 6L)
  circ <- morie_matroid_circuits(u$ground, u$independent)
  expect_equal(length(circ), 4L)
  expect_true(all(vapply(circ, length, integer(1)) == 3L))
})

test_that("the graphic matroid on K4 minus an edge matches Python", {
  g <- morie_graphic_matroid(K4E, 4)
  expect_equal(length(g$ground), 5L)
  expect_equal(length(g$independent), 24L)
  expect_equal(morie_matroid_rank(g$ground, g$independent), 3L)
  expect_equal(length(morie_matroid_bases(g$ground, g$independent)), 8L)
})

test_that("all bases have the same size", {
  g <- morie_graphic_matroid(K4E, 4)
  sizes <- unique(vapply(morie_matroid_bases(g$ground, g$independent),
                         length, integer(1)))
  expect_equal(length(sizes), 1L)
})

test_that("duality is an involution", {
  for (p in list(c(3, 1), c(4, 2), c(4, 3), c(5, 2))) {
    u <- morie_uniform_matroid(p[1], p[2])
    d <- morie_matroid_dual(u$ground, u$independent)
    dd <- morie_matroid_dual(u$ground, d)
    a <- sort(vapply(dd, function(s) paste(s, collapse = ","), character(1)))
    b <- sort(vapply(u$independent, function(s) paste(sort(s), collapse = ","),
                     character(1)))
    expect_equal(a, b)
  }
})

test_that("the dual of a uniform matroid has complementary rank", {
  for (p in list(c(4, 1), c(4, 2), c(5, 3), c(6, 2))) {
    u <- morie_uniform_matroid(p[1], p[2])
    d <- morie_matroid_dual(u$ground, u$independent)
    expect_equal(morie_matroid_rank(u$ground, d), p[1] - p[2])
  }
})

test_that("the dual of a matroid is a matroid", {
  for (p in list(c(3, 1), c(4, 2), c(5, 2))) {
    u <- morie_uniform_matroid(p[1], p[2])
    d <- morie_matroid_dual(u$ground, u$independent)
    expect_true(morie_is_matroid(u$ground, d)$is_matroid)
  }
})

# ------------------------------------------------------------------
# Rado-Edmonds, both directions
# ------------------------------------------------------------------

test_that("greedy is optimal on uniform matroids", {
  set.seed(11)
  for (p in list(c(4, 2), c(5, 2), c(5, 3), c(6, 3))) {
    u <- morie_uniform_matroid(p[1], p[2])
    for (i in seq_len(30L)) {
      w <- sample.int(16, p[1], replace = TRUE) - 6
      g <- morie_greedy_independent_set(u$ground, u$independent, w)
      b <- morie_brute_force_max_weight(u$ground, u$independent, w)
      expect_equal(g$weight, b$weight)
    }
  }
})

test_that("greedy is optimal on the graphic matroid", {
  set.seed(12)
  g <- morie_graphic_matroid(K4E, 4)
  for (i in seq_len(80L)) {
    w <- sample.int(20, 5, replace = TRUE)
    got <- morie_greedy_independent_set(g$ground, g$independent, w)
    best <- morie_brute_force_max_weight(g$ground, g$independent, w)
    expect_equal(got$weight, best$weight)
  }
})

test_that("greedy FAILS on a system that is not a matroid", {
  # the converse half of Rado-Edmonds; a test of only the forward
  # direction would pass on code with no notion of a matroid
  set.seed(13)
  failures <- 0L
  for (i in seq_len(200L)) {
    w <- sample.int(10, 3, replace = TRUE)
    g <- morie_greedy_independent_set(NON_MAT_GROUND, NON_MAT_IND, w)
    b <- morie_brute_force_max_weight(NON_MAT_GROUND, NON_MAT_IND, w)
    expect_lte(g$weight, b$weight)
    if (g$weight < b$weight) failures <- failures + 1L
  }
  expect_gt(failures, 0L)
})

test_that("the concrete losing weighting matches Python", {
  g <- morie_greedy_independent_set(NON_MAT_GROUND, NON_MAT_IND, c(5, 3, 3))
  b <- morie_brute_force_max_weight(NON_MAT_GROUND, NON_MAT_IND, c(5, 3, 3))
  expect_equal(g$set, 1L)          # Python [0], shifted
  expect_equal(g$weight, 5)
  expect_equal(b$set, c(2L, 3L))   # Python [1, 2], shifted
  expect_equal(b$weight, 6)
})

test_that("greedy never takes a negative-weight element", {
  u <- morie_uniform_matroid(4, 3)
  g <- morie_greedy_independent_set(u$ground, u$independent,
                                    c(-1, -2, 5, -3))
  expect_equal(g$set, 3L)          # Python [2], shifted
})

# ------------------------------------------------------------------
# Minimum spanning tree
# ------------------------------------------------------------------

test_that("the MST matches Python on the reference graph", {
  m <- morie_minimum_spanning_tree(K4E, 4, c(4, 1, 3, 2, 5))
  expect_equal(m$weight, 6)
  expect_true(m$connected)
  expect_equal(m$n_edges_chosen, 3L)
  expect_equal(sort(m$tree_edges), c(2L, 3L, 4L))   # Python [1,3,2] shifted
})

test_that("the MST equals exhaustive search over spanning trees", {
  set.seed(14)
  brute <- function(edges, n, w) {
    best <- Inf
    cmb <- utils::combn(length(edges), n - 1, simplify = FALSE)
    for (c in cmb) {
      uf <- seq_len(n)
      find <- function(x) {
        while (uf[x] != x) x <- uf[x]
        x
      }
      ok <- TRUE
      for (i in c) {
        a <- find(edges[[i]][1]); b <- find(edges[[i]][2])
        if (a == b) { ok <- FALSE; break }
        uf[a] <- b
      }
      if (ok) best <- min(best, sum(w[c]))
    }
    best
  }
  checked <- 0L
  for (i in seq_len(40L)) {
    n <- sample(3:5, 1)
    alle <- utils::combn(n, 2, simplify = FALSE)
    keep <- which(stats::runif(length(alle)) < 0.8)
    if (length(keep) < n - 1) next
    edges <- alle[keep]
    w <- sample.int(20, length(edges), replace = TRUE)
    got <- morie_minimum_spanning_tree(edges, n, w)
    if (!got$connected) next
    expect_equal(got$weight, brute(edges, n, w))
    checked <- checked + 1L
  }
  expect_gt(checked, 10L)
})

test_that("the MST is exactly greedy on the cycle matroid", {
  set.seed(15)
  g <- morie_graphic_matroid(K4E, 4)
  for (i in seq_len(80L)) {
    w <- sample.int(20, 5, replace = TRUE)
    mst <- morie_minimum_spanning_tree(K4E, 4, w)
    M <- max(w) + 1
    got <- morie_greedy_independent_set(g$ground, g$independent, M - w)
    expect_equal(sum(w[got$set]), mst$weight)
  }
})

test_that("a disconnected graph gives a forest and says so", {
  out <- morie_minimum_spanning_tree(list(c(1, 2), c(3, 4)), 4, c(1, 1))
  expect_false(out$connected)
  expect_equal(out$n_components, 2L)
  expect_true(any(grepl("spanning forest", out$warnings)))
})

# ------------------------------------------------------------------
# Konig and Hall
# ------------------------------------------------------------------

test_that("Konig matches Python on the reference graph", {
  E <- list(c(1, 1), c(1, 2), c(2, 2), c(3, 1), c(3, 3))
  out <- morie_konig_theorem(3, 3, E)
  expect_equal(out$matching_size, 3L)
  expect_equal(out$cover_size, 3L)
  expect_true(out$cover_is_valid)
  expect_true(out$konig_holds)
})

test_that("Konig holds on random bipartite graphs", {
  set.seed(16)
  for (i in seq_len(80L)) {
    ln <- sample.int(5, 1); rn <- sample.int(5, 1)
    E <- list()
    for (a in seq_len(ln)) for (b in seq_len(rn)) {
      if (stats::runif(1) < 0.5) E[[length(E) + 1L]] <- c(a, b)
    }
    out <- morie_konig_theorem(ln, rn, E)
    expect_true(out$konig_holds)
    expect_equal(out$matching_size, out$cover_size)
  }
})

test_that("the Konig cover really covers every edge", {
  E <- list(c(1, 1), c(1, 2), c(2, 2), c(3, 1), c(3, 3))
  out <- morie_konig_theorem(3, 3, E)
  for (e in E) {
    expect_true(e[1] %in% out$cover_left || e[2] %in% out$cover_right)
  }
  expect_equal(out$n_uncovered, 0L)
})

test_that("Hall matches Python on the failing example", {
  out <- morie_hall_condition(3, 2, list(c(1, 1), c(2, 1), c(3, 2)))
  expect_false(out$holds)
  expect_equal(out$violating_set, c(1L, 2L))   # Python [0,1] shifted
  expect_equal(out$deficiency, 1L)
  expect_false(out$perfect_on_left)
})

test_that("Hall agrees with the matching everywhere", {
  set.seed(17)
  for (i in seq_len(100L)) {
    ln <- sample.int(5, 1); rn <- sample.int(5, 1)
    E <- list()
    for (a in seq_len(ln)) for (b in seq_len(rn)) {
      if (stats::runif(1) < 0.5) E[[length(E) + 1L]] <- c(a, b)
    }
    expect_true(morie_hall_condition(ln, rn, E)$agrees_with_matching)
  }
})

test_that("Hall holds on a complete bipartite graph", {
  E <- list()
  for (a in 1:3) for (b in 1:3) E[[length(E) + 1L]] <- c(a, b)
  out <- morie_hall_condition(3, 3, E)
  expect_true(out$holds)
  expect_equal(out$matching_size, 3L)
  expect_null(out$violating_set)
})

# ------------------------------------------------------------------
# Max-flow min-cut
# ------------------------------------------------------------------

test_that("the classic network matches Python", {
  C <- matrix(c(0, 3, 2, 0,
                0, 0, 5, 2,
                0, 0, 0, 3,
                0, 0, 0, 0), 4, 4, byrow = TRUE)
  out <- morie_max_flow_min_cut(C, 1, 4)
  expect_equal(out$flow, 5)
  expect_equal(out$cut_capacity, 5)
  expect_equal(out$min_cut_source_side, 1L)     # Python [0] shifted
  expect_equal(length(out$cut_edges), 2L)
  expect_true(out$theorem_holds)
})

test_that("max flow equals min cut on random networks", {
  set.seed(18)
  for (i in seq_len(80L)) {
    n <- sample(3:5, 1)
    C <- matrix(0, n, n)
    for (a in seq_len(n)) for (b in seq_len(n)) {
      if (a != b && stats::runif(1) < 0.5) {
        C[a, b] <- sample.int(15, 1)
      }
    }
    out <- morie_max_flow_min_cut(C, 1, n)
    expect_true(out$theorem_holds)
    expect_lt(out$residual_gap, 1e-9)
  }
})

test_that("the cut capacity is recomputed from the original capacities", {
  set.seed(19)
  n <- 5L
  C <- matrix(0, n, n)
  for (a in seq_len(n)) for (b in seq_len(n)) {
    if (a != b && stats::runif(1) < 0.6) C[a, b] <- sample.int(10, 1)
  }
  out <- morie_max_flow_min_cut(C, 1, n)
  S <- out$min_cut_source_side
  manual <- sum(C[S, setdiff(seq_len(n), S), drop = FALSE])
  expect_equal(manual, out$cut_capacity)
})

test_that("a disconnected sink has zero flow", {
  C <- matrix(c(0, 5, 0, 0, 0, 0, 0, 0, 0), 3, 3, byrow = TRUE)
  out <- morie_max_flow_min_cut(C, 1, 3)
  expect_equal(out$flow, 0)
  expect_equal(out$cut_capacity, 0)
})

test_that("matroid and optimisation input validation", {
  expect_error(morie_uniform_matroid(-1, 2), "non-negative")
  expect_error(morie_minimum_spanning_tree(list(c(1, 2)), 2, c(1, 2)),
               "weights has length")
  expect_error(morie_minimum_spanning_tree(list(c(1, 5)), 2, 1), "leaves 1")
  expect_error(morie_max_flow_min_cut(matrix(-1, 2, 2)), "non-negative")
  expect_error(morie_max_flow_min_cut(matrix(0, 2, 2), 1, 1), "must differ")
  expect_error(morie_bipartite_matching(2, 2, list(c(5, 1))), "left endpoint")
})
