// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// morie_crypto_liboqs_available
bool morie_crypto_liboqs_available();
RcppExport SEXP _morie_morie_crypto_liboqs_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_liboqs_available());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_liboqs_version
std::string morie_crypto_liboqs_version();
RcppExport SEXP _morie_morie_crypto_liboqs_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_liboqs_version());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mlkem768_keygen
Rcpp::List morie_crypto_mlkem768_keygen();
RcppExport SEXP _morie_morie_crypto_mlkem768_keygen() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mlkem768_keygen());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mlkem768_encaps
Rcpp::List morie_crypto_mlkem768_encaps(SEXP pk_sxp);
RcppExport SEXP _morie_morie_crypto_mlkem768_encaps(SEXP pk_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pk_sxp(pk_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mlkem768_encaps(pk_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mlkem768_decaps
SEXP morie_crypto_mlkem768_decaps(SEXP sk_sxp, SEXP ct_sxp);
RcppExport SEXP _morie_morie_crypto_mlkem768_decaps(SEXP sk_sxpSEXP, SEXP ct_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sk_sxp(sk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ct_sxp(ct_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mlkem768_decaps(sk_sxp, ct_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mldsa65_keygen
Rcpp::List morie_crypto_mldsa65_keygen();
RcppExport SEXP _morie_morie_crypto_mldsa65_keygen() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mldsa65_keygen());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mldsa65_sign
SEXP morie_crypto_mldsa65_sign(SEXP sk_sxp, SEXP message_sxp);
RcppExport SEXP _morie_morie_crypto_mldsa65_sign(SEXP sk_sxpSEXP, SEXP message_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sk_sxp(sk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type message_sxp(message_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mldsa65_sign(sk_sxp, message_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mldsa65_verify
bool morie_crypto_mldsa65_verify(SEXP pk_sxp, SEXP message_sxp, SEXP signature_sxp);
RcppExport SEXP _morie_morie_crypto_mldsa65_verify(SEXP pk_sxpSEXP, SEXP message_sxpSEXP, SEXP signature_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pk_sxp(pk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type message_sxp(message_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type signature_sxp(signature_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mldsa65_verify(pk_sxp, message_sxp, signature_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_sodium_available
bool morie_crypto_sodium_available();
RcppExport SEXP _morie_morie_crypto_sodium_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_sodium_available());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_sodium_version
std::string morie_crypto_sodium_version();
RcppExport SEXP _morie_morie_crypto_sodium_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_sodium_version());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_chacha20poly1305_encrypt
SEXP morie_crypto_chacha20poly1305_encrypt(SEXP key_sxp, SEXP nonce_sxp, SEXP plaintext_sxp, SEXP aad_sxp);
RcppExport SEXP _morie_morie_crypto_chacha20poly1305_encrypt(SEXP key_sxpSEXP, SEXP nonce_sxpSEXP, SEXP plaintext_sxpSEXP, SEXP aad_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type key_sxp(key_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nonce_sxp(nonce_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type plaintext_sxp(plaintext_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type aad_sxp(aad_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_chacha20poly1305_encrypt(key_sxp, nonce_sxp, plaintext_sxp, aad_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_chacha20poly1305_decrypt
SEXP morie_crypto_chacha20poly1305_decrypt(SEXP key_sxp, SEXP nonce_sxp, SEXP ct_with_tag_sxp, SEXP aad_sxp);
RcppExport SEXP _morie_morie_crypto_chacha20poly1305_decrypt(SEXP key_sxpSEXP, SEXP nonce_sxpSEXP, SEXP ct_with_tag_sxpSEXP, SEXP aad_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type key_sxp(key_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nonce_sxp(nonce_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ct_with_tag_sxp(ct_with_tag_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type aad_sxp(aad_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_chacha20poly1305_decrypt(key_sxp, nonce_sxp, ct_with_tag_sxp, aad_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_hkdf_sha256
SEXP morie_crypto_hkdf_sha256(SEXP ikm_sxp, SEXP length_sxp, SEXP salt_sxp, SEXP info_sxp);
RcppExport SEXP _morie_morie_crypto_hkdf_sha256(SEXP ikm_sxpSEXP, SEXP length_sxpSEXP, SEXP salt_sxpSEXP, SEXP info_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ikm_sxp(ikm_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type length_sxp(length_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type salt_sxp(salt_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type info_sxp(info_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_hkdf_sha256(ikm_sxp, length_sxp, salt_sxp, info_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_random_bytes
SEXP morie_crypto_random_bytes(int n);
RcppExport SEXP _morie_morie_crypto_random_bytes(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_random_bytes(n));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_lms_cpp
List morie_dsp_lms_cpp(NumericVector x, NumericVector d, int order, double mu);
RcppExport SEXP _morie_morie_dsp_lms_cpp(SEXP xSEXP, SEXP dSEXP, SEXP orderSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_lms_cpp(x, d, order, mu));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_nlms_cpp
List morie_dsp_nlms_cpp(NumericVector x, NumericVector d, int order, double mu, double eps);
RcppExport SEXP _morie_morie_dsp_nlms_cpp(SEXP xSEXP, SEXP dSEXP, SEXP orderSEXP, SEXP muSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_nlms_cpp(x, d, order, mu, eps));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_rls_cpp
List morie_dsp_rls_cpp(NumericVector x, NumericVector d, int order, double lam, double delta);
RcppExport SEXP _morie_morie_dsp_rls_cpp(SEXP xSEXP, SEXP dSEXP, SEXP orderSEXP, SEXP lamSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_rls_cpp(x, d, order, lam, delta));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_cross_correlation_cpp
NumericVector morie_dsp_cross_correlation_cpp(NumericVector x, NumericVector y, int max_lag);
RcppExport SEXP _morie_morie_dsp_cross_correlation_cpp(SEXP xSEXP, SEXP ySEXP, SEXP max_lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type max_lag(max_lagSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_cross_correlation_cpp(x, y, max_lag));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_median_filter_cpp
NumericVector morie_dsp_median_filter_cpp(NumericVector x, int kernel_size);
RcppExport SEXP _morie_morie_dsp_median_filter_cpp(SEXP xSEXP, SEXP kernel_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_size(kernel_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_median_filter_cpp(x, kernel_size));
    return rcpp_result_gen;
END_RCPP
}
// morie_normal_pdf_cpp
NumericVector morie_normal_pdf_cpp(NumericVector x, double mean, double sd);
RcppExport SEXP _morie_morie_normal_pdf_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_normal_pdf_cpp(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// morie_mean_cpp
double morie_mean_cpp(NumericVector x);
RcppExport SEXP _morie_morie_mean_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_mean_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// morie_var_cpp
double morie_var_cpp(NumericVector x, int ddof);
RcppExport SEXP _morie_morie_var_cpp(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_var_cpp(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// morie_cor_pearson_cpp
double morie_cor_pearson_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _morie_morie_cor_pearson_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(morie_cor_pearson_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_exp_const_cpp
double morie_hawkes_ll_exp_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double beta);
RcppExport SEXP _morie_morie_hawkes_ll_exp_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_exp_const_cpp(t, T_horizon, a0, eta, beta));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_weibull_const_cpp
double morie_hawkes_ll_weibull_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double alpha, double lam);
RcppExport SEXP _morie_morie_hawkes_ll_weibull_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_weibull_const_cpp(t, T_horizon, a0, eta, alpha, lam));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_lomax_const_cpp
double morie_hawkes_ll_lomax_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double alpha, double c);
RcppExport SEXP _morie_morie_hawkes_ll_lomax_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_lomax_const_cpp(t, T_horizon, a0, eta, alpha, c));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_gamma_const_cpp
double morie_hawkes_ll_gamma_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double alpha, double beta);
RcppExport SEXP _morie_morie_hawkes_ll_gamma_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_gamma_const_cpp(t, T_horizon, a0, eta, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_kernel_density_cpp
NumericVector morie_hawkes_kernel_density_cpp(NumericVector u, std::string kind, NumericVector psi);
RcppExport SEXP _morie_morie_hawkes_kernel_density_cpp(SEXP uSEXP, SEXP kindSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_kernel_density_cpp(u, kind, psi));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_kernel_cdf_cpp
NumericVector morie_hawkes_kernel_cdf_cpp(NumericVector u, std::string kind, NumericVector psi);
RcppExport SEXP _morie_morie_hawkes_kernel_cdf_cpp(SEXP uSEXP, SEXP kindSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_kernel_cdf_cpp(u, kind, psi));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_pair_excitation_sum_cpp
NumericVector morie_hawkes_pair_excitation_sum_cpp(NumericVector t, double eta, std::string kind, NumericVector psi);
RcppExport SEXP _morie_morie_hawkes_pair_excitation_sum_cpp(SEXP tSEXP, SEXP etaSEXP, SEXP kindSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_pair_excitation_sum_cpp(t, eta, kind, psi));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_baseline_integral_cpp
double morie_hawkes_baseline_integral_cpp(double T_horizon, NumericVector alpha, int n_grid);
RcppExport SEXP _morie_morie_hawkes_baseline_integral_cpp(SEXP T_horizonSEXP, SEXP alphaSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_baseline_integral_cpp(T_horizon, alpha, n_grid));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_get_
std::string morie_http_get_(std::string url, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _morie_morie_http_get_(SEXP urlSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_get_(url, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_get_bytes_
Rcpp::RawVector morie_http_get_bytes_(std::string url, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _morie_morie_http_get_bytes_(SEXP urlSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_get_bytes_(url, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_post_
std::string morie_http_post_(std::string url, std::string body, std::string content_type, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _morie_morie_http_post_(SEXP urlSEXP, SEXP bodySEXP, SEXP content_typeSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< std::string >::type body(bodySEXP);
    Rcpp::traits::input_parameter< std::string >::type content_type(content_typeSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_post_(url, body, content_type, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_get_with_status_
Rcpp::List morie_http_get_with_status_(std::string url, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _morie_morie_http_get_with_status_(SEXP urlSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_get_with_status_(url, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_post_with_status_
Rcpp::List morie_http_post_with_status_(std::string url, std::string body, std::string content_type, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _morie_morie_http_post_with_status_(SEXP urlSEXP, SEXP bodySEXP, SEXP content_typeSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< std::string >::type body(bodySEXP);
    Rcpp::traits::input_parameter< std::string >::type content_type(content_typeSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_post_with_status_(url, body, content_type, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_curl_version_
std::string morie_http_curl_version_();
RcppExport SEXP _morie_morie_http_curl_version_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_http_curl_version_());
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_mahalanobis_pairs_cpp
arma::mat morie_matching_mahalanobis_pairs_cpp(const arma::mat& X_t, const arma::mat& X_c, const arma::mat& S_inv);
RcppExport SEXP _morie_morie_matching_mahalanobis_pairs_cpp(SEXP X_tSEXP, SEXP X_cSEXP, SEXP S_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_t(X_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_c(X_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_inv(S_invSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_mahalanobis_pairs_cpp(X_t, X_c, S_inv));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_euclidean_pairs_cpp
arma::mat morie_matching_euclidean_pairs_cpp(const arma::mat& X_t, const arma::mat& X_c);
RcppExport SEXP _morie_morie_matching_euclidean_pairs_cpp(SEXP X_tSEXP, SEXP X_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_t(X_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_c(X_cSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_euclidean_pairs_cpp(X_t, X_c));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_nn_select_cpp
List morie_matching_nn_select_cpp(const arma::mat& D, bool with_replacement, double caliper, int n_neighbors);
RcppExport SEXP _morie_morie_matching_nn_select_cpp(SEXP DSEXP, SEXP with_replacementSEXP, SEXP caliperSEXP, SEXP n_neighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< bool >::type with_replacement(with_replacementSEXP);
    Rcpp::traits::input_parameter< double >::type caliper(caliperSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_nn_select_cpp(D, with_replacement, caliper, n_neighbors));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_cem_strata_cpp
IntegerVector morie_matching_cem_strata_cpp(const IntegerMatrix& X_binned);
RcppExport SEXP _morie_morie_matching_cem_strata_cpp(SEXP X_binnedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type X_binned(X_binnedSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_cem_strata_cpp(X_binned));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_abadie_imbens_kernel_cpp
double morie_matching_abadie_imbens_kernel_cpp(NumericVector y, IntegerVector t, IntegerVector treated_pos, IntegerVector control_pos);
RcppExport SEXP _morie_morie_matching_abadie_imbens_kernel_cpp(SEXP ySEXP, SEXP tSEXP, SEXP treated_posSEXP, SEXP control_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treated_pos(treated_posSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type control_pos(control_posSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_abadie_imbens_kernel_cpp(y, t, treated_pos, control_pos));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_nominate_iterate_cpp
Rcpp::List morie_spatial_nominate_iterate_cpp(arma::mat votes, arma::mat X, arma::vec w, arma::mat nv, arma::mat mid, double beta, int max_iter);
RcppExport SEXP _morie_morie_spatial_nominate_iterate_cpp(SEXP votesSEXP, SEXP XSEXP, SEXP wSEXP, SEXP nvSEXP, SEXP midSEXP, SEXP betaSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type votes(votesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mid(midSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_nominate_iterate_cpp(votes, X, w, nv, mid, beta, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_emirt_theta_update_cpp
arma::mat morie_spatial_emirt_theta_update_cpp(arma::mat theta, const arma::mat& a, const arma::vec& d, const arma::mat& votes);
RcppExport SEXP _morie_morie_spatial_emirt_theta_update_cpp(SEXP thetaSEXP, SEXP aSEXP, SEXP dSEXP, SEXP votesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type votes(votesSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_emirt_theta_update_cpp(theta, a, d, votes));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_smacof_step_cpp
Rcpp::List morie_spatial_smacof_step_cpp(arma::mat X, const arma::mat& D, arma::mat W);
RcppExport SEXP _morie_morie_spatial_smacof_step_cpp(SEXP XSEXP, SEXP DSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_smacof_step_cpp(X, D, W));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_classical_mds_cpp
Rcpp::List morie_spatial_classical_mds_cpp(const arma::mat& D, int n_dims);
RcppExport SEXP _morie_morie_spatial_classical_mds_cpp(SEXP DSEXP, SEXP n_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type n_dims(n_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_classical_mds_cpp(D, n_dims));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_wordfish_omega_update_cpp
arma::vec morie_spatial_wordfish_omega_update_cpp(const arma::mat& dtm, const arma::vec& psi, const arma::vec& alpha, const arma::vec& beta, arma::vec omega);
RcppExport SEXP _morie_morie_spatial_wordfish_omega_update_cpp(SEXP dtmSEXP, SEXP psiSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_wordfish_omega_update_cpp(dtm, psi, alpha, beta, omega));
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get
std::string siu_http_get(std::string url, int timeout_s);
RcppExport SEXP _morie_siu_http_get(SEXP urlSEXP, SEXP timeout_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get(url, timeout_s));
    return rcpp_result_gen;
END_RCPP
}
// siu_curl_version
std::string siu_curl_version();
RcppExport SEXP _morie_siu_curl_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(siu_curl_version());
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get_many
Rcpp::CharacterVector siu_http_get_many(Rcpp::CharacterVector urls, int concurrency, int timeout_s, double rate_rps, int max_retries);
RcppExport SEXP _morie_siu_http_get_many(SEXP urlsSEXP, SEXP concurrencySEXP, SEXP timeout_sSEXP, SEXP rate_rpsSEXP, SEXP max_retriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< int >::type concurrency(concurrencySEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< double >::type rate_rps(rate_rpsSEXP);
    Rcpp::traits::input_parameter< int >::type max_retries(max_retriesSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get_many(urls, concurrency, timeout_s, rate_rps, max_retries));
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get_many_with_status
Rcpp::List siu_http_get_many_with_status(Rcpp::CharacterVector urls, int concurrency, int timeout_s, double rate_rps, int max_retries);
RcppExport SEXP _morie_siu_http_get_many_with_status(SEXP urlsSEXP, SEXP concurrencySEXP, SEXP timeout_sSEXP, SEXP rate_rpsSEXP, SEXP max_retriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< int >::type concurrency(concurrencySEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< double >::type rate_rps(rate_rpsSEXP);
    Rcpp::traits::input_parameter< int >::type max_retries(max_retriesSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get_many_with_status(urls, concurrency, timeout_s, rate_rps, max_retries));
    return rcpp_result_gen;
END_RCPP
}
// siu_parse_report
Rcpp::CharacterVector siu_parse_report(std::string html, int drid, std::string url);
RcppExport SEXP _morie_siu_parse_report(SEXP htmlSEXP, SEXP dridSEXP, SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type html(htmlSEXP);
    Rcpp::traits::input_parameter< int >::type drid(dridSEXP);
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_parse_report(html, drid, url));
    return rcpp_result_gen;
END_RCPP
}
// siu_parse_news
Rcpp::CharacterVector siu_parse_news(std::string html, int nrid, std::string url);
RcppExport SEXP _morie_siu_parse_news(SEXP htmlSEXP, SEXP nridSEXP, SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type html(htmlSEXP);
    Rcpp::traits::input_parameter< int >::type nrid(nridSEXP);
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_parse_news(html, nrid, url));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_morie_morie_crypto_liboqs_available", (DL_FUNC) &_morie_morie_crypto_liboqs_available, 0},
    {"_morie_morie_crypto_liboqs_version", (DL_FUNC) &_morie_morie_crypto_liboqs_version, 0},
    {"_morie_morie_crypto_mlkem768_keygen", (DL_FUNC) &_morie_morie_crypto_mlkem768_keygen, 0},
    {"_morie_morie_crypto_mlkem768_encaps", (DL_FUNC) &_morie_morie_crypto_mlkem768_encaps, 1},
    {"_morie_morie_crypto_mlkem768_decaps", (DL_FUNC) &_morie_morie_crypto_mlkem768_decaps, 2},
    {"_morie_morie_crypto_mldsa65_keygen", (DL_FUNC) &_morie_morie_crypto_mldsa65_keygen, 0},
    {"_morie_morie_crypto_mldsa65_sign", (DL_FUNC) &_morie_morie_crypto_mldsa65_sign, 2},
    {"_morie_morie_crypto_mldsa65_verify", (DL_FUNC) &_morie_morie_crypto_mldsa65_verify, 3},
    {"_morie_morie_crypto_sodium_available", (DL_FUNC) &_morie_morie_crypto_sodium_available, 0},
    {"_morie_morie_crypto_sodium_version", (DL_FUNC) &_morie_morie_crypto_sodium_version, 0},
    {"_morie_morie_crypto_chacha20poly1305_encrypt", (DL_FUNC) &_morie_morie_crypto_chacha20poly1305_encrypt, 4},
    {"_morie_morie_crypto_chacha20poly1305_decrypt", (DL_FUNC) &_morie_morie_crypto_chacha20poly1305_decrypt, 4},
    {"_morie_morie_crypto_hkdf_sha256", (DL_FUNC) &_morie_morie_crypto_hkdf_sha256, 4},
    {"_morie_morie_crypto_random_bytes", (DL_FUNC) &_morie_morie_crypto_random_bytes, 1},
    {"_morie_morie_dsp_lms_cpp", (DL_FUNC) &_morie_morie_dsp_lms_cpp, 4},
    {"_morie_morie_dsp_nlms_cpp", (DL_FUNC) &_morie_morie_dsp_nlms_cpp, 5},
    {"_morie_morie_dsp_rls_cpp", (DL_FUNC) &_morie_morie_dsp_rls_cpp, 5},
    {"_morie_morie_dsp_cross_correlation_cpp", (DL_FUNC) &_morie_morie_dsp_cross_correlation_cpp, 3},
    {"_morie_morie_dsp_median_filter_cpp", (DL_FUNC) &_morie_morie_dsp_median_filter_cpp, 2},
    {"_morie_morie_normal_pdf_cpp", (DL_FUNC) &_morie_morie_normal_pdf_cpp, 3},
    {"_morie_morie_mean_cpp", (DL_FUNC) &_morie_morie_mean_cpp, 1},
    {"_morie_morie_var_cpp", (DL_FUNC) &_morie_morie_var_cpp, 2},
    {"_morie_morie_cor_pearson_cpp", (DL_FUNC) &_morie_morie_cor_pearson_cpp, 2},
    {"_morie_morie_hawkes_ll_exp_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_exp_const_cpp, 5},
    {"_morie_morie_hawkes_ll_weibull_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_weibull_const_cpp, 6},
    {"_morie_morie_hawkes_ll_lomax_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_lomax_const_cpp, 6},
    {"_morie_morie_hawkes_ll_gamma_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_gamma_const_cpp, 6},
    {"_morie_morie_hawkes_kernel_density_cpp", (DL_FUNC) &_morie_morie_hawkes_kernel_density_cpp, 3},
    {"_morie_morie_hawkes_kernel_cdf_cpp", (DL_FUNC) &_morie_morie_hawkes_kernel_cdf_cpp, 3},
    {"_morie_morie_hawkes_pair_excitation_sum_cpp", (DL_FUNC) &_morie_morie_hawkes_pair_excitation_sum_cpp, 4},
    {"_morie_morie_hawkes_baseline_integral_cpp", (DL_FUNC) &_morie_morie_hawkes_baseline_integral_cpp, 3},
    {"_morie_morie_http_get_", (DL_FUNC) &_morie_morie_http_get_, 5},
    {"_morie_morie_http_get_bytes_", (DL_FUNC) &_morie_morie_http_get_bytes_, 5},
    {"_morie_morie_http_post_", (DL_FUNC) &_morie_morie_http_post_, 7},
    {"_morie_morie_http_get_with_status_", (DL_FUNC) &_morie_morie_http_get_with_status_, 5},
    {"_morie_morie_http_post_with_status_", (DL_FUNC) &_morie_morie_http_post_with_status_, 7},
    {"_morie_morie_http_curl_version_", (DL_FUNC) &_morie_morie_http_curl_version_, 0},
    {"_morie_morie_matching_mahalanobis_pairs_cpp", (DL_FUNC) &_morie_morie_matching_mahalanobis_pairs_cpp, 3},
    {"_morie_morie_matching_euclidean_pairs_cpp", (DL_FUNC) &_morie_morie_matching_euclidean_pairs_cpp, 2},
    {"_morie_morie_matching_nn_select_cpp", (DL_FUNC) &_morie_morie_matching_nn_select_cpp, 4},
    {"_morie_morie_matching_cem_strata_cpp", (DL_FUNC) &_morie_morie_matching_cem_strata_cpp, 1},
    {"_morie_morie_matching_abadie_imbens_kernel_cpp", (DL_FUNC) &_morie_morie_matching_abadie_imbens_kernel_cpp, 4},
    {"_morie_morie_spatial_nominate_iterate_cpp", (DL_FUNC) &_morie_morie_spatial_nominate_iterate_cpp, 7},
    {"_morie_morie_spatial_emirt_theta_update_cpp", (DL_FUNC) &_morie_morie_spatial_emirt_theta_update_cpp, 4},
    {"_morie_morie_spatial_smacof_step_cpp", (DL_FUNC) &_morie_morie_spatial_smacof_step_cpp, 3},
    {"_morie_morie_spatial_classical_mds_cpp", (DL_FUNC) &_morie_morie_spatial_classical_mds_cpp, 2},
    {"_morie_morie_spatial_wordfish_omega_update_cpp", (DL_FUNC) &_morie_morie_spatial_wordfish_omega_update_cpp, 5},
    {"_morie_siu_http_get", (DL_FUNC) &_morie_siu_http_get, 2},
    {"_morie_siu_curl_version", (DL_FUNC) &_morie_siu_curl_version, 0},
    {"_morie_siu_http_get_many", (DL_FUNC) &_morie_siu_http_get_many, 5},
    {"_morie_siu_http_get_many_with_status", (DL_FUNC) &_morie_siu_http_get_many_with_status, 5},
    {"_morie_siu_parse_report", (DL_FUNC) &_morie_siu_parse_report, 3},
    {"_morie_siu_parse_news", (DL_FUNC) &_morie_siu_parse_news, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_morie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
