// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// morie_crypto_sha256_native
Rcpp::RawVector morie_crypto_sha256_native(SEXP data);
RcppExport SEXP _rmorie_morie_crypto_sha256_native(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_sha256_native(data));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_sha256_hex_native
std::string morie_crypto_sha256_hex_native(SEXP data);
RcppExport SEXP _rmorie_morie_crypto_sha256_hex_native(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_sha256_hex_native(data));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_hmac_sha256_native
Rcpp::RawVector morie_crypto_hmac_sha256_native(SEXP key, SEXP msg);
RcppExport SEXP _rmorie_morie_crypto_hmac_sha256_native(SEXP keySEXP, SEXP msgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type key(keySEXP);
    Rcpp::traits::input_parameter< SEXP >::type msg(msgSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_hmac_sha256_native(key, msg));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_pbkdf2_sha256_native
Rcpp::RawVector morie_crypto_pbkdf2_sha256_native(SEXP password, SEXP salt, int iterations, int dklen);
RcppExport SEXP _rmorie_morie_crypto_pbkdf2_sha256_native(SEXP passwordSEXP, SEXP saltSEXP, SEXP iterationsSEXP, SEXP dklenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type password(passwordSEXP);
    Rcpp::traits::input_parameter< SEXP >::type salt(saltSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type dklen(dklenSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_pbkdf2_sha256_native(password, salt, iterations, dklen));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_blake2b_native
Rcpp::RawVector morie_crypto_blake2b_native(SEXP data, int outlen, SEXP key);
RcppExport SEXP _rmorie_morie_crypto_blake2b_native(SEXP dataSEXP, SEXP outlenSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type outlen(outlenSEXP);
    Rcpp::traits::input_parameter< SEXP >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_blake2b_native(data, outlen, key));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_argon2_native
Rcpp::RawVector morie_crypto_argon2_native(SEXP password, SEXP salt, int memory, int passes, int parallelism, int tag_length, std::string variant, SEXP secret, SEXP associated);
RcppExport SEXP _rmorie_morie_crypto_argon2_native(SEXP passwordSEXP, SEXP saltSEXP, SEXP memorySEXP, SEXP passesSEXP, SEXP parallelismSEXP, SEXP tag_lengthSEXP, SEXP variantSEXP, SEXP secretSEXP, SEXP associatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type password(passwordSEXP);
    Rcpp::traits::input_parameter< SEXP >::type salt(saltSEXP);
    Rcpp::traits::input_parameter< int >::type memory(memorySEXP);
    Rcpp::traits::input_parameter< int >::type passes(passesSEXP);
    Rcpp::traits::input_parameter< int >::type parallelism(parallelismSEXP);
    Rcpp::traits::input_parameter< int >::type tag_length(tag_lengthSEXP);
    Rcpp::traits::input_parameter< std::string >::type variant(variantSEXP);
    Rcpp::traits::input_parameter< SEXP >::type secret(secretSEXP);
    Rcpp::traits::input_parameter< SEXP >::type associated(associatedSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_argon2_native(password, salt, memory, passes, parallelism, tag_length, variant, secret, associated));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_liboqs_available
bool morie_crypto_liboqs_available();
RcppExport SEXP _rmorie_morie_crypto_liboqs_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_liboqs_available());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_liboqs_version
std::string morie_crypto_liboqs_version();
RcppExport SEXP _rmorie_morie_crypto_liboqs_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_liboqs_version());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mlkem768_keygen
Rcpp::List morie_crypto_mlkem768_keygen();
RcppExport SEXP _rmorie_morie_crypto_mlkem768_keygen() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mlkem768_keygen());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mlkem768_encaps
Rcpp::List morie_crypto_mlkem768_encaps(SEXP pk_sxp);
RcppExport SEXP _rmorie_morie_crypto_mlkem768_encaps(SEXP pk_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pk_sxp(pk_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mlkem768_encaps(pk_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mlkem768_decaps
SEXP morie_crypto_mlkem768_decaps(SEXP sk_sxp, SEXP ct_sxp);
RcppExport SEXP _rmorie_morie_crypto_mlkem768_decaps(SEXP sk_sxpSEXP, SEXP ct_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sk_sxp(sk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ct_sxp(ct_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mlkem768_decaps(sk_sxp, ct_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mldsa65_keygen
Rcpp::List morie_crypto_mldsa65_keygen();
RcppExport SEXP _rmorie_morie_crypto_mldsa65_keygen() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mldsa65_keygen());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mldsa65_sign
SEXP morie_crypto_mldsa65_sign(SEXP sk_sxp, SEXP message_sxp);
RcppExport SEXP _rmorie_morie_crypto_mldsa65_sign(SEXP sk_sxpSEXP, SEXP message_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sk_sxp(sk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type message_sxp(message_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mldsa65_sign(sk_sxp, message_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_mldsa65_verify
bool morie_crypto_mldsa65_verify(SEXP pk_sxp, SEXP message_sxp, SEXP signature_sxp);
RcppExport SEXP _rmorie_morie_crypto_mldsa65_verify(SEXP pk_sxpSEXP, SEXP message_sxpSEXP, SEXP signature_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pk_sxp(pk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type message_sxp(message_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type signature_sxp(signature_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_mldsa65_verify(pk_sxp, message_sxp, signature_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_slhdsa128s_keygen
SEXP morie_crypto_slhdsa128s_keygen();
RcppExport SEXP _rmorie_morie_crypto_slhdsa128s_keygen() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_slhdsa128s_keygen());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_slhdsa128s_sign
SEXP morie_crypto_slhdsa128s_sign(SEXP sk_sxp, SEXP message_sxp);
RcppExport SEXP _rmorie_morie_crypto_slhdsa128s_sign(SEXP sk_sxpSEXP, SEXP message_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sk_sxp(sk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type message_sxp(message_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_slhdsa128s_sign(sk_sxp, message_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_slhdsa128s_verify
SEXP morie_crypto_slhdsa128s_verify(SEXP pk_sxp, SEXP message_sxp, SEXP signature_sxp);
RcppExport SEXP _rmorie_morie_crypto_slhdsa128s_verify(SEXP pk_sxpSEXP, SEXP message_sxpSEXP, SEXP signature_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pk_sxp(pk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type message_sxp(message_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type signature_sxp(signature_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_slhdsa128s_verify(pk_sxp, message_sxp, signature_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_hqc128_keygen
SEXP morie_crypto_hqc128_keygen();
RcppExport SEXP _rmorie_morie_crypto_hqc128_keygen() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_hqc128_keygen());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_hqc128_encaps
SEXP morie_crypto_hqc128_encaps(SEXP pk_sxp);
RcppExport SEXP _rmorie_morie_crypto_hqc128_encaps(SEXP pk_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pk_sxp(pk_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_hqc128_encaps(pk_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_hqc128_decaps
SEXP morie_crypto_hqc128_decaps(SEXP sk_sxp, SEXP ct_sxp);
RcppExport SEXP _rmorie_morie_crypto_hqc128_decaps(SEXP sk_sxpSEXP, SEXP ct_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sk_sxp(sk_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ct_sxp(ct_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_hqc128_decaps(sk_sxp, ct_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_sodium_available
bool morie_crypto_sodium_available();
RcppExport SEXP _rmorie_morie_crypto_sodium_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_sodium_available());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_sodium_version
std::string morie_crypto_sodium_version();
RcppExport SEXP _rmorie_morie_crypto_sodium_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_crypto_sodium_version());
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_chacha20poly1305_encrypt
SEXP morie_crypto_chacha20poly1305_encrypt(SEXP key_sxp, SEXP nonce_sxp, SEXP plaintext_sxp, SEXP aad_sxp);
RcppExport SEXP _rmorie_morie_crypto_chacha20poly1305_encrypt(SEXP key_sxpSEXP, SEXP nonce_sxpSEXP, SEXP plaintext_sxpSEXP, SEXP aad_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type key_sxp(key_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nonce_sxp(nonce_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type plaintext_sxp(plaintext_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type aad_sxp(aad_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_chacha20poly1305_encrypt(key_sxp, nonce_sxp, plaintext_sxp, aad_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_chacha20poly1305_decrypt
SEXP morie_crypto_chacha20poly1305_decrypt(SEXP key_sxp, SEXP nonce_sxp, SEXP ct_with_tag_sxp, SEXP aad_sxp);
RcppExport SEXP _rmorie_morie_crypto_chacha20poly1305_decrypt(SEXP key_sxpSEXP, SEXP nonce_sxpSEXP, SEXP ct_with_tag_sxpSEXP, SEXP aad_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type key_sxp(key_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nonce_sxp(nonce_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ct_with_tag_sxp(ct_with_tag_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type aad_sxp(aad_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_chacha20poly1305_decrypt(key_sxp, nonce_sxp, ct_with_tag_sxp, aad_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_hkdf_sha256
SEXP morie_crypto_hkdf_sha256(SEXP ikm_sxp, SEXP length_sxp, SEXP salt_sxp, SEXP info_sxp);
RcppExport SEXP _rmorie_morie_crypto_hkdf_sha256(SEXP ikm_sxpSEXP, SEXP length_sxpSEXP, SEXP salt_sxpSEXP, SEXP info_sxpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ikm_sxp(ikm_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type length_sxp(length_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type salt_sxp(salt_sxpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type info_sxp(info_sxpSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_hkdf_sha256(ikm_sxp, length_sxp, salt_sxp, info_sxp));
    return rcpp_result_gen;
END_RCPP
}
// morie_crypto_random_bytes
SEXP morie_crypto_random_bytes(int n);
RcppExport SEXP _rmorie_morie_crypto_random_bytes(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_crypto_random_bytes(n));
    return rcpp_result_gen;
END_RCPP
}
// morie_twfe_demean_cpp
arma::mat morie_twfe_demean_cpp(arma::mat M, const arma::ivec& g1, const arma::ivec& g2, int K1, int K2, double tol, int max_iter);
RcppExport SEXP _rmorie_morie_twfe_demean_cpp(SEXP MSEXP, SEXP g1SEXP, SEXP g2SEXP, SEXP K1SEXP, SEXP K2SEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< int >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< int >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_twfe_demean_cpp(M, g1, g2, K1, K2, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// morie_digest_native
Rcpp::RawVector morie_digest_native(SEXP data, int algo, double seed);
RcppExport SEXP _rmorie_morie_digest_native(SEXP dataSEXP, SEXP algoSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type algo(algoSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_digest_native(data, algo, seed));
    return rcpp_result_gen;
END_RCPP
}
// morie_digest2int_native
Rcpp::IntegerVector morie_digest2int_native(Rcpp::CharacterVector x, int seed);
RcppExport SEXP _rmorie_morie_digest2int_native(SEXP xSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_digest2int_native(x, seed));
    return rcpp_result_gen;
END_RCPP
}
// morie_aes_ecb_native
Rcpp::RawVector morie_aes_ecb_native(Rcpp::RawVector key, Rcpp::RawVector data, bool encrypt);
RcppExport SEXP _rmorie_morie_aes_ecb_native(SEXP keySEXP, SEXP dataSEXP, SEXP encryptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type key(keySEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type encrypt(encryptSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_aes_ecb_native(key, data, encrypt));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_lms_cpp
List morie_dsp_lms_cpp(NumericVector x, NumericVector d, int order, double mu);
RcppExport SEXP _rmorie_morie_dsp_lms_cpp(SEXP xSEXP, SEXP dSEXP, SEXP orderSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_lms_cpp(x, d, order, mu));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_nlms_cpp
List morie_dsp_nlms_cpp(NumericVector x, NumericVector d, int order, double mu, double eps);
RcppExport SEXP _rmorie_morie_dsp_nlms_cpp(SEXP xSEXP, SEXP dSEXP, SEXP orderSEXP, SEXP muSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_nlms_cpp(x, d, order, mu, eps));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_rls_cpp
List morie_dsp_rls_cpp(NumericVector x, NumericVector d, int order, double lam, double delta);
RcppExport SEXP _rmorie_morie_dsp_rls_cpp(SEXP xSEXP, SEXP dSEXP, SEXP orderSEXP, SEXP lamSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_rls_cpp(x, d, order, lam, delta));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_cross_correlation_cpp
NumericVector morie_dsp_cross_correlation_cpp(NumericVector x, NumericVector y, int max_lag);
RcppExport SEXP _rmorie_morie_dsp_cross_correlation_cpp(SEXP xSEXP, SEXP ySEXP, SEXP max_lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type max_lag(max_lagSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_cross_correlation_cpp(x, y, max_lag));
    return rcpp_result_gen;
END_RCPP
}
// morie_dsp_median_filter_cpp
NumericVector morie_dsp_median_filter_cpp(NumericVector x, int kernel_size);
RcppExport SEXP _rmorie_morie_dsp_median_filter_cpp(SEXP xSEXP, SEXP kernel_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_size(kernel_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_dsp_median_filter_cpp(x, kernel_size));
    return rcpp_result_gen;
END_RCPP
}
// morie_normal_pdf_cpp
NumericVector morie_normal_pdf_cpp(NumericVector x, double mean, double sd);
RcppExport SEXP _rmorie_morie_normal_pdf_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_normal_pdf_cpp(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// morie_mean_cpp
double morie_mean_cpp(NumericVector x);
RcppExport SEXP _rmorie_morie_mean_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_mean_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// morie_var_cpp
double morie_var_cpp(NumericVector x, int ddof);
RcppExport SEXP _rmorie_morie_var_cpp(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_var_cpp(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// morie_cor_pearson_cpp
double morie_cor_pearson_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _rmorie_morie_cor_pearson_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(morie_cor_pearson_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_exp_const_cpp
double morie_hawkes_ll_exp_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double beta);
RcppExport SEXP _rmorie_morie_hawkes_ll_exp_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_exp_const_cpp(t, T_horizon, a0, eta, beta));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_weibull_const_cpp
double morie_hawkes_ll_weibull_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double alpha, double lam);
RcppExport SEXP _rmorie_morie_hawkes_ll_weibull_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_weibull_const_cpp(t, T_horizon, a0, eta, alpha, lam));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_lomax_const_cpp
double morie_hawkes_ll_lomax_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double alpha, double c);
RcppExport SEXP _rmorie_morie_hawkes_ll_lomax_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_lomax_const_cpp(t, T_horizon, a0, eta, alpha, c));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_gamma_const_cpp
double morie_hawkes_ll_gamma_const_cpp(NumericVector t, double T_horizon, double a0, double eta, double alpha, double beta);
RcppExport SEXP _rmorie_morie_hawkes_ll_gamma_const_cpp(SEXP tSEXP, SEXP T_horizonSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_gamma_const_cpp(t, T_horizon, a0, eta, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_kernel_density_cpp
NumericVector morie_hawkes_kernel_density_cpp(NumericVector u, std::string kind, NumericVector psi);
RcppExport SEXP _rmorie_morie_hawkes_kernel_density_cpp(SEXP uSEXP, SEXP kindSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_kernel_density_cpp(u, kind, psi));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_kernel_cdf_cpp
NumericVector morie_hawkes_kernel_cdf_cpp(NumericVector u, std::string kind, NumericVector psi);
RcppExport SEXP _rmorie_morie_hawkes_kernel_cdf_cpp(SEXP uSEXP, SEXP kindSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_kernel_cdf_cpp(u, kind, psi));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_pair_excitation_sum_cpp
NumericVector morie_hawkes_pair_excitation_sum_cpp(NumericVector t, double eta, std::string kind, NumericVector psi);
RcppExport SEXP _rmorie_morie_hawkes_pair_excitation_sum_cpp(SEXP tSEXP, SEXP etaSEXP, SEXP kindSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_pair_excitation_sum_cpp(t, eta, kind, psi));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_baseline_integral_cpp
double morie_hawkes_baseline_integral_cpp(double T_horizon, NumericVector alpha, int n_grid);
RcppExport SEXP _rmorie_morie_hawkes_baseline_integral_cpp(SEXP T_horizonSEXP, SEXP alphaSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T_horizon(T_horizonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_baseline_integral_cpp(T_horizon, alpha, n_grid));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_get_
std::string morie_http_get_(std::string url, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _rmorie_morie_http_get_(SEXP urlSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_get_(url, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_get_bytes_
Rcpp::RawVector morie_http_get_bytes_(std::string url, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _rmorie_morie_http_get_bytes_(SEXP urlSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_get_bytes_(url, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_post_
std::string morie_http_post_(std::string url, std::string body, std::string content_type, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _rmorie_morie_http_post_(SEXP urlSEXP, SEXP bodySEXP, SEXP content_typeSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< std::string >::type body(bodySEXP);
    Rcpp::traits::input_parameter< std::string >::type content_type(content_typeSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_post_(url, body, content_type, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_get_with_status_
Rcpp::List morie_http_get_with_status_(std::string url, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _rmorie_morie_http_get_with_status_(SEXP urlSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_get_with_status_(url, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_post_with_status_
Rcpp::List morie_http_post_with_status_(std::string url, std::string body, std::string content_type, int timeout_s, Rcpp::CharacterVector headers, std::string user_agent, bool follow_redirects);
RcppExport SEXP _rmorie_morie_http_post_with_status_(SEXP urlSEXP, SEXP bodySEXP, SEXP content_typeSEXP, SEXP timeout_sSEXP, SEXP headersSEXP, SEXP user_agentSEXP, SEXP follow_redirectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< std::string >::type body(bodySEXP);
    Rcpp::traits::input_parameter< std::string >::type content_type(content_typeSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type headers(headersSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_agent(user_agentSEXP);
    Rcpp::traits::input_parameter< bool >::type follow_redirects(follow_redirectsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_http_post_with_status_(url, body, content_type, timeout_s, headers, user_agent, follow_redirects));
    return rcpp_result_gen;
END_RCPP
}
// morie_http_curl_version_
std::string morie_http_curl_version_();
RcppExport SEXP _rmorie_morie_http_curl_version_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(morie_http_curl_version_());
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_mahalanobis_pairs_cpp
arma::mat morie_matching_mahalanobis_pairs_cpp(const arma::mat& X_t, const arma::mat& X_c, const arma::mat& S_inv);
RcppExport SEXP _rmorie_morie_matching_mahalanobis_pairs_cpp(SEXP X_tSEXP, SEXP X_cSEXP, SEXP S_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_t(X_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_c(X_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_inv(S_invSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_mahalanobis_pairs_cpp(X_t, X_c, S_inv));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_euclidean_pairs_cpp
arma::mat morie_matching_euclidean_pairs_cpp(const arma::mat& X_t, const arma::mat& X_c);
RcppExport SEXP _rmorie_morie_matching_euclidean_pairs_cpp(SEXP X_tSEXP, SEXP X_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_t(X_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_c(X_cSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_euclidean_pairs_cpp(X_t, X_c));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_nn_select_cpp
List morie_matching_nn_select_cpp(const arma::mat& D, bool with_replacement, double caliper, int n_neighbors);
RcppExport SEXP _rmorie_morie_matching_nn_select_cpp(SEXP DSEXP, SEXP with_replacementSEXP, SEXP caliperSEXP, SEXP n_neighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< bool >::type with_replacement(with_replacementSEXP);
    Rcpp::traits::input_parameter< double >::type caliper(caliperSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_nn_select_cpp(D, with_replacement, caliper, n_neighbors));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_cem_strata_cpp
IntegerVector morie_matching_cem_strata_cpp(const IntegerMatrix& X_binned);
RcppExport SEXP _rmorie_morie_matching_cem_strata_cpp(SEXP X_binnedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type X_binned(X_binnedSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_cem_strata_cpp(X_binned));
    return rcpp_result_gen;
END_RCPP
}
// morie_matching_abadie_imbens_kernel_cpp
double morie_matching_abadie_imbens_kernel_cpp(NumericVector y, IntegerVector t, IntegerVector treated_pos, IntegerVector control_pos);
RcppExport SEXP _rmorie_morie_matching_abadie_imbens_kernel_cpp(SEXP ySEXP, SEXP tSEXP, SEXP treated_posSEXP, SEXP control_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treated_pos(treated_posSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type control_pos(control_posSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_matching_abadie_imbens_kernel_cpp(y, t, treated_pos, control_pos));
    return rcpp_result_gen;
END_RCPP
}
// morie_match_greedy_kd_cpp
IntegerMatrix morie_match_greedy_kd_cpp(NumericMatrix treated, NumericMatrix control, int ratio, double caliper_dist, bool replace);
RcppExport SEXP _rmorie_morie_match_greedy_kd_cpp(SEXP treatedSEXP, SEXP controlSEXP, SEXP ratioSEXP, SEXP caliper_distSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type treated(treatedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type control(controlSEXP);
    Rcpp::traits::input_parameter< int >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< double >::type caliper_dist(caliper_distSEXP);
    Rcpp::traits::input_parameter< bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_match_greedy_kd_cpp(treated, control, ratio, caliper_dist, replace));
    return rcpp_result_gen;
END_RCPP
}
// morie_match_greedy_1d_cpp
IntegerMatrix morie_match_greedy_1d_cpp(NumericVector treated_val, NumericVector control_val, int ratio, double caliper_width, bool replace);
RcppExport SEXP _rmorie_morie_match_greedy_1d_cpp(SEXP treated_valSEXP, SEXP control_valSEXP, SEXP ratioSEXP, SEXP caliper_widthSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type treated_val(treated_valSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type control_val(control_valSEXP);
    Rcpp::traits::input_parameter< int >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< double >::type caliper_width(caliper_widthSEXP);
    Rcpp::traits::input_parameter< bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_match_greedy_1d_cpp(treated_val, control_val, ratio, caliper_width, replace));
    return rcpp_result_gen;
END_RCPP
}
// morie_match_optimal_1d_cpp
Rcpp::IntegerVector morie_match_optimal_1d_cpp(Rcpp::NumericVector treated_val, Rcpp::NumericVector control_val);
RcppExport SEXP _rmorie_morie_match_optimal_1d_cpp(SEXP treated_valSEXP, SEXP control_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type treated_val(treated_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_val(control_valSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_match_optimal_1d_cpp(treated_val, control_val));
    return rcpp_result_gen;
END_RCPP
}
// morie_match_optimal_assign_cpp
Rcpp::IntegerVector morie_match_optimal_assign_cpp(Rcpp::NumericMatrix treated, Rcpp::NumericMatrix control);
RcppExport SEXP _rmorie_morie_match_optimal_assign_cpp(SEXP treatedSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type treated(treatedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_match_optimal_assign_cpp(treated, control));
    return rcpp_result_gen;
END_RCPP
}
// morie_rlearner_forest_cpp
Rcpp::NumericMatrix morie_rlearner_forest_cpp(Rcpp::NumericMatrix X, Rcpp::NumericVector pseudo, Rcpp::NumericVector weight, Rcpp::NumericMatrix Xpred, int n_trees, int max_depth, int min_node, double subsample, int seed);
RcppExport SEXP _rmorie_morie_rlearner_forest_cpp(SEXP XSEXP, SEXP pseudoSEXP, SEXP weightSEXP, SEXP XpredSEXP, SEXP n_treesSEXP, SEXP max_depthSEXP, SEXP min_nodeSEXP, SEXP subsampleSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pseudo(pseudoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xpred(XpredSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type min_node(min_nodeSEXP);
    Rcpp::traits::input_parameter< double >::type subsample(subsampleSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_rlearner_forest_cpp(X, pseudo, weight, Xpred, n_trees, max_depth, min_node, subsample, seed));
    return rcpp_result_gen;
END_RCPP
}
// morie_rlm_cpp
List morie_rlm_cpp(const arma::mat& X, const arma::vec& y, double k, int maxit, double acc);
RcppExport SEXP _rmorie_morie_rlm_cpp(SEXP XSEXP, SEXP ySEXP, SEXP kSEXP, SEXP maxitSEXP, SEXP accSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type acc(accSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_rlm_cpp(X, y, k, maxit, acc));
    return rcpp_result_gen;
END_RCPP
}
// morie_sobol_cpp
NumericMatrix morie_sobol_cpp(const int n, const int d);
RcppExport SEXP _rmorie_morie_sobol_cpp(SEXP nSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_sobol_cpp(n, d));
    return rcpp_result_gen;
END_RCPP
}
// morie_knn_index_cpp
IntegerMatrix morie_knn_index_cpp(const arma::mat& coords, const int k);
RcppExport SEXP _rmorie_morie_knn_index_cpp(SEXP coordsSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_knn_index_cpp(coords, k));
    return rcpp_result_gen;
END_RCPP
}
// morie_coord_descent_cpp
List morie_coord_descent_cpp(const arma::mat& Xs, const arma::vec& yc, const double alpha, const double lambda, const int max_iter, const double tol, const arma::vec& warm);
RcppExport SEXP _rmorie_morie_coord_descent_cpp(SEXP XsSEXP, SEXP ycSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP warmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xs(XsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yc(ycSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type warm(warmSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_coord_descent_cpp(Xs, yc, alpha, lambda, max_iter, tol, warm));
    return rcpp_result_gen;
END_RCPP
}
// morie_tsne_descent_cpp
List morie_tsne_descent_cpp(const arma::mat& P, arma::mat Y, const int n_iter, const double eta);
RcppExport SEXP _rmorie_morie_tsne_descent_cpp(SEXP PSEXP, SEXP YSEXP, SEXP n_iterSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_tsne_descent_cpp(P, Y, n_iter, eta));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_nominate_iterate_cpp
Rcpp::List morie_spatial_nominate_iterate_cpp(arma::mat votes, arma::mat X, arma::vec w, arma::mat nv, arma::mat mid, double beta, int max_iter);
RcppExport SEXP _rmorie_morie_spatial_nominate_iterate_cpp(SEXP votesSEXP, SEXP XSEXP, SEXP wSEXP, SEXP nvSEXP, SEXP midSEXP, SEXP betaSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type votes(votesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mid(midSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_nominate_iterate_cpp(votes, X, w, nv, mid, beta, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_emirt_theta_update_cpp
arma::mat morie_spatial_emirt_theta_update_cpp(arma::mat theta, const arma::mat& a, const arma::vec& d, const arma::mat& votes);
RcppExport SEXP _rmorie_morie_spatial_emirt_theta_update_cpp(SEXP thetaSEXP, SEXP aSEXP, SEXP dSEXP, SEXP votesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type votes(votesSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_emirt_theta_update_cpp(theta, a, d, votes));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_smacof_step_cpp
Rcpp::List morie_spatial_smacof_step_cpp(arma::mat X, const arma::mat& D, arma::mat W);
RcppExport SEXP _rmorie_morie_spatial_smacof_step_cpp(SEXP XSEXP, SEXP DSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_smacof_step_cpp(X, D, W));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_classical_mds_cpp
Rcpp::List morie_spatial_classical_mds_cpp(const arma::mat& D, int n_dims);
RcppExport SEXP _rmorie_morie_spatial_classical_mds_cpp(SEXP DSEXP, SEXP n_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type n_dims(n_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_classical_mds_cpp(D, n_dims));
    return rcpp_result_gen;
END_RCPP
}
// morie_spatial_wordfish_omega_update_cpp
arma::vec morie_spatial_wordfish_omega_update_cpp(const arma::mat& dtm, const arma::vec& psi, const arma::vec& alpha, const arma::vec& beta, arma::vec omega);
RcppExport SEXP _rmorie_morie_spatial_wordfish_omega_update_cpp(SEXP dtmSEXP, SEXP psiSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_spatial_wordfish_omega_update_cpp(dtm, psi, alpha, beta, omega));
    return rcpp_result_gen;
END_RCPP
}
// morie_svc_train_cpp
List morie_svc_train_cpp(NumericMatrix X, NumericVector y, double C, int kernel_type, double gamma, double coef0, double degree, double tol, int max_iter);
RcppExport SEXP _rmorie_morie_svc_train_cpp(SEXP XSEXP, SEXP ySEXP, SEXP CSEXP, SEXP kernel_typeSEXP, SEXP gammaSEXP, SEXP coef0SEXP, SEXP degreeSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_type(kernel_typeSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< double >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_svc_train_cpp(X, y, C, kernel_type, gamma, coef0, degree, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// morie_svr_train_cpp
List morie_svr_train_cpp(NumericMatrix X, NumericVector z, double C, double epsilon, int kernel_type, double gamma, double coef0, double degree, double tol, int max_iter);
RcppExport SEXP _rmorie_morie_svr_train_cpp(SEXP XSEXP, SEXP zSEXP, SEXP CSEXP, SEXP epsilonSEXP, SEXP kernel_typeSEXP, SEXP gammaSEXP, SEXP coef0SEXP, SEXP degreeSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_type(kernel_typeSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< double >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_svr_train_cpp(X, z, C, epsilon, kernel_type, gamma, coef0, degree, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// morie_svm_decision_cpp
NumericVector morie_svm_decision_cpp(NumericMatrix SV, NumericVector coef, double rho, NumericMatrix Xnew, int kernel_type, double gamma, double coef0, double degree);
RcppExport SEXP _rmorie_morie_svm_decision_cpp(SEXP SVSEXP, SEXP coefSEXP, SEXP rhoSEXP, SEXP XnewSEXP, SEXP kernel_typeSEXP, SEXP gammaSEXP, SEXP coef0SEXP, SEXP degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type SV(SVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xnew(XnewSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_type(kernel_typeSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< double >::type degree(degreeSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_svm_decision_cpp(SV, coef, rho, Xnew, kernel_type, gamma, coef0, degree));
    return rcpp_result_gen;
END_RCPP
}
// morie_tree_fit_cpp
List morie_tree_fit_cpp(NumericMatrix X, NumericVector g, NumericVector h, int max_depth, int min_node, int mtry, double lambda, double alpha, double gamma_pen);
RcppExport SEXP _rmorie_morie_tree_fit_cpp(SEXP XSEXP, SEXP gSEXP, SEXP hSEXP, SEXP max_depthSEXP, SEXP min_nodeSEXP, SEXP mtrySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP gamma_penSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type min_node(min_nodeSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_pen(gamma_penSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_tree_fit_cpp(X, g, h, max_depth, min_node, mtry, lambda, alpha, gamma_pen));
    return rcpp_result_gen;
END_RCPP
}
// morie_tree_predict_cpp
NumericVector morie_tree_predict_cpp(List tree, NumericMatrix X);
RcppExport SEXP _rmorie_morie_tree_predict_cpp(SEXP treeSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_tree_predict_cpp(tree, X));
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get
std::string siu_http_get(std::string url, int timeout_s);
RcppExport SEXP _rmorie_siu_http_get(SEXP urlSEXP, SEXP timeout_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get(url, timeout_s));
    return rcpp_result_gen;
END_RCPP
}
// siu_curl_version
std::string siu_curl_version();
RcppExport SEXP _rmorie_siu_curl_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(siu_curl_version());
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get_many
Rcpp::CharacterVector siu_http_get_many(Rcpp::CharacterVector urls, int concurrency, int timeout_s, double rate_rps, int max_retries);
RcppExport SEXP _rmorie_siu_http_get_many(SEXP urlsSEXP, SEXP concurrencySEXP, SEXP timeout_sSEXP, SEXP rate_rpsSEXP, SEXP max_retriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< int >::type concurrency(concurrencySEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< double >::type rate_rps(rate_rpsSEXP);
    Rcpp::traits::input_parameter< int >::type max_retries(max_retriesSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get_many(urls, concurrency, timeout_s, rate_rps, max_retries));
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get_many_with_status
Rcpp::List siu_http_get_many_with_status(Rcpp::CharacterVector urls, int concurrency, int timeout_s, double rate_rps, int max_retries);
RcppExport SEXP _rmorie_siu_http_get_many_with_status(SEXP urlsSEXP, SEXP concurrencySEXP, SEXP timeout_sSEXP, SEXP rate_rpsSEXP, SEXP max_retriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< int >::type concurrency(concurrencySEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    Rcpp::traits::input_parameter< double >::type rate_rps(rate_rpsSEXP);
    Rcpp::traits::input_parameter< int >::type max_retries(max_retriesSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get_many_with_status(urls, concurrency, timeout_s, rate_rps, max_retries));
    return rcpp_result_gen;
END_RCPP
}
// siu_parse_report
Rcpp::CharacterVector siu_parse_report(std::string html, int drid, std::string url);
RcppExport SEXP _rmorie_siu_parse_report(SEXP htmlSEXP, SEXP dridSEXP, SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type html(htmlSEXP);
    Rcpp::traits::input_parameter< int >::type drid(dridSEXP);
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_parse_report(html, drid, url));
    return rcpp_result_gen;
END_RCPP
}
// siu_parse_news
Rcpp::CharacterVector siu_parse_news(std::string html, int nrid, std::string url);
RcppExport SEXP _rmorie_siu_parse_news(SEXP htmlSEXP, SEXP nridSEXP, SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type html(htmlSEXP);
    Rcpp::traits::input_parameter< int >::type nrid(nridSEXP);
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_parse_news(html, nrid, url));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmorie_morie_crypto_sha256_native", (DL_FUNC) &_rmorie_morie_crypto_sha256_native, 1},
    {"_rmorie_morie_crypto_sha256_hex_native", (DL_FUNC) &_rmorie_morie_crypto_sha256_hex_native, 1},
    {"_rmorie_morie_crypto_hmac_sha256_native", (DL_FUNC) &_rmorie_morie_crypto_hmac_sha256_native, 2},
    {"_rmorie_morie_crypto_pbkdf2_sha256_native", (DL_FUNC) &_rmorie_morie_crypto_pbkdf2_sha256_native, 4},
    {"_rmorie_morie_crypto_blake2b_native", (DL_FUNC) &_rmorie_morie_crypto_blake2b_native, 3},
    {"_rmorie_morie_crypto_argon2_native", (DL_FUNC) &_rmorie_morie_crypto_argon2_native, 9},
    {"_rmorie_morie_crypto_liboqs_available", (DL_FUNC) &_rmorie_morie_crypto_liboqs_available, 0},
    {"_rmorie_morie_crypto_liboqs_version", (DL_FUNC) &_rmorie_morie_crypto_liboqs_version, 0},
    {"_rmorie_morie_crypto_mlkem768_keygen", (DL_FUNC) &_rmorie_morie_crypto_mlkem768_keygen, 0},
    {"_rmorie_morie_crypto_mlkem768_encaps", (DL_FUNC) &_rmorie_morie_crypto_mlkem768_encaps, 1},
    {"_rmorie_morie_crypto_mlkem768_decaps", (DL_FUNC) &_rmorie_morie_crypto_mlkem768_decaps, 2},
    {"_rmorie_morie_crypto_mldsa65_keygen", (DL_FUNC) &_rmorie_morie_crypto_mldsa65_keygen, 0},
    {"_rmorie_morie_crypto_mldsa65_sign", (DL_FUNC) &_rmorie_morie_crypto_mldsa65_sign, 2},
    {"_rmorie_morie_crypto_mldsa65_verify", (DL_FUNC) &_rmorie_morie_crypto_mldsa65_verify, 3},
    {"_rmorie_morie_crypto_slhdsa128s_keygen", (DL_FUNC) &_rmorie_morie_crypto_slhdsa128s_keygen, 0},
    {"_rmorie_morie_crypto_slhdsa128s_sign", (DL_FUNC) &_rmorie_morie_crypto_slhdsa128s_sign, 2},
    {"_rmorie_morie_crypto_slhdsa128s_verify", (DL_FUNC) &_rmorie_morie_crypto_slhdsa128s_verify, 3},
    {"_rmorie_morie_crypto_hqc128_keygen", (DL_FUNC) &_rmorie_morie_crypto_hqc128_keygen, 0},
    {"_rmorie_morie_crypto_hqc128_encaps", (DL_FUNC) &_rmorie_morie_crypto_hqc128_encaps, 1},
    {"_rmorie_morie_crypto_hqc128_decaps", (DL_FUNC) &_rmorie_morie_crypto_hqc128_decaps, 2},
    {"_rmorie_morie_crypto_sodium_available", (DL_FUNC) &_rmorie_morie_crypto_sodium_available, 0},
    {"_rmorie_morie_crypto_sodium_version", (DL_FUNC) &_rmorie_morie_crypto_sodium_version, 0},
    {"_rmorie_morie_crypto_chacha20poly1305_encrypt", (DL_FUNC) &_rmorie_morie_crypto_chacha20poly1305_encrypt, 4},
    {"_rmorie_morie_crypto_chacha20poly1305_decrypt", (DL_FUNC) &_rmorie_morie_crypto_chacha20poly1305_decrypt, 4},
    {"_rmorie_morie_crypto_hkdf_sha256", (DL_FUNC) &_rmorie_morie_crypto_hkdf_sha256, 4},
    {"_rmorie_morie_crypto_random_bytes", (DL_FUNC) &_rmorie_morie_crypto_random_bytes, 1},
    {"_rmorie_morie_twfe_demean_cpp", (DL_FUNC) &_rmorie_morie_twfe_demean_cpp, 7},
    {"_rmorie_morie_digest_native", (DL_FUNC) &_rmorie_morie_digest_native, 3},
    {"_rmorie_morie_digest2int_native", (DL_FUNC) &_rmorie_morie_digest2int_native, 2},
    {"_rmorie_morie_aes_ecb_native", (DL_FUNC) &_rmorie_morie_aes_ecb_native, 3},
    {"_rmorie_morie_dsp_lms_cpp", (DL_FUNC) &_rmorie_morie_dsp_lms_cpp, 4},
    {"_rmorie_morie_dsp_nlms_cpp", (DL_FUNC) &_rmorie_morie_dsp_nlms_cpp, 5},
    {"_rmorie_morie_dsp_rls_cpp", (DL_FUNC) &_rmorie_morie_dsp_rls_cpp, 5},
    {"_rmorie_morie_dsp_cross_correlation_cpp", (DL_FUNC) &_rmorie_morie_dsp_cross_correlation_cpp, 3},
    {"_rmorie_morie_dsp_median_filter_cpp", (DL_FUNC) &_rmorie_morie_dsp_median_filter_cpp, 2},
    {"_rmorie_morie_normal_pdf_cpp", (DL_FUNC) &_rmorie_morie_normal_pdf_cpp, 3},
    {"_rmorie_morie_mean_cpp", (DL_FUNC) &_rmorie_morie_mean_cpp, 1},
    {"_rmorie_morie_var_cpp", (DL_FUNC) &_rmorie_morie_var_cpp, 2},
    {"_rmorie_morie_cor_pearson_cpp", (DL_FUNC) &_rmorie_morie_cor_pearson_cpp, 2},
    {"_rmorie_morie_hawkes_ll_exp_const_cpp", (DL_FUNC) &_rmorie_morie_hawkes_ll_exp_const_cpp, 5},
    {"_rmorie_morie_hawkes_ll_weibull_const_cpp", (DL_FUNC) &_rmorie_morie_hawkes_ll_weibull_const_cpp, 6},
    {"_rmorie_morie_hawkes_ll_lomax_const_cpp", (DL_FUNC) &_rmorie_morie_hawkes_ll_lomax_const_cpp, 6},
    {"_rmorie_morie_hawkes_ll_gamma_const_cpp", (DL_FUNC) &_rmorie_morie_hawkes_ll_gamma_const_cpp, 6},
    {"_rmorie_morie_hawkes_kernel_density_cpp", (DL_FUNC) &_rmorie_morie_hawkes_kernel_density_cpp, 3},
    {"_rmorie_morie_hawkes_kernel_cdf_cpp", (DL_FUNC) &_rmorie_morie_hawkes_kernel_cdf_cpp, 3},
    {"_rmorie_morie_hawkes_pair_excitation_sum_cpp", (DL_FUNC) &_rmorie_morie_hawkes_pair_excitation_sum_cpp, 4},
    {"_rmorie_morie_hawkes_baseline_integral_cpp", (DL_FUNC) &_rmorie_morie_hawkes_baseline_integral_cpp, 3},
    {"_rmorie_morie_http_get_", (DL_FUNC) &_rmorie_morie_http_get_, 5},
    {"_rmorie_morie_http_get_bytes_", (DL_FUNC) &_rmorie_morie_http_get_bytes_, 5},
    {"_rmorie_morie_http_post_", (DL_FUNC) &_rmorie_morie_http_post_, 7},
    {"_rmorie_morie_http_get_with_status_", (DL_FUNC) &_rmorie_morie_http_get_with_status_, 5},
    {"_rmorie_morie_http_post_with_status_", (DL_FUNC) &_rmorie_morie_http_post_with_status_, 7},
    {"_rmorie_morie_http_curl_version_", (DL_FUNC) &_rmorie_morie_http_curl_version_, 0},
    {"_rmorie_morie_matching_mahalanobis_pairs_cpp", (DL_FUNC) &_rmorie_morie_matching_mahalanobis_pairs_cpp, 3},
    {"_rmorie_morie_matching_euclidean_pairs_cpp", (DL_FUNC) &_rmorie_morie_matching_euclidean_pairs_cpp, 2},
    {"_rmorie_morie_matching_nn_select_cpp", (DL_FUNC) &_rmorie_morie_matching_nn_select_cpp, 4},
    {"_rmorie_morie_matching_cem_strata_cpp", (DL_FUNC) &_rmorie_morie_matching_cem_strata_cpp, 1},
    {"_rmorie_morie_matching_abadie_imbens_kernel_cpp", (DL_FUNC) &_rmorie_morie_matching_abadie_imbens_kernel_cpp, 4},
    {"_rmorie_morie_match_greedy_kd_cpp", (DL_FUNC) &_rmorie_morie_match_greedy_kd_cpp, 5},
    {"_rmorie_morie_match_greedy_1d_cpp", (DL_FUNC) &_rmorie_morie_match_greedy_1d_cpp, 5},
    {"_rmorie_morie_match_optimal_1d_cpp", (DL_FUNC) &_rmorie_morie_match_optimal_1d_cpp, 2},
    {"_rmorie_morie_match_optimal_assign_cpp", (DL_FUNC) &_rmorie_morie_match_optimal_assign_cpp, 2},
    {"_rmorie_morie_rlearner_forest_cpp", (DL_FUNC) &_rmorie_morie_rlearner_forest_cpp, 9},
    {"_rmorie_morie_rlm_cpp", (DL_FUNC) &_rmorie_morie_rlm_cpp, 5},
    {"_rmorie_morie_sobol_cpp", (DL_FUNC) &_rmorie_morie_sobol_cpp, 2},
    {"_rmorie_morie_knn_index_cpp", (DL_FUNC) &_rmorie_morie_knn_index_cpp, 2},
    {"_rmorie_morie_coord_descent_cpp", (DL_FUNC) &_rmorie_morie_coord_descent_cpp, 7},
    {"_rmorie_morie_tsne_descent_cpp", (DL_FUNC) &_rmorie_morie_tsne_descent_cpp, 4},
    {"_rmorie_morie_spatial_nominate_iterate_cpp", (DL_FUNC) &_rmorie_morie_spatial_nominate_iterate_cpp, 7},
    {"_rmorie_morie_spatial_emirt_theta_update_cpp", (DL_FUNC) &_rmorie_morie_spatial_emirt_theta_update_cpp, 4},
    {"_rmorie_morie_spatial_smacof_step_cpp", (DL_FUNC) &_rmorie_morie_spatial_smacof_step_cpp, 3},
    {"_rmorie_morie_spatial_classical_mds_cpp", (DL_FUNC) &_rmorie_morie_spatial_classical_mds_cpp, 2},
    {"_rmorie_morie_spatial_wordfish_omega_update_cpp", (DL_FUNC) &_rmorie_morie_spatial_wordfish_omega_update_cpp, 5},
    {"_rmorie_morie_svc_train_cpp", (DL_FUNC) &_rmorie_morie_svc_train_cpp, 9},
    {"_rmorie_morie_svr_train_cpp", (DL_FUNC) &_rmorie_morie_svr_train_cpp, 10},
    {"_rmorie_morie_svm_decision_cpp", (DL_FUNC) &_rmorie_morie_svm_decision_cpp, 8},
    {"_rmorie_morie_tree_fit_cpp", (DL_FUNC) &_rmorie_morie_tree_fit_cpp, 9},
    {"_rmorie_morie_tree_predict_cpp", (DL_FUNC) &_rmorie_morie_tree_predict_cpp, 2},
    {"_rmorie_siu_http_get", (DL_FUNC) &_rmorie_siu_http_get, 2},
    {"_rmorie_siu_curl_version", (DL_FUNC) &_rmorie_siu_curl_version, 0},
    {"_rmorie_siu_http_get_many", (DL_FUNC) &_rmorie_siu_http_get_many, 5},
    {"_rmorie_siu_http_get_many_with_status", (DL_FUNC) &_rmorie_siu_http_get_many_with_status, 5},
    {"_rmorie_siu_parse_report", (DL_FUNC) &_rmorie_siu_parse_report, 3},
    {"_rmorie_siu_parse_news", (DL_FUNC) &_rmorie_siu_parse_news, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmorie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
