# SPDX-License-Identifier: AGPL-3.0-or-later
#' The self-play evaluation gate
#'
#' Silver et al. (2018), arXiv:1712.01815 (FETCHED), describes the gate
#' and then its removal, verbatim: "In AlphaGo Zero, self-play games were
#' generated by the best player from all previous iterations.  After each
#' iteration of training, the performance of the new player was measured
#' against the best player; if it won by a margin of 55% then it replaced
#' the best player ...  In contrast, AlphaZero simply maintains a single
#' neural network that is updated continually ... omitting the evaluation
#' step and the selection of best player."  So the 55% gate is AlphaGo
#' Zero's (Nature 550, 354-359), not AlphaZero's, and this function
#' implements AlphaGo Zero's rule while saying so.  score = (wins +
#' draws/2) / games; the one-sided binomial tail at p = 1/2 is returned
#' too, so a 55% result out of ten games is not mistaken for evidence.
#'
#' @param new_net,old_net player identifiers, or win/loss counts when
#'   `wins` is NULL.
#' @param n_games number of evaluation games.
#' @param wins wins for new_net.
#' @param draws drawn games.
#' @param threshold the replacement margin.
#' @return list: estimate, score, replace, p_value, wins, draws, losses,
#'   n, method.
#' @keywords internal
#' @examples
#' Evalgate(NULL, NULL, 100, wins = 60, draws = 10)$replace
#' @export
Evalgate <- function(new_net, old_net = NULL, n_games = 100, wins = NULL,
                     draws = 0, threshold = 0.55) {
  if (is.null(wins)) {
    w <- as.numeric(new_net)
    l <- if (!is.null(old_net)) as.numeric(old_net) else 0
    d <- as.numeric(draws)
    n <- w + l + d
  } else {
    w <- as.numeric(wins); d <- as.numeric(draws); n <- as.numeric(n_games)
    l <- n - w - d
  }
  score <- if (n > 0) (w + 0.5 * d) / n else NaN
  dec <- as.integer(round(w + l)); kk <- as.integer(round(w))
  p <- NaN
  if (dec > 0L) {
    tail <- 0
    for (i in seq(kk, dec)) {
      tail <- tail + exp(lgamma(dec + 1) - lgamma(i + 1) -
                           lgamma(dec - i + 1) - dec * log(2))
    }
    p <- tail
  }
  list(estimate = score, score = score, replace = score > as.numeric(threshold),
       p_value = p, wins = w, draws = d, losses = l, n = n,
       method = paste0("AlphaGo Zero self-play evaluation gate (55%); AlphaZero ",
                       "itself omits this step and updates continually"))
}
