# SPDX-License-Identifier: AGPL-3.0-or-later
#' Sieve bootstrap: fit a growing parametric model, resample its innovations
#'
#' Buehlmann, P. (1997), "Sieve Bootstrap for Time Series", Bernoulli 3(2),
#' 123-148, doi:10.2307/3318584 (verified against Crossref).
#'
#' The block bootstrap keeps dependence by keeping data contiguous, which
#' costs it the ability to extrapolate beyond the observed sample paths.  The
#' sieve bootstrap instead approximates the process by a sequence of
#' finite-dimensional models whose order grows with n -- Buehlmann's sieve is
#' the AR(p) family with p = p(n) -> infinity -- fits one, and resamples the
#' FITTED INNOVATIONS iid, which is legitimate precisely because a correctly
#' ordered linear sieve leaves white residuals.  The bootstrap series is then
#' regenerated by running the fitted recursion forward on the resampled
#' innovations, so it is a genuinely new path rather than a rearrangement of
#' the old one.
#'
#' This takes the general form of the procedure: fit_fn(x) returns
#' list(model, resid), rvs_fn(model, resid, n, g) regenerates a series, and
#' stat is evaluated on each regenerated series.  The default sieve is the
#' AR(p) one with p chosen by AIC over 0..p_max, fitted by the package's
#' ridge-stabilised least squares on the lagged design, with a burn-in of 100
#' discarded points so the regenerated path is not anchored at the fitted
#' starting values.
#'
#' Anchors: with p_max = 0 the sieve is white noise, the "residuals" are the
#' centred data, and the procedure reduces to the ordinary iid bootstrap; and
#' on a noiseless AR(1) the AIC order is 1, the fitted coefficient is rho to
#' machine precision, and the residuals are identically zero.
#'
#' @param x the series, in time order.
#' @param fit_fn fit_fn(x) returning list(model = , resid = ); NULL uses the
#'   AR(p) sieve with AIC order selection.
#' @param rvs_fn rvs_fn(model, resid, n, g) regenerating a series; NULL uses
#'   the AR recursion with burn-in 100.
#' @param stat statistic of a series; NULL uses the mean.
#' @param B replicates.
#' @param seed seed for the shared deterministic stream.
#' @param p_max maximum sieve order; NULL uses floor(10 log10 n).
#' @param alpha two-sided error rate.
#' @return list: theta_b, estimate, se, lo, hi, order, phi, sigma2, aic, n, B,
#'   method.
#' @keywords internal
#' @examples
#' Btsieve(as.numeric(filter(rep(c(1, -1), 40), 0.5, "recursive")), B = 20)$order
#' @export
Btsieve <- function(x, fit_fn = NULL, rvs_fn = NULL, stat = NULL, B = 200,
                    seed = 1, p_max = NULL, alpha = 0.05) {
  xx <- .s03vec(x)
  n <- length(xx)
  if (n < 4L) stop("boot_sieve_general: need at least four observations")
  if (as.integer(B) < 2L) stop("boot_sieve_general: need at least two replicates")
  a <- as.numeric(alpha)
  if (!(a > 0 && a < 1)) stop("boot_sieve_general: alpha must lie strictly between 0 and 1")
  f <- if (is.null(stat)) .s03mean else stat
  if (is.null(fit_fn)) {
    ft <- .btsieve_arfit(xx, p_max)
    phi <- ft$phi
    res <- ft$resid
    order <- ft$p
    aic <- ft$aic
    model <- list(phi = phi, mu = ft$mu)
  } else {
    ft <- fit_fn(xx)
    model <- ft$model
    res <- ft$resid
    phi <- numeric(0)
    order <- 0L
    aic <- NaN
  }
  res <- res - .s03mean(res)
  r <- if (is.null(rvs_fn)) .btsieve_arrvs else rvs_fn
  g <- .t1_lcg(seed)
  theta <- vapply(seq_len(as.integer(B)),
                  function(b) as.numeric(f(r(model, res, n, g))), 0)
  list(theta_b = theta, estimate = as.numeric(f(xx)), se = .s03sd(theta, 1L),
       lo = .s03quantile7(theta, a / 2), hi = .s03quantile7(theta, 1 - a / 2),
       order = order, phi = phi, sigma2 = sum(res^2) / length(res), aic = aic,
       n = n, B = as.integer(B),
       method = "Buehlmann (1997) Bernoulli 3(2):123-148, AR(p) sieve with AIC order")
}

#' @noRd
.btsieve_arfit <- function(x, p_max = NULL) {
  n <- length(x)
  if (is.null(p_max)) p_max <- as.integer(floor(10 * log10(n)))
  p_max <- as.integer(p_max)
  if (p_max < 0L) stop("boot_sieve_general: p_max must be non-negative")
  if (p_max > n - 2L) p_max <- as.integer(max(n - 2L, 0L))
  mu <- .s03mean(x)
  z <- x - mu
  best <- NULL
  for (p in 0:p_max) {
    m <- n - p_max
    if (m < 2L) break
    y <- z[(p_max + 1L):n]
    if (p == 0L) {
      phi <- numeric(0)
      res <- y
    } else {
      X <- matrix(0, m, p)
      for (k in seq_len(p)) X[, k] <- z[(p_max + 1L - k):(n - k)]
      phi <- .s03lstsq(X, y)
      res <- y - as.numeric(X %*% phi)
    }
    s2 <- sum(res^2) / m
    aic <- if (s2 <= 0) -Inf else m * log(s2) + 2 * p
    if (is.null(best) || aic < best$aic)
      best <- list(phi = phi, mu = mu, resid = res, p = p, aic = aic)
  }
  if (is.null(best)) stop("boot_sieve_general: series too short for the sieve")
  best
}

#' @noRd
.btsieve_arrvs <- function(model, resid, n, g) {
  phi <- model$phi
  mu <- model$mu
  p <- length(phi)
  m <- length(resid)
  hist <- numeric(max(p, 1L))
  out <- numeric(n)
  q <- 0L
  BURN <- 100L
  for (t in seq_len(BURN + n)) {
    j <- as.integer(g$unif() * m)
    if (j >= m) j <- m - 1L
    v <- resid[j + 1L]
    if (p > 0L) for (k in seq_len(p)) v <- v + phi[k] * hist[k]
    if (length(hist) > 1L) for (k in length(hist):2L) hist[k] <- hist[k - 1L]
    hist[1] <- v
    if (t > BURN) { q <- q + 1L
    out[q] <- v + mu }
  }
  out
}
