# morie.fn -- function file (rootcoder007/morie)
# GRACE: contrastive graph learning at the node level.
#
# Deep Graph InfoMax maximises mutual information between node
# embeddings and a *global* summary obtained by a readout. GRACE's
# objection is that the local-global framing depends heavily on that
# readout being expressive, and that the injectivity it needs is not
# guaranteed. Contrast **node against node** instead.
#
# **Two views, corrupted two ways.** A view is generated by removing
# edges and, separately, by masking feature dimensions -- topology and
# attributes both. Doing both gives nodes genuinely different contexts
# across the views, which is what the contrastive objective needs;
# corrupting only one leaves the two views too similar to learn from.
#
# **Three kinds of pair, and two of them are negatives.** For node
# :math:`i` with embeddings :math:`u_i, v_i` in the two views, the pair
# :math:`(u_i, v_i)` is positive. Every *other* node is a negative --
# both in the other view (**inter-view**) and in the same view
# (**intra-view**). Including the intra-view negatives is the part that
# is easy to omit and matters: without them nothing pushes apart two
# nodes that happen to sit in the same view.
#
# .. math:: \ell(u_i, v_i) = \log
#           \frac{e^{\theta(u_i,v_i)/\tau}}
#                {\underbrace{e^{\theta(u_i,v_i)/\tau}}_{\text{positive}}
#                + \underbrace{\sum_{k \ne i} e^{\theta(u_i,v_k)/\tau}}
#                  _{\text{inter-view}}
#                + \underbrace{\sum_{k \ne i} e^{\theta(u_i,u_k)/\tau}}
#                  _{\text{intra-view}}},
#
# with :math:`\theta` cosine similarity after a projection head and
# :math:`\tau` a temperature. The overall objective averages
# :math:`\ell(u_i,v_i)` and :math:`\ell(v_i,u_i)`, since the two views
# are symmetric.
#
# **No labels anywhere.** The method is unsupervised, and the paper
# reports it beating supervised counterparts on transductive tasks.
#
# References
# ----------
# Zhu, Y., Xu, Y., Yu, F., Liu, Q., Wu, S. & Wang, L. (2020) "Deep Graph
# Contrastive Representation Learning", *ICML Workshop on Graph
# Representation Learning and Beyond*, arXiv:2006.04131. The abstract
# and Sec. 1 (a node-level contrastive objective; two views generated by
# corruption at both the topology and attribute levels -- removing edges
# and masking features -- to give diverse node contexts; the criticism
# that DGI's local-global MI maximisation depends on the readout; the
# theoretical connection to mutual information and the triplet loss; and
# that the unsupervised method surpasses supervised counterparts on
# transductive tasks). Sec. 3 (the pairwise objective with positive,
# inter-view negative and intra-view negative terms, and the symmetric
# average over the two views).
#
# Velickovic, P., Fedus, W., Hamilton, W. L., Lio, P., Bengio, Y. &
# Hjelm, R. D. (2019) "Deep Graph Infomax", *ICLR 2019*,
# arXiv:1809.10341. The local-global objective GRACE argues against.
#
# Hjelm, R. D., Fedorov, A., Lavoie-Marchildon, S., Grewal, K.,
# Bachman, P., Trischler, A. & Bengio, Y. (2019) "Learning deep
# representations by mutual information estimation and maximization",
# *ICLR 2019*, arXiv:1808.06670. Deep InfoMAX; implemented in
# :mod:`mienco`.

.grace_eps <- 1e-12

#' .grace_drop_edges
#'
#' A step of the grace_native implementation. Called by \code{.grace_generate_view},
#' \code{morie_drop_edges}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param edges A vector; its length is taken and its elements indexed.
#' @param p Coerced to numeric by the body, with \code{as.numeric}.
#' @param rng Passed to \code{.ghc_unif}.
#' @return The value of \code{[}.
#' @export
.grace_drop_edges <- function(edges, p, rng) {
  pp <- as.numeric(p)
  if (pp < 0 || pp >= 1) {
    stop(sprintf("grace: the drop rate must lie in [0,1), got %s", p))
  }
  if (length(edges) == 0) return(edges)
  n <- length(edges)
  u <- .ghc_unif(rng, n)
  edges[u >= pp]
}

#' .grace_mask_features
#'
#' A step of the grace_native implementation. Called by \code{.grace_generate_view},
#' \code{morie_mask_features}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X A matrix; passed to \code{as.matrix}.
#' @param p Coerced to numeric by the body, with \code{as.numeric}.
#' @param rng Passed to \code{.ghc_unif}.
#' @return A list with \code{X}, \code{kept}, \code{n_masked}.
#' @export
.grace_mask_features <- function(X, p, rng) {
  pp <- as.numeric(p)
  if (pp < 0 || pp >= 1) {
    stop(sprintf("grace: the mask rate must lie in [0,1), got %s", p))
  }
  rows <- as.matrix(X)
  storage.mode(rows) <- "double"
  nr <- nrow(rows)
  d <- ncol(rows)
  if (d == 0) {
    return(list(X = rows, kept = numeric(0), n_masked = 0L))
  }
  u <- .ghc_unif(rng, d)
  keep <- ifelse(u < pp, 0.0, 1.0)
  if (nr > 0) {
    masked <- rows * matrix(keep, nrow = nr, ncol = d, byrow = TRUE)
  } else {
    masked <- rows
  }
  list(X = masked, kept = keep, n_masked = as.integer(d - sum(keep)))
}

#' .grace_generate_view
#'
#' A step of the grace_native implementation. Called by \code{morie_generate_view}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X Passed to \code{.grace_mask_features}.
#' @param edges Passed to \code{.grace_drop_edges}.
#' @param p_edge Passed to \code{.grace_drop_edges}.
#' @param p_feature Passed to \code{.grace_mask_features}.
#' @param rng Passed to \code{.grace_mask_features}.
#' @return A list with \code{X}, \code{edges}, \code{n_masked_features}.
#' @export
.grace_generate_view <- function(X, edges, p_edge, p_feature, rng) {
  m <- .grace_mask_features(X, p_feature, rng)
  list(X = m$X, edges = .grace_drop_edges(edges, p_edge, rng),
       n_masked_features = m$n_masked)
}

#' .grace_cos
#'
#' A step of the grace_native implementation. Called by \code{.grace_pair_loss}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param a Numeric; combined arithmetically in the body.
#' @param b Numeric; combined arithmetically in the body.
#' @return A numeric value.
#' @export
#' @examples
#' A <- matrix(c(4, 1, 0.5, 1, 3, 0.8, 0.5, 0.8, 2), nrow = 3)
#' b <- c(1.5, 2.5, 3.5)
#' res <- .grace_cos(a = A, b = b)
#' res
.grace_cos <- function(a, b) {
  na <- sqrt(sum(a * a))
  nb <- sqrt(sum(b * b))
  if (na <= .grace_eps || nb <= .grace_eps) {
    stop("grace: cosine similarity needs non-zero vectors")
  }
  sum(a * b) / (na * nb)
}

#' .grace_pair_loss
#'
#' A step of the grace_native implementation. Called by \code{.grace_objective},
#' \code{morie_pair_loss}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param U A matrix; indexed by row and column.
#' @param V A matrix; indexed by row and column.
#' @param i Passed to \code{!=}.
#' @param tau Coerced to numeric by the body, with \code{as.numeric}. Defaults to \code{0.5}.
#' @param intra A flag; the body branches on it. Defaults to \code{TRUE}.
#' @return A numeric value.
#' @export
.grace_pair_loss <- function(U, V, i, tau = 0.5, intra = TRUE) {
  t <- as.numeric(tau)
  if (t <= 0) {
    stop("grace: the temperature must be positive")
  }
  pos <- exp(.grace_cos(U[i, ], V[i, ]) / t)
  n_V <- nrow(V)
  n_U <- nrow(U)
  inter <- 0
  for (j in seq_len(n_V)) {
    if (j != i) inter <- inter + exp(.grace_cos(U[i, ], V[j, ]) / t)
  }
  same <- 0
  if (intra) {
    for (j in seq_len(n_U)) {
      if (j != i) same <- same + exp(.grace_cos(U[i, ], U[j, ]) / t)
    }
  }
  -log(pos / (pos + inter + same))
}

#' .grace_objective
#'
#' A step of the grace_native implementation. Called by \code{morie_grace},
#' \code{morie_graphcontrastive}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param U A matrix; passed to \code{nrow}.
#' @param V A matrix; passed to \code{nrow}.
#' @param tau Passed to \code{.grace_pair_loss}. Defaults to \code{0.5}.
#' @param intra Passed to \code{.grace_pair_loss}. Defaults to \code{TRUE}.
#' @return A list with \code{estimate}, \code{loss}, \code{tau},
#' \code{intra_view_negatives}, \code{n_nodes}, \code{method}, \code{note}.
#' @export
#' @examples
#' x <- c(1.2, 2.4, 3.1, 4.8, 5.3, 6.7, 7.1, 8.9)
#' res <- .grace_objective(U = x, V = x)
#' res
.grace_objective <- function(U, V, tau = 0.5, intra = TRUE) {
  U <- as.matrix(U)
  V <- as.matrix(V)
  n <- nrow(U)
  if (n != nrow(V)) {
    stop(sprintf("grace: the views have %d and %d nodes", n, nrow(V)))
  }
  if (n < 2) {
    stop("grace: at least 2 nodes are needed for negatives")
  }
  tot <- 0
  for (i in seq_len(n)) {
    tot <- tot + .grace_pair_loss(U, V, i, tau, intra) +
                .grace_pair_loss(V, U, i, tau, intra)
  }
  list(
    estimate = tot / (2 * n),
    loss = tot / (2 * n),
    tau = as.numeric(tau),
    intra_view_negatives = as.logical(intra),
    n_nodes = n,
    method = "node-level contrastive objective; Zhu et al. (2020) Sec. 3",
    note = "negatives come from BOTH views -- inter-view and intra-view; omitting the latter leaves same-view nodes unseparated"
  )
}

#' .grace_cheatsheet
#'
#' A step of the grace_native implementation. Called by \code{.grace_morie_cheatsheet}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return A character value.
#' @export
#' @examples
#' res <- .grace_cheatsheet()
#' res
.grace_cheatsheet <- function() {
  paste("grace: contrast NODE AGAINST NODE, not node against a ",
        "global summary -- DGI's local-global objective leans on ",
        "the readout being expressive. Two views by corrupting ",
        "BOTH topology (drop edges) and attributes (mask feature ",
        "DIMENSIONS). (u_i, v_i) is positive; every other node is ",
        "a negative in the other view AND in the same view, and ",
        "the INTRA-view term is the one people drop. InfoNCE with ",
        "cosine similarity and temperature tau, averaged ",
        "symmetrically. Fully unsupervised.", collapse = "")
}

#' morie_drop_edges
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param edges Passed to \code{.grace_drop_edges}.
#' @param p Passed to \code{.grace_drop_edges}.
#' @param rng Passed to \code{.grace_drop_edges}.
#' @return The value of \code{.grace_drop_edges}.
#' @export
morie_drop_edges <- function(edges, p, rng) {
  .grace_drop_edges(edges, p, rng)
}

#' morie_mask_features
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X Passed to \code{.grace_mask_features}.
#' @param p Passed to \code{.grace_mask_features}.
#' @param rng Passed to \code{.grace_mask_features}.
#' @return The value of \code{.grace_mask_features}.
#' @export
morie_mask_features <- function(X, p, rng) {
  .grace_mask_features(X, p, rng)
}

#' morie_generate_view
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X Passed to \code{.grace_generate_view}.
#' @param edges Passed to \code{.grace_generate_view}.
#' @param p_edge Passed to \code{.grace_generate_view}.
#' @param p_feature Passed to \code{.grace_generate_view}.
#' @param rng Passed to \code{.grace_generate_view}.
#' @return The value of \code{.grace_generate_view}.
#' @export
morie_generate_view <- function(X, edges, p_edge, p_feature, rng) {
  .grace_generate_view(X, edges, p_edge, p_feature, rng)
}

#' morie_pair_loss
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param U A matrix; passed to \code{as.matrix}.
#' @param V A matrix; passed to \code{as.matrix}.
#' @param i Passed to \code{.grace_pair_loss}.
#' @param tau Passed to \code{.grace_pair_loss}. Defaults to \code{0.5}.
#' @param intra Passed to \code{.grace_pair_loss}. Defaults to \code{TRUE}.
#' @return The value of \code{.grace_pair_loss}.
#' @export
morie_pair_loss <- function(U, V, i, tau = 0.5, intra = TRUE) {
  U <- as.matrix(U)
  V <- as.matrix(V)
  .grace_pair_loss(U, V, i, tau, intra)
}

#' morie_grace
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param U Passed to \code{.grace_objective}.
#' @param V Passed to \code{.grace_objective}.
#' @param tau Passed to \code{.grace_objective}. Defaults to \code{0.5}.
#' @param intra Passed to \code{.grace_objective}. Defaults to \code{TRUE}.
#' @return The value of \code{.grace_objective}.
#' @export
morie_grace <- function(U, V, tau = 0.5, intra = TRUE) {
  .grace_objective(U, V, tau, intra)
}

#' morie_graphcontrastive
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param U Passed to \code{.grace_objective}.
#' @param V Passed to \code{.grace_objective}.
#' @param tau Passed to \code{.grace_objective}. Defaults to \code{0.5}.
#' @param intra Passed to \code{.grace_objective}. Defaults to \code{TRUE}.
#' @return The value of \code{.grace_objective}.
#' @export
morie_graphcontrastive <- function(U, V, tau = 0.5, intra = TRUE) {
  .grace_objective(U, V, tau, intra)
}

#' .grace_morie_cheatsheet
#'
#' A step of the grace_native implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.grace_cheatsheet}.
#' @export
#' @examples
#' res <- .grace_morie_cheatsheet()
#' res
.grace_morie_cheatsheet <- function() {
  .grace_cheatsheet()
}
