# Documentation-only stubs for the compiled entry points in
# R/RcppExports.R. That file is regenerated by Rcpp::compileAttributes()
# and must stay pure glue; roxygen written inside it is lost on the next
# regeneration (which is exactly what happened on 2026-09-01).

#' .rmorie_sha256_impl
#'
#' A step of the RcppExports implementation. Called by \code{.morie_wrapping_key}, \code{morie_crypto_lamport_sign}, \code{morie_crypto_lamport_verify}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param data Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_sha256_impl
#' @rdname dot-rmorie_sha256_impl
NULL

#' .rmorie_sha256_hex_impl
#'
#' A step of the RcppExports implementation. Called by \code{.morie_sha256_hex}, \code{create_reproducibility_manifest}, \code{morie_crypto_lamport_keygen} and 4 others in the module.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param data Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_sha256_hex_impl
#' @rdname dot-rmorie_sha256_hex_impl
NULL

#' .rmorie_hmac_sha256_impl
#'
#' A step of the RcppExports implementation. Called by \code{.morie_hkdf_sha256}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param key Passed to \code{.Call}.
#' @param msg Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_hmac_sha256_impl
#' @rdname dot-rmorie_hmac_sha256_impl
NULL

#' .rmorie_pbkdf2_sha256_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param password Passed to \code{.Call}.
#' @param salt Passed to \code{.Call}.
#' @param iterations Passed to \code{.Call}.
#' @param dklen Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_pbkdf2_sha256_impl
#' @rdname dot-rmorie_pbkdf2_sha256_impl
NULL

#' .morie_blake2b_impl
#'
#' A step of the RcppExports implementation. Called by \code{morie_secarg_prehash}, \code{morie_secarg_variable_hash}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param data Passed to \code{.Call}.
#' @param outlen Passed to \code{.Call}.
#' @param key Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_blake2b_impl
#' @rdname dot-morie_blake2b_impl
NULL

#' .morie_argon2_impl
#'
#' A step of the RcppExports implementation. Called by \code{morie_secarg_argon2}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param password Passed to \code{.Call}.
#' @param salt Passed to \code{.Call}.
#' @param memory Passed to \code{.Call}.
#' @param passes Passed to \code{.Call}.
#' @param parallelism Passed to \code{.Call}.
#' @param tag_length Passed to \code{.Call}.
#' @param variant Passed to \code{.Call}.
#' @param secret Passed to \code{.Call}.
#' @param associated Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_argon2_impl
#' @rdname dot-morie_argon2_impl
NULL

#' .rmorie_liboqs_available_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_liboqs_available_impl
#' @rdname dot-rmorie_liboqs_available_impl
NULL

#' .rmorie_liboqs_version_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_liboqs_version_impl
#' @rdname dot-rmorie_liboqs_version_impl
NULL

#' .rmorie_mlkem768_keygen_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_mlkem768_keygen_impl
#' @rdname dot-rmorie_mlkem768_keygen_impl
NULL

#' .rmorie_mlkem768_encaps_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param pk_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_mlkem768_encaps_impl
#' @rdname dot-rmorie_mlkem768_encaps_impl
NULL

#' .rmorie_mlkem768_decaps_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param sk_sxp Passed to \code{.Call}.
#' @param ct_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_mlkem768_decaps_impl
#' @rdname dot-rmorie_mlkem768_decaps_impl
NULL

#' .rmorie_mldsa65_keygen_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_mldsa65_keygen_impl
#' @rdname dot-rmorie_mldsa65_keygen_impl
NULL

#' .rmorie_mldsa65_sign_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param sk_sxp Passed to \code{.Call}.
#' @param message_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_mldsa65_sign_impl
#' @rdname dot-rmorie_mldsa65_sign_impl
NULL

#' .rmorie_mldsa65_verify_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param pk_sxp Passed to \code{.Call}.
#' @param message_sxp Passed to \code{.Call}.
#' @param signature_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_mldsa65_verify_impl
#' @rdname dot-rmorie_mldsa65_verify_impl
NULL

#' .rmorie_slhdsa128s_keygen_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_slhdsa128s_keygen_impl
#' @rdname dot-rmorie_slhdsa128s_keygen_impl
NULL

#' .rmorie_slhdsa128s_sign_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param sk_sxp Passed to \code{.Call}.
#' @param message_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_slhdsa128s_sign_impl
#' @rdname dot-rmorie_slhdsa128s_sign_impl
NULL

#' .rmorie_slhdsa128s_verify_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param pk_sxp Passed to \code{.Call}.
#' @param message_sxp Passed to \code{.Call}.
#' @param signature_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_slhdsa128s_verify_impl
#' @rdname dot-rmorie_slhdsa128s_verify_impl
NULL

#' .rmorie_hqc128_keygen_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_hqc128_keygen_impl
#' @rdname dot-rmorie_hqc128_keygen_impl
NULL

#' .rmorie_hqc128_encaps_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param pk_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_hqc128_encaps_impl
#' @rdname dot-rmorie_hqc128_encaps_impl
NULL

#' .rmorie_hqc128_decaps_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param sk_sxp Passed to \code{.Call}.
#' @param ct_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_hqc128_decaps_impl
#' @rdname dot-rmorie_hqc128_decaps_impl
NULL

#' .rmorie_sodium_available_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_sodium_available_impl
#' @rdname dot-rmorie_sodium_available_impl
NULL

#' .rmorie_sodium_version_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_sodium_version_impl
#' @rdname dot-rmorie_sodium_version_impl
NULL

#' .rmorie_chacha20poly1305_encrypt_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param key_sxp Passed to \code{.Call}.
#' @param nonce_sxp Passed to \code{.Call}.
#' @param plaintext_sxp Passed to \code{.Call}.
#' @param aad_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_chacha20poly1305_encrypt_impl
#' @rdname dot-rmorie_chacha20poly1305_encrypt_impl
NULL

#' .rmorie_chacha20poly1305_decrypt_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param key_sxp Passed to \code{.Call}.
#' @param nonce_sxp Passed to \code{.Call}.
#' @param ct_with_tag_sxp Passed to \code{.Call}.
#' @param aad_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_chacha20poly1305_decrypt_impl
#' @rdname dot-rmorie_chacha20poly1305_decrypt_impl
NULL

#' .rmorie_hkdf_sha256_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param ikm_sxp Passed to \code{.Call}.
#' @param length_sxp Passed to \code{.Call}.
#' @param salt_sxp Passed to \code{.Call}.
#' @param info_sxp Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_hkdf_sha256_impl
#' @rdname dot-rmorie_hkdf_sha256_impl
NULL

#' .rmorie_random_bytes_impl
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param n Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .rmorie_random_bytes_impl
#' @rdname dot-rmorie_random_bytes_impl
NULL

#' .morie_twfe_demean_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_twfe_demean}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param M Passed to \code{.Call}.
#' @param g1 Passed to \code{.Call}.
#' @param g2 Passed to \code{.Call}.
#' @param K1 Passed to \code{.Call}.
#' @param K2 Passed to \code{.Call}.
#' @param tol Passed to \code{.Call}. Defaults to \code{1e-11}.
#' @param max_iter Passed to \code{.Call}. Defaults to \code{500L}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_twfe_demean_cpp
#' @rdname dot-morie_twfe_demean_cpp
NULL

#' morie_dsp_lms_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_dsp_lms}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param d Passed to \code{.Call}.
#' @param order Passed to \code{.Call}.
#' @param mu Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_dsp_lms_cpp
#' @rdname morie_dsp_lms_cpp
NULL

#' morie_dsp_nlms_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_dsp_nlms}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param d Passed to \code{.Call}.
#' @param order Passed to \code{.Call}.
#' @param mu Passed to \code{.Call}.
#' @param eps Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_dsp_nlms_cpp
#' @rdname morie_dsp_nlms_cpp
NULL

#' morie_dsp_rls_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_dsp_rls}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param d Passed to \code{.Call}.
#' @param order Passed to \code{.Call}.
#' @param lam Passed to \code{.Call}.
#' @param delta Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_dsp_rls_cpp
#' @rdname morie_dsp_rls_cpp
NULL

#' morie_dsp_cross_correlation_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_dsp_cross_correlation}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param y Passed to \code{.Call}.
#' @param max_lag Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_dsp_cross_correlation_cpp
#' @rdname morie_dsp_cross_correlation_cpp
NULL

#' morie_dsp_median_filter_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_dsp_median_filter}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param kernel_size Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_dsp_median_filter_cpp
#' @rdname morie_dsp_median_filter_cpp
NULL

#' morie_normal_pdf_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_normal_pdf}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param mean Passed to \code{.Call}.
#' @param sd Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_normal_pdf_cpp
#' @rdname morie_normal_pdf_cpp
NULL

#' morie_mean_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_mean}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_mean_cpp
#' @rdname morie_mean_cpp
NULL

#' morie_var_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_var}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param ddof Passed to \code{.Call}. Defaults to \code{1L}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_var_cpp
#' @rdname morie_var_cpp
NULL

#' morie_cor_pearson_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_cor_pearson}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param x Passed to \code{.Call}.
#' @param y Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_cor_pearson_cpp
#' @rdname morie_cor_pearson_cpp
NULL

#' morie_hawkes_ll_exp_const_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.hawkes_nll_cpp}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param t Passed to \code{.Call}.
#' @param T_horizon Passed to \code{.Call}.
#' @param a0 Passed to \code{.Call}.
#' @param eta Passed to \code{.Call}.
#' @param beta Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_ll_exp_const_cpp
#' @rdname morie_hawkes_ll_exp_const_cpp
NULL

#' morie_hawkes_ll_weibull_const_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.hawkes_nll_cpp}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param t Passed to \code{.Call}.
#' @param T_horizon Passed to \code{.Call}.
#' @param a0 Passed to \code{.Call}.
#' @param eta Passed to \code{.Call}.
#' @param alpha Passed to \code{.Call}.
#' @param lam Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_ll_weibull_const_cpp
#' @rdname morie_hawkes_ll_weibull_const_cpp
NULL

#' morie_hawkes_ll_lomax_const_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.hawkes_nll_cpp}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param t Passed to \code{.Call}.
#' @param T_horizon Passed to \code{.Call}.
#' @param a0 Passed to \code{.Call}.
#' @param eta Passed to \code{.Call}.
#' @param alpha Passed to \code{.Call}.
#' @param c Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_ll_lomax_const_cpp
#' @rdname morie_hawkes_ll_lomax_const_cpp
NULL

#' morie_hawkes_ll_gamma_const_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.hawkes_nll_cpp}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param t Passed to \code{.Call}.
#' @param T_horizon Passed to \code{.Call}.
#' @param a0 Passed to \code{.Call}.
#' @param eta Passed to \code{.Call}.
#' @param alpha Passed to \code{.Call}.
#' @param beta Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_ll_gamma_const_cpp
#' @rdname morie_hawkes_ll_gamma_const_cpp
NULL

#' morie_hawkes_kernel_density_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.tps_hwka_kernel_density}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param u Passed to \code{.Call}.
#' @param kind Passed to \code{.Call}.
#' @param psi Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_kernel_density_cpp
#' @rdname morie_hawkes_kernel_density_cpp
NULL

#' morie_hawkes_kernel_cdf_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.tps_hwka_kernel_cdf}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param u Passed to \code{.Call}.
#' @param kind Passed to \code{.Call}.
#' @param psi Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_kernel_cdf_cpp
#' @rdname morie_hawkes_kernel_cdf_cpp
NULL

#' morie_hawkes_pair_excitation_sum_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.tps_hwka_neg_loglik_general}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param t Passed to \code{.Call}.
#' @param eta Passed to \code{.Call}.
#' @param kind Passed to \code{.Call}.
#' @param psi Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_pair_excitation_sum_cpp
#' @rdname morie_hawkes_pair_excitation_sum_cpp
NULL

#' morie_hawkes_baseline_integral_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.tps_hwka_baseline_integral}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param T_horizon Passed to \code{.Call}.
#' @param alpha Passed to \code{.Call}.
#' @param n_grid Passed to \code{.Call}. Defaults to \code{0L}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_hawkes_baseline_integral_cpp
#' @rdname morie_hawkes_baseline_integral_cpp
NULL

#' Synchronous HTTP(S) GET via the shared libcurl backend (C++)
#'
#' Phase-3VV promoted helper. Returns the response body as a length-1
#' character vector. On any libcurl-level failure returns the empty
#' string (parity with the SIU parser's transport contract).
#'
#' @param url Fully-formed URL.
#' @param timeout_s Total request timeout in seconds.
#' @param headers Character vector of `"Key: Value"` HTTP headers.
#' @param user_agent Optional User-Agent override.
#' @param follow_redirects Logical; default `TRUE`.
#' @return Length-1 character vector with the response body.
#' @keywords internal
#' @name .morie_http_get
#' @rdname dot-morie_http_get
NULL

#' Binary-safe HTTP(S) GET via libcurl
#'
#' Phase-3XX get_bytes wrapper. Returns the response body as an R
#' raw vector (no NUL truncation), suitable for shapefiles, FGDB
#' zips, PDFs, KMZ, and any other binary payload the std::string
#' get() interface would corrupt.
#'
#' @inheritParams .morie_http_get
#' @return Raw vector with the response body. Empty raw vector on
#'   any libcurl-level transport failure (parity with .morie_http_get's
#'   empty-string-on-failure contract).
#' @keywords internal
#' @name .morie_http_get_bytes
#' @rdname dot-morie_http_get_bytes
NULL

#' Synchronous HTTP(S) POST via the shared libcurl backend (C++)
#'
#' Phase-3YY helper. Body is sent verbatim; for JSON payloads call
#' `.s03json_toJSON(...)` before passing in. Default content_type
#' is "application/json"; pass "" to skip the Content-Type header
#' (caller can set it explicitly via `headers`).
#'
#' @inheritParams .morie_http_get
#' @param body Length-1 character vector containing the request body.
#' @param content_type Content-Type header value (default
#'   `"application/json"`). Empty string skips the header.
#' @return Length-1 character vector with the response body. Empty
#'   string on libcurl-level transport failure.
#' @keywords internal
#' @name .morie_http_post
#' @rdname dot-morie_http_post
NULL

#' Status-aware HTTP(S) GET via the libcurl backend (C++)
#'
#' Phase-3ZZ helper for callers that need HTTP status-code
#' inspection (401/403/4xx error handling). Returns a length-2
#' list: `body` (character) + `status_code` (integer, 0 on
#' transport failure).
#'
#' @inheritParams .morie_http_get
#' @return Named list with elements `body` (length-1 character
#'   vector with the response body, possibly empty on 4xx) and
#'   `status_code` (length-1 integer HTTP status, 0 on libcurl-
#'   level transport failure).
#' @keywords internal
#' @name .morie_http_get_with_status
#' @rdname dot-morie_http_get_with_status
NULL

#' Status-aware HTTP(S) POST via the libcurl backend (C++)
#'
#' Phase-3ZZ helper. Same status-code-return contract as
#' .morie_http_get_with_status, but for POST bodies.
#'
#' @inheritParams .morie_http_post
#' @return Named list with elements `body` + `status_code`.
#' @keywords internal
#' @name .morie_http_post_with_status
#' @rdname dot-morie_http_post_with_status
NULL

#' libcurl version string the morie C++ backend was built against
#' @return Length-1 character vector.
#' @keywords internal
#' @name .morie_http_curl_version
#' @rdname dot-morie_http_curl_version
NULL

#' morie_matching_mahalanobis_pairs_cpp
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X_t Passed to \code{.Call}.
#' @param X_c Passed to \code{.Call}.
#' @param S_inv Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_matching_mahalanobis_pairs_cpp
#' @rdname morie_matching_mahalanobis_pairs_cpp
NULL

#' morie_matching_euclidean_pairs_cpp
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X_t Passed to \code{.Call}.
#' @param X_c Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_matching_euclidean_pairs_cpp
#' @rdname morie_matching_euclidean_pairs_cpp
NULL

#' morie_matching_nn_select_cpp
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param D Passed to \code{.Call}.
#' @param with_replacement Passed to \code{.Call}.
#' @param caliper Passed to \code{.Call}.
#' @param n_neighbors Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_matching_nn_select_cpp
#' @rdname morie_matching_nn_select_cpp
NULL

#' morie_matching_cem_strata_cpp
#'
#' A step of the RcppExports implementation. No other function in the package calls it.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X_binned Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_matching_cem_strata_cpp
#' @rdname morie_matching_cem_strata_cpp
NULL

#' morie_matching_abadie_imbens_kernel_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_matching_abadie_imbens_se}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param y Passed to \code{.Call}.
#' @param t Passed to \code{.Call}.
#' @param treated_pos Passed to \code{.Call}.
#' @param control_pos Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_matching_abadie_imbens_kernel_cpp
#' @rdname morie_matching_abadie_imbens_kernel_cpp
NULL

#' .morie_match_greedy_kd_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_match_genetic_eval}, \code{.morie_match_genetic_native}, \code{.morie_match_mahalanobis_native}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param treated Passed to \code{.Call}.
#' @param control Passed to \code{.Call}.
#' @param ratio Passed to \code{.Call}.
#' @param caliper_dist Passed to \code{.Call}.
#' @param replace Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_match_greedy_kd_cpp
#' @rdname dot-morie_match_greedy_kd_cpp
NULL

#' .morie_match_greedy_1d_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_match_greedy_1d}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param treated_val Passed to \code{.Call}.
#' @param control_val Passed to \code{.Call}.
#' @param ratio Passed to \code{.Call}.
#' @param caliper_width Passed to \code{.Call}.
#' @param replace Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_match_greedy_1d_cpp
#' @rdname dot-morie_match_greedy_1d_cpp
NULL

#' .morie_match_optimal_1d_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_match_optimal_native}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param treated_val Passed to \code{.Call}.
#' @param control_val Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_match_optimal_1d_cpp
#' @rdname dot-morie_match_optimal_1d_cpp
NULL

#' .morie_match_optimal_assign_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_match_optimal_native}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param treated Passed to \code{.Call}.
#' @param control Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_match_optimal_assign_cpp
#' @rdname dot-morie_match_optimal_assign_cpp
NULL

#' .morie_rlearner_forest_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_cate_dr_learner}, \code{.morie_causal_forest_native}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X Passed to \code{.Call}.
#' @param pseudo Passed to \code{.Call}.
#' @param weight Passed to \code{.Call}.
#' @param Xpred Passed to \code{.Call}.
#' @param n_trees Passed to \code{.Call}.
#' @param max_depth Passed to \code{.Call}.
#' @param min_node Passed to \code{.Call}.
#' @param subsample Passed to \code{.Call}.
#' @param seed Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_rlearner_forest_cpp
#' @rdname dot-morie_rlearner_forest_cpp
NULL

#' .morie_rlm_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_rlm}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X Passed to \code{.Call}.
#' @param y Passed to \code{.Call}.
#' @param k Passed to \code{.Call}.
#' @param maxit Passed to \code{.Call}.
#' @param acc Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_rlm_cpp
#' @rdname dot-morie_rlm_cpp
NULL

#' .morie_sobol_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_sobol}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param n Passed to \code{.Call}.
#' @param d Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_sobol_cpp
#' @rdname dot-morie_sobol_cpp
NULL

#' .morie_knn_index_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_knn_index}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param coords Passed to \code{.Call}.
#' @param k Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_knn_index_cpp
#' @rdname dot-morie_knn_index_cpp
NULL

#' .morie_coord_descent_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_coord_descent}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param Xs Passed to \code{.Call}.
#' @param yc Passed to \code{.Call}.
#' @param alpha Passed to \code{.Call}.
#' @param lambda Passed to \code{.Call}.
#' @param max_iter Passed to \code{.Call}.
#' @param tol Passed to \code{.Call}.
#' @param warm Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_coord_descent_cpp
#' @rdname dot-morie_coord_descent_cpp
NULL

#' .morie_tsne_descent_cpp
#'
#' A step of the RcppExports implementation. Called by \code{.morie_tsne}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param P Passed to \code{.Call}.
#' @param Y Passed to \code{.Call}.
#' @param n_iter Passed to \code{.Call}.
#' @param eta Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name .morie_tsne_descent_cpp
#' @rdname dot-morie_tsne_descent_cpp
NULL

#' morie_spatial_nominate_iterate_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_spatial_voting_dw_nominate}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param votes Passed to \code{.Call}.
#' @param X Passed to \code{.Call}.
#' @param w Passed to \code{.Call}.
#' @param nv Passed to \code{.Call}.
#' @param mid Passed to \code{.Call}.
#' @param beta Passed to \code{.Call}.
#' @param max_iter Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_spatial_nominate_iterate_cpp
#' @rdname morie_spatial_nominate_iterate_cpp
NULL

#' morie_spatial_emirt_theta_update_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_spatial_voting_em_irt}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param theta Passed to \code{.Call}.
#' @param a Passed to \code{.Call}.
#' @param d Passed to \code{.Call}.
#' @param votes Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_spatial_emirt_theta_update_cpp
#' @rdname morie_spatial_emirt_theta_update_cpp
NULL

#' morie_spatial_smacof_step_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_spatial_voting_smacof}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param X Passed to \code{.Call}.
#' @param D Passed to \code{.Call}.
#' @param W Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_spatial_smacof_step_cpp
#' @rdname morie_spatial_smacof_step_cpp
NULL

#' morie_spatial_classical_mds_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_spatial_voting_classical_mds}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param D Passed to \code{.Call}.
#' @param n_dims Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_spatial_classical_mds_cpp
#' @rdname morie_spatial_classical_mds_cpp
NULL

#' morie_spatial_wordfish_omega_update_cpp
#'
#' A step of the RcppExports implementation. Called by \code{morie_spatial_voting_wordfish}.
#' See the file header for the source the module follows.
#' source it follows.
#'
#' @param dtm Passed to \code{.Call}.
#' @param psi Passed to \code{.Call}.
#' @param alpha Passed to \code{.Call}.
#' @param beta Passed to \code{.Call}.
#' @param omega Passed to \code{.Call}.
#' @return The value of \code{.Call}.
#' @export
#' @name morie_spatial_wordfish_omega_update_cpp
#' @rdname morie_spatial_wordfish_omega_update_cpp
NULL

#' Binary C-SVC via SMO (compiled)
#' @noRd
#' @name morie_svc_train_cpp
#' @rdname morie_svc_train_cpp
NULL

#' eps-SVR via SMO (compiled)
#' @noRd
#' @name morie_svr_train_cpp
#' @rdname morie_svr_train_cpp
NULL

#' Decision values for new data given fitted SVM coefficients (compiled)
#' @noRd
#' @name morie_svm_decision_cpp
#' @rdname morie_svm_decision_cpp
NULL

#' Grow one regression / second-order tree (compiled)
#' @noRd
#' @name morie_tree_fit_cpp
#' @rdname morie_tree_fit_cpp
NULL

#' Predict from a flattened tree (compiled)
#' @noRd
#' @name morie_tree_predict_cpp
#' @rdname morie_tree_predict_cpp
NULL

#' Fetch a single URL over HTTP(S) via libcurl
#'
#' Internal building block of the SIU parser. Returns the response
#' body, or an empty string on any transport-level failure.
#'
#' @param url URL to fetch.
#' @param timeout_s Request timeout in seconds.
#' @return The response body as a length-1 character vector.
#' @keywords internal
#' @name .siu_http_get
#' @rdname dot-siu_http_get
NULL

#' libcurl version string morie was built against
#' @return A length-1 character vector.
#' @keywords internal
#' @name .siu_curl_version
#' @rdname dot-siu_curl_version
NULL

#' Fetch many URLs concurrently via libcurl, with rate-limiting + retry
#'
#' Drives up to \code{concurrency} simultaneous transfers, but with a
#' global token-bucket limit of \code{rate_rps} request starts per
#' second across the whole pool. HTTP 429/502/503/504 and transport
#' errors are retried up to \code{max_retries} times with exponential
#' backoff (250ms * 2^attempt). Final failures yield an empty string
#' at their slot.
#'
#' Throttling is the safe default for SIU and similar small-gov
#' endpoints: hammering them with 16-24 concurrent requests triggers
#' WAF/Cloudflare-style bot-protection that returns short
#' interstitial pages, which look like data but aren't.
#'
#' @param urls Character vector of URLs.
#' @param concurrency Maximum simultaneous transfers.
#' @param timeout_s Per-request timeout in seconds.
#' @param rate_rps Maximum request starts per second across the pool.
#'   Default \code{4.0} is a polite scrape rate that stays well under
#'   any common WAF threshold. Set very large (e.g. \code{1e9}) to
#'   effectively disable throttling.
#' @param max_retries Maximum retry attempts per URL on 429/5xx /
#'   transport failure.
#' @return A character vector of response bodies, parallel to \code{urls}.
#' @keywords internal
#' @name .siu_http_get_many
#' @rdname dot-siu_http_get_many
NULL

#' Fetch many URLs and return body + http_code + attempts
#'
#' Same throttle/retry behaviour as \code{.siu_http_get_many} but the
#' return value preserves the HTTP status code and attempt count for
#' each URL, so callers can distinguish a healthy 200 with a small
#' body from a 429/503/short interstitial. Used by the DRID manifest
#' builder (\code{morie_siu_refresh_manifest}).
#'
#' @inheritParams .siu_http_get_many
#' @return A list with three parallel slots: \code{body} (character),
#'   \code{http_code} (integer), \code{attempts} (integer).
#' @keywords internal
#' @name .siu_http_get_many_with_status
#' @rdname dot-siu_http_get_many_with_status
NULL

#' Parse one SIU director's-report HTML page into the 64-column schema
#'
#' @param html The report page HTML.
#' @param drid The director's-report id.
#' @param url The source URL of the report page.
#' @return A named character vector with the 64 SIU dataset columns;
#'   report-derived fields are populated, news fields left empty.
#' @keywords internal
#' @name .siu_parse_report
#' @rdname dot-siu_parse_report
NULL

#' Parse one SIU news-release HTML page
#'
#' @param html The news-release page HTML.
#' @param nrid The news-release id.
#' @param url The source URL of the news-release page.
#' @return A named character vector: nrid, source_url_news,
#'   news_release_title, news_release_date_iso, news_release_date_raw,
#'   news_release_summary.
#' @keywords internal
#' @name .siu_parse_news
#' @rdname dot-siu_parse_news
NULL
