# SPDX-License-Identifier: AGPL-3.0-or-later
# R arm of rlhfRS -- reinforcement learning for recommendation. Mirrors
# src/morie/fn/rlhfRS.py operation for operation, on the shared RNG in
# R/aaa_helpers_ghc_rng.R and the shared numerics in
# R/aaa_helpers_w3num.R.
#
# A recommender is not a classifier. It does not predict a label, it
# takes an ACTION -- it puts an item in front of someone -- and that
# action changes what happens next. So the objective is a return over a
# session, not an accuracy on a held-out row, and the natural formalism
# is a Markov decision process whose state is the interaction history,
# whose action is the item shown, and whose reward is what the user did
# about it.
#
# Which creates the problem this module is mostly about. You cannot
# measure a new policy by replaying the log, because the log was
# generated by a DIFFERENT policy. Three published estimators correct
# for that, and all three are here because they fail in different ways.
#
#   ips    inverse propensity scoring. Unbiased, and its variance
#          explodes when the two policies disagree.
#   snips  the same, divided by the mean weight instead of by the
#          sample size. Slightly biased, far steadier, and it cannot
#          return a value outside the range of the rewards it saw,
#          which the plain estimator can and does.
#   dr     doubly robust: a reward model plus the propensity correction
#          applied to its residual. Right if EITHER the model or the
#          propensities are right.
#
# THE SUPPORT CONDITION IS ENFORCED, NOT ASSUMED. If the log contains a
# state where the target policy would take an action the logging policy
# could never have taken, no reweighting of that log can estimate the
# target's value there. The module refuses and names the state, rather
# than returning a number whose error has no bound.
#
# Also included, because a recommender is judged on a ranked slate:
# precision at k, normalised discounted cumulative gain at k, and the
# mean reciprocal rank, by their textbook definitions.
#
# References
#   Zhao, X., Zhang, L., Ding, Z., Xia, L., Tang, J. and Yin, D. (2018)
#     "Recommendations with negative feedback via pairwise deep
#     reinforcement learning." KDD, 1040-1048.
#     doi:10.1145/3219819.3219886.
#   Horvitz, D.G. and Thompson, D.J. (1952) "A generalization of
#     sampling without replacement from a finite universe." JASA
#     47(260), 663-685.
#   Swaminathan, A. and Joachims, T. (2015) "The self-normalized
#     estimator for counterfactual learning." NeurIPS 28, 3231-3239.
#   Dudik, M., Langford, J. and Li, L. (2011) "Doubly robust policy
#     evaluation and learning." ICML, 1097-1104.
#   Jarvelin, K. and Kekalainen, J. (2002) "Cumulated gain-based
#     evaluation of IR techniques." ACM TOIS 20(4), 422-446.

.rlhfRS_estimators <- c("ips", "snips", "dr")

#' The share of the top k that were relevant
#'
#' @param relevance The graded relevance of the ranked list.
#' @param k The cut-off.
#' @return A number between zero and one.
#' @export
morie_rlhfRS_precision <- function(relevance, k) {
  k <- as.integer(k)
  if (k < 1L) stop("a cut-off below one ranks nothing")
  top <- relevance[seq_len(min(k, length(relevance)))]
  sum(top > 0) / k
}

#' Discounted cumulative gain over its own best possible value
#'
#' The discount is one over the log base two of the rank plus one, so
#' the first position is undiscounted and the tenth is worth about a
#' third of it. Dividing by the ideal ordering's gain makes it one for a
#' perfect ranking and comparable across queries with different numbers
#' of relevant items.
#'
#' A query with nothing relevant has an ideal gain of zero, so the ratio
#' is undefined; it is reported as zero, and that is a choice, not an
#' accident of the arithmetic.
#'
#' @param relevance The graded relevance of the ranked list.
#' @param k The cut-off.
#' @return A number between zero and one.
#' @export
morie_rlhfRS_ndcg <- function(relevance, k) {
  k <- as.integer(k)
  if (k < 1L) stop("a cut-off below one ranks nothing")
  rel <- as.numeric(relevance)
  dcg <- function(v) {
    m <- min(k, length(v))
    if (m < 1L) return(0)
    .w3_csum(vapply(seq_len(m), function(i)
      v[i] / (log(i + 1) / log(2)), numeric(1)))
  }
  ideal <- dcg(sort(rel, decreasing = TRUE))
  if (ideal > 0) dcg(rel) / ideal else 0
}

#' One over the rank of the first relevant item, or zero
#'
#' @param relevance The graded relevance of the ranked list.
#' @return A number between zero and one.
#' @export
morie_rlhfRS_mrr <- function(relevance) {
  for (i in seq_along(relevance)) if (relevance[i] > 0) return(1 / i)
  0
}

#' Run the policy in a tabular session environment
#'
#' The environment gives the states, the actions, the transition
#' probabilities and the expected reward of each state-action pair; the
#' policy gives the probability of each action in each state. Both are
#' indexed by position, so the environment and the policy cannot
#' silently disagree about which action is which.
#'
#' The return is discounted, because a session is not infinite and a
#' click now is worth more than a click after the user has left.
#'
#' @param env The environment.
#' @param policy A matrix of action probabilities per state.
#' @param n_episodes How many sessions.
#' @param horizon How many steps each.
#' @param gamma The discount.
#' @param seed The random stream.
#' @return A list with the returns, their mean and standard error, and
#'   the visitation counts.
#' @export
morie_rlhfRS_rollout <- function(env, policy, n_episodes = 20L,
                                 horizon = 10L, gamma = 0.9,
                                 seed = 0) {
  P <- env$transition; R <- env$reward
  n_s <- length(P); n_a <- length(P[[1]])
  if (nrow(policy) != n_s || ncol(policy) != n_a)
    stop("the policy must give a distribution over the environment's ",
         "actions in every state")
  start <- if (is.null(env$start)) 0L else as.integer(env$start)
  e <- .ghc_rng(seed)
  rets <- numeric(0)
  visits <- matrix(0L, n_s, n_a)
  for (ep in seq_len(as.integer(n_episodes))) {
    s <- start
    g <- 0; d <- 1
    for (h in seq_len(as.integer(horizon))) {
      u <- .ghc_unif(e, 1L)
      acc <- 0; a <- n_a - 1L
      for (j in seq_len(n_a)) {
        acc <- acc + policy[s + 1L, j]
        if (u < acc) { a <- j - 1L; break }
      }
      visits[s + 1L, a + 1L] <- visits[s + 1L, a + 1L] + 1L
      g <- g + d * R[[s + 1L]][a + 1L]
      d <- d * gamma
      u <- .ghc_unif(e, 1L)
      acc <- 0; nxt <- n_s - 1L
      for (j in seq_len(n_s)) {
        acc <- acc + P[[s + 1L]][[a + 1L]][j]
        if (u < acc) { nxt <- j - 1L; break }
      }
      s <- nxt
    }
    rets <- c(rets, g)
  }
  mean <- .w3_csum(rets) / length(rets)
  se <- if (length(rets) > 1L)
    sqrt((.w3_csum((rets - mean) * (rets - mean)) /
            (length(rets) - 1)) / length(rets)) else NaN
  list(returns = rets, mean = mean, se = se, visits = visits)
}

#' Estimate a policy's value from another policy's log
#'
#' The log is a list of state, action and reward triples as they were
#' actually observed. The behaviour vector is the probability the
#' logging policy assigned to the action it took -- the propensity --
#' and it has to come from the logging system, not be re-estimated here,
#' or the correction corrects for the wrong thing.
#'
#' The clip caps the importance weight. It trades unbiasedness for a
#' bounded variance and it is off by default, because a silently clipped
#' estimate is a biased estimate that looks like an unbiased one; the
#' number of weights it bit is reported.
#'
#' @param log The logged decisions.
#' @param policy The target policy.
#' @param behaviour The logging propensities.
#' @param estimator One of ips, snips or dr.
#' @param reward_model A per-state-action reward model, for dr.
#' @param clip A cap on the importance weight, or NULL.
#' @return A list with the estimate, the weights and the diagnostics.
#' @export
morie_rlhfRS_offpolicy <- function(log, policy, behaviour,
                                   estimator = "ips",
                                   reward_model = NULL, clip = NULL) {
  if (!(estimator %in% .rlhfRS_estimators))
    stop("the estimator is ips, snips or dr")
  n <- length(log)
  if (n == 0L) stop("an off-policy estimate needs a log")
  if (length(behaviour) != n)
    stop("one propensity per logged decision")
  # The support condition. Without it the estimate has no bound on its
  # error, so it is refused rather than returned.
  for (i in seq_len(n)) {
    s <- log[[i]][1]; a <- log[[i]][2]
    if (behaviour[i] <= 0 && policy[s + 1L, a + 1L] > 0)
      stop(sprintf(paste0("the target policy takes action %d in state ",
                          "%d, which the logging policy never could: ",
                          "no reweighting of this log can estimate its ",
                          "value there"), as.integer(a), as.integer(s)))
  }
  w <- numeric(n); clipped <- 0L
  for (i in seq_len(n)) {
    s <- log[[i]][1]; a <- log[[i]][2]
    v <- if (behaviour[i] > 0) policy[s + 1L, a + 1L] / behaviour[i]
         else 0
    if (!is.null(clip) && v > clip) { v <- as.numeric(clip)
                                      clipped <- clipped + 1L }
    w[i] <- v
  }
  rs <- vapply(log, function(t) as.numeric(t[3]), numeric(1))
  if (estimator == "ips") {
    est <- .w3_csum(w * rs) / n
  } else if (estimator == "snips") {
    tot <- .w3_csum(w)
    est <- if (tot > 0) .w3_csum(w * rs) / tot else 0
  } else {
    if (is.null(reward_model))
      stop("the doubly robust estimator needs a reward model")
    terms <- numeric(n)
    for (i in seq_len(n)) {
      s <- log[[i]][1]; a <- log[[i]][2]
      base <- .w3_csum(policy[s + 1L, ] * reward_model[s + 1L, ])
      terms[i] <- base + w[i] * (rs[i] - reward_model[s + 1L, a + 1L])
    }
    est <- .w3_csum(terms) / n
  }
  sw <- .w3_csum(w); sw2 <- .w3_csum(w * w)
  ess <- if (sw2 > 0) sw * sw / sw2 else 0
  list(estimate = est, weights = w, n = n, mean_weight = sw / n,
       max_weight = if (n > 0L) max(w) else 0, ess = ess,
       n_clipped = clipped, estimator = estimator)
}

#' Evaluate a recommendation policy, on-policy or from a log
#'
#' An environment carrying transition and reward is simulated. One
#' carrying log and behaviour is evaluated off-policy against those
#' logged decisions. Both may be present, and then both are reported --
#' which is the useful case, because the gap between the simulated value
#' and the off-policy estimate is the thing worth looking at.
#'
#' @param env The environment.
#' @param policy A matrix of action probabilities per state.
#' @param n_episodes,horizon,gamma,seed The rollout settings.
#' @param estimator Which off-policy estimator.
#' @param reward_model A per-state-action reward model, for dr.
#' @param clip A cap on the importance weight, or NULL.
#' @param relevance A ranked relevance vector, or NULL.
#' @param k The ranking cut-off.
#' @return A list with the value estimate or estimates, the visitation,
#'   the ranking metrics, and the off-policy diagnostics.
#' @export
morie_rlhfRS <- function(env, policy, n_episodes = 20L, horizon = 10L,
                         gamma = 0.9, seed = 0, estimator = "ips",
                         reward_model = NULL, clip = NULL,
                         relevance = NULL, k = 5L) {
  has_sim <- !is.null(env$transition) && !is.null(env$reward)
  has_log <- !is.null(env$log) && !is.null(env$behaviour)
  if (!has_sim && !has_log)
    stop("an environment must carry either a transition and reward ",
         "model or a log and its propensities")
  out <- list(method = paste0("session-MDP recommendation with ",
                              "off-policy evaluation"))
  if (has_sim) {
    r <- morie_rlhfRS_rollout(env, policy, n_episodes, horizon, gamma,
                              seed)
    out$returns <- r$returns; out$value <- r$mean; out$se <- r$se
    out$ci_lower <- if (is.nan(r$se)) NaN else
      r$mean - 1.959963984540054 * r$se
    out$ci_upper <- if (is.nan(r$se)) NaN else
      r$mean + 1.959963984540054 * r$se
    out$visits <- r$visits
    out$n_episodes <- as.integer(n_episodes)
    out$horizon <- as.integer(horizon)
  } else {
    out$returns <- numeric(0); out$value <- NULL; out$se <- NULL
    out$ci_lower <- NULL; out$ci_upper <- NULL
    out$visits <- matrix(0L, 0L, 0L)
    out$n_episodes <- 0L; out$horizon <- 0L
  }
  if (has_log) {
    r <- morie_rlhfRS_offpolicy(env$log, policy, env$behaviour,
                                estimator, reward_model, clip)
    out$off_policy <- r$estimate; out$weights <- r$weights
    out$mean_weight <- r$mean_weight; out$max_weight <- r$max_weight
    out$ess <- r$ess; out$n_clipped <- r$n_clipped; out$n_log <- r$n
  } else {
    out$off_policy <- NULL; out$weights <- numeric(0)
    out$mean_weight <- NULL; out$max_weight <- NULL; out$ess <- NULL
    out$n_clipped <- 0L; out$n_log <- 0L
  }
  if (!is.null(relevance)) {
    out$precision_at_k <- morie_rlhfRS_precision(relevance, k)
    out$ndcg_at_k <- morie_rlhfRS_ndcg(relevance, k)
    out$mrr <- morie_rlhfRS_mrr(relevance)
  } else {
    out$precision_at_k <- NULL; out$ndcg_at_k <- NULL; out$mrr <- NULL
  }
  out$gamma <- as.numeric(gamma); out$k <- as.integer(k)
  out$estimator <- estimator; out$has_simulator <- has_sim
  out$has_log <- has_log
  out
}

#' One-line summary of the rlhfRS module
#'
#' @return A character scalar.
#' @export
morie_rlhfRS_cheatsheet <- function()
  paste0("rlhfRS: recommendation as a session MDP. Discounted rollout ",
         "plus IPS, self-normalised IPS or doubly robust off-policy ",
         "value; the support condition is enforced")
