#' Spatial simulation and interpolation
#'
#' \code{TurningBandsSpherical}: spherical-covariance Gaussian field by
#' turning bands with Matheron's dilution line process.
#' \code{DlaAggregate}: diffusion-limited aggregation on the square lattice.
#' \code{MovingLeastSquares}: MLS approximation with Gaussian weights.
#' \code{DeformationFieldSimulate}: Sampson-Guttorp deformation field.
#' \code{AnnealingSimulation}: simulated annealing matching a histogram and a
#' variogram. Philox draws; identical to the Python arm \code{morie.fn.geosimx}.
#'
#' @param coords Matrix of coordinates (two or three columns).
#' @param sill,range_ Sill and range.
#' @param n_bands Number of bands.
#' @param lam Poisson intensity of the dilution (default 50 / range).
#' @param seed Philox seed.
#' @param n_particles Number of walkers.
#' @param points,values,targets Data points, their values and target points.
#' @param h Bandwidth.
#' @param degree Polynomial degree (1 or 2).
#' @param deformed Matrix of deformed coordinates.
#' @param model Covariance model (\code{\link{KrigingCovariance}}).
#' @param nsim Number of realisations.
#' @param nx,ny Grid size.
#' @param lags Matrix of lag vectors (dx, dy).
#' @param n_iter,t0,cooling Annealing iterations, initial temperature and cooling rate.
#' @return List.
#' @references Lantuejoul, C. (2002). Geostatistical Simulation: Models and
#'   Algorithms. Springer.
#'
#'   Witten, T. A. and Sander, L. M. (1981). Diffusion-limited aggregation, a
#'   kinetic critical phenomenon. Physical Review Letters 47, 1400-1403.
#'
#'   Lancaster, P. and Salkauskas, K. (1981). Surfaces generated by moving
#'   least squares methods. Mathematics of Computation 37, 141-158.
#'
#'   Sampson, P. D. and Guttorp, P. (1992). Nonparametric estimation of
#'   nonstationary spatial covariance structure. JASA 87, 108-119.
#'
#'   Deutsch, C. V. and Journel, A. G. (1998). GSLIB, 2nd edn. Oxford
#'   University Press.
#' @examples
#' P <- rbind(c(0, 0), c(1, 0), c(0, 1), c(1, 1), c(0.5, 0.5))
#' MovingLeastSquares(P, 1 + 2 * P[, 1] - P[, 2], rbind(c(0.3, 0.7)), 0.8)$prediction
#' @export
TurningBandsSpherical <- function(coords, sill = 1, range_ = 1, n_bands = 100L, lam = NULL, seed = 1) {
  X <- as.matrix(coords)
  if (ncol(X) < 3) X <- cbind(X, matrix(0, nrow(X), 3 - ncol(X)))
  a <- range_
  if (is.null(lam)) lam <- 50 / a
  L <- n_bands
  ga <- pi * (3 - sqrt(5))
  dirs <- t(vapply(0:(L - 1), function(b) {
    zc <- 1 - (2 * b + 1) / L
    r <- sqrt(max(1 - zc^2, 0))
    c(r * cos(b * ga), r * sin(b * ga), zc)
  }, numeric(3)))
  U <- .gx_unif(seed, 0)
  field <- numeric(nrow(X))
  nrm <- sqrt(sill / L) / sqrt(lam * a^3 / 12)
  for (l in seq_len(L)) {
    tt <- as.vector(X %*% dirs[l, ])
    s <- min(tt) - a / 2
    hi <- max(tt) + a / 2
    pk <- numeric(0)
    ek <- numeric(0)
    repeat {
      s <- s + -log(1 - U()) / lam
      if (s > hi) break
      pk <- c(pk, s)
      ek <- c(ek, if (U() < 0.5) 1 else -1)
    }
    for (i in seq_along(tt)) {
      v <- 0
      for (k in seq_along(pk)) {
        d <- tt[i] - pk[k]
        if (d > -a / 2 && d < a / 2) v <- v + ek[k] * d
      }
      field[i] <- field[i] + nrm * v
    }
  }
  list(field = field, directions = dirs)
}

.gx_unif <- function(seed, stream0) {
  env <- new.env()
  env$block <- stream0
  env$buf <- numeric(0)
  env$pos <- 0
  function() {
    if (env$pos >= length(env$buf)) {
      env$buf <- .morie_random_uniform(4096, seed = seed, stream = env$block)
      env$block <- env$block + 1
      env$pos <- 0
    }
    env$pos <- env$pos + 1
    env$buf[env$pos]
  }
}

.gx_ss <- function(v) {
  s <- 0
  for (a in v) s <- s + a
  s
}

#' @rdname TurningBandsSpherical
#' @export
DlaAggregate <- function(n_particles, seed = 1) {
  if (!is.numeric(n_particles) || length(n_particles) != 1L || is.na(n_particles) ||
      n_particles < 0 || n_particles != round(n_particles)) {
    stop("`n_particles` must be one whole number >= 0", call. = FALSE)
  }
  key <- function(x, y) paste(x, y)
  occ <- new.env()
  assign(key(0, 0), TRUE, envir = occ)
  sites <- matrix(c(0, 0), 1)
  U <- .gx_unif(seed, 0)
  rmax <- 0
  rg <- 0
  moves <- rbind(c(1, 0), c(-1, 0), c(0, 1), c(0, -1))
  isocc <- function(x, y) exists(key(x, y), envir = occ, inherits = FALSE)
  while (nrow(sites) <= n_particles) {
    R <- rmax + 5
    th <- 2 * pi * U()
    x <- round(R * cos(th))
    y <- round(R * sin(th))
    repeat {
      if (any(vapply(1:4, function(m) isocc(x + moves[m, 1], y + moves[m, 2]), TRUE))) {
        if (!isocc(x, y)) {
          assign(key(x, y), TRUE, envir = occ)
          sites <- rbind(sites, c(x, y))
          rmax <- max(rmax, sqrt(x^2 + y^2))
          mx <- .gx_ss(sites[, 1]) / nrow(sites)
          my <- .gx_ss(sites[, 2]) / nrow(sites)
          rg <- c(rg, sqrt(.gx_ss((sites[, 1] - mx)^2 + (sites[, 2] - my)^2) / nrow(sites)))
        }
        break
      }
      m <- min(floor(U() * 4), 3) + 1
      x <- x + moves[m, 1]
      y <- y + moves[m, 2]
      if (sqrt(x^2 + y^2) > 3 * R) {
        th <- 2 * pi * U()
        x <- round(R * cos(th))
        y <- round(R * sin(th))
      }
    }
  }
  k <- (length(rg) %/% 2 + 1):length(rg)
  k <- k[rg[k] > 0]
  lx <- log(rg[k])
  ly <- log(k)
  mx <- .gx_ss(lx) / length(lx)
  my <- .gx_ss(ly) / length(ly)
  D <- .gx_ss((lx - mx) * (ly - my)) / .gx_ss((lx - mx)^2)
  list(sites = unname(sites), radius_of_gyration = rg, fractal_dimension = D)
}

#' @rdname TurningBandsSpherical
#' @export
MovingLeastSquares <- function(points, values, targets, h, degree = 1L) {
  P <- as.matrix(points)
  Tg <- as.matrix(targets)
  d <- ncol(P)
  basis <- function(p) {
    b <- c(1, p)
    if (degree == 2) for (i in seq_len(d)) for (j in i:d) b <- c(b, p[i] * p[j])
    b
  }
  B <- t(apply(P, 1, basis))
  out <- numeric(nrow(Tg))
  for (k in seq_len(nrow(Tg))) {
    w <- exp(-colSums((t(P) - Tg[k, ])^2) / (h * h))
    M <- crossprod(B * w, B)
    r <- crossprod(B, w * values)
    out[k] <- sum(basis(Tg[k, ]) * solve(M, r))
  }
  list(prediction = out)
}

#' @rdname TurningBandsSpherical
#' @export
DeformationFieldSimulate <- function(coords, deformed, model, nsim = 1L, seed = 1) {
  G <- as.matrix(deformed)
  n <- nrow(G)
  if (nrow(as.matrix(coords)) != n) stop("coords and deformed must have the same length")
  C <- matrix(0, n, n)
  for (i in seq_len(n)) for (j in seq_len(n)) C[i, j] <- KrigingCovariance(sqrt(sum((G[i, ] - G[j, ])^2)), model) + (if (i == j) 1e-12 else 0)
  L <- .s03chol(C)
  sims <- lapply(seq_len(nsim) - 1, function(k) {
    e <- .morie_random_normal(n, seed = seed, stream = k)
    vapply(seq_len(n), function(i) .gx_ss(L[i, seq_len(i)] * e[seq_len(i)]), 0)
  })
  list(realisations = sims, covariance = C)
}

#' @rdname TurningBandsSpherical
#' @export
AnnealingSimulation <- function(nx, ny, values, model, lags, n_iter = 5000L, t0 = 1, cooling = 0.001, seed = 1) {
  N <- nx * ny
  if (length(values) != N) stop("need nx * ny values")
  lags <- matrix(lags, ncol = 2)
  U <- .gx_unif(seed, 0)
  idx <- seq_len(N)
  for (k in (N - 1):1) {
    j <- min(floor(U() * (k + 1)), k)
    tmp <- idx[k + 1]
    idx[k + 1] <- idx[j + 1]
    idx[j + 1] <- tmp
  }
  g <- values[idx]
  c0 <- KrigingCovariance(0, model)
  target <- vapply(seq_len(nrow(lags)), function(k) c0 - KrigingCovariance(sqrt(sum(lags[k, ]^2)), model), 0)
  pairs <- lapply(seq_len(nrow(lags)), function(k) {
    dx <- lags[k, 1]
    dy <- lags[k, 2]
    pl <- matrix(0L, 0, 2)
    for (y in 0:(ny - 1)) for (x in 0:(nx - 1)) {
      if (x + dx >= 0 && x + dx < nx && y + dy >= 0 && y + dy < ny) pl <- rbind(pl, c(y * nx + x, (y + dy) * nx + x + dx))
    }
    pl
  })
  pairsum <- function(pl) {
    s <- 0
    for (r in seq_len(nrow(pl))) s <- s + (g[pl[r, 1] + 1] - g[pl[r, 2] + 1])^2
    s
  }
  sums <- vapply(pairs, pairsum, 0)
  obj <- function(s) .gx_ss(vapply(seq_along(pairs), function(k) ((s[k] / (2 * nrow(pairs[[k]])) - target[k]) / target[k])^2, 0))
  touch <- function(k, i, j) {
    pl <- pairs[[k]]
    sel <- pl[pl[, 1] %in% c(i, j) | pl[, 2] %in% c(i, j), , drop = FALSE]
    sel[order(sel[, 1], sel[, 2]), , drop = FALSE]
  }
  cur <- obj(sums)
  path <- cur
  for (it in 0:(n_iter - 1)) {
    i <- min(floor(U() * N), N - 1)
    j <- min(floor(U() * N), N - 1)
    u <- U()
    if (i == j || g[i + 1] == g[j + 1]) {
      path <- c(path, cur)
      next
    }
    tl <- lapply(seq_along(pairs), function(k) touch(k, i, j))
    old <- vapply(tl, pairsum, 0)
    tmp <- g[i + 1]
    g[i + 1] <- g[j + 1]
    g[j + 1] <- tmp
    new <- vapply(tl, pairsum, 0)
    cand <- sums - old + new
    o <- obj(cand)
    T <- t0 / (1 + it * cooling)
    if (o <= cur || u < exp(-(o - cur) / T)) {
      sums <- cand
      cur <- o
    } else {
      tmp <- g[i + 1]
      g[i + 1] <- g[j + 1]
      g[j + 1] <- tmp
    }
    path <- c(path, cur)
  }
  list(grid = matrix(g, ny, nx, byrow = TRUE), objective = path, target = target)
}
